### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by boionfire81** [revive-adserver/revive-adserver#1000]
Attempting to install and get this error:

> Installation failed to create the core tables

try again and it can not install as it keeps populating only 2 of the tables. Error is the prefix already exists. Despite not using it beyond this install. 

Deleting the created tables (2) it just starts the error process over again.

**Comment by andrewatfornax** [comment]
Please create a support request in the forums - there's insufficient information here to classify this as a bug at this stage. Thanks.
