### ISSUE TITLE
Scope: Ads appearing and disappearing from website on iPhone 7

### ISSUE THREAD

**Issue by SabrinaEmessy** [revive-adserver/revive-adserver#1001]
Problem:
When accessing the website via an iPhone 7, the ads are not on the homepage: https://www.dolphinibc.com/ 

Steps To Reproduce:
Go to the homepage on an iPhone 7, scroll down to under "For latest club news and updates", after this section the ads should be there. Refreshing several times and they show up, check again at a different time and they have gone, refresh again and they show up, refresh again and they disappear. This has happened on and off on various iPhone 7 devices, with different internet connections. 

[issue-video-1.zip](https://github.com/revive-adserver/revive-adserver/files/2339613/issue-video-1.zip)

**Comment by erikgeurts** [comment]
Generally we recommend posting questions like this on the Community Forums at https://forum.revive-adserver.com
