### ISSUE TITLE
Field for 'password' in AgencyInfo.php to be removed

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1017]
The Revive Adserver API returns a field 'password' because of:
https://github.com/revive-adserver/revive-adserver/blob/master/lib/OA/Dll/AgencyInfo.php#L84

The value returned is always 'null' since there isn't actually a password associated with an agency.

I seem to recall from a very long time ago, before usernames were introduced, that each agency had its own password, but this is no longer the case.

To avoid confusion, I propose to remove this from the Dll.

**Comment by mbeccati** [comment]
I had tried, but it seems to be used, going from memory, during agency creation. Closing issue.
