### ISSUE TITLE
Moving a user from sysadmin to manager for an agency results in incorrect default account id

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1018]
Steps to reproduce:
- create a new sysadmin user -> that user's default_account_id is set to 1 (which is correct)
- add the same user as a manager user to one of the agencies
- go back to the Admin access screen and remove the user as a sysadmin (meaning that they are still a manager user for the agency)
- in the Users table, the default_account_id for the user is now set to 0, instead of the account ID associated with the agency they are a member of
- in the rv_account_user_assoc table, the link between the user and the account is correct

This incorrect default account ID also appears to happen on a new install, in this scenario:
- set up a new instance of Revive Adserver
- this automatically creates one agency called 'default agency', and a username who is both a sysadmin and a manager of the agency, with the default account ID for them being the account of the default agency
- when we now remove the user as manager of the default agency, in order for that user to just be an admin user going forward, the default_account_id of the user is set to 0 instead of 1

The account ID value of 1 of the sysadmin users is supposed to be taken from the rv_application_variable table's entry for it:
![image](https://user-images.githubusercontent.com/5102461/49142591-6c25df80-f2f9-11e8-9ca9-ff2cfdbd2ea4.png)

**Comment by erikgeurts** [comment]
It might be that this problem originates here:
https://github.com/revive-adserver/revive-adserver/blob/master/lib/OA/Admin/UI/UserAccess.php#L361

**Comment by mbeccati** [comment]
I don't recall what was the impact of the default_account_id being set to 0, and it is also something that's not user visible... so I'm not exactly sure what to write in the release notes. /cc @andrewatfornax

**Comment by erikgeurts** [comment]
@mbeccati do you need a hand from me with formulating the description of this fix for the release notes?

**Comment by mbeccati** [comment]
@erikgeurts if you want to give it a shot, be my guest :)

**Comment by erikgeurts** [comment]
I would propose "* Fixed issue causing a user to be assigned to a non-existent account ID 0 when changing the user from a sysadmin to an agency manager or vice versa".
