### ISSUE TITLE
Proposal to change text of "Allow this user to create new accounts" when adding/editing a username

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1021]
When creating a new manager user or editing an existing manager user, there is a checkbox on the screen labeled:
"Allow this user to create new accounts"
![image](https://user-images.githubusercontent.com/5102461/49329059-2297f780-f57a-11e8-8be5-1d0225655cd6.png)

This text is defined here:
https://github.com/revive-adserver/revive-adserver/blob/master/lib/max/language/en/default.lang.php#L299

I propose to rephrase it as:
"Allow this user to create new users" to avoid confusing with the creation of accounts/agencies elsewhere.

**Comment by andrewatfornax** [comment]
Thanks @erikgeurts!

I have actually gone with "Allow this user to associate users (new or existing) with this account".

Hope that makes sense?

**Comment by erikgeurts** [comment]
I personally think that this text is overly complicated, and I propose the following instead:

"Allow this user to add users (new or existing) to this account."

**Comment by erikgeurts** [comment]
Come to think of it, an even better text might be:

"Allow this user to manage users on this account."

**Comment by andrewatfornax** [comment]
Yes! Even better, thanks @erikgeurts!

I'll change that and update the documentation next week.

**Comment by andrewatfornax** [comment]
"Allow this user to manage this account's users"
