### ISSUE TITLE
Close image on interstitial broken in hosted edition

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1025]
I'm using the hosted edition. The close image on the interstitial is broken, The simple style that moves with the page is not smooth as one moves up and down the page

 
![screenshot from 2019-02-05 16-24-21](https://user-images.githubusercontent.com/38984775/52279928-59680080-2963-11e9-8752-1c1dc3f39242.png)

_Originally posted by @mbadaone in https://github.com/revive-adserver/revive-adserver/issues/465#issuecomment-460657004_

**Comment by erikgeurts** [comment]
I created an new issue for this, since it is not likely to be related to the one you commented on.

We'll look into this in the coming days.

**Comment by mbeccati** [comment]
The issue should be fixed now. Thanks for reporting it.

**Comment by mbadaone** [comment]
Fixed thank you. Another issue that just came up. There are sites where when you select no boarder for an interstitial the boarder shows please see attached image

![image](https://user-images.githubusercontent.com/38984775/52406807-3b231180-2ad7-11e9-8f21-070706b46596.png)
