### ISSUE TITLE
Incompatabillity with XAMPP / PHP 5.6

### ISSUE THREAD

**Issue by samdisk11** [revive-adserver/revive-adserver#1027]
i am unable to install Revive as it is showing only text.
upon checking i am getting these errors (see screenshots)
this issue only happens when i am doing this via domains (see floatvps.tk)
![image](https://user-images.githubusercontent.com/24478471/52537948-28584900-2d32-11e9-979b-19dd30d115ee.png)

when it should be like this:
![image](https://user-images.githubusercontent.com/24478471/52537963-4b82f880-2d32-11e9-9fe6-62593cf0e5c3.png)

Steps To Reproduce:
#1 Download XAMMP for windows (but with PHP 5.6)
#2 Download Revive
#3 Get domain and route the DNS to windows XAMMP server IP
#4 Attempt installation via domain

**Comment by erikgeurts** [comment]
We've seen this more often, and it turned out in almost all cases to be the result of having an ad blocker installed (which in itself is a bit ironic).

**Comment by erikgeurts** [comment]
Closing this as there have been no new information or updates.
