### ISSUE TITLE
PHP 7.2.0 Compatibility Issue

### ISSUE THREAD

**Issue by wojewsky** [revive-adserver/revive-adserver#1031]
As of PHP 7.2.0, each() has been deprecated:

http://php.net/manual/en/function.each.php

Revive Adserver's uses of each() will need to be replaced to allow PHP 7.2.0 to be used.

**Comment by andrewatfornax** [comment]
This is a big change - there are a lot of each() function uses. 

I think we should do this with the 5.0.0 release, so that we can have a longer beta release test with users to confirm it's all working.

**Comment by mbeccati** [comment]
Revive Adserver will work with 7.2.0, you just need to remove E_DEPRECATED from your error_reporting if you include `alocal.php` in your own code.

**Comment by mbeccati** [comment]
Since PHP 7.2.x is now the lower bound of supported PHP versions, I would expect this to be solved already.
