### ISSUE TITLE
Time - Hour of day delivery rule ignored

### ISSUE THREAD

**Issue by murichej** [revive-adserver/revive-adserver#1034]
Problem:
Time - Hour of the rule is ignored in Override campaigns. It happens when campaign type is changed from Contract to Override.

Steps To Reproduce:
1. Create contract campaign with Time-Hour of day 12:00-24:00
2. Change contract type to Override (in example: at 10:30)
3. Campaign will start delivery but it shouldn't

**Comment by andrewatfornax** [comment]
I've spent some time attempting to re-produce, but can't. When I create a campaign with a banner in it, with a Time - Hour of Day limitation, such that it's not currently permitted to deliver, and then change the campaign from Contract (testing first that it's not delivering) to then be Override, there's no change - the banner still does not deliver.

Only after changing the Time - Hour of Day limitation to something different where it can deliver do I see a banner show up.
