### ISSUE TITLE
Use async tags in website invocation code generation screen

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1039]
I would like to propose that we start a process of deprecating the single page call feature.

My reasoning is that with the introduction of the async javascript code tags at the zone level, we now have a superior method for putting zones onto webpages. Single page call, in contrast, can result in a page not loading while a browser waits for the ad server's response, since the code is in the page's `<head>` section.

Since the async javascript tags automatically detect each other on a page and will result in a single call to the ad server at the end, this combines the advantages of single page code with the asynchronous nature of the new tags.

In my view, we should help users to avoid the single page call by not showing it to them unless they make an extra effort to find it.

As a first step, I propose to disable the single page call tab at the website level by default, using a switch in the config file, enabling anyone to re-enable it if they so desire. Any existing single page call code already present in websites will continue to work, but new users will simply not see the tab, and thus not be tempted to use the feature.

**Comment by FirstImpression** [comment]
Except for UI, does this imply changes in delivery engine? Or just depreciation of spc.php?

**Comment by erikgeurts** [comment]
With this proposal, it is not my intention to make any changes to the delivery engine, and the spc code will continue to work as before. I literally wrote
> Any existing single page call code already present in websites will continue to work

All I proposed is to hide the tab in the UI that enables users to get the single page call code, in an effort to discourage the use of it for novice users.

In the long run, I think we should consider getting rid of SPC entirely, should the community be in favor.

**Comment by erikgeurts** [comment]
In a recent Revive Adserver project team meeting, we discussed a slight modification of this proposal, which was to display the async js tags for all zones in the UI in the place where it now shows the single page call code snippets. This is to encourage people to start using async js tags instead of spc.
