### ISSUE TITLE
Update Minimum PHP Version

### ISSUE THREAD

**Issue by andrewatfornax** [revive-adserver/revive-adserver#1042]
Update the minimum supported version of PHP to 7.0 for the 4.2.0 release.

This includes both the code check in the product, and documentation updates as required.

**Comment by mbeccati** [comment]
The code part has been done. Mininum required version is 7.0.8. Also the zip extension is now required as the html5 functionality depends on it.

**Comment by erikgeurts** [comment]
I have updated the page at https://www.revive-adserver.com/support/requirements/ to reflect that for Revive Adserver version 4.2.0, the minimum required version of PHP is 7.0.8. I've also added the zip extension to the list of required PHP extensions.

@andrewatfornax Can you please check if anything needs to be edited on https://documentation.revive-adserver.com/ for these requirement changes, and then close this issue?

**Comment by erikgeurts** [comment]
For the record, the only page that I think needs changing is https://documentation.revive-adserver.com/display/DOCS/Non-BC+Changes . While doing that, it's perhaps a good idea to list v4.1.4 as well.

**Comment by andrewatfornax** [comment]
Done!
