### ISSUE TITLE
Failed to generate tables on MySQL 8.0

### ISSUE THREAD

**Issue by gekkotokio** [revive-adserver/revive-adserver#1048]
Some SQL statements of creating tables seem incompatible with MySQL 8.0.

> The default value specified in a DEFAULT clause can be a literal constant or an expression. With one exception, enclose expression **default values within parentheses** to distinguish them from literal constant default values.<br>[MySQL :: MySQL 8.0 Reference Manual :: 11.7 Data Type Default Values](https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html#data-types-defaults-explicit)

The current instalation scripts (ver. 4.1.4) generates SQL statements like this, and fails to create tables on MySQL 8.0.

```sql
CREATE TABLE `rv_banners`(
    ...
    `acls_updated` DATETIME DEFAULT '0000-00-00 00:00:00' NOT NULL,
    ...
    PRIMARY KEY(bannerid)
) ENGINE = INNODB;
```

The following statement works well.

```sql
CREATE TABLE `rv_banners`(
    ...
    `acls_updated` DATETIME DEFAULT ('0000-00-00 00:00:00') NOT NULL,
    ...
    PRIMARY KEY(bannerid)
) ENGINE = INNODB;
```

**Comment by mbeccati** [comment]
That is true. We haven't properly tested MySQL 8 just yet, but this is the issue:

> Incompatible Change: These deprecated compatibility SQL modes have been removed: DB2, MAXDB, MSSQL, MYSQL323, MYSQL40, ORACLE, POSTGRESQL, NO_FIELD_OPTIONS, NO_KEY_OPTIONS, NO_TABLE_OPTIONS. They can no longer be assigned to the sql_mode system variable or used as permitted values for the mysqldump --compatible option.

Revive Adserver currently uses SET SQL_MODE = 'MYSQL40' to work properly. We'll need to find an alternative.

**Comment by gekkotokio** [comment]
Thanks you for your reply.

I will try to install Revive Adserver, downgrade MySQL, install Revive Adserver and then migrate the database to MySQL 8.0+ from MySQL 5.7.

**Comment by andrewatfornax** [comment]
Hey @mbeccati & @erikgeurts,
As part of setting up a new dev environment, I've discovered that I've hit this issue as well, as I installed MySQL 8.0, based on it being the latest stable version.
Do you think we can do anything about the issues with compatibility with MySQL 8 for the 5.0 release? Or do we need to update our documentation to exclude support for MySQL 8 for now?

**Comment by Zer0Divis0r** [comment]
@gekkotokio, did this ever work?
I am running Revive on MySQL 8 for a while, and did not notice any major problems. Just discovered that according to https://www.revive-adserver.com/support/requirements/ , MySQL 8.x is not stated as  supported version for use with any version of Revive Adserver.

**Comment by ronaldmifsud** [comment]
> @gekkotokio, did this ever work?
> I am running Revive on MySQL 8 for a while, and did not notice any major problems. Just discovered that according to https://www.revive-adserver.com/support/requirements/ , MySQL 8.x is not stated as supported version for use with any version of Revive Adserver.

Did you make any changes on the application or MySQL for it to work on MySQL 8 as I cannot get it to work. I did not manage to create the schema.

**Comment by domveres** [comment]
Hello, do you have any plans to make Revive compatible w/ **MySQL 8.x**? It would be much appreciated.
I found difficulties with these tables - zones, banners and channel (could be more..)
1. No default values on datetime columns
2. Data truncated for column 'alt_contenttype' - expected enum, received empty string - banners table
3. BLOB, TEXT, GEOMETRY or JSON column 'compiledlimitation' can't have a default value
https://bugs.mysql.com/bug.php?id=21532
https://dev.mysql.com/doc/refman/8.0/en/blob.html#idm140312903326336
- make all columns type `text` as nullable, might resolve issue

I'd be happy to contribute, but I didn't find developer guide very helpful. Also, as written in docs, database schema changes should be discussed first, so please, can we move this forward please?

**Comment by mbeccati** [comment]
@domveres Unfortunately MySQL version 8.x dropped MySQL4 compatibility mode and the Revive mysql db adapter was build on top of all those quirks and inconsistencies (e.g. 0000-00-00 dates). I also read from you that 8.x brings new ones like no defaults allowed for those column types. It's going to be challenging to say the least.

**Comment by domveres** [comment]
@mbeccati Yes, for sure. I'd like to know if its on the list with major priority? I think it'll be increasingly required. Can we somehow kick it off? As I written in earlier post, I'd be happy to give a helping hand, or is there any other kind of support, which could this issue up vote to development?

**Comment by amit0021** [comment]
Is there any way to run on MySQL version 8+ ?. If yes can anyone tell how it is been trying to run from the whole but kept on failing.
Currently, the log is `Native message: Invalid default value for 'acls_updated'`

**Comment by domveres** [comment]
@amit0021 There's unfortunately not. It's not possible without direct intervention in database, which I would not recommend.
@mbeccati Any ongoing development that leads to support MySQL 8.x?

**Comment by erikgeurts** [comment]
See the technical requirements page at https://www.revive-adserver.com/support/requirements/ .

**Comment by mbeccati** [comment]
@domveres for now, I have PHP8+ on my list. Sadly, the whole DAL / DO mysql implementation is based on some legacy behaviour that has been removed, e.g. the nasty 0000-00-00 dates. My fear is that this can easily become a time sink and my efforts are better spent elsewhere.

**Comment by Zer0Divis0r** [comment]
Seeing this issue to become alive again, I can confirm that had not issues at all running Revive on MySQL 8, although I am not using the entire set of it's featuers, so can't tell about 100% of functionality. 
As far as I remember, all I had to do is to set sql_mode to `''`

So, in contrary to @domveres 's opinion, I'd say that if you know what you are doing it is fine to tamper with database structure to make Revive work, give it a try.

**Comment by amit0021** [comment]
> Seeing this issue to become alive again, I can confirm that had not issues at all running Revive on MySQL 8, although I am not using the entire set of it's featuers, so can't tell about 100% of functionality.
> As far as I remember, all I had to do is to set sql_mode to `''`
> 
> So, in contrary to @domveres 's opinion, I'd say that if you know what you are doing it is fine to tamper with database structure to make Revive work, give it a try.

Awesome that is what I am searching for, a midway. It works !!. **Thanks @Zer0Divis0r**

**Comment by eletrico-amarelo** [comment]
> Seeing this issue to become alive again, I can confirm that had not issues at all running Revive on MySQL 8, although I am not using the entire set of it's featuers, so can't tell about 100% of functionality.
> As far as I remember, all I had to do is to set sql_mode to `''`
> 
> So, in contrary to @domveres 's opinion, I'd say that if you know what you are doing it is fine to tamper with database structure to make Revive work, give it a try.

Thanks @Zer0Divis0r

**Comment by mbeccati** [comment]
Assiging tentatively to 5.3.0

**Comment by knofte** [comment]
> Looks like I never understood how MySQL `sql_mode` really worked. After digging into MySQL's sourcecode and specifically the commit removing `MODE_MYSQL40`, I realised it was little more than the alias for an empty `sql_mode` (plus `HIGH_NOT_PRECEDENCE` which I don't think we actually make use of).
> 
> I've therefore decided to completely remove the old `mysql4_compatibility` setting and made sure Revive always sets the appropriate SQL mode.

Do you recommend to set the sql_mode then at this point to get a new install working with mysql 8.* or will there be a new release soon that handles this by itself? :)

5.2.1 is the version I'm trying, and that ain't flying. :)

**Comment by erikgeurts** [comment]
We recommend that you wait for v5.3.0, because that's expected to have full PHP8 and MySQL8 support.

**Comment by knofte** [comment]
> We recommend that you wait for v5.3.0, because that's expected to have full PHP8 and MySQL8 support.

Excellent, thank you @erikgeurts 
Do we have an expected release date for 5.3.0 ? :)

**Comment by erikgeurts** [comment]
You can follow the progress for the upcoming release by checking this URL: https://github.com/revive-adserver/revive-adserver/milestone/3
