### ISSUE TITLE
Should we deprecate fl.js?

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1049]
Now that Flash has been dead for several years, it is unlikely anyone is still using Flash ads.

Yet, the Revive Adserver UI still loads the fl.js file on every page view. I wonder if this is still necessary for anything useful. If not, it might be a smart move to get rid of the fl.js file in /www/delivery and stop it from being loaded in the UI.

**Comment by mbeccati** [comment]
Yes, but should we go through some kind of deprecation? I.e. can we write in the 4.2.0 release notes that Flash banners are deprecated and will be removed / disabled in a subsequent version?

**Comment by erikgeurts** [comment]
I agree that it should be properly announced that this will be deprecated. Hence the title of this issue is "Should we deprecate fl.js?" :)

**Comment by andrewatfornax** [comment]
We should deprecate it, without in-product warning. Just remove it when appropriate, and note in the release notes.
