### ISSUE TITLE
The "Active campaigns" filter does not show all active campaigns

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1053]
A user reported that a campaign that started on May 1st 2019 does not show up in the list of campaigns of the advertiser on May 2nd, when he selects "Active campaigns" as the filter.

The campaign is actually serving, there are numbers in the statistics for it since May 1st.

Here it is with "All campaigns":
![image](https://user-images.githubusercontent.com/5102461/57075006-de09b700-6ce5-11e9-9940-2f4fd9d1a6b6.png)

If I switch to "Active campaigns" it disappears from the list.

This is most likely related to #992 in the v4.2.0 release

**Comment by andrewatfornax** [comment]
Thanks for the report. I am working on this.

So far, I have created a new Remnant campaign, which is not yet active - but will become active "tomorrow".

When the campaign has no banners, it shows up with the "All Campaigns" option, but does not show up with the "Active Campaigns" option.

When the campaign is updated to include banners, it shows up with both options.

So, in the pre-activated state, this looks okay.

Next is to check how it looks once activated.

**Comment by andrewatfornax** [comment]
Moved my clock forward a day, and maintenance activated the banner.

Unfortunately, I see the campaign with both the "All Campaigns" and "Active Campaigns" options.

**Comment by andrewatfornax** [comment]
@erikgeurts, is it possible to check the state of the campaign, and the state of all banners in the campaign, please?

**Comment by erikgeurts** [comment]
We just received a report from another customer about the same matter. In both cases, these were upgrades from v4.1.4, not new installs (if that matter in any way).

I already checked for the first report, the campaign is active and serving (statistics are collecting) and all banners in the campaign are active. Start date of that campaign was May 1st, 2019. It's a remnant campaign with weight 1. It may be important to mention that some of the banners in the campaign are deactivated, but there are 2 that are active and serving.

In the new report from the other customer, it's a campaign that has been running since July 2018. It also has a number of active and a number of inactive banners in it.

My first guess would be that somehow the new filter definition misinterprets a case where a few of the banners in an otherwise active campaign have been deactivated.

**Comment by andrewatfornax** [comment]
Thanks @erikgeurts - it's when they have a disabled banner in there, it's treating the whole thing as disabled. Working to fix.

**Comment by andrewatfornax** [comment]
Issue found and fixed - PR with @mbeccati for review.
