### ISSUE TITLE
Need updated privacy policy and Cookie policy

### ISSUE THREAD

**Issue by sheikhrehman** [revive-adserver/revive-adserver#1060]

**Comment by erikgeurts** [comment]
See https://www.revive-adserver.com/privacy/, it's all there.

**Comment by sheikhrehman** [comment]
> See https://www.revive-adserver.com/privacy/, it's all there.

I think we should not use this paragraph "Website and company" right?

**Comment by erikgeurts** [comment]
It's *our* privacy page, and it links to several pages about how the software handles cookies. It is *not* intended to be an example or template for your own privacy policy or cookie page. We are not legal consultants, you will have to consult one yourself to get a policy that suits your situation.
