### ISSUE TITLE
Ad banners not delivering/showing when redirecting from Facebook Android app

### ISSUE THREAD

**Issue by midler29** [revive-adserver/revive-adserver#1063]
Hello,
we have news agency website and posting news every day. We've placed ad banners on this website, and everything works great (on Windows, Linux, IOS, android browsers). But, if we share post (url of our website's single post) on Facebook, and than try to enter that link from android Facebook app (Android uses built-in  'Facebook Mobile Browser' to open links) banners are not showing up. On IOS this problem does not exists, banner is showing up properly.

We tried .png, html banner type but without success. also, We tried Adocean and it works without problem.

Can you plase confirm this is bug? Our company is ready to pay for  fixing this issue ASAP. 

Thanks.

**Comment by erikgeurts** [comment]
Please post your questions about using the application on our community forums at https://forum.revive-adserver.com
