### ISSUE TITLE
I can't insert HTML Banners

### ISSUE THREAD

**Issue by mxra8** [revive-adserver/revive-adserver#1064]
I installed Revive Adserver into localhost.

Today I installed but this time into my server, but HTML Banners option doesn't appear when I want to create a new banner.

![admin](https://i.ibb.co/BV6bL9s/Screen-Shot-2019-06-13-at-5-51-10-PM.png)

![banner](https://i.ibb.co/5jFLNqq/Screen-Shot-2019-06-13-at-5-51-53-PM.png)

**Comment by mxra8** [comment]
The plugins won't installed, I need to install it manually, and is fix it.

**Comment by erikgeurts** [comment]
It is generally recommended to post questions like this on our community forums at https://forum.revive-adserver.com , perhaps after reviewing the documentation first. This particular matter is addressed here: https://documentation.revive-adserver.com/display/DOCS/Plugins+Missing+or+Disabled
