### ISSUE TITLE
Redesign Password Recovery email

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1066]
When a user requests a password recovery, the email they receive leaves a bit to be desired as far as the user experience is concerned.

I propose to redesign the email a bit, with a better email subject line and better content body.

Here is a screenshot of what it currently looks like (sensitive data blurred):
![recovery](https://user-images.githubusercontent.com/5102461/59685245-05f0a380-91dc-11e9-9349-e0357a92dc9e.png)

The following items can be improved:

**Subject line**
https://github.com/revive-adserver/revive-adserver/blob/master/lib/max/language/en/default.lang.php#L1078 is the string used for the mail subject. However, the "%s" in "%s password recovery" does not get replaced with anything in https://github.com/revive-adserver/revive-adserver/blob/master/lib/OA/Admin/PasswordRecovery.php#L247 . I assume that %s is supposed to be application name from $aPref['name'].

**Content**
The body of the email could do with a bit more text to explain what it is, why it was sent, and what the recipient is supposed to do. Also, it should have some text to help a recipient who did not request a password recovery (since that could indicate an ongoing attempt at compromising their password).

A opening greeting ("Dear %name,") and a signature should also be part of the content.

**Comment by erikgeurts** [comment]
See also #109

**Comment by erikgeurts** [comment]
I had a look at the redesigned password recovery email template.

I'd like to propose that the use of the word "account" is changed to "username", in order to prevent confusion between accounts (formerly known as agencies), and usernames/users. For example:

> A request was recently made to reset the password for your {$PRODUCT_NAME} account.

should (in my view) read:

> A request was recently made to reset the password for your {$PRODUCT_NAME} username.

This is my attempt at rephrasing the text:

> $GLOBALS['strPwdRecEmailBody'] = "Dear {name},
> 
> You, or someone pretending to be you, requested to reset the password for your username at {$PRODUCT_NAME}.
> 
> If this request was made by you, then you can reset the password for your username
> '{username}' by clicking this link:
> {reset_link}
> 
> If you submitted the password reset request by mistake, or if you didn't make a request at all, simply ignore this email. No changes have been made to your password. The password reset link will expire automatically after a while.
> 
> If you continue to receive these password reset mails, then it may indicated that someone is attempting to gain access to your username. In that case, please contact the support team or system  administrator for your {$PRODUCT_NAME} system, and notify them of the situation.
> 
> Best regards, {admin_signature}";

**Comment by andrewatfornax** [comment]
Thanks @erikgeurts - updated the text based on suggestions!

**Comment by erikgeurts** [comment]
Thanks for incorporating most of my feedback and suggestion. I was wondering if you could consider using the entire text. The one that is in there now is somewhat inconsistent, and it has a mix of active and inactive tone. There is also a grammar error.

Also, I was wondering if this email could be wrapped in a responsive email template, so that it looks just that little bit more modern and professional. I think I can provide a template that I've used for other projects. It would also mean we can include the project logo or the custom logo in the email.

**Comment by mbeccati** [comment]
That would be an improvement but I think we should leave responsive (which brings along HTML / MIME emailing) for a separate issue / PR.

**Comment by erikgeurts** [comment]
Looks like things are progressing nicely.

I'd like to ask about a few final bits:
- did you make any changes to the subject line of the email message at https://github.com/revive-adserver/revive-adserver/blob/1066_redesign_password_recovery_email/lib/max/language/en/default.lang.php#L1083 ?
I think might be possible to improve this a tiny bit more. Perhaps something along the lines of:
> "Reset your password for %s"

- In general, I'd like to propose using the term "reset" instead of "recover" everywhere.

- I'm still in favor of changing the first sentence of the email from:
> A request was recently made to reset {$PRODUCT_NAME} password.
to
> You, or someone pretending to be you, requested to reset the password for your username at {$PRODUCT_NAME}.

- What is https://github.com/revive-adserver/revive-adserver/blob/1066_redesign_password_recovery_email/lib/max/language/en/default.lang.php#L1074 being used for? What "ID" is it referring to?

- I'd like to propose changing the text in https://github.com/revive-adserver/revive-adserver/blob/1066_redesign_password_recovery_email/lib/max/language/en/default.lang.php#L1071 to
> "Request a new password"
or
> "Reset your password"

**Comment by mbeccati** [comment]
> someone pretending to be you

That sounds alarming to me though. I think I usually read "if it wasn't you, ignore the email" kind of reset messages.

**Comment by erikgeurts** [comment]
It was my intention to make it sound alarming, to be honest, because I think it is important that people are alert when there might be an ongoing attempt to hijack their username by changing the password.

**Comment by andrewatfornax** [comment]
I think that the phrasing is okay - it's something I have seen relatively commonly used. I did try and follow some of the "best practices" I have see around for these types of emails.

Updated language pack coming in a moment.
