### ISSUE TITLE
Problem installing on ubuntu 18.04 Linux Server

### ISSUE THREAD

**Issue by UbuntuEvangelist** [revive-adserver/revive-adserver#1076]
i am using ubuntu 18.04 LTS  try using this https://documentation.revive-adserver.com/display/DOCS/Installation but fail

**Comment by erikgeurts** [comment]
We strongly recommend that you post questions like this on our community forums at http://forum.revive-adserver.com/ . If it turns out to be a bug, we can always re-visit here.

**Comment by saydulk** [comment]
its was bug related issue with PHP 7.1 btw I fixed this and its working :) 

Thanks
saydulk
Skype: helios-sw

![Screenshot from 2019-07-16 19-08-43](https://user-images.githubusercontent.com/1058663/61297106-523ffb00-a7fd-11e9-9583-778c186d7429.png)

**Comment by erikgeurts** [comment]
Without sharing any details, it's impossible for us to look into this.

**Comment by k7n2g** [comment]
You ask for help but when you fix it, be nice if you shared the details so others may profit
