### ISSUE TITLE
Invocation code generated with http despite console and delivery configured for https

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1078]
This doesn't apply the async js invocation code, since those tags are generated with:
`<script async src="//{delivery URL}/asyncjs.php"></script>`
and will thus automatically follow the site's protocol.

And the regular javascript tag will also switch to https automatically if the website it runs on is also https.

Assuming the ad server is configured to work with https, this will work just fine. If the ad server is not configured for ad delivery on https and the site is on https, it's an issue that can't be fixed in code.

However, several other types of invocation code, including iframe, newsletter, always get generated with http:// in the URLs, even when the ad server is perfectly capable of https. This may cause confusion and head scratching that could be avoided.

Perhaps there is some way to improve this, for example a checkbox that instructs the ad server to always generate tags with https:// or with // ?

**Comment by GeertHauwaerts** [comment]
Bump. I agree that the generated invocation code should have `//` or at least use https when configured.
