### ISSUE TITLE
Suspending/deactivating an account

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1079]
For the Hosted edition, but also for other use cases, it would be very helpful to be able to deactivate (suspend) an account, ideally by a checkbox in the account properties screen:
![image](https://user-images.githubusercontent.com/5102461/61533639-bd701400-aa2d-11e9-976c-1f344f0ce179.png)

The desired effect of suspending an account would be:
- Any username associated with the account will not be able to access that account in the UI.
- If it is the only account they have access to, they will not be able to log in at all (and/or see a message saying something like "your username does not have access to any of the accounts in this system").
- The probability of all banners in all zones will be set to 0.00% at the next maintenance run, thus resulting in the ads no longer serving for the entire account. Another way to achieve this might be to enforce a delivery rule that effectively always evaluates to false, "like 0=1".

Optional extra:
- in addition to the impression logging pixel (which by definition logs a blank at this point), the zone's invocation code will output a bit of html code, effectively saying something like `"<strong>This ad server account has been suspended.</strong>"` or words of a similar nature, in the location where the prepend (if any) is also returned.

Note:
- There is a column called "active" in the agency table, with default value 0 (zero), which doesn't appear to do anything in the code. If that would be set to 1 in all accounts, it could then be used to indicate that the account is suspended by changing the value to 0.

**Comment by erikgeurts** [comment]
See also #1147

**Comment by mbeccati** [comment]
@andrewatfornax in case you haven't already: I've started looking into this. The pre-existing `agency.active` field seems unused, but defaults to 0 for anything but the starting agency, at least according to my test.

I suppose we could either:
- change the default to 1 and update the existing agencies, or
- drop the field and add a new status field, similar to what we have on `campaigns` and `banners`.

Both approaches have pros and cons, I'd be happy to discuss.

**Comment by andrewatfornax** [comment]
I agree that we should replace "active" with "status" so that we can have 3 states.

- Active - normal operation;
- Suspended - block the login, and during ad rendering, only ever select a custom banner with appropriate (configured) content to indicate the account is suspended;
- Inactive - block the login, no banner delivery.

**Comment by erikgeurts** [comment]
My approach would be slightly different:

- Active - normal operation;
- Suspended - prevent any user from logging in on the account, or from switching to the account using the "Working as..." drop down (if they can access to multiple accounts).
During ad selection, always return a configurable snippet of HTML code, which indicates that the account has been suspended.
- Inactive - no logins, just like when suspended.
During ad selection, always return a configurable snippet of HTML code, which indicates that the account has been deactivated.

These HTML snippets can be placed in the config file, and/or managed via the UI (optional).

**Comment by mbeccati** [comment]
The feature has been almost fully implemented in a branch. What's missing is the login part which to me requires a bit more thought as status applies to the "agency" entity (or "manager account") whereas logins apply to "users" and the two are completely independent.

**Comment by erikgeurts** [comment]
Wonderful news, thanks for the update.
I was thinking: instead of blocking users from logging in, we might consider an alternative approach were they are allowed to log in, but once they attempt to access a suspended or inactive account, they will only get to see the relevant message "This ad server account has been suspended" instead of the usual UI. That might be more easy since it is a setting/state related to the account, not the user.

**Comment by erikgeurts** [comment]
Having tested this in a release candidate, it seems to be working very well.

It would be wonderful if the two delivery responses about the account being suspended and the account being cancelled, could be added to the UI's delivery settings screen.
