### ISSUE TITLE
Redirected after uploading banner

### ISSUE THREAD

**Issue by agentpublishing** [revive-adserver/revive-adserver#1082]
Redirected after attempting to upload and save banner

Image will upload, the system will allow it to be named/placed/etc. but when save is hit it takes a moment and then redirects me saying I no longer have access to that page.

I fill out the following:
![Screen Shot 2019-07-24 at 11 07 16 AM](https://user-images.githubusercontent.com/53270403/61809617-507cc580-ae03-11e9-9a89-a1a013d9a2e1.png)

Then I hit save. And this appears after a moment:
![Screen Shot 2019-07-24 at 11 08 40 AM](https://user-images.githubusercontent.com/53270403/61809689-6d18fd80-ae03-11e9-9fa0-323139273610.png)

I have full access from my company so should not be redirected for any reason.

**Comment by erikgeurts** [comment]
We prefer to use the issues in the Github project for bugs only. Please consider posting your case in the community forums at https://forum.revive-adserver.com. If it turns out to be a bug after all, we can always re-address it here at a later stage.
