### ISSUE TITLE
Delivery options IP

### ISSUE THREAD

**Issue by henrikpalm** [revive-adserver/revive-adserver#1087]
Hi
Delivery options - client IP does not work for me. 
I'm not sure how search for errors on this. I have checked php to see that it gets $_SERVER['REMOTE_ADDR'] correctly

Revive Adserver v4.2.1 running on nginx 1.14.0, PHP 7.2.19-0ubuntu0.18.04.2 and MySQL 5.7.27-0ubuntu0.18.04.1.

**Comment by erikgeurts** [comment]
Would you be able to try if this still occurs after you upgrade to the most recent version 5.0.1?

**Comment by andrewatfornax** [comment]
No response, closing.
