### ISSUE TITLE
Carousel banner option

### ISSUE THREAD

**Issue by ezhan** [revive-adserver/revive-adserver#1094]
We need the carousel banners: on one placeholder multiple banners, that change every X seconds. It is a popular format for a e-shops. 

It should have scrolling arrows as well, that the client may scroll thru the banners manually. 

Example: https://www.computeruniverse.net/de/

**Comment by andrewatfornax** [comment]
I think it's very unlikely the core team will work on this.

Leaving open in case anyone wants to submit a PR.

**Comment by erikgeurts** [comment]
Given the lack of feedback from the community on this matter, it would appear there is very little to no interest in a feature like this.
