### ISSUE TITLE
How to avoid downloading the .mmdb file when using multiple installations?

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1096]
In a scenario where there are multiple Revive Adserver installations on a single server, it is beneficial to be able to have all of those refer to a single GeoIP2 .mmdb file in a shared location on the server, instead of each installation downloading its own copy of the file.

@mbeccati Can you double check that this has been added to the functionality of the new Geotargeting plugin?

We should document how this can be achieved, and possibly also how to avoid that every new installation or every upgrade performs the initial download.

**Comment by erikgeurts** [comment]
I'm reopening this issue because I think there is also a bit of documentation that we need to create so admins know how to make use of this.

**Comment by erikgeurts** [comment]
Documented at https://documentation.revive-adserver.com/display/DOCS/Geotargeting+Settings

**Comment by mbeccati** [comment]
Nice, thanks!
Perhaps wh should show a screenshot of the plugin configuration screen rather than suggesting to modify configuration files directly.

**Comment by erikgeurts** [comment]
I didn't even realize that it was a setting in the plugin configuration screen!

**Comment by erikgeurts** [comment]
To be honest, I think it is safe to assume that people with the skills and tools to set up their own process for keeping the GeoIP2 files up to date, should have no trouble editing the configuration file either.
