### ISSUE TITLE
Incorrect FROM header on outgoing emails

### ISSUE THREAD

**Issue by jamieburchell** [revive-adserver/revive-adserver#1098]
From: https://forum.revive-adserver.com/topic/4799-wrong-from-address-in-automatic-email/

Please can I request that the Revive team take another look at this, as it's still an issue today.

I already took the step to force an envelope sender address:

```php_value[sendmail_path] = /usr/sbin/sendmail -t -i -fnobody@example.com```

But if you see, it's the other from address that is getting set/mangled by Revive:

```
To: "Administrator" <team@xxx>
Subject: Impending campaign expiration: XXX
X-PHP-Originating-Script: 1005:Email.php
...
From: "n" <n@mymailserver.domain>
X-Original-Authentication-Results: mx.google.com;       dkim=pass
 header.i=@example.com header.s=krs header.b="b/nn6hqL";       spf=pass
 (google.com: domain of nobody@example.com designates XXX as
 permitted sender) smtp.mailfrom=nobody@example.com
```

Line in maillog:

```
Sep 12 00:05:03 x postfix/cleanup[1549]: 9F27F4696CC: prepend: header From: "n" <n> from local; from=<nobody@example.com>: X-Mailgun-Native-Send: true
```

In my Revive config:

```
[email]
logOutgoing=1
headers=
qmailPatch=
fromName="Admin"
fromAddress="no-reply@example.com"
fromCompany="My Company"
useManagerDetails=
```

Further, all of my Advertisers have email addresses and names configured.

I think there's at least one potential issue in the Email.php file [here](https://github.com/revive-adserver/revive-adserver/blob/master/lib/OA/Email.php#L53)

What happens if `$aConf['email']['useManagerDetails']` is `false`? `$aFromDetails` does not get defined but is used further down.

I did look through Email.php, but I'm not familiar enough with the codebase to locate the issue.

TIA

**Comment by mbeccati** [comment]
I think I've seen the bug in action at least once. From the looks of it, Revive tries to access the a string variable as an array with a 0 or string index, and only the first character is returned, e.g. `$aConf['email']['fromAddress']['foo']`.

We'll investigate.

**Comment by jamieburchell** [comment]
I thought the same, given the "n" from "no-reply" but didn't manage to find where it was being accessed as an array

**Comment by jamieburchell** [comment]
My best guess is `$aConf['email']` is the email address string `no-reply@example.com` and accessing `$aConf['email']['fromName'];` and `$aConf['email']['fromAddress'];` returns `n` as well as an Illegal string offset warning. Not sure why it's a string at that point.

**Comment by jamieburchell** [comment]
I'm curious how that change resolves the issue? I see you are setting the variable to be a new array with those keys rather than setting the keys of the array directly.

**Comment by mbeccati** [comment]
`$fromDetails` is null, not an array, so `$fromDetails['foo']` is accessing the variable as string offset (any non numeric string is offset 0) and turning the variable to a 1 character string, raising a notice or warning (ignored in Revive). It used to be different in earlier PHP versions, but right now I can't look up when the behaviour was fixed/changed.

The original code is basically equivalent to:
```
$fromDetails = $aConf['email']['fromName'][0];
$fromDetails = $aConf['email']['fromAddress'][0];
```

**Comment by jamieburchell** [comment]
I don't quite follow the logic there because this is an assignment. If `$fromDetails` is `null`, in my tests:

`$fromDetails['name'] = 'foo';`

Results in an array with key "name" and value "foo".

**Comment by mbeccati** [comment]
You're right. In fact the thing sounded weird as I was typing. The incoming variable is an empty string:
```
// Use the Admin details
$aFromDetails = '';
```

so the fix could as well have been setting that to null.

**Comment by jamieburchell** [comment]
Even as an empty string, the result is the same as my test example.

So I don't believe what you have committed will fix this issue. As far as I can see, it's a different way to create a variable with the same end result.

**Comment by mbeccati** [comment]
Sorry @jamieburchell That's the truth: https://3v4l.org/93hH6

**Comment by jamieburchell** [comment]
Yes, the string "Really" not "R". That's as I expect. So why is Revive taking the first letter?

**Comment by jamieburchell** [comment]
You are absolutely right. I don't know how I came to the conclusion that the result was the same with an empty string as with null. Finally I see!

```<?php

$fromDetails = '';
$fromDetails['email'] = 'nobody@bar';

echo $fromDetails['email'];

// n```

Glad it's fixed anyway.
