### ISSUE TITLE
Recommendation to avoid using _blank

### ISSUE THREAD

**Issue by scott8787979** [revive-adserver/revive-adserver#1106]
I'm surprised you haven't fixed this by now. I've been correcting the code for years now so I decided to report the issue here, but you can't use _blank without rel="noopener". It's probably just better to switch to "external." More info on this issue is at:

- https://developers.google.com/web/tools/lighthouse/audits/noopener

- https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

- https://medium.com/sedeo/how-to-fix-target-blank-a-security-and-performance-issue-in-web-pages-2118eba1ce2f

**Comment by scott8787979** [comment]
I'm surprised you haven't fixed this by now...I've been correcting the code for years now so I decided to report the issue here, but you can't use _blank without rel="noopener". It's probably just better to switch to "external." More info on this security issue is at:

- https://developers.google.com/web/tools/lighthouse/audits/noopener

- https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

- https://medium.com/sedeo/how-to-fix-target-blank-a-security-and-performance-issue-in-web-pages-2118eba1ce2f

**Comment by erikgeurts** [comment]
Feel free to submit a pull request, so we can review this suggestion in its full context.

**Comment by scott8787979** [comment]
Sure, let me know what to select in the two "Compare Changes" drop down boxes that will allow me to post it there and I'll be happy to do that.

**Comment by mbeccati** [comment]
@scott8787979 here's a tutorial on how to create a pull request:
https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

**Comment by scott8787979** [comment]
I appreciate the invite to install software on my local machine and read through a complex guide for how to do this, but I've already done more than 99.9% of people who use this software would do--recommend a security fix to you via this thread. 

If one of you would like to submit this, feel free, but I won't be doing it. I will continue to patch my own version so I'm covered.

Another fix that I highly recommend to you, and I believe I also posted here on this, is to use secure https cookies. You currently use P3P cookies that are insecure, and this triggers security warnings in nearly all of the SEO speed test site audits.

**Comment by erikgeurts** [comment]
Closing since there has been no further feedback.
