### ISSUE TITLE
 Scope :: An error occurred while accessing the database

### ISSUE THREAD

**Issue by andrcami** [revive-adserver/revive-adserver#1112]
HI we are receiving an error when trying to create a zone 'An error occurred while accessing the database'

Revive Version: Revive Adserver v5.0.0

![image](https://user-images.githubusercontent.com/5041074/67385165-db03cb00-f592-11e9-94d8-436d433e3cb2.png)

**Comment by mbeccati** [comment]
> Important notes about MySQL versions
> At the time of this page being updated, MySQL 8.x is NOT supported for use with any version of Revive Adserver, including the upcoming v5.0.0 (scheduled for September 2019).

from https://www.revive-adserver.com/support/requirements/

**Comment by Zer0Divis0r** [comment]
@andrcami , could you be so kind and post the entire query? Does it work on Revive Adserver v5.0.1?
I have PHP 7.1 and MySQL 8.0.18, Revive 5.0.1, and creation of zones works fine.
