### ISSUE TITLE
Prepared statement gives error in acls check function

### ISSUE THREAD

**Issue by Zer0Divis0r** [revive-adserver/revive-adserver#1122]
In Delivery tab of all banners permanently getting the following message: 

> WARNING: The cached delivery rules DO NOT AGREE with the delivery rules shown below
> Please hit save changes to update the cached delivery rules

The problem is that parameter of `->execute($aParams)` is an object with multiple keys, of which only one is actually used in the statement. This results in MDB2 error:
```
_execute: [Error message: Unable to bind to missing placeholder: bannerid]
[Last executed query: PREPARE MDB2_STATEMENT_mysqli_09d3c961005b2b18dd87da2d4c934b89 FROM 'SELECT compiledlimitation, acl_plugins FROM ox_banners WHERE bannerid = ?']
```

Contents of `$aParams` is:
```
Array (
   [clientid] => 1
   [campaignid] => 2
   [bannerid] => 12345
)
```

The fix for this was:
in `lib/ox/lib/max/other/lib-acl.inc.php`, in function `MAX_AclValidate()`
to specify what object is checked, and create `$paramName` with values `bannerid` or `channelid` accordingly, and to change 
```PHP
// from
$oResult = $oStmtAcl->execute([$paramName=>$aParams[$paramName]]);
// to:
$oResult = $oStmt->execute([$paramName=>$aParams[$paramName]]);
```

and 
```PHP
// from:
$oResult = $oStmtAcl->execute($aParams);
// to:
$oResult = $oStmtAcl->execute([$paramName=>$aParams[$paramName]]);
```

Is anyone else getting the problem, or my PHP/PEAR/MDB2/MySQL setup is somehow specific?
I am using MySQL 8.0.16.

**Comment by erikgeurts** [comment]
As per the information on the Requirements page at https://www.revive-adserver.com/support/requirements/ , MySQL 8.x is NOT supported for use with any version of Revive Adserver

**Comment by Zer0Divis0r** [comment]
Thank you.
Are there any specifics, why MySQL 8 would not work, except the specific issue outlined above?

**Comment by mbeccati** [comment]
So:
1. this is in fact a duplicate of #1123 (I know it was reported before), which will be fixed
2. MySQL 8.0 basically dropped the `MYSQL40` SQL mode which is used by Revive Adserver to make MySQL backwards compatible with all its legacy c*ap that is still heavily used in the old Revive Adserver code (e.g. 0000-00-00). As a result table creation fails and surely a number of other things.
