### ISSUE TITLE
Installation fails if default charset of MariaDB is utf8mb4

### ISSUE THREAD

**Issue by jackyhallyday** [revive-adserver/revive-adserver#1124]
During the installation, if Revive Adserver has to create its tables, it uses the default charset of the database, but fails for utf8mb4, which is now a very common charset (you know why 👋).

The installation process doesn't crash for a utf8_bin database. Maybe this very common charset should be enforced?

**Comment by OneAndOnlyOdin** [comment]
Had the same issue I think a list of supported charsets would also be really helpful.
