### ISSUE TITLE
It's 2019, Flash is dead

### ISSUE THREAD

**Issue by jackyhallyday** [revive-adserver/revive-adserver#1125]
"Maybe" it's time to get rid of the Flash support.
It might take some time to spot every line of code about Flash and remove it, but it's pretty simple to remove its support in the javascript code, and have a smaller, faster invocation code.
For instance, with the Async  in /www/delivery/asyncjs.php, comment the
require __DIR__.'/'.$GLOBALS['_MAX']['CONF']['file']['flash'];
line. Done.

**Comment by erikgeurts** [comment]
Feel free to submit a pull request.
