### ISSUE TITLE
Async JS Sends Credentials over XHR

### ISSUE THREAD

**Issue by OneAndOnlyOdin** [revive-adserver/revive-adserver#1131]
Problem:
Due to security considerations credentials of a webapp should obviously not be send to the ad server.

Steps To Reproduce:
Use this code without setting the cors header on your revive instance.

Chrome says

> Access to XMLHttpRequest at 'ZENSORED' (redirected from 'ZENSORED') from origin 'null' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

```html
  <head>
    <script async src="//MYREVIVESERVERHERE/www/delivery/asyncjs.php"></script>
  </head>
  <body>
      <ins data-revive-zoneid="1" data-revive-id="ZENSORED"></ins>
  </body>
```

The ad server code should explicitly avoid sending the credentials because they might be needed for the backend api of the actual webapp.

**Comment by mbeccati** [comment]
"Credentials" include cookies, which are required for some Revive Adserver features to work properly.

I'll keep this ticket open as we could sometimes to better than sending a "*" as Access-Control-Allow-Origin header.

**Comment by lgoehrs** [comment]
HEllo,
I have found a solution arround CORS issue with this:

I would recommend changing this function in lib/max/Delivery/common.php

/**
 * This function sends the anti-caching headers when called
 *
 */
function MAX_commonSetNoCacheHeaders()
{
    MAX_header('Pragma: no-cache');
    MAX_header('Cache-Control: no-cache, no-store, must-revalidate');
    MAX_header('Expires: 0');

    // Also send default CORS headers
    if (!empty($_SERVER['HTTP_ORIGIN']) && preg_match('#https?://#', $_SERVER['HTTP_ORIGIN'])) {
        MAX_header('Access-Control-Allow-Origin: '.$_SERVER['HTTP_ORIGIN']);
        MAX_header("Access-Control-Allow-Credentials: true");
    }
    else
        MAX_header('Access-Control-Allow-Origin: *');
}

**Comment by erikgeurts** [comment]
Could you please elaborate a bit more about what's the actual problem you're facing?

Also, please feel free to create a pull request for your proposed change.

**Comment by lgoehrs** [comment]
Well, when loading dynamically javascript, some brwoser to avoit cross site hacking, will require the use of Access-Control-Allow-Origin. On the latests releases, whenever you have a cookie, it will be considered "with credentials", and using credentials is forbidden when the policy is *

Access-Control-Allow-Origin: *

I saw that a fix was eventually implemented already, but it is not working.
At the ends of the delivery files, we have:
```
if (!empty($_SERVER['HTTP_ORIGIN']) && preg_match('#https?://#', $_SERVER['HTTP_ORIGIN'])) {
header("Access-Control-Allow-Origin: ".$_SERVER['HTTP_ORIGIN']);
header("Access-Control-Allow-Credentials: true");
}
header("Content-Type: application/json");
echo json_encode($spc_output);

```
but for some reason, it is not the right place for it to be used 

When CORS is used, we will also receive in a header the HTTP_ORIGIN. 
We should implement a whitelist, in the database of websites allowed to call us, or we can simply allow them, by simply returning in the Access-Control-Allow-Origin the ORigin of the call.

If we do not, then, the loading of the javascript will be denied by the browser.

I hope this clarifies the query.

**Comment by erikgeurts** [comment]
If you believe this is a generic problem, and you know how to fix it, please feel free to submit a pull request.

**Comment by mbeccati** [comment]
Closing as we can't do anything about the original issue. Solution is to host Revive on a different domain/subdomain so that credentials are not shared with the web app.
