### ISSUE TITLE
Parts of the code are unreadable even for experts

### ISSUE THREAD

**Issue by OneAndOnlyOdin** [revive-adserver/revive-adserver#1132]
I'm a seasoned developer and I still couldn't figure out what the `n` parameter in the iframe option does by reading this file https://github.com/revive-adserver/revive-adserver/blob/master/www/delivery/ck.php#L3165 

Would it be asked to much if a linter would clean up the mess and humans gradually change variable names from single character ones to ones where a new interested contributor or security auditor actually wants to read the code?

**Comment by NiciusB** [comment]
You should read the comments at the beggining of that file 😉

https://github.com/revive-adserver/revive-adserver/blob/ed13c04a2e809b25a7d79c4fbf29c05a73bc89d2/lib/max/Delivery/querystring.php#L68

**Comment by erikgeurts** [comment]
Closing this issue as there has not been any more feedback.
