### ISSUE TITLE
Dev tools warning about cookies

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1136]
A customer using a Revive Adserver v5.0.2 installation on someadserverdomain.com, being used to show ads on somewebsitedomain.com reported that the Chrome dev tools show warnings about cookies, for example:

> A cookie associated with a cross-site resource at http://someadserverdomain.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by Zer0Divis0r** [comment]
Yes, Revive Adserver needs to implement setting the SameSite property for cookies ASAP.
Chrome plans to implement the new cookie security model with Chrome 80 in February 2020. Mozilla and Microsoft have also indicated intent to implement the new model in Firefox and Edge, on their own timelines.
By default, SameSite=Lax would be enforced for all cookies without explicit setting. Lax means that cookie is only sent on same-site requests or top-level navigation over https. That is, it will not be sent with cross-domain GET requests like it happens in Revive with iframe implementation, and with asyncspc. 

I would be happy to be wrong about any of the below, but from the first sight the issue looks pretty serious and complicating the Revive prerequisites. 

All delivery side cookie based functionality would not work after the changes would come to effect, specifically:
- Client-side capping would not work
- Viewer ID cookie would be reset on every request
- Conversion cookie would not work.

From my research, Revive Adserver on delivery side should use:
**SameSite=Lax** is enough, in case the ad server is in the same origin context with publisher website (eg.: revive.example.com and www.example.com
**SameSite=None** in case the ad server and the publisher are in different origins. There is an additional limitation here - to set cookie's SameSite to "None" the cookie has to be **secure**. That means, that if the ad server is installed in a different origin, it will have to be under https to keep the delivery cookies functional.

And one more issue - PHP supports SameSite settings for cookies *only starting from PHP 7.3*.

*To sum up:* 
Installations in the same origin context with publishers would not suffer.
Installations that are outside publisher's origin context would suffer from this change. To fix they will need: updated version of Revive, PHP 7.3+, and the Revive installation under SSL.

_Additional resources:_
- Chrome Developer Documentation: [Web.Dev "SameSite Cookies Explained"](https://web.dev/samesite-cookies-explained)
- Launch Status:[ Cookies default to SameSite=Lax](https://www.chromestatus.com/feature/5088147346030592); and [Reject insecure SameSite=None cookies](https://www.chromestatus.com/feature/5633521622188032)
- Updates related to SameSite: [SameSite Updates](https://www.chromium.org/updates/same-site)
- Developer tips for testing site implications: [Suggested Tips](https://www.chromium.org/updates/same-site?pli=1#20190930)
- Emulation of the changes that will go permanent:
[chrome://flags/#same-site-by-default-cookie](chrome://flags/#same-site-by-default-cookie) - set to "Enabled"
[chrome://flags/#cookies-without-same-site-must-be-secure](chrome://flags/#cookies-without-same-site-must-be-secure) - set to "Enabled"

Code examples:
Specifying samesite property in PHP 7.3:
`setcookie('cookie_name', 'cookie_value', ['samesite' => 'Lax']);`

Setting samesite for session cookie in php.ini:
`session.cookie_samesite=Lax`
in code:
`<? ini_set("session.cookie_samesite", "Lax"); ?>`

**Comment by mbeccati** [comment]
I'm a bit hesitant do add yet another configuration option and deciding what would be the best default for it (i.e. allowing mixed http/https and Lax).

I think we should just accept that https must be configured for ad delivery and go with SameSite=None + Secure. Without a proper https setup, cookie based delivery features would not be working, as @Zer0Divis0r pointed out.

**Comment by mbeccati** [comment]
It also looks like we can make this work on PHP < 7.3 in a variety of ways, e.g.
 * reuse symfony/http-foundation
 * hack setcookie's bug https://bugs.php.net/bug.php?id=69948 that has been fixed in 7.3+
