### ISSUE TITLE
HTTP3 - Ads not showing up with <ins> using Asyncjs.php code? | Revive v4.1.4

### ISSUE THREAD

**Issue by fritexvz** [revive-adserver/revive-adserver#1144]
**CLIENT INFORMATION:**
OS: Windows 8.1 Pro
Web browser: FireFox Developer 73.0b1 - 64bit - hr-hr (Croatian)

**WEBSITE INFORMATION:**
Domain: www.racunalo.com
Revive Adserver (OpenX) v4.1.4 - openx.racunalo.com
- CSP policy, HSTS, X-headers ...

**STATUS:**
 Installed and running on a sub-domain openx.example.com and serving ads on example.com.

**Nginx version:** 1.17.7
**PHP version:** 7.2.26-1+020191218.33+debian9~1.gbpb5a34b
**MySQL version:** 5.7.28 - MySQL Community Server (GPL)

**CloudFlare**
- using HTTP/2 and HTTP/3 with QUIC and 0-RTT is "enabled" on the CloudFlare dashboard
- CDN and features like rocketloader.js are enabled
- HTTPS enabled
- TLS enabled

**Problem description / Issue / Reproduce the problem:**
When wanting to try out HTTP3, went to "about:config" and changed settings "network.http.http3.enabled" to "true".
Restart the Web browser.
Visiting the page with Revive Adserver/OpenX, I got "white boxes" where ads should be loaded, but instead they where not showing up.

I went to look up in the browser console, and there were errors:
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data (1:1282)`

**PICTURE:** https://ibb.co/DwWsdfc

**The code for showing the ads**
For each zone:
`<ins data-revive-zoneid="ZONE_ID" data-revive-id="UNIQUE_ID"></ins>`

Written once in the footer, before closing </body> tag:
`<script async="async" src="//openx.example.com/www/delivery/asyncjs.php" type="text/javascript"></script>`

**WORKING EXAMPLE - ajs.php**
The JavaScript code for showing up ads with ajs.php - is working on the same settings with HTTP3 enabled in Web browser:
example - https://openx.example.com/www/delivery/ajs.php - working

To sumarize and conclude all, Async display of the ads on HTTP3 is not working, while standard JavaScript code works.

Any ideas?

Thank you!

**Comment by erikgeurts** [comment]
That v4.1.4 is extremely outdated. Please upgrade to v5.0.2 or later and try again. I'm not saying it'll magically work, but if this is just about an old version, it would be a great waste of everyone's time.

Also, stop referring to our software as 'openx'. That name was replaced almost 7 years ago.

**Comment by mbeccati** [comment]
The adserver shouldn't be behind a CDN that mangles its JS. Please disable any additional rocketloader or whatnot feature.

**Comment by fritexvz** [comment]
Ok, thank you for advice and suggestions.
Will do and try that out as soon as possible.
