### ISSUE TITLE
Revive Adserver 5.0.3 doesnt work capping

### ISSUE THREAD

**Issue by fh-sitelement** [revive-adserver/revive-adserver#1148]
Revive Adserver version 5.0.3 doesnt work any capping set on campaign or banner. For example if i set campaign capping 1 for session, adserver display banner  each refresh (reloading ctr+R) of page without limit.

**Comment by mbeccati** [comment]
Please make sure you use HTTPS if you want capping to work.

**Comment by fh-sitelement** [comment]
We have set everything via HTTPS. I tried install version 5.0.2 the same setup and capping working well. Version 5.0.3 doesn’t. 

I can send you login details to revive adserver admin 5.0.3 so you can see setup.

 

Here is test page https://sitelement.cdn.platon.sk/DEMO/TEST.html  where u can see that banner with capping 1 adserver diplay each reload page with no limit

So there is no possibility run any campaign.

**Comment by erikgeurts** [comment]
We do not use our Github environment for support. Please post your questions on our forums at https://forum.revive-adserver.com. If it turns out that there is a bug after all, we'll be glad to revisit it here.

**Comment by fh-sitelement** [comment]
But this is bug report

**Comment by fh-sitelement** [comment]
I have added fix but still the same. https://sitelement.cdn.platon.sk/DEMO/TEST.html

**Comment by mbeccati** [comment]
@fh-sitelement both delivery_dev and delivery?

**Comment by mbeccati** [comment]
@fh-sitelement I mean, this is the change that affects the delivery files in the release package:

https://github.com/revive-adserver/revive-adserver/pull/1149/commits/f898324cc9f7ea4ca8305121f368d4d39582b8f5

**Comment by fh-sitelement** [comment]
It is possibility to have some fix for release 5.0.3 to make it work ?

**Comment by mbeccati** [comment]
5.0.4 is planned for that purpose very soon.
