### ISSUE TITLE
Links dont work for emails if zone contains multiple unique banners

### ISSUE THREAD

**Issue by hubertnnn** [revive-adserver/revive-adserver#1150]
If you add more than one banner to an email zone it will break link even if the banners are configured in unique way.

Example:
Zone contains 2 banners:
Banner 1 with delivery rule: "week" = "1"
Banner 2 with variable delivery rule: "week" <> "1"

Links:
```
    <a href='http://example.com/delivery/ck.php?zoneid=1&week=1' target='_blank'>
        <img src='http://example.com/delivery/avw.php?zoneid=1&week=1' border='0' alt='' />
    </a>
    <a href='http://example.com/delivery/ck.php?zoneid=1&week=2' target='_blank'>
        <img src='http://example.com/delivery/avw.php?zoneid=1&week=2' border='0' alt='' />
    </a>
```

Expected result:
Since both links are in unique way specifying only a single banner in the zone it should work

What happened:
Banner does show correctly, but the link shows a blank page instead of redirecting user to target website.

**Comment by erikgeurts** [comment]
You can not have multiple banners actively linked at the same time in an email zone. How did you manage to achieve that?

**Comment by hubertnnn** [comment]
I could add them from both zone settings: `/admin/zone-include.php?affiliateid=1&zoneid=24`
As well as from banner settings: `/admin/banner-zone.php?clientid=1&campaignid=1&bannerid=19`

**Comment by erikgeurts** [comment]
OK, interesting, that's not supposed to be possible.

Either way, an email zone can only have a single banner linked to it at any given time, and that's also where the click will redirect to. See also: https://documentation.revive-adserver.com/display/DOCS/Only+One+Active+Banner+in+Email-Newsletter+Zones

**Comment by hubertnnn** [comment]
That is true, but it says it allows one banner to be active at a time.
If I use delivery rules like in my example, I still have only one banner active at each of those links, but I have multiple assigned to the zone.

**Comment by erikgeurts** [comment]
Closing because there was no further feedback.
