### ISSUE TITLE
async.js - iframe content missing in SPA after element removal and insertion

### ISSUE THREAD

**Issue by karlsve** [revive-adserver/revive-adserver#1151]
Problem:
In an angular application the ad contents are missing after a route change when using the angular router. This is caused by the browsers (chrome/firefox/safari at least) removing the body of the iframe if it was written by using `document.open()`, `document.writeln(...)` and `document.close()` and then removed from the DOM.

To avoid this issue on browsers that would replace this the document write could be refactored to using the srcdoc-attribute, where applicable, that is supported by most major browsers.

Steps To Reproduce:
This can be reproduced on any recent version of the named browsers on a website where nodes are removed and added without full reload. A simplified example can be found [in this jsfiddle](https://jsfiddle.net/karlsve/cqe8fzak/). It also demonstrates the 'correct' behavior if srcdoc or an actual src attribute are used.

**Comment by mbeccati** [comment]
Interesting. That highlights my own deficiencies when it comes to modern JS...

However, I see that there's no compatibility with IE/Edge and older versions of other browsers (possibly still in use? I didn't bother checking at this stage).

I'd be very happy if you could come up with a simple PR that uses `srcdoc` and falls back to the current method when it's not available.

**Comment by karlsve** [comment]
I'll check when I get the time to do so.

For now anyone stumbling onto this can fix the issue temporarily by removing the reviveLoaded data attribute and reapplying the adserver call.

**Comment by erikgeurts** [comment]
I noticed the PR associated with this issue has been assigned to milestone 5.1.0. Can't this be part of the 5.0.5 milestone that's also in the works?
