### ISSUE TITLE
debug.log Questions

### ISSUE THREAD

**Issue by omexlu** [revive-adserver/revive-adserver#1152]
Hello,

The debug.log file is getting bigger and bigger, currently around 300MB, is there a rotation that automatically deletes or clears it?

Or can I simply delete it in the FTP folder and disable it in the settings?

Thanks in advance.

**Comment by mbeccati** [comment]
No rotation is happening, nor it is planned: there are plenty of tools that do that very well.

I don't think it is wise to completely disable it, but you can decide to do that.

**Comment by omexlu** [comment]
Ok, thank you.

Even if I should not deactivate the function, can I empty or delete it completely? Will it be created again after deletion?

**Comment by mbeccati** [comment]
Yes it will.
