### ISSUE TITLE
Admin :: hitting any save button doesn't respect admin interface URL

### ISSUE THREAD

**Issue by legezam** [revive-adserver/revive-adserver#1154]
Problem:
If revive webserver is configured such a way where the admin interface url is set to something like `example.com/foo/www/...` instead of the default `example.com/www/...` then save buttons are sending post requests to the default `example.com/www/...` instead of `example.com/foo/www/...`

Steps To Reproduce:
`You are currently using Revive Adserver v5.0.2 running on nginx 1.16.1, PHP 7.3.13 and MySQL 5.7.28-.`
I have this setup:
Running revive behind a reverse proxy in a docker env: [image](https://hub.docker.com/r/krish512/revive/).
Host system:
apache2 set up as reverse proxy to forward everything to a container exposed on 8080 port on localhost. The apache on the host system has ssl enforced.
This is the reverse proxy configuration:
```
	ProxyPass /foo http://0.0.0.0:8080/
	ProxyPassReverse /foo http://0.0.0.0:8080/
	ProxyPassReverseCookieDomain "example.com" "example.com"
	ProxyPassReverseCookiePath "/" "/foo/"
```

Inside revive i set the Admin interface URL accordingly to:
`example.com/foo/www/admin`

Also set forceSSL in revive configuration to 1

And admin UI shows up, i can navigate through screens without any issues. I expect the setup is correct.

However, when making any changes on the UI and hit save button, i get 404 page not found errors, because it seems the save operation doesn't respect the custom url of the admin UI.
It sends the email changing POST request to: `https://example.com/www/admin/account-settings-email.php`
Instead of: `https://example.com/foo/www/admin/account-settings-email.php`

I don't think it has anything to do with the reverse proxy setup but that's just a guess.

Thanks for the help!

**Comment by mbeccati** [comment]
This is not a bug, please post your support requests to our forum instead.

However, you might just need to update the admin URL in your configuration file.
