### ISSUE TITLE
Bug during the baner upload (jpeg, gif) on Revive 5.0.4 

### ISSUE THREAD

**Issue by fritexvz** [revive-adserver/revive-adserver#1159]
Hello,
I've got the following error recently: 

>  An error occurred while accessing the database
>
>Due to a problem with the database Revive Adserver couldn't retrieve or store data. If this problem is reproducable it might be caused by a bug in Revive Adserver. Please report the following information to the creators of Revive Adserver. Also try to describe the actions that led to this error as clearly as possible.
>
>Version:       Revive Adserver v5.0.4
>PHP/DB:    PHP 7.2.28-4+0~20200224.38+debian9~1.gbp1ca010 / Unknown 5.7.29-
>Page:    /www/admin/banner-edit.php
>Error:    
>Query:    
>INSERT INTO ox_banners (campaignid , contenttype , pluginversion , storagetype , filename , imageurl , htmltemplate , htmlcache , width , height , weight , target , url , alt , statustext , bannertext , description , adserver , alt_filename , alt_imageurl , alt_contenttype , comments , updated , keyword , parameters , status , iframe_friendly ) VALUES ( 196 , 'gif' ,  0 , 'web' , 'a79289c5ee4c35f9bdfc08a4206730fe.gif' , '' , '' , '' ,  300 ,  250 ,  1 , '_blank' , 'https://www.hrvatskitelekom.hr/pogodnosti/diners?utm_source=racunalo.com&utm_medium=display&utm_campaign=diners-03-2020&utm_content=300x250' , '' , '' , '' , 'HT Diners Pogodnosti (300x250)' , '' , '' , '' , '' , '' , '2020-03-10 19:23:12' , 'HT Diners Pogodnosti' , 'N;' ,  0 ,  0 )
>
>$_POST:    
>
>Array
>(
>    [_qf__bannerForm] =>
>    [token] => 3ad72414b03898e6a30d01be3fee4f82
>    [clientid] => 41
>    [campaignid] => 196
>    [bannerid] =>
>    [type] => web
>    [status] =>
>    [MAX_FILE_SIZE] => 10485760
>    [replaceimage] => t
>    [replacealtimage] => t
>    [description] => HT Diners Pogodnosti (300x250)
>    [checkswf] => 1
>    => https://www.hrvatskitelekom.hr/pogodnosti/diners?utm_source=racunalo.com&utm_medium=display&utm_campaign=diners-03-2020&utm_content=300x250
>    [target] => _blank
>    [alt] =>
>    [statustext] =>
>    [bannertext] =>
>    [keyword] => HT Diners Pogodnosti
>    [weight] => 1
>    [comments] =>
>    [submit] => Save changes
>)
>
>$_GET:    
>
>Empty

**Comment by fritexvz** [comment]
The banner is successfully uploaded, but this error happens

**Comment by fritexvz** [comment]
Image link: https://imgur.com/X3iiLLU

**Comment by mbeccati** [comment]
My guess is that an unsupported version of MySQL is being used here.

**Comment by fritexvz** [comment]
Solved: config was old, and database structure old.

I had to have change it to support old mysql in the conf file, so it works.
Also, uncheck the "mysql persistent connection".
