### ISSUE TITLE
HTML5 banner zip - field "destination link" not working

### ISSUE THREAD

**Issue by fritexvz** [revive-adserver/revive-adserver#1163]
I am using Revive Adserver v5.0.4.

When I try to upload the HTML5 .zip package of the baner, it works well.
But, when I add the destination URL to the field "destination link", the banner is not clickable.
The "anchor" around the banner, either no link via Revive Adserver URI is not added.
So it cannot be tracked that way by the linked zone/campaign.

I have to put the destination URL directly into the index.html of the .zip file which I uploaded.

But, also I have to make it in my index.html of the .zip file to be and look like:
https://marketiong.example.com/www/delivery/ck.php?oaparams=2__bannerid=BANERID__zoneid=ZONEID__cb=CUSTOMSTRING__oadest=ENCODED_URL_LINK

And re-upload the modified .zip file (index.html and other assets) so it could work.

Any other having some issues?

Thanks!

**Comment by mbeccati** [comment]
Please use our forums for support questions.

Have a look at https://support.google.com/admanager/answer/7046799?hl=en to see how to properly use HTML5 clicktags.
