### ISSUE TITLE
asseteer not working propertly in windows

### ISSUE THREAD

**Issue by matiasperrone** [revive-adserver/revive-adserver#1168]
I think you should consider publish your asseter package in https://packagist.org/ because the repository (figdice/asseteer) is now abandoned, two years for join a PR?...

**Comment by andrewatfornax** [comment]
Closing. We have no such package, and state in a number of locations that Revive Adserver should only be installed using our official package from our website.

**Comment by mbeccati** [comment]
We do have our fork in https://github.com/revive-adserver/asseteer

However, I'd be more tempted to find a suitable replacement than to publish an abandoned project or try to support it.
