### ISSUE TITLE
Non static method should not be called statically

### ISSUE THREAD

**Issue by matiasperrone** [revive-adserver/revive-adserver#1170]
Version: 5.0.5

There are numerous problems like these:
lib/OA/Creative/File.php (4  #calls)
![static_calls](https://user-images.githubusercontent.com/2567511/83656509-04a7ba80-a596-11ea-88f9-29e32eefea4c.jpg)

I think this will be a problem in future versions of PHP.

**Comment by mbeccati** [comment]
This should be fixed in de667a1892b2b4679c51500102ea4385a51909e7
