### ISSUE TITLE
Update to Vers. 5.0.5: "Revive Adserver v5.0.5 (warning: database is stamped as v4.2.1)"

### ISSUE THREAD

**Issue by forummedia** [revive-adserver/revive-adserver#1183]
Hi Adserver Team,

- detailed description of the issue.

We tried to update from 4.2.1 to 5.0.2 and got that waning after sucessfull update: "**warning: database is stamped as v4.2.1"**

From 5.0.2 we tried to update to 5.0,3 -> 5.0.4 -> 5.0.5  but the warning is still there.

-  Full Warning Text:

"Sie nutzen derzeit Revive Adserver v5.0.5 **(warning: database is stamped as v4.2.1) ** laufend auf **Apache, PHP 7.2.29-1+0~20200320.39+debian9~1.gbp513c2e und MySQL 5.5.5-10.1.44-MariaDB-0+deb9u1."**

- Workaround we tried:

editing the the value of **oa_version** in **table rv_application_variable**  solved the warning. 
Is this the appropiate workaround? Is the database migrated correctly?

What else can we do to perform this upgrade?

Please let us know if providing any data etc could help.

Best regards and thanks in Advance,
Jessica

**Comment by matiasperrone** [comment]
ADD a UPGRADE file in var directory

**Comment by erikgeurts** [comment]
See https://www.revive-adserver.com/support/upgrading/ for the recommend upgrade procedure.
