### ISSUE TITLE
Does Revive support video ads does it have a built in Rest api?

### ISSUE THREAD

**Issue by elieobeid7** [revive-adserver/revive-adserver#1188]
My company is in the video streaming business, we'd like to offer video ads like Youtube. Does revive offer that option? I did not see that option in the tutorials.

Also, does it have a built-in rest API? We're not really interested in buying https://www.reviveadserverrestapi.com/. It seems kind of a rip off to pay $1000 for a rest API in 2020, in this day and age all software have a built-in API, especially the most popular ones, and Revive market itself as being the most popular open-source Ad server,.

If there's no REST API, does revive support some other built-in protocol we can use to send the ads to the mobile?

**Comment by erikgeurts** [comment]
This is primarily for posting bug reports and related matters. Please consider posting your questions on our community forums at https://forum.revive-adserver.com/ .

**Comment by elieobeid7** [comment]
the forum page is a mess, check how it looks, unusable, in fact, the website needs some work too.


![Capture](https://user-images.githubusercontent.com/660142/86902787-19d4b380-c117-11ea-91fe-4b6971212087.PNG)

**Comment by elieobeid7** [comment]
Ahh it's because I have an ad blocker enabled. Ok now it looks good, will ask there

**Comment by erikgeurts** [comment]
If you're working in the ad business and are using an ad blocker...

**Comment by elieobeid7** [comment]
I'm not working in the business of ads, I'm working in the streaming business and we don't get paid by ads, we get paid by direct subscriptions. the CTO wants to sell ads, not me, personally fuck ads.

**Comment by erikgeurts** [comment]
Sounds to me like you need to find a new job then. Also, you edited your comment, but I did see what you wrote initially. A bit more respect would help in getting assistance from us. If it happens again I will not hesitate to block you.
