### ISSUE TITLE
Install Revive-Adserver v5.0.5 

### ISSUE THREAD

**Issue by Konstantinos-Socialab** [revive-adserver/revive-adserver#1189]
Hi Adserver Team,

I am trying to install stable version 5.0.5 and I get the following error: 

> Fatal error: Uncaught TypeError: Argument 1 passed to RV\Container::__construct() must be of the type array, boolean given, called in /xxx/xxxx/xxxx/xxxx/xxxxxxx/public/init.php on line 65 and defined in /xxx/xxxx/xxxx/xxxx/xxxxxxx/public/lib/RV/Container.php:38 Stack trace: #0 /xxx/xxxx/xxxx/xxxx/xxxxxxx/public/init.php(65): RV\Container->__construct(false) #1 /xxx/xxxx/xxxx/xxxx/xxxxxxx/public/init.php(143): init() #2 /xxx/xxxx/xxxx/xxxx/xxxxxxx/public/index.php(21): require_once('/xxx/xxxx/xxxxx...') #3 {main} thrown in /xxx/xxxx/xxxx/xxxx/xxxxxxx/public/lib/RV/Container.php on line 38

The database has been created. The only tables that have some records are rv_application_variable and rv_upgrade_action. 
All other tables are empty.
I have checked all the requirements of the server and the softwares that are needed, I run php7.2. 
What should I do to solve this issue?

**Comment by erikgeurts** [comment]
As far as I can tell, this doesn't look like a bug. Please consider posting your question on our community forums at https://forum.revive-adserver.com.

**Comment by matiasperrone** [comment]
Are you using MySQL 8? because is not fully compatible...

**Comment by erikgeurts** [comment]
Closing because there was no feedback.
