### ISSUE TITLE
revive-adserver websites don't render correctly + no downloads are possible

### ISSUE THREAD

**Issue by humantex** [revive-adserver/revive-adserver#1190]
Nothing seems to be working on any of the main sites. No downloads are possible for any version. The main site has rendering issues and no styling, and the forum is even worse. Links are missing or dead, or generating errors everywhere.

**Comment by erikgeurts** [comment]
Sites are working just fine for me.

Most likely you have an ad blocker installed/active.

**Comment by erikgeurts** [comment]
Closing due to lack of feedback.
