### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by matiasperrone** [revive-adserver/revive-adserver#1191]
These are some of the more important changes:

- The **ability to call non-static methods statically was removed** on the alpha version.
- The default error_reporting level is now E_ALL. Previously it excluded E_NOTICE and E_DEPRECATED.
- get_magic_quotes_gpc() and get_magic_quotes_gpc_runtime() has been removed.
- Removed each(). foreach or ArrayIterator should be used instead.

Check this out:
https://github.com/php/php-src/blob/php-8.0.0alpha3/UPGRADING

**Comment by mbeccati** [comment]
Thanks. I'm afraid there's much more than that. It is going to be a challenge to bring Revive into PHP8 territory.

**Comment by matiasperrone** [comment]
Yeah I think so... maybe I can provide some PRs?
Are you interested?

**Comment by mbeccati** [comment]
Any help is very welcome. I will re-enable the Bamboo job for PHP8 - that can serve as a starting point to find all the various incompatibilities. One separate PR and branch for each kind of them would be probably easier to review.

**Comment by matiasperrone** [comment]
What about using `php8-` prefix, for example `php8-static-calls`

**Comment by mbeccati** [comment]
https://revive.beccati.com/bamboo/browse/REV-LP-PMP-2295/log

Issues start with composer update... we will probably need to review the minimum required PHP version too, PHP 7.2 is approaching EOL.

**Comment by matiasperrone** [comment]
PHP 8.0.0 Beta 1 available for testing (https://www.php.net/archive/2020.php#2020-08-06-3)

**Comment by matiasperrone** [comment]
The next release will be Beta 2, planned for Aug 20 2020.

**Comment by Bigbear7** [comment]
Hi, What's the status on this one regarding PHP 8 compatibility? E.g. how ready is Revive 5.2 and plans for 5.3?

**Comment by mbeccati** [comment]
@Bigbear7 It's an ongoing (massive) effort. As of today the status of my experimental php8 branch is: 287 tests in total 56 tests failed (+4 failing on PHP 7.4 due to the changes I've done). When I started, the test suite wasn't even running and the first successful run had 240 failing test files.

**Comment by mbeccati** [comment]
After the release of 5.2.1, master has now become 5.3.0-dev and I've just merged the PHP8 compatibility changes I've been doing for the past few months. Tests are green and all errors in UI/dev/maintenance I could find have been fixed.

Release candidates will be packaged in the coming weeks to allow the community to test what will become Revive Adserver 5.3.0.

**Comment by Bigbear7** [comment]
Is there a release candidate for 5.3.0 available?

**Comment by erikgeurts** [comment]
> Is there a release candidate for 5.3.0 available?

https://www.revive-adserver.com/blog/release-candidate-1-for-revive-adserver-v5-3-0/

**Comment by Bigbear7** [comment]
Really nice! I will go ahead and test it. We run Revive 4.2 as a local installation on a dedicated server today.

**Comment by erikgeurts** [comment]
Remember: staging only!

**Comment by Bigbear7** [comment]
Of course! Anyway, I just updated Revive from 4.2 to 5.3-RC1 on our test server. It was a bit iffy, but after some trial & error I succeeded. The steps were:
- Backup 4.2 DB and keep old installation in place
- Copy RC1 to ads5 directory
- Copy old config file exactly as is (got warning  about rv_preferences table), e.g. no changes of directory paths
- Run Revive upgrade that converts DB etc
- Test new install and find that it jumps seamlessly to old one ;-)
- Rename old install dir (ads) and rename new install (ads5) to old dir (ads)
- Test new install again and all widgets are empty, hm... -> empty /ads/var/templates_compiled -> it works!
- Test with an ad from an old campaign and voilà it shows on test site.
- Switch PHP version from 7.4.22 to 8.0.9 and logs are not flooded with warnings :-)

One remaining item is that my WAF blocks Revive for certain operations, but that's outside the upgrade. So now eagerly waiting for 5.3 GA release!

r//Björn L

**Comment by Bigbear7** [comment]
Of course! Anyway, I just updated Revive from 4.2 to 5.3-RC1 on our test server. It was a bit iffy, but after some trial & error I succeeded. The steps were:
- Backup 4.2 DB and keep old installation in place
- Copy RC1 to ads5 directory
- Copy old config file exactly as is (got warning about rv_preferences table), e.g. no changes of directory paths
- Run Revive upgrade that converts DB etc
- Test new install and find that it jumps seamlessly to old one ;-)
- Rename old install dir (ads) and rename new install (ads5) to old dir (ads)
- Test new install again and all widgets are empty, hm... -> empty /ads/var/templates_compiled -> it works!
- Test with an ad from an old campaign and voilà it shows on test site
- Switch PHP version from 7.4.22 to 8.0.9 and logs are not flooded with warnings & errors :-)

One remaining item is that my WAF blocks Revive for certain operations, but that's outside the upgrade. So now eagerly waiting for 5.3 GA release!

r//Björn L

**Comment by erikgeurts** [comment]
Update process described in great detail here: https://www.revive-adserver.com/how-to/update/

Please open a new issue for any bugs or anomalies.

**Comment by Bigbear7** [comment]
Yes, I used these instructions but I think they can be improved. So, when the GA release is out I will rerun the upgrade procedure more thoroughly and file an issue if needed.

**Comment by erikgeurts** [comment]
I have personally run updates following this procedure at least 500 times (if not more often), never had any major issues.

**Comment by Bigbear7** [comment]
Well, for me it was more reading the fine print of these instructions ;-) E.g. I never needed to update any config file, just use the old one exactly as is.

**Comment by erikgeurts** [comment]
> I never needed to update any config file, just use the old one exactly as is.

If that's the case, then you're not doing it as per the recipe.

**Comment by Bigbear7** [comment]
I got this message that I had an rv_preferences table and that I needed to use old config file (or how it now was). First I changed the 4.2 config file so that it pointed to ads5 directory, but then when I renamed the new installation dir to ads directory it didn't work.

I will revisit the upgrade procedure when the GA is out to more accurately pinpoint things if there are any. Anyway, I think it's good that some concentrated work during less then one day succeeds in upgrading the Revive server!

**Comment by erikgeurts** [comment]
> I got this message that I had an rv_preferences table and that I needed to use old config file (or how it now was). First I changed the 4.2 config file so that it pointed to ads5 directory, but then when I renamed the new installation dir to ads directory it didn't work.
 
This appears to indicate that you didn't follow the update process to the letter.

**Comment by Bigbear7** [comment]
I ran the upgrade script and it connected successfully to the existing DB and then I got the message about rv_preferences table and acted accordingly to what the upgrade script said. I don't have time to rerun it now so I can provide you with the exact details, but I will do it when the 5.3 is out.

Anyway, the upgrade succeeded so now one stumbling block is gone for migrating the production site to 8.0!

**Comment by Bigbear7** [comment]
As a final note, this is the message I got during the upgrade procedure which lead me to copy the old config file as is:
- "Your database contains an old OpenX configuration table: rv_preferences. If you are trying to upgrade this database, please copy your existing configuration file into the var folder of this install. If you wish to proceed with a fresh installation, please either choose a new Table Prefix or a new Database."

**Comment by mbeccati** [comment]
@Bigbear7 possibly the most essential part of the upgrade procedure is to copy the configuration file over. Which you skipped until being reminded by Revive itself as you were trying to re-install it over the existing one ;-)
