### ISSUE TITLE
Customize Favicon

### ISSUE THREAD

**Issue by s1-ranjan** [revive-adserver/revive-adserver#1195]
By default, the favicon file that is been used is located in /www/admin/assets/images folder and by replacing the favicon file will solve the problem for a single install version of Revive adserver, but the real problem occurs when a single copy of the adserver is been used for multiple different sites, so it would be nice if there is an entry for a favicon in the setting that can take care of this small issue. I am sharing a screenshot of this issue. 
![Screenshot from 2020-08-23 17-17-01](https://user-images.githubusercontent.com/20767253/91065041-a39bfa00-e64d-11ea-8012-f80a8c53dca4.png)

**Comment by erikgeurts** [comment]
It's generally best to open separate issues for separate topics.

**Comment by s1-ranjan** [comment]
It was my mistake and I put both the issue in one, from next time this will not be repeated.

**Comment by erikgeurts** [comment]
Why don't you just create a second issue, and then edit the first one. Then we can discuss them both separately.

**Comment by erikgeurts** [comment]
The favicon is being used for the ad management and statistics UI only, it's not relevant for the ads being served to multiple websites. Can you please elaborate why you need to customize the favicon?

**Comment by s1-ranjan** [comment]
I wish to reflect revive-adserver is associated with a particular domain, by using the domain-specific favicon this will appear as each individual adserver is associated with a specific domain.

**Comment by erikgeurts** [comment]
I'm afraid this is currently not a feature, and I doubt we'll ever implement this. However, you are free to submit a Pull Request for this.

**Comment by erikgeurts** [comment]
Note that if you wish to have another favicon show up, you can simply replace the file that comes with the Revive Adserver download and use your own icon.

Since there hasn't been any further community feedback on this, we're closing this issue.
