### ISSUE TITLE
Compatibility issue with the Brave browser

### ISSUE THREAD

**Issue by s1-ranjan** [revive-adserver/revive-adserver#1196]
By default, Brave browsers block all types of cross-site trackers and the same is applied to the single instance of revive adserver on multiple domains.
![Screenshot from 2020-08-23 19-40-19](https://user-images.githubusercontent.com/20767253/91065687-6e43dc00-e64e-11ea-8f77-2d8f192ce7db.png)
I was facing a similar issue with Matomo, but the issue was been resolved by using a script (**Matomo Tracker Proxy**) which was hiding the Matomo server in the background without revealing the Matomo server URL, it would be great if Revive adserver uses something similar approach to hide the real URLs using some proxy script.

**Comment by mbeccati** [comment]
> Brave is a free and open-source web browser developed by Brave Software, Inc. based on the Chromium web browser. It blocks ads and website trackers

Sorry, we're not going to fight ad blockers or similar technologies. If one decides to block ads, that's their choice.
