### ISSUE TITLE
[Question/Feature] How to check if a banner has been loaded or not?

### ISSUE THREAD

**Issue by yesworld** [revive-adserver/revive-adserver#1197]
_Revive Adserver version 5.0.5_

Hello team.

Q1. I have several zones where banners are displayed. Sometimes a banner is removed from publication, but the zone stays on a page. How can I use JavaScript to determine in which zone the banner is missing (zone is empty)?

Q2. Is there any Callback (JS function) that the banner in the zone number # has been loaded?

I already asked on the [forum](https://forum.revive-adserver.com/topic/5893-how-to-check-if-a-banner-has-loaded-or-not/), but there is still no answer.
P.s. If this isn't implemented, then you can add the **New Feature** tag.

Thank you for your attention!

**Comment by erikgeurts** [comment]
@yesworld It is strongly recommended to open separate issues for separate topics. Either way, we prefer to use Github issues for actual bugs, not for support questions.

Regarding Q1: this is not possible.

Regarding Q2: no. If you'd like to request this as a feature, create a new issue please. Also, provide as much information and/or examples as possible. This does not mean we'll take your request on board, but it does allow us to more carefully consider it.
