### ISSUE TITLE
Allow payments for ads with "cloned" GoodDollar

### ISSUE THREAD

**Issue by vporton** [revive-adserver/revive-adserver#1198]
[GoodDollar](https://gooddollar.org) is a UBI open to everyone.

I have [allowed](https://github.com/GoodDollar/GoodContracts/pull/205) to "clone" GoodDollar creating a new smart contract that receives money from GoodDollar UBI but allows to spend it independently of the main GoodDollar value.

Let us "clone" it and use the resulting ERC-20 to support inclusive journalism/blogging: Everybody is given a sum of money to pay for ads of his or her blog or other site. It is to promote inclusivity and equality. The "cloning" is needed because if somebody needs to spend more for bread, he his inclusiveness in journalism should not decrease.

Please create the smart contract and use its money to accept payments for ads. The amount of the ads given to the UBI receivers should be configurable (or better yet calculated by some (clever?) formula).

We could also accept (under a different price per ad) ads from regular GoodDollar.

**Comment by erikgeurts** [comment]
How/why is this relevant to Revive Adserver?

**Comment by mbeccati** [comment]
Doesn't seem relevant to me. Closing.

**Comment by vporton** [comment]
Why did my last comment disappear? Is it a bug? I am repeating it again.

It is relevant for Revive Adserver because it involves adding a new payment method to Revive Adserver. Moreover, during this, we can also easily accept general Ethereum and Fuse.io payments, as a useful for you feature, as a side effect of fulfilling this issue.

Or do you think that inclusive journalism is not relevant? At least we should give publishers the freedom to choose whether they support inclusive journalism.

Please reopen.

**Comment by erikgeurts** [comment]
Nothing was removed, it simply never arrived here.

As said, this is not relevant, Revive Adserver does not accept payments directly (nor indirectly), so adding a new payment is not relevant. The issue you opened looks remarkably similar to spam for the sake of getting links. I'm removing these URLs.

**Comment by vporton** [comment]
@erikgeurts So, suppose I am a publisher using Revive Adserver and want to get paid for my ads. How do I receive payments?

What about integrating payments into Revive Adserver in the future?

**Comment by vporton** [comment]
@erikgeurts It is in PHP? I know PHP. If I will in a few months create a pull request to integrate some kinds of crypto payments, will you accept the PR?

**Comment by erikgeurts** [comment]
Yes, it is PHP. Personally, I doubt we'll consider a payment integration using crypto only.
