### ISSUE TITLE
What's the purpose of these two database tables?

### ISSUE THREAD

**Issue by 420Banners** [revive-adserver/revive-adserver#1200]
These two tables in our database are very large:

b_data_intermediate_ad
b_data_summary_ad_hourly

Can you tell me what their purpose is and why they're so large?

**Comment by erikgeurts** [comment]
As mentioned, we do not offer dedicated support with the service. You can consider posting your question at https://forum.revive-adserver.com/ .

**Comment by 420Banners** [comment]
We have but the forum is dead. We rarely get replies and bumping doesn't make a difference. 

https://forum.revive-adserver.com/topic/5913-whats-the-purpose-of-these-two-database-tables/

The developers should be most familiar with the software, its database and its tables. It wouldn't take 5 minutes for someone to  tell  us what the purpose of it is to conclude if it's normal or not. 

If this ends up being a bug, it'll go ignored. How do you prove it's not buggy code filling up the database with junk?

**Comment by erikgeurts** [comment]
Please be patient, it can take days or weeks until a fellow community member will respond to the post.

The two tables you mentioned contain crucial data, it is certainly not junk. Their size is perfectly normal.

**Comment by 420Banners** [comment]
Hi Erik,

 

With all due respect, what’s the purpose of the support forums if nobody answers the bug reports?

 

We’ve been bumping threads for months with no attention.

 

Greenest Regards,

Webmaster

 

420 Magazine

PO Box 3420

Hollywood, CA 90078

1-888-420-MAGG

http://www.420magazine.com <http://www.420magazine.com/> 

http://www.twitter.com/420magazine

http://www.youtube.com/420magazine 

http://www.facebook.com/420magazine

http://www.instagram.com/420magazine 

 

 

Confidentiality Notice. This e-mail is covered by the Electronic Communications Privacy Act, 18 U.S.C. Sections 2510-2521 and is legally privileged. This e-mail is the property of 420 Magazine, Inc. and contains confidential and/or privileged information. This e-mail is intended to be received and reviewed only by the individual named above. Any review, use, dissemination, disclosure or copying of this e-mail or any attachments is strictly prohibited. If you have received this e-mail in error, please immediately notify the sender at support@420magazine.com <mailto:support@420magazine.com>  and delete all copies of the e-mail and any attachments. Thank you for your cooperation and assistance.

**Comment by 420Banners** [comment]
Yes but our database is 5GB, we want to know if there is a problem or if we should just reset everything.

 

Greenest Regards,

Webmaster

 

420 Magazine

PO Box 3420

Hollywood, CA 90078

1-888-420-MAGG

http://www.420magazine.com <http://www.420magazine.com/> 

http://www.twitter.com/420magazine

http://www.youtube.com/420magazine 

http://www.facebook.com/420magazine

http://www.instagram.com/420magazine 

 

 

Confidentiality Notice. This e-mail is covered by the Electronic Communications Privacy Act, 18 U.S.C. Sections 2510-2521 and is legally privileged. This e-mail is the property of 420 Magazine, Inc. and contains confidential and/or privileged information. This e-mail is intended to be received and reviewed only by the individual named above. Any review, use, dissemination, disclosure or copying of this e-mail or any attachments is strictly prohibited. If you have received this e-mail in error, please immediately notify the sender at support@420magazine.com <mailto:support@420magazine.com>  and delete all copies of the e-mail and any attachments. Thank you for your cooperation and assistance.

**Comment by 420Banners** [comment]
Specifically, could a 5GB Revive AdServer database slow down page loads when serving thousands of banners simultaneously?

 

Greenest Regards,

Webmaster

 

420 Magazine

PO Box 3420

Hollywood, CA 90078

1-888-420-MAGG

http://www.420magazine.com <http://www.420magazine.com/> 

http://www.twitter.com/420magazine

http://www.youtube.com/420magazine 

http://www.facebook.com/420magazine

http://www.instagram.com/420magazine 

 

 

Confidentiality Notice. This e-mail is covered by the Electronic Communications Privacy Act, 18 U.S.C. Sections 2510-2521 and is legally privileged. This e-mail is the property of 420 Magazine, Inc. and contains confidential and/or privileged information. This e-mail is intended to be received and reviewed only by the individual named above. Any review, use, dissemination, disclosure or copying of this e-mail or any attachments is strictly prohibited. If you have received this e-mail in error, please immediately notify the sender at support@420magazine.com <mailto:support@420magazine.com>  and delete all copies of the e-mail and any attachments. Thank you for your cooperation and assistance.

**Comment by erikgeurts** [comment]
> Hi Erik, With all due respect, what’s the purpose of the support forums if nobody answers the bug reports? We’ve been bumping threads for months with no attention.

It's not a bug, this is intended to work like this. It's not a Support forum, it's a Community forum.

**Comment by erikgeurts** [comment]
> Yes but our database is 5GB, we want to know if there is a problem or if we should just reset everything.

5 Gigabyte is not a lot. No need to reset anything.

**Comment by erikgeurts** [comment]
> Specifically, could a 5GB Revive Adserver database slow down page loads when serving thousands of banners simultaneously?

No, these 2 tables are not involved in the delivery of the ads, they are just for the statistics (historical data). Of course, if you're running on a server that can't even handle 5 GB of disk usage for database, it might be time to upgrade the server.

**Comment by erikgeurts** [comment]
This will be my last response on this non-issue. Forums from now on.
