### ISSUE TITLE
Delivery rules (site page url) not working in all browsers

### ISSUE THREAD

**Issue by michaelp66** [revive-adserver/revive-adserver#1201]
Problem:
Revive 5.0.5, no additional plugins or mods
Delivery rule "Site - Page URL" doesn't seem to work in all browsers (iframe delivery).

Example:
Green banner - no rules
Red banner - one rule, "Site - Page URL" does not contain "-promo"

https://praca.farmacja.pl/sites/default/files/ads_test.html
https://praca.farmacja.pl/sites/default/files/ads_test-promo.html

Latest Firefox, Edge, Opera GX - it works as intended, ads_test-promo doesn't show red ad
Latest Chrome, Safari (not tested by me), Firefox private mode - doesn't work, red ad shows on ads_test-promo

What could be a problem, I could not find the answers - is this a bug in Revive?
We can't use async because it doesn't work with our WordPress sites and everything is programmed around iframes.

**Comment by erikgeurts** [comment]
This is not a bug, it's an unfortunate side effect of how iframes behave in some browsers. The ad server will see the ad delivery URL of the iframe, and not the page URL.

**Comment by michaelp66** [comment]
OK, thank you.
