### ISSUE TITLE
Support for emojis (utf8mb4_unicode_ci)

### ISSUE THREAD

**Issue by soknifedev** [revive-adserver/revive-adserver#1203]
Problem:
You can't use emojis in banners. trying so will result in the removal of the emoji. This happens because of the table charset codification (`utf8_unicode_ci`). Changing manually the table's charset to the needed one (`utf8mb4_unicode_ci`) may result in unexpected bugs and/or malfunction of the adserver.

Steps To Reproduce:
Try to place a symbol, or an emoji in a banner title, or banner content.

**Comment by erikgeurts** [comment]
We welcome feedback from the community about the desirability of including emojis in banners.

**Comment by erikgeurts** [comment]
Given the lack of feedback on this issue, it appears there is no particular interest to add this.

**Comment by mbeccati** [comment]
Duplicate of #1124
