### ISSUE TITLE
Increase imageurl beyond 255

### ISSUE THREAD

**Issue by magazinexperts** [revive-adserver/revive-adserver#1204]
Problem:
When using the url banner type (link to an external banner) the image field is limited to 255 characters. Some images hosted on a CDN, or by some third party ad servers are more than 255 characters (Flash Talking is one example, their impression tags can be well over 500 characters, and I'm sure there are others)

Steps To Reproduce:
Create a remote image banner and enter any URL over 255 characters for the image URL. Save the banner, then review the URL - it will have been trimmed, silently, to 255 characters.
If you want, you can change the column type to text in your database, save a longer URL and then compare it, it will work now. It does seem there's a handful of hardcoded text references in Revive Adserver's code to this being a 255 character field.

I am currently using Revive Adserver v5.0.5 running on Apache 2.4.29, PHP 7.2.30-1+ubuntu18.04.1+deb.sury.org+1 and MySQL 5.5.5-10.1.44-MariaDB-0ubuntu0.18.04.1.

Suggested Fix:
Change this field from a varchar(255) to text or mediumtext.

Side effect:
In addition, making a longer field, whether its text or something longer makes it possible to upload base64encoded images. A quick text confirmed this is possible.

**Comment by erikgeurts** [comment]
Create a banner that references an external image file with a (very) long URL is already possible by using the HTML banner type. As such, this is probably not going to get a very high priority.

Uploading base64encoded into the field intended for the URL of an external image is not likely to be something we would encourage.

We welcome feedback from the community about this issue.

**Comment by magazinexperts** [comment]
The HTML banner doesn't seem to work for enewsletter ad positions.
I'll look more into submitting a pull request

**Comment by erikgeurts** [comment]
Correct, but neither are those external rich media ads. You'll have to stick to simple static images for newsletters.

**Comment by erikgeurts** [comment]
Since there hasn't been any further feedback, we're closing this issue now. Feel free to submit a PR and we'll be glad to review it.
