### ISSUE TITLE
statistics are not logged in direct selection any fix

### ISSUE THREAD

**Issue by yashmeena7005** [revive-adserver/revive-adserver#1205]
Hello when using direct selection no log are genrated for zoneid..it sets zoneid value 0 in lg.php any fix is there

**Comment by yashmeena7005** [comment]
this is the best feature of revive adserver...it gives more flexibility in displaying ads on website and also one of the reason that i am using revive adserver

**Comment by yashmeena7005** [comment]
> We do not offer dedicated support with the software. You can consider posting your question at https://forum.revive-adserver.com/ .
> 
> Moreover, we do not recommend using direct selection, and we would like you to be aware that this feature is going to be deprecated.
this is the best feature of revive adserver...it gives more flexibility in displaying ads on website and also one of the reason that i am using revive adserver

**Comment by yashmeena7005** [comment]
> We do not offer dedicated support with the software. You can consider posting your question at https://forum.revive-adserver.com/ .
> 
> Moreover, we do not recommend using direct selection, and we would like you to be aware that this feature is going to be deprecated.

this is the best feature of revive adserver...it gives more flexibility in displaying ads on website and also one of the reason that i am using revive adserver

**Comment by yashmeena7005** [comment]
Moreover,No one replies on your forum..if i have to ask something reply comes like 'we are working on it...we are not sure'

**Comment by yashmeena7005** [comment]
> We do not offer dedicated support with the software. You can consider posting your question at https://forum.revive-adserver.com/ .
> 
> Moreover, we do not recommend using direct selection, and we would like you to be aware that this feature is going to be deprecated.

this is the best feature of revive adserver...it gives more flexibility in displaying ads on website and also one of the reason that i am using revive adserver

**Comment by erikgeurts** [comment]
Direct selection stems from a time before the Websites and Zones features were added. They work by requesting ads directly instead of through zones. That explains why the statistics aren't logged with zone IDs.

**Comment by yashmeena7005** [comment]
may you thing why i am obsessed with direct selection..? here is the answer: with direct selction i was able to add retargetting in revive adserver...also i am able to show ads accroding to visitors intent...you would aks how well that is another story..also banners based on keywords on the page...thats why direct selection can bring whole new functionality..in my opinion adserver dev should work on improving things not deprecating them by thinking that its a old thing..
Unless dev team has money making intresets from an open source project like revive..?

**Comment by yashmeena7005** [comment]
> Direct selection stems from a time before the Websites and Zones features were added. They work by requesting ads directly instead of through zones. That explains why the statistics aren't logged with zone IDs.

may you thing why i am obsessed with direct selection..? here is the answer: with direct selction i was able to add retargetting in revive adserver...also i am able to show ads accroding to visitors intent...you would aks how well that is another story..also banners based on keywords on the page...thats why direct selection can bring whole new functionality..in my opinion adserver dev should work on improving things not deprecating them by thinking that its a old thing..
Unless dev team has money making intresets from an open source project like revive..?

**Comment by erikgeurts** [comment]
Trying to offend us won't change our minds (on the contrary).

To get back to your original question: direct selection won't log stats by zone ID, simply because it is a method to request banners directly, completely by-passing zones. So asking why this doesn't work shows you haven't really mastered this application.

Please feel free to continue commenting here, and we'll continue to ignore the comments.
