### ISSUE TITLE
Banner destination URL is rewriten

### ISSUE THREAD

**Issue by gorgiselkov** [revive-adserver/revive-adserver#1207]
Problem:
Hi,

I have latest version of Revive Adserver running on IIS web server with CGI and latest version of PHP installed. I have a campaign with a banner that is supposed to redirect to the following LINK, but when I click on the banner, it redirects to this LINK.

The ad server is installed on the following LINK. So it seems that the URL is rewritten with the base domain from the location where the adserver is installed.

When I click on the banner, this is the link generated (with the ck.php) LINK

I would be grateful if you take a look into the ck.php script and confirm IIS compatibility.

(EG edit: links redacted, for your own safety)

**Comment by erikgeurts** [comment]
We prefer to use Github issues for actual bug reports. I would like to recommend that you post your question on our community forums at https://forum.revive-adserver.com.
