### ISSUE TITLE
Remove 3rd party click tracking plugin and functionality

### ISSUE THREAD

**Issue by mbeccati** [revive-adserver/revive-adserver#1213]
Fixing open redirects meant that any 3rd party click tracking functionality had to go as well. We should therefore remove the plugin and any associated functionality.

While there, we agreed to make "Do not alter HTML" the deafult when creating HTML banners.

**Comment by erikgeurts** [comment]
There's a section on third party click tracking in Global Settings -> Banner Delivery Settings -> Invocation Defaults:
![image](https://user-images.githubusercontent.com/5102461/103011017-831b7800-4539-11eb-9f15-34fcf13df855.png)
which can also re removed.
