### ISSUE TITLE
Excessive clicks skewing statistics

### ISSUE THREAD

**Issue by phillipblancher** [revive-adserver/revive-adserver#1215]
I have the most recent version of Revive and recently I have noticed the click reporting on our stats have been through the roof. For example, one campaign just today reports this:

Impressions: 243
Clicks: 1,979
CTR: 814.40%

--

Overall yesterday, our site reporting showed the following stats for the entire day:

Impressions: 7,973
Clicks: 33,892
CTR: 425.08%

I think there may be a bug or an issue with reporting.

**Comment by erikgeurts** [comment]
The issues section on our Github pages is not intended for support questions. Please consider posting your question on our community forums at https://forum.revive-adserver.com. If you've already done so, then please just wait patiently for a community member to respond.
