### ISSUE TITLE
API for Revive Ad server

### ISSUE THREAD

**Issue by ganeshkrishnan1** [revive-adserver/revive-adserver#1222]
Do we have API for revive ad server? 
I came across this github link (redacted) but thats around 8 years old. We only need the ability to create campaigns and view statistics for it

**Comment by erikgeurts** [comment]
There is a built-in XML-RPC API inside Revive Adserver, but it's largely undocumented. There is also a paid add-on [Revive Adserver REST API](https://www.reviveadserverrestapi.com/). Full disclosure: that product is brought to market by my company.
