### ISSUE TITLE
Error prevents upgrade to 5.1.1:  "This version cannot be upgraded"

### ISSUE THREAD

**Issue by utrenkner** [revive-adserver/revive-adserver#1224]
I just wanted to upgrade our Revive installation from 5.0.4 directly to today's 5.1.1. The upgrade wizard did not go through but reported a database problem "This version cannot be upgraded".

![Screenshot_2021-01-26_17-02-16](https://user-images.githubusercontent.com/8254715/105871587-c023d000-5ff9-11eb-9eb1-ef3fdf27f407.png)

Thus, I tried to incrementally upgrade to 5.0.5, then to 5.1.0 and finally to 5.1.1. The first upgrade went smoothly, the second "forgot" to copy the plugins, and the last step failed, again, with the same error.

I followed exactly the recommended upgrade steps from this page https://www.revive-adserver.com/how-to/update/.

This is the info on the used platform from the Revive 5.1.0. backend:
``You are currently using Revive Adserver v5.1.0 running on h2o 2.3.0-beta2, PHP 7.4.13 and MySQL 5.5.5-10.5.8-MariaDB.``

**Comment by erikgeurts** [comment]
As mentioned on our website and here on Github, we do not offer dedicated support. You can consider posting your question at https://forum.revive-adserver.com/ .

**Comment by utrenkner** [comment]
Thank you, I was aware of this. But I believe this is a bug. I have upgraded through many different versions of OpenX and Revive and have always succeeded. I also succeeded with upgrading to 5.0.5 and 5.1.0, today.

Filing bug reports is one of the important things an opensource community can contribute. That's why I took the time to give as much information as I had, including a screenshot to give you a chance to identify a possible problem. I thought you might be interested in quick feedback after a new release, because I assume I will not remain the only one with this problem.

**Comment by erikgeurts** [comment]
Whatever you experienced, there is no evidence of a specific bug. If it turns out there is a bug after all, we will be more than happy to reopen this issue. I have personally run several updates of 5.1.0 to 5.1.1 with no issues whatsoever, and also from 5.0.5 to 5.1.1.

You can find the actual cause of the issue listed in detail in the debug.log and/or install.log files in the var folder.
