### ISSUE TITLE
Video Ads Reports trying to use Flash

### ISSUE THREAD

**Issue by ebolax** [revive-adserver/revive-adserver#1235]
edit: Sorry, I forgot to say which version I'm using. it's 5.1.1.

if I get "Advertiser Video Report" for my vast ad then I get an error.

Fatal error: Uncaught Error: Class 'VastAreaGraph' not found in F:\wwwroot\revive\www\admin\plugins\videoReport\stats-video.php:125 Stack trace: #0 {main} thrown in F:\wwwroot\revive\www\admin\plugins\videoReport\stats-video.php on line 125

I opened stats-video.php and it's line 17

include_once 'VastAreaGraph.php';

and there is no VastAreaGraph.php.

if I commented the codes below, problem solved.

Line 17: include_once 'VastAreaGraph.php';
Line 125: $topGraph = new VastAreaGraph($graphValues, $graphEventsIdToName);
Line 126: $topGraphJSON = $topGraph->getJSON();

I think it's a Flash error (I saw VastAreaGraph.php in Revive 5.0.5)

**Comment by erikgeurts** [comment]
The Video Ads Reports for various metrics do indeed still attempt to use a Flash component. The effect is that the graph on the page remains empty, but in my test installation I do get a table underneath:
![image](https://user-images.githubusercontent.com/5102461/107201229-006f4f00-69f9-11eb-8c7d-dca71ff97bd5.png)

This screenshot is from a v5.0.5, so even from before we removed several Flash components. Most likely the browser simply ignores anything Flash related in this case.
