### ISSUE TITLE
Async tags lose protocol schema of parent when iframe generated by srcdoc attibute

### ISSUE THREAD

**Issue by fab104c1** [revive-adserver/revive-adserver#1244]
Since the async tag's iframe is created using srcdoc attribute, the value of "location.protocol" inside the iframe itself  is always "about:".
This behaviour is not compatible with the use of url with relative protocol (eg. //www.google.com), and every other js script that use a logic of protocol recognition, as used by same revive in sync tags:_location.protocol=='https:'?'https://adv.example.com/www/delivery/ajs.php':'http://adv.example.com/www/delivery/ajs.php'_
So, when used on https pages, all urls are used in http mode, causing "mixed content" error.
There is a way to maintain the same protocol of the parent page, in the same way as before start using the srcdoc property?
Or always force "https:" to avoid this kind of exceptions?

**Comment by mbeccati** [comment]
Introduced in 5.1.0 w/ #1153
