### ISSUE TITLE
3rd-party click tracking with DFP

### ISSUE THREAD

**Issue by PUBinteractive** [revive-adserver/revive-adserver#1245]
Hello.
I'm using Revive as a 3rd-party ad server with a publisher that uses DFP.
Everything is working fine except for the click tracking on the publisher side.

Here is below the tag I sent them after reading [https://github.com/revive-adserver/revive-adserver/issues/440](url):

(...)<![CDATA[
   **document.MAX_ct0 = '%%CLICK_URL_UNESC%%';**
   var m3_u = 
(...)

Unfortunately, the publisher tells me they are not able to track clicks on their end.
Do I need to add something else
Can you let me know why this is not working properly please?
Thank you in advance.

**Comment by erikgeurts** [comment]
There doesn't seem to be an issue 440, so that's probably a typo.

Third party click tracking has been removed starting with version 5.1.0 of the Revive Adserver software, see https://github.com/revive-adserver/revive-adserver/issues/1213 and https://www.revive-adserver.com/security/revive-sa-2021-001/ (see Vulnerability 3 – Open Redirect).

**Comment by PUBinteractive** [comment]
Thank you very much for your quick answer. I was not aware of this.
Assuming I need this functionnality so the publisher continues to use my third-party tags for a specific campaign, is there a way I can put back the part of the code that handled this functionality in the Download edition?
(I don't want to cause trouble, I'm just searching for a solution for the specific situation I'm in...)

**Comment by erikgeurts** [comment]
The nice thing about open source is that you can fork it and then do whatever you want. However, we won't be able to support you with that. The way third party click tracking was coded before resulted in a security vulnerability, which has now been removed in v5.1.

**Comment by mbeccati** [comment]
@erikgeurts referenced #440
