### ISSUE TITLE
HTML Banner - Destination URL {clickurl} oadest

### ISSUE THREAD

**Issue by bskade** [revive-adserver/revive-adserver#1256]
Problem:

We use HTML banners to deliver animated HTML5 banners. Previously it was possible to manipulate the destination address via clickurl.
e.g. HTML CODE in Textarea
<iframe src='{img_url_prefix}/banner.html?clickTag={clickurl}&oadest=http://target.domain.com'><inframe/>

In version 5.1.1 this was no longer possible. From version 5.2. this can be enabled again by clickUrlValidity.

My question:
Why is it not just simply add the form field of the "Destination URL" like for image Banners on HTML Banners as well. 
This could save the cumbersome part of the 'oadest' specification as in the example above.

Maybe there is another solution or I'm approaching the problem the wrong way.

For HTML5 banners as zip upload the specification of the "Destination URL" is again possible. 
Unfortunately HTML5 banners as zip upload are not a practicable solution for us at the moment.

Thanks a lot

**Comment by erikgeurts** [comment]
As far as I understand your note, this is not a supported use case in the Revive Adserver software.

As a matter of fact, the destination URL field was removed for Generic HTML banners was removed some time ago because it resulted in invalid HTML frequently.

You might want to try putting your links in properly:
`<iframe src='{img_url_prefix}/banner.html?clickTag={clickurl}http://target.domain.com'>`
but I have a hunch this won't work either.

**Comment by mbeccati** [comment]
`<iframe src='{img_url_prefix}/banner.html?clickTag={clickurl_enc}http://target.domain.com'>` should work though

**Comment by bskade** [comment]
Thank you for suggestion
Your suggestion was our original implementation, which unfortunately no longer worked since said update.
Maybe it works again - I will check it out and report

**Comment by bskade** [comment]
Thanx a lot. Your Solution seems to work again.
It creates now a valid signature for the target url.

for example
<iframe src="{img_url_prefix}/banner.html?clickTag={clickurl_enc}http://target.domain.com">
will crete somthing like this
....clickTag=https://myreviveserver.com/www/delivery/cl.php?bannerid=187&amp;zoneid=5
&amp;sig=4aa70e8951e8eba49b34f908a0fbf6ca6712fcd742d3e104d9d655b378725f1b
&amp;oadest=https%3A%2F%2Ftarget.domain.com%2Fde"

perfect

**Comment by erikgeurts** [comment]
Thanks for your feedback.
