### ISSUE TITLE
Redirect is not working with the newsletter invocation code

### ISSUE THREAD

**Issue by GuillaumeRoques** [revive-adserver/revive-adserver#1257]
Hi

Problem:
Since 5.2.0 (I've skipped 5.1.0 and 5.1.1) the redirect with the newsletter invocation code is not working when the banner is clicked (but the banner is displayed correctly). It seems to be related to the new signature feature (I tried to skip the signature validation and the redirect is working)

Steps To Reproduce:
Insert in a newsletter the invocation code provided by the zone : 
`<a href='https://HOST/delivery/ck.php?zoneid=ID' target='_blank'><img src='https://HOST/delivery/avw.php?zoneid=ID&amp;cb=INSERT_RANDOM_NUMBER_HERE' border='0' alt='' /></a>`
Open the newsletter, click on the banner, the browser is redirected to https://HOST/delivery/ck.php?zoneid=ID (blank page, HTTP code 200) but not redirected to the ad URL.

I checked also with curl, the location header is not set.

I did not find a new invocation code for newsletter working with the signature feature in the admin and in the documentation.

**Comment by erikgeurts** [comment]
Thanks for your report, I have just tried this myself and I see similar behavior. This is peculiar, because I've been testing this with the internal release candidate we had before the final release of v5.2.0 and I distinctly remember that it worked at the time. We'll continue investigating this.

**Comment by mbeccati** [comment]
@lparikka That doesn't look like a newsletter click link, sorry

**Comment by lparikka** [comment]
Followup to the previous question: Is it not possible to do the click-tracking as shown above any more? Is the dest-parameter not working any more? 
The click-url is defined in the banner like this:
https://host.com/adstats/click.php?uid={uid}&source={source}&banner_id={bannerid}&zone_id={zoneid}&campaign_id={campaignid}&destination=https%3A%2F%2Fdestinationhost.com%2F

**Comment by lparikka** [comment]
Maybe that is a direct selection tag. Has it been deprecated now?

**Comment by mbeccati** [comment]
@lparikka pls do not hijack this issue with unrelated questions. Our forums are best suited for that.

**Comment by zachnicodemous** [comment]
> 
> 
> I confirm that is working with your patch. Thanks!

Also confirming that this patch works. Thanks for the quick fix!

**Comment by utessemo** [comment]
Hi,
we have the same Problem with the Version  v5.3.0. Redirect is not working when we use the Image Tag. Could someone help me.

**Comment by erikgeurts** [comment]
> Hi, we have the same Problem with the Version v5.3.0. Redirect is not working when we use the Image Tag. Could someone help me.

This issue is closed, plus your question appears to be unrelated. I suggest you open a new issue and provide all the information being requested while doing so.
