### ISSUE TITLE
Updating to v5.2 from any version still using GeoIP1 triggers an error related to MaxMind's license key missing

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1265]
When running an update from v4.2.1 to v5.2.0, there is an error message at the very end of the update process. In this particular case, it turned out to be caused by the update process not being able to download a copy of the current GeoIP2 data file. MaxMind have a license key requirement for that nowadays, which did not exist yet at the time when the update process from GeoIP1 to GeoIP2 was developed.

**Comment by mbeccati** [comment]
After further inspection, I can confirm a warning is logged, however that is not the cause for an error message being displayed during the upgrade. It is unclear what has been causing it in that particular upgrade.
