### ISSUE TITLE
Version 5.2 data Injected into Table ox_banners, ox_users, and ox_zones

### ISSUE THREAD

**Issue by jschaum-arrl** [revive-adserver/revive-adserver#1266]
I appreciate all of the detail you would like, but I am not sure if I will be able to provide it, based on the issue.  We just recently built a new Centos linux server and installed the latest version (5.2) of the Revive ad server on it.  It meets or exceeds all of the technical specs that you provide.  Somehow, someone is getting bogus data into our database.  We are seeing unknown users in the ox_users table and bogus data in the prepend and append fields of the tables ox_banners and ox_zones.  It looks like some type of SQL injection attack. {personal data redacted by @erikgeurts}

**Comment by erikgeurts** [comment]
This is not a support forum. If your installation is compromised, it does not automatically mean there is a (new) issue with our code.

**Comment by jschaum-arrl** [comment]
Understood, but there is a possibility and I thought you might like to know.


Jim Schaum
IT Infrastructure & Operations Manager

ARRL - The national association for Amateur Radio®
225 Main Street
Newington CT 06111-1400
Telephone: 860-594-0245
Fax: 860-594-0298
***@***.******@***.***>
www.arrl.org<http://www.arrl.org/>

**Comment by jschaum-arrl** [comment]
P.S.  If I click on “Support” at the top of your websites main page and select “Bugs” from the dropdown list, I go to a page that has the following towards the bottom:

How to file a bug report
Have you discovered a new issue? We’d like to hear about it!
Please file a new issue on our Github issue tracker<https://github.com/revive-adserver/revive-adserver/issues> and provide as much detail as possible.

If I got to someplace through your link that is not a support forum, you should correct your link.



Jim Schaum
IT Infrastructure & Operations Manager

ARRL - The national association for Amateur Radio®
225 Main Street
Newington CT 06111-1400
Telephone: 860-594-0245
Fax: 860-594-0298
***@***.******@***.***>
www.arrl.org<http://www.arrl.org/>

**Comment by erikgeurts** [comment]
The thing is: this is not a bug (at least you have not provided any evidence it is a bug).

**Comment by erikgeurts** [comment]
For community support, go to https://forum.revive-adserver.com

**Comment by jschaum-arrl** [comment]
Erik,

I understand what you are saying and I agree with you to a point.  If I had the time to look through the code and see how you are sanitizing input data, I might be able to identify the issue.  I would believe that your developers know the code better than I do and would be able to more quickly identify all code touching the tables and columns I mentioned to see if there are any potential issues there.


Jim Schaum
IT Infrastructure & Operations Manager

ARRL - The national association for Amateur Radio®
225 Main Street
Newington CT 06111-1400
Telephone: 860-594-0245
Fax: 860-594-0298
***@***.******@***.***>
www.arrl.org<http://www.arrl.org/>

**Comment by erikgeurts** [comment]
@jschaum-arrl, you wrote:
> P.S. If I click on “Support” at the top of your websites main page and select “Bugs” from the dropdown list, I go to a page that has the following towards the bottom: How to file a bug report Have you discovered a new issue? We’d like to hear about it! Please file a new issue on our Github issue tracker<https://github.com/revive-adserver/revive-adserver/issues> and provide as much detail as possible. If I got to someplace through your link that is not a support forum, you should correct your link.

Your assumption that this is a bug is not warranted. Instead, this is a matter related to security, so you should have looked at Support -> Security, which takes you to https://www.revive-adserver.com/security/ . That page introduces our Hacker1 reporting program, and there it very clearly says:

> **Being hacked is not the same as having found a vulnerability!**
> Very often, what people believe to be security vulnerabilities, turn out to be cases of (unauthorized) access to an installation through password guessing, social engineering or (sadly) simply using extremely weak passwords, or other methods not related to the code at all.
> If your own ad server installation has been compromised, do not report it here! This program is only for reporting security vulnerabilities you have discovered in our code.
>

**Comment by jschaum-arrl** [comment]
Erik,

I do not wish to have an adversarial relationship with you.  I also do not assume anything.  I just leave myself open to all possibilities.

I am relatively new to ARRL, having started here on 11/30/20.  I have inherited a lot of systems.  One of them was an ad server.  At the time I started, the ad server was running Revive 3.x.  I was told by a developer at ARRL that there had been problems with the ad server (it had been compromised) for a while.  They were originally running a pre-Revive ad server and upgraded to the 3.x version to try and resolve the issues.  It made no sense to me, as a compromised server is not going to become uncompromised by upgrading to an already old version of Revive.  At the time they upgraded to the 3.x version, there was already a 5.x version available.  In the first month that I was here, the developer tried upgrading to a 4.x version of the Revive software.  Again, this made no sense to me.  Upon subsequent issues and at the prompting of the CEO, a few weeks ago I spun up a new cloud instance at Rackspace with Centos 7.9 and all of the latest updates for that, as well as PHP and MariaDB versions that all met or exceeded the technical requirements posted on your site.  At this point, I handed the server over to a developer to install the latest version of Revive, which happened to be 5.2, which had recently been released.  All of the system and database users and passwords were new and we were the only people who knew them.  I know that my passwords are not simple or easy to hack.  I would hope that our developer would have created passwords that were equally strong.  We do not even know each other’s passwords.

At this point, the developer dumped the ad data from the old server and loaded it into the new server.  Since I am not familiar with how the software works, I understand that this could have been a mistake and a point at which we may have compromised the new server.  That being said, I provided the names of the table and columns that we were seeing data being added to when I submitted a ticket.  It seems like we are the victims of some sort of SQL injection attack.  Since I do not know the code and do not have the time to go through it and try to identify what could be happening, it was my hope that the people who developed the software may be able to identify potential avenues of SQL injection and see if there are any that could potentially compromise the tables and columns I identified in my ticket.

Since ARRL is a non-profit organization, we have limited resources.  Because of that, the decision had been made to use the free version of Revive to run our ad server.  If switching to the paid version will help give us access to more support resources, please let me know and I will look into getting us upgraded to a paid subscription.


Thank you for your time.


Jim Schaum
IT Infrastructure & Operations Manager

ARRL - The national association for Amateur Radio®
225 Main Street
Newington CT 06111-1400
Telephone: 860-594-0245
Fax: 860-594-0298
***@***.******@***.***>
www.arrl.org<http://www.arrl.org/>

**Comment by erikgeurts** [comment]
What I meant was that your Revive Adserver installation was already compromised before you started all of that. Dumping and reimporting most likely move that problem along to your new server. This is not a bug.
