### ISSUE TITLE
Revive Adserver No Cookie Image Tag Invocation Code Not Working

### ISSUE THREAD

**Issue by essjayeire** [revive-adserver/revive-adserver#1267]
Not entirely sure is this a know issue or a config setting I'm missing but the invocation code for "Email/Newsletter zone" is not working.

Below will load the image but the link redirect does not work for the zone

http://domain.com/www/delivery/avw.php?zoneid=21
http://domain.com/www/delivery/cl.php?zoneid=19

If I append the bannerid to the href URL, then it will direct to the destination

http://domain.com/www/delivery/cl.php?zoneid=19&bannerid=13

**Comment by erikgeurts** [comment]
See https://github.com/revive-adserver/revive-adserver/issues/1257
