### ISSUE TITLE
Google Analytics not reporting click stats from Revive Adserver

### ISSUE THREAD

**Issue by 420Banners** [revive-adserver/revive-adserver#1268]
Google Analytics isn't reporting correct/proper click stats from Revive Ad Server ads.

Advertisers have been reporting that they're not seeing the same stats that Revive Ad Server reports. I understand it doesn't have to be exact, but the numbers are drastically different. It's enough to make advertisers complain and stop advertising with us. There have been more people reporting the same in your forums but it goes unread, so I'm submitting a bug report. 

Google Analytics is used by thousands of advertisers because Google is a company people trust. Advertisers wouldn't settle if we tell them to trust Revive Server Ad stats over Google's—that's just crazy.

So can someone please look into this issue when you have a chance?

Thank you!

**Comment by erikgeurts** [comment]
You can't compare ad server statistics (of any ad server, not just Revive Adserver) with web analytics. They're measuring entirely different things. There is no evidence of a (new) bug in your report.

**Comment by 420Banners** [comment]
Why do you keep deleting this without any proper discussion?

 

You never ask for details or anything, just spout off some random words and close?

 

Clicks from your software are not being registered by Google, how do we get rid of the long affiliate looking urls and have our banners simply link to the domain like www.domain.com <http://www.domain.com>  

 

instead of 

https://www.domain.com/bmg/www/delivery/cl.php?bannerid=997 <https://www.domain.com/bmg/www/delivery/cl.php?bannerid=997&zoneid=0&sig=34fb1b67785dd39c7eb8f308dfa497712b275f02933d23e3d648813bf1f4973e&oadest=https%3A%2F%2Fatreumlighting.com%2Fproducts%2Fhydra-1000-pro> &zoneid=0&sig=34fb1b67785dd39c7eb8f308dfa497712b275f02933d23e3d648813bf1f4973e&oadest=https%3A%2F%2Fatreumlighting.com%2Fproducts%2Fhydra-1000-pro

 

Can you please help us figure this out?

 

Who owns your company, can we get in touch with your manager?

 

We will pay you money to help us, we are not asking for handouts.

 

Please show some professionalism and respond to our dilemma, it’s costing us hundreds of thousands of dollars in loss of renewals from angry advertisers.

 

Greenest Regards,

Webmaster

 

420 Magazine

PO Box 3420

Hollywood, CA 90078

1-888-420-MAGG

https://www.420magazine.com <https://www.420magazine.com/> 

 

 

 

Confidentiality Notice. This e-mail is covered by the Electronic Communications Privacy Act, 18 U.S.C. Sections 2510-2521 and is legally privileged. This e-mail is the property of 420 Magazine, Inc. and contains confidential and/or privileged information. This e-mail is intended to be received and reviewed only by the individual named above. Any review, use, dissemination, disclosure or copying of this e-mail or any attachments is strictly prohibited. If you have received this e-mail in error, please immediately notify the sender at ***@***.*** ***@***.***>  and delete all copies of the e-mail and any attachments. Thank you for your cooperation and assistance.

**Comment by erikgeurts** [comment]
Nothing has been deleted (as demonstrated by this comment).

**Comment by 420Banners** [comment]
Are you able to answer the above question? Is something like that possible or can it be added in a later release?

**Comment by 420Banners** [comment]
Okay, then why do you keep closing it then?

 

Can you please reopen and help us investigate?

 

Thankyou.

 

Greenest Regards,

Webmaster

 

420 Magazine

PO Box 3420

Hollywood, CA 90078

1-888-420-MAGG

https://www.420magazine.com <https://www.420magazine.com/> 

 

 

Confidentiality Notice. This e-mail is covered by the Electronic Communications Privacy Act, 18 U.S.C. Sections 2510-2521 and is legally privileged. This e-mail is the property of 420 Magazine, Inc. and contains confidential and/or privileged information. This e-mail is intended to be received and reviewed only by the individual named above. Any review, use, dissemination, disclosure or copying of this e-mail or any attachments is strictly prohibited. If you have received this e-mail in error, please immediately notify the sender at ***@***.*** ***@***.***>  and delete all copies of the e-mail and any attachments. Thank you for your cooperation and assistance.

**Comment by erikgeurts** [comment]
The link you mentioned is the click tracking functionality. You can read about it here: https://www.revive-adserver.com/blog/changes-to-click-tracking-in-v5-1-and-v5-2/

As per your own description, the Revive Adserver software counts the clicks. Assuming the redirect to the actual landing page works (you do seem to imply it does), then the Revive Adserver software works as intended for you. If Google Analytics, subsequently, does not count an incoming visit, then this must be attributed to Google Analytics.

> Who owns your company, can we get in touch with your manager?

That's funny. "Let me speak with your supervisor" ;) . It's not a secret, see https://www.revive-sas.com/#founders .

> We will pay you money to help us, we are not asking for handouts.

You've been 'threatening' to pay us or to become a sponsor many times, but nothing of the sort has ever happened.

> Please show some professionalism and respond to our dilemma, it’s costing us hundreds of thousands of dollars in loss of renewals from angry advertisers.

You have a long history here of posting question in a very aggressive and hostile manner. But threats won't help, what you posted here is simply not a bug, it is the intended functionality, and per your own description, it is working just fine.
