### ISSUE TITLE
Feature request: Static HTML banner type 

### ISSUE THREAD

**Issue by 420Banners** [revive-adserver/revive-adserver#1270]
Inventory -> Choose Advertiser -> Campaigns -> Banners 

Banner campaigns have the option to link to a specific banner URL. I assume that when that option is chosen, the website URL entered in the field will be shown instead of the uploaded/in-house banner URL from Revive Ad Server. 

There should also be an option in there to remove the Revive Ad Server banner tracking URL so that a specific advertiser can have their banner ad directly link to their website instead of the long URL generated by Revive. 

This solves the problem that we brought up here - https://github.com/revive-adserver/revive-adserver/issues/1268

Can it be done? 

Thanks!

**Comment by erikgeurts** [comment]
This can't be done, the very purpose of an ad server (any ad server, really), is to measure impressions, clicks, and conversions.
