### ISSUE TITLE
Allow full screen display of async tag's iframe content

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1282]
One of my customers suggested the addition of an allowfullscreen parameter to the iframe that's generated by the async javascript invocation code.

Since this would be a potentially breaking change for other users, it might be an idea to add an optional and initially undocumented parameter to the async js code, something like:

> <ins data-revive-zoneid="123" data-revive-id="hash#" **data-revive-fullscreen=x**></ins>
> <script async src="//ad-server-url/asyncjs.php"></script>
> 

Then we do something so that fullscreen=1 inserts `allowfullscreen` whereas fullscreen=2 inserts `allow="fullscreen"` into the async output iframe. This would enable easily switching to use the newer approach since allowfullscreen is already considered [legacy](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-allowfullscreen) by many.

This disadvantage is that this adds a reserved word 'fullscreen' to the list of predefined parameters, which could theoretically break site-variable of custom magic macro implementations already using this parameter.

**Comment by mbeccati** [comment]
> This disadvantage is that this adds a reserved word 'fullscreen' 

Yes, that's why I would prefer `data-revive-allowfullscreen` as it does what it's written on the tin.

**Comment by mbeccati** [comment]
I also wouldn't go as far as `fullscreen=1` / `fullscreen=2` as it's overcomplicated and most likely not useful at all.

**Comment by erikgeurts** [comment]
Sure, but how can we add support for both allowfullscreen now and allow="fullscreen" in the future? Add both to the iframe right away and make it the browser's problem?

**Comment by mbeccati** [comment]
> Add both to the iframe right away and make it the browser's problem?

Yes :)

**Comment by erikgeurts** [comment]
The customer who initially reported this, has not responded to my request for one or two ads that we could use to test this. However, in our own testing this appears to work just fine, so I propose that we close this issue now.
