### ISSUE TITLE
Invocation code dropdown coming empty

### ISSUE THREAD

**Issue by devbokaap-9** [revive-adserver/revive-adserver#1288]
We are not seeing dropdwon in invocation code tab , so we are not able to select any type like js and other and not able to generate code.

Steps To Reproduce:
<URL removed by moderator>
![image](https://user-images.githubusercontent.com/84016833/125107427-72f66f00-e0fe-11eb-9b70-d9e37c03ddcc.png)
![image](https://user-images.githubusercontent.com/84016833/125107502-886b9900-e0fe-11eb-8fe5-acf0c3dcca8d.png)

**Comment by erikgeurts** [comment]
This is not a bug, please review https://documentation.revive-adserver.com/display/DOCS/Plugins+Missing+or+Disabled
