### ISSUE TITLE
PHP8.0 does not support Each() function used by Revive Adserver

### ISSUE THREAD

**Issue by GazzaChalmers** [revive-adserver/revive-adserver#1289]
Your documentation for Revive Adserver says supports PHP 7.0.8 or higher. While it may have been the case before PHP8.0 was released, this is no longer true.
The Each() function is still used quite often throughout the code, but this function has been removed in PHP8.

**Comment by erikgeurts** [comment]
See https://github.com/revive-adserver/revive-adserver/milestone/3 for the upcoming release that will support PHP8 (and MySQL8).
We'll update the system requirements page once Revive Adserver 5.3 is out.
