### ISSUE TITLE
Trying to add a delivery rule to a banner triggers a 500 error

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1293]
While testing one of the RCs, I ran into what appears to be a bug.

When I try to add a delivery rule (any rule actually) to a banner, there is a 500 error the very second I click "add"
![image](https://user-images.githubusercontent.com/5102461/125802654-b1674005-67c0-4afa-b4d0-cf561a00d2e3.png)

**Comment by ianvm** [comment]
in addition :

lib/RV.php on line 13
PHP Fatal error:  Uncaught Error: Undefined constant "RV_PATH" in lib/RV.php:13

PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, null given in lib/max/other/lib-acl.inc.php:53
Stack trace:
#0 www/admin/banner-acl.php(49): MAX_AclAdjust()
#1 {main}
  thrown in lib/max/other/lib-acl.inc.php on line 53

**Comment by mbeccati** [comment]
> lib/RV.php on line 13
PHP Fatal error: Uncaught Error: Undefined constant "RV_PATH" in lib/RV.php:13

This one was triggered by the security check accessing lib/RV.php directly. Maybe we can change the check to a file that does not trigger an error to avoid confusion.

**Comment by erikgeurts** [comment]
in addition :

> lib/RV.php on line 13
> PHP Fatal error: Uncaught Error: Undefined constant "RV_PATH" in lib/RV.php:13


 
> PHP Fatal error: Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, null given in lib/max/other/lib-acl.inc.php:53
> Stack trace:
> #0 www/admin/banner-acl.php(49): MAX_AclAdjust()
> #1 {main}
> thrown in lib/max/other/lib-acl.inc.php on line 53

For anyone reading this: these are actually two snippets from an error log, the first one refers to an error that was logged during the installation, the other one is the error that was logged when trying to add a delivery rule.
