### ISSUE TITLE
Delivery engine - not using SSL/TLS to connect to database

### ISSUE THREAD

**Issue by fishsaidno** [revive-adserver/revive-adserver#1295]
We've recently moved our database to an external server. Naturally we want to enforce a secure connection here.

Relevant section of config file:
```
[database]
type=mysqli
host="external-host.com"
socket=
port=3306
username=username
password=password
name=db_name
persistent=
mysql4_compatibility=
protocol=tcp
compress=
ssl=1
capath="/path/to/install/var/"
ca="/path/to/install/var/ca-cert.pem"
``` 

Firstly switched `ssl=1`. As the database uses a self signed certificate, it's necessary to provide the client the CA certificate as to verify the server (preventing MITM).
Adding the CA certificate & path as above got the admin interface connecting to the db with TLS correctly.
However the delivery engine could not connect, ie. not able to write any delivery logs to db etc.

Turning on the delivery debugging feature,
```
[deliveryLog]
enabled=1
name="delivery.log"
fileMode=0644
priority=6
```
revealed the following: 
`DB connection error: Connections using insecure transport are prohibited while --require_secure_transport=ON.`

The offending section of code (when using mysqli) is in `lib/OA/Dal/Delivery/mysqli.php` 
See: https://github.com/revive-adserver/revive-adserver/blob/f077338/lib/OA/Dal/Delivery/mysqli.php#L56

As you can see, the code in this function does not check `$dbConf` for TLS related options.
Nor does it check for compression - not relevant for us, but worth mentioning?

Perhaps there are other considerations for not using TLS here (eg. performance) though this is a blocker for us due to `require-secure-transport`. PR for your consideration on its way shortly.

**Comment by mbeccati** [comment]
Awesome @fishsaidno, thanks! I'll revivew the PR shortly, but it seems ok at the first glance.

**Comment by mbeccati** [comment]
PR merged, thanks!
