### ISSUE TITLE
Bug in creating "Generic Html5" banner.

### ISSUE THREAD

**Issue by ganeshkrishnan1** [revive-adserver/revive-adserver#1304]
Problem:
Creating a generic html5 banner throws error due to malformed sql query.

Steps To Reproduce:
Click on create banner. 
Select "Generic html5" banner.
Add code and hit save.

The application throws error and shows the sql code it generated.

The SQL it generated
INSERT INTO 
ade_banners (campaignid , contenttype , storagetype , filename , imageurl , htmltemplate , htmlcache ,
width , height , weight , target , url , alt , statustext , bannertext , 
description , adserver , alt_filename , alt_imageurl , alt_contenttype , 
comments , updated , keyword , parameters , status , ext_bannertype , iframe_friendly ) 
VALUES ( 8 , **'' , 'html'** , '' , '' , '<a href="https://www.aihello.com>Image</a>' , 
'<a href="https://www.aihello.com>Banner</a>' ,  300 ,  250 ,  1 , '' , '' , '' , '' , '' , '300x250banner' , 'none' , '' , '' , '' , '' , '2021-08-17 17:41:28' , '' , 'N;' ,  0 , 'bannerTypeHtml:oxHtml:genericHtml' ,  1 ) 

The correct SQL

INSERT INTO 
ade_banners (campaignid , contenttype , storagetype , filename , imageurl , htmltemplate , htmlcache ,
width , height , weight , target , url , alt , statustext , bannertext , 
description , adserver , alt_filename , alt_imageurl , alt_contenttype , 
comments , updated , keyword , parameters , status , ext_bannertype , iframe_friendly ) 
VALUES ( 8 , **'html' , 'web'** , '' , '' , '<a href="https://www.aihello.com>Image</a>' , 
'<a href="https://www.aihello.com>Banner</a>' ,  300 ,  250 ,  1 , '' , '' , '' , '' , '' , '300x250banner' , 'none' , '' , '' , '' , '' , '2021-08-17 17:41:28' , '' , 'N;' ,  0 , 'bannerTypeHtml:oxHtml:genericHtml' ,  1 ) 

Not the column type and data value. In content type it's inserting blanks and in storage type its inserting "html".
The correct value is for content type it should be html and storage type it should be "web"

Screenshot
![image](https://user-images.githubusercontent.com/11154261/129783907-22b62d4f-532f-41fd-8449-9e9fd25bb290.png)

**Comment by erikgeurts** [comment]
Which version of Revive Adserver is this about? Which database server are you using, and what version exactly? Any other information that may be helpful to investigate this would be appreciated.

**Comment by ganeshkrishnan1** [comment]
php 7.4.3
Mysql 7
Revive adserver 5.2.1 (the latest version)
Ubuntu 20.

It looks like a bug in the way the sql is generated so I assume this is a php code issue.

**Comment by erikgeurts** [comment]
It looks like you're running MySQL 8, which isn't supported for Revive Adserver 5.2.1. You'll have to wait for the forthcoming v5.3.0, see https://www.revive-adserver.com/blog/release-candidate-1-for-revive-adserver-v5-3-0/ for details.

**Comment by ganeshkrishnan1** [comment]
That's weird. You are right, its mysql 8. But everything else seems to be perfect except for this error.

**Comment by erikgeurts** [comment]
There may be plenty of other things that won't work with MySQL 8, but you probably haven't noticed them.
