### ISSUE TITLE
Zone chaining should be disabled for newsletter zones

### ISSUE THREAD

**Issue by mbeccati** [revive-adserver/revive-adserver#1307]
Newsletter zones should not be relying on zone chaining to bypass the 1 banner rule. Click tracking is not properly working with chaining is enabled and active, as the `<a href>` tag contains the first/original zoneid in its URL.

See: https://forum.revive-adserver.com/topic/6195-chained-zones-banner-link-not-working/

**Comment by miamicityman** [comment]
We're in 2024 and I keep hoping this issue gets fixed.

I'd like to use chained newsletter advertising as a fall-back when the spot is not sold. But the redirect to the URL never works.

Thanks.

**Comment by mbeccati** [comment]
@miamicityman well, the fix would actually be disabling zone chaining for newsletters because it's technically impossible...

**Comment by miamicityman** [comment]
Thank you for response.

So it's not a **bug** then? Or it's a bug only in that chaining shouldn't be allowed for newsletters? 

If so, then it should be a **feature request**?

**Comment by erikgeurts** [comment]
As indicated by @mbeccati , zone chaining in email newsletters is impossible, because email clients won't allow it/don't support it. The Revive Adserver UI seems to allow it, and that should be removed because that's confusing.

**Comment by miamicityman** [comment]
Thank you for the clarification. 

The banner of the chained newsletter advertisement appears, but it never redirects properly.

Now I understand why.
