### ISSUE TITLE
Conversion with cookies not working using the same Sig paramether

### ISSUE THREAD

**Issue by Pasquale27** [revive-adserver/revive-adserver#1309]
Hi,
we need to track several links we use on a specific website. We created manually some tracking links like:

https://admanager.adintend.com/delivery/cl.php?bannerid=1585&zoneid=1776&sig=ab7f5fac69113290b19ab2f36755fd13b7bfb40e1ec664ddd46b514d405a7561&oadest=https%3A%2F%2Fwww.cocooners.com%2Fviaggi-vacanze%2Fvisite-guidate

sig paramther is alway the same, and not updated. We noticed that in this way we are not able to track conversiona. Instead generating the text link frmo the invocation code tracking is working.

Is it possibile to have tracking liks for textlinks that allow to track sales or leads without using a sig paramether?

Thanks

**Comment by erikgeurts** [comment]
Please study the blog post describing the various changes and improvements to click tracking, including the reasons for those changes, at https://www.revive-adserver.com/blog/changes-to-click-tracking-in-v5-1-and-v5-2/

Sig is a dynamically calculated parameter, so hard coding it can never produce the results you're looking for.

Moreover, Revive Adserver is an ad server, not an affiliate system, and it is not intended to be used just for tracking clicks and conversions without an impression to precede it.
