### ISSUE TITLE
admin: Getting access denied on banner history

### ISSUE THREAD

**Issue by machour** [revive-adserver/revive-adserver#1310]
Problem:

I upgraded from revive 5.2 to 5.3.0 two days ago, and since then I'm denied access when I try to see a campaign stats :

For example, I can access `/admin/stats.php?entity=campaign&breakdown=banners&clientid=69&campaignid=720` : 

![Screen Shot 2021-09-21 at 1 00 36 PM](https://user-images.githubusercontent.com/304450/134166803-255f976b-45f1-475d-b79b-4b6d76254cbe.png)

but clicking the first item in the table yields an access error :
`/admin/stats.php?entity=banner&breakdown=history&clientid=&campaignid=720&bannerid=2720&placement_id=720&period_preset=today&period_start=2021-09-21&period_end=2021-09-21` : 

![Screen Shot 2021-09-21 at 1 02 05 PM](https://user-images.githubusercontent.com/304450/134166931-ef4e2625-f09d-4f9c-aa29-ccd31ebb6a5c.png)

I'm logged in as the sole user of the admin interface, who have all privileges.
Even using the interface as "System Administrator" yields the same result.

This used to work fine on 5.2

Adding a debug_print_backtrace to `_checkAccess()` in `lib/OA/Admin/Statistics/Common.php`, right before the `phpAds_Die()` call, I see that the function was called with these parameters:

0 - OA_Admin_Statistics_Common->_checkAccess(Array ([advertiser] => 0, [placement] => 720, [ad] => 2720)) called at [/**redacted**/www/lib/OA/Admin/Statistics/Delivery/Controller/BannerHistory.php:62] 
1 - OA_Admin_Statistics_Delivery_Controller_BannerHistory->start() called at [/**redacted**/www/admin/stats.php:163]

**Comment by erikgeurts** [comment]
Thanks for your report, I just tested it in a 5.3.0 installation and I was able to reproduce this behavior.
