### ISSUE TITLE
XML-RPC method marked private

### ISSUE THREAD

**Issue by kunzelmanm** [revive-adserver/revive-adserver#1312]
Problem:
2021/09/22 17:41:59 [error] 11#11: *170 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to private method XmlRpcUtils::getScalarValues() from context 'LogonXmlRpcService' in /var/www/www/api/v2/xmlrpc/LogonXmlRpcService.php:62
Stack trace:
#0 /var/www/www/api/v2/xmlrpc/XmlRpcFrontController.php(43): LogonXmlRpcService->logon()
#1 /var/www/lib/pear/XML/RPC/Server.php(647): XmlRpcFrontController->logon()
#2 /var/www/lib/pear/XML/RPC/Server.php(467): XML_RPC_Server->parseRequest()
#3 /var/www/lib/pear/XML/RPC/Server.php(419): XML_RPC_Server->createServerPayload()
#4 /var/www/lib/pear/XML/RPC/Server.php(354): XML_RPC_Server->service()
#5 /var/www/www/api/v2/xmlrpc/index.php(953): XML_RPC_Server->__construct()
#6 {main}
  thrown in /var/www/www/api/v2/xmlrpc/LogonXmlRpcService.php on line 62" while reading response header from upstream, client: 172.20.0.11, server: , request: "POST /api/v2/xmlrpc/ HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "revive"

Steps To Reproduce:

**Comment by erikgeurts** [comment]
Which version of Revive Adserver are you using?

**Comment by kunzelmanm** [comment]
5.3.0
