### ISSUE TITLE
Error Message "Not Acceptable! An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security."

### ISSUE THREAD

**Issue by MathiewBurkett** [revive-adserver/revive-adserver#1314]
Hi,

I keep receiving an error message after I click on a banner ad that I created with Revive Ad Server.

Instead of being redirected to the link that it is supposed to redirect to, I am receiving this Error Message 

"Not Acceptable!
An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security."

If there is anyone here that could login to my Revive Ad Server Website I would Appreciate It.

My Email address is [redacted]

Thanks,

Mathiew Burkett

**Comment by erikgeurts** [comment]
It seems that your issue is unrelated to Revive Adserver, rather it's caused by mod_security.
