### ISSUE TITLE
Date overlap check for newsletter zones doesn't work when the campaing being added starts before and ends after the currently linked one

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1322]
When a user attempts to link multiple banners with overlapping campaign date ranges to an email zone, it might be useful to display a warning that this will result in unpredictable/incorrect behavior when the zone gets used.

**Comment by mbeccati** [comment]
Sorry, I couldn't find a shorter description, the old one was in fact misleading.
