### ISSUE TITLE
Images not responsive

### ISSUE THREAD

**Issue by lgoehrs** [revive-adserver/revive-adserver#1332]
Hello,

I am facing some ssues on the template used to deliver pictures, more specifically for responsive interaces on mobile devices.
I have found a very simple fix. 

in www/delivery/asyncspc.php

I replace 
$imageTag = "$clickTag<img src='".htmlspecialchars($imageUrl, ENT_QUOTES)."' width='$width' height='$height' alt='$alt' title='$alt' border='0'$imgStatus />$clickTagEnd";

by 

$imageTag = "$clickTag<img src='".htmlspecialchars($imageUrl, ENT_QUOTES)."' class='img-responsive' width='$width' height='$height' alt='$alt' title='$alt' border='0'$imgStatus />$clickTagEnd";

By adding this class, it will allow the pictures to fit to the actual content space, and look great !

Thanks

Leo

**Comment by erikgeurts** [comment]
This appears to be a change that's very specific to your particular use case, not so much for everyone in general.

**Comment by lgoehrs** [comment]
Well, I disagree, this class is a well known class. At least, we whall have a way in the configuration to add some class for the way images are being displayed. 
img-responsive is part of the Bootstrap SDK, and is used in many many places.
We could also add a class, like rv-img-responsive so people can reference it in their website, and act on the way the pictures are being displayed. 

The main issue here, is that with every release, I need to make changes to the php of Revive, when I believe it shall benefit everyone.

Leo

**Comment by erikgeurts** [comment]
Can you point us to some kind of standards document that indicates that img-responsive is a standardized class name? Bootstrap is well know, but hardly an official standard.

**Comment by lgoehrs** [comment]
Well, I don't know how standard it needs to be, but at least, we would need a way to set a class for a picture, so the size, its responsiveness, and the way we display them could be controlled.
by forcing the size, we are not allowing multiples devices to display the pictures in the required proportion.

So, if img-responsive is not the way to do, then we would need a way, at a zone level, to setup some class se we could apply some CSS to it to fix, for example this issue.

**Comment by erikgeurts** [comment]
That's already possible by adding prepend and append code snippets.

**Comment by lgoehrs** [comment]
Are you saying we can add stuff inside the <img> tag ? 
If so, how do we do it ? Con you point some documentation ?

**Comment by erikgeurts** [comment]
Just to go any zone, click on the Advanced tab, and have a look at the section labeled "Append and prepend settings". So simple, no documentation required.

**Comment by lgoehrs** [comment]
this will add some code after or before, not in the img tag. there is no way to target for example the image, or maybe I am wrong somewhere ?

**Comment by erikgeurts** [comment]
Please point us to a standards document that explains how to handle this use case.

**Comment by lgoehrs** [comment]
Well, there are many cases where the images need not follow a standard size.
An obvious reason is when a picture is displayed on a phone. If we force the picture size, it will destroy the look of the website.
So, it is important to able to act on the class, adding class so it can be used in conjunction of the css  of the website. In my case bootstrap.

We could add a field, on a zone, in advanced, that would permit to force some classes.

Why do you need standards documents to understand that this level of customization is important ? 

Leo

**Comment by erikgeurts** [comment]
> Why do you need standards documents to understand that this level of customization is important ?

If we'd implement anything like this, it would have to work for thousands of users, in all kinds of scenarios and on all sorts of devices. Standards ensure that this is done correctly.

**Comment by mbeccati** [comment]
What a long thread! ;-)

> If we'd implement anything like this, it would have to work for thousands of users, in all kinds of scenarios and on all sorts of devices. Standards ensure that this is done correctly.

Yes, sorry!

That said, not all hope is lost. Some clever JS triggered at the right time would suffice:

```
document.querySelectorAll("ins[data-revive-loaded] > a > img").forEach(function (i) {i.class = "img-responsive";})
```

or, combining that with a new feature that will be introduced in 5.4 (see 41da6f479159),

```
document.addEventListener("revive-<YOURID>-completed", function (e) {
    document.querySelectorAll("ins[data-revive-loaded] > a > img").forEach(function (i) {i.class = "img-responsive";});
});
```
