### ISSUE TITLE
{clickurl} macro confict with {random} macro

### ISSUE THREAD

**Issue by nmdangkhoa** [revive-adserver/revive-adserver#1345]
When I create HTML5 banner, I put two macro {clickurl} and {random} in click url. Banner can't redirect to landing page.
Is this bug?
Example code: Banner 1

**Comment by erikgeurts** [comment]
You sample code didn't make it through. Please add a screenshot instead

**Comment by nmdangkhoa** [comment]
This is screenshot
![image](https://user-images.githubusercontent.com/97088756/148035784-381be7ac-7487-4767-b0a1-93dea28678a1.png)

**Comment by erikgeurts** [comment]
In our testing of the most recent version of the Revive Adserver software, this worked just fine, but it is possible something slipped through.

Cache busting is generally not necessary with third party ad tags, so I'd suggest to simply get rid of the &ord={random} bit and it should work for you again.

**Comment by mbeccati** [comment]
Could you please try to remove {clickurl} and use the Alter HTML functionality instead?

**Comment by nmdangkhoa** [comment]
It's true that if I remove {random} the URL is runnable.
Previously with Revive 4.x, I didn't have this problem. This only happens when moving to version 5.2.x, I think the problem is caused by the clickURL validity function. {random} macro generates a random number that makes the URL different from the original so it blocks the URL.

**Comment by mbeccati** [comment]
@nmdangkhoa yes, precisely. I'm not sure if we're able to fix the regression whout adverse side effects.
