### ISSUE TITLE
Add minimum password length

### ISSUE THREAD

**Issue by mbeccati** [revive-adserver/revive-adserver#1349]
As a security improvment, we've decided to settle for a 12 characters default minimum length, but allow that to be changed in the conf file, should anyone want to make it easier or harder for their users.

```
[security]
passwordMinLength=12
```

**Comment by erikgeurts** [comment]
I've been testing this with a release candidate, works very well and my password manager recognizes things correctly.

Should we mention this minimum password length setting in the release notes, so that people wanting to change this are aware of it?

**Comment by mbeccati** [comment]
> Should we mention this minimum password length setting in the release notes, so that people wanting to change this are aware of it?

Yes, I haven't pushed the branch I've been working on just yet.
