### ISSUE TITLE
Please consider handling the password migration differently

### ISSUE THREAD

**Issue by jamieburchell** [revive-adserver/revive-adserver#1354]
Looking at the pending release notes it would appear that there will be some friction at login as users must update their password. There are two ways to handle this without annoying users:

- Automatically rehash and save the validated password at login time (verify using old md5 method)
- Bcrypt all current md5 hashes so that the hashes essentially become the new passwords and check the md5 of the password entered against the hash at login and rehash as necessary

**Comment by erikgeurts** [comment]
We've been discussing this internally already and are working on a more smooth process. We won't be rehashing existing passwords, that's not a safe approach.

**Comment by jamieburchell** [comment]
> We won't be rehashing existing passwords, that's not a safe approach.

Is that due to new password strength requirements or a concern that existing passwords could have been compromised due to using a weak hash?

**Comment by erikgeurts** [comment]
Both, and other considerations.

**Comment by mbeccati** [comment]
@jamieburchell Thanks for your feedback. Here's what we're currently planning to do:

* Automatic rehash for the admin user executing the upgrade wizard
* Successful login for all the other users will trigger a reset email and show an informative message

![immagine](https://user-images.githubusercontent.com/282388/153016271-b813e1d7-9274-4fb9-9bc9-e36a6d24ed7b.png)

* API login will still allow checking the password against the md5 hash in 5.4.x to avoid service disruptions.
