### ISSUE TITLE
Authentication via LDAP

### ISSUE THREAD

**Issue by FedericoHeichou** [revive-adserver/revive-adserver#1361]
Hi, checking the code I found out this application saves passwords in the database using md5 algorithm.
I suggest to change it to bcrypt using the standard PHP `password_verify` and `password_hash`.

Furthermore I am interested to authenticate users using LDAP, is there a way to accomplish that (with a plugin)?
Did you plan to add it to this product?

**Comment by hwde** [comment]
Hi @FedericoHeichou,
I couple of years ago (before "revive" - openads/openx) I wrote a plugin for LDAP authentication. No idea if it is still working, because I don't have an LDAP Server to test with. You may PM me if you'll want to give it a try.

**Comment by FedericoHeichou** [comment]
> Hi @FedericoHeichou, I couple of years ago (before "revive" - openads/openx) I wrote a plugin for LDAP authentication. No idea if it is still working, because I don't have an LDAP Server to test with. You may PM me if you'll want to give it a try.

Hi @hwde , sure, I really appreciate to test your plugin.
Where can I contact you?

**Comment by mbeccati** [comment]
Hi @FedericoHeichou, md5 has been replaced with bcrypt in #1291. The RC1 of 5.4.0 is planned to be released very soon.

There is no plan to add LDAP in core. Hopefully the pluggability of authentication, which is what @hwde's plugin uses, hasn't been broken during these years, especially with the recent password algorithm upgrade.

**Comment by FedericoHeichou** [comment]
> Hi @FedericoHeichou, md5 has been replaced with bcrypt in #1291. The RC1 of 5.4.0 is planned to be released very soon.
> 
> There is no plan to add LDAP in core. Hopefully the pluggability of authentication, which is what @hwde's plugin uses, hasn't been broken during these years, especially with the recent password algorithm upgrade.

Thank you, I already saw that commit but I didn't deep the code enough to find if the new authentication was used after the upgrade, because I still saw the unused `$useMd5`. Probably I made the same mistake of [twmobius](https://github.com/twmobius)!

Anyway glad to know, I will wait for @hwde

**Comment by hwde** [comment]
For anyone interested, I published my (old) codebase at

[https://github.com/hwde/wecosAuthLDAP](https://github.com/hwde/wecosAuthLDAP)

I verified it can still installed with latest revive adserver (v5.*) and (except the LDAP functions) seems to work well. I added a small (Q&D) LDAP Login-Testpage. Maybe it helps, feedback is welcome.
