### ISSUE TITLE
Website distribution statistics displays SQL error on Postgres 

### ISSUE THREAD

**Issue by robertravnik** [revive-adserver/revive-adserver#1366]
**Problem:** 
When viewing distribution statistics for a campaign that ran on multiple websites, SQL error is displayed above statistics table. User can however, still see and navigate statistics table. Problem arises when trying to export that data to Excel as Excel reports corrupted file (probably due to error message). 

Reported SQL error is:

```
_doQuery: [Error message: Could not execute statement]
[Last executed query: SELECT z.affiliateid AS pkey FROM "rv_data_summary_ad_hourly" AS s INNER JOIN "rv_banners" AS d ON (d.bannerid=s.ad_id) INNER JOIN "rv_zones" AS z ON (z.zoneid=s.zone_id) WHERE d.campaignid = 1 AND s.date_time>='2022-04-06 00:00:00' AND s.date_time<='2022-04-06 23:59:59' GROUP BY publisher_id]
[Native message: ERROR:  column "publisher_id" does not exist
LINE 1: ...' AND s.date_time]
```

SQL error screenshot: ![screenshot](https://user-images.githubusercontent.com/9676174/161977827-dc1afb7f-adfe-457c-ab24-14555c692361.jpg) 

**Expected results and behaviour:**
When users is viewing distribution statistics for a campaign that ran on multiple websites, no error appears. Exported Excel statistics file is valid and not corrupted due to SQL error message.

**Steps to reproduce:**
- create `Website A`, with zone `Zone A`,
- create `Website B`, with zone `Zone B`,
- create campaign `Campaign AB` with banner `Banner AB` and link it to `Zone A` and `Zone B`
- generate and run invocation codes for `Zone A` and `Zone B` to display `Banner AB` at least once in each zone.
- wait for next maintenance task to finish
- Go to `Campaign AB` statistics page and click on `Website distribution`.
- Click on `Website A` or `Website B` to get SQL error.

This issue was discovered in Revive 5.3.1. System setup was Ubuntu 20 LTS, Apache2 and PHP7.4-FPM.

**Working solution**
It seems to me that issue is related with code naming schema. Attribute `publisher_id` is used in code while database has field `affiliateid`. I managed to trace this issue down to the `var/max/SqlBuilder.php`. I believe that code-column naming transformation from `publisher_id` to `affiliateid` is missing in function `_getGroupColumns()`. I propose the bugfix below (line 897), which resolves this issue:

```
891     case 'stats_by_entity' :
892          $aGroupColumns = array('ad_id', 'zone_id');
893          if (isset($aParams['include'])) $aGroupColumns = array_merge($aGroupColumns, $aParams['include']);
894          if (isset($aParams['exclude'])) $aGroupColumns = array_diff($aGroupColumns, $aParams['exclude']);
895
896          //bugfix-start
897          if (array_search('publisher_id', $aGroupColumns) !== false) $aGroupColumns[array_search('publisher_id', $aGroupColumns)] = 'z.affiliateid';
897          //bugfix-end
898          break;
```

Please let me know, if you want me to prepare pull request. 

Best regards, Robert

**Comment by mbeccati** [comment]
Thanks for the report. Looks like you are also running on Postgres, right?

**Comment by robertravnik** [comment]
Sorry, I completely forgot to mention that. Yes, it is Postgresql 12.

**Comment by mbeccati** [comment]
@robertravnik I have been trying to replicate this but I wasn't able to. You must be running some third party plugin or code change, as the "export to excel" functionality is disabled.

**Comment by robertravnik** [comment]
@mbeccati Our production server has plugins, but we also confirmed this issue on clean install. I can send you login credentials to our demo server with clean revive install and minimum demo campaign.

**Comment by mbeccati** [comment]
@robertravnik I would suggest re-testing the clean install with 5.4.0 when it's released (in a few days).

**Comment by robertravnik** [comment]
@mbeccati Sure, no problem.

**Comment by robertravnik** [comment]
@mbeccati I re-tested the scenario with clean 5.4.0 version using MySQL and PostgreSQL. The results are as follows: 
- MySQL version works as expected, no error is displayed;
- PostgreSQL version still displays same error as reported above.

I have demo server up and running. I can provide you with credentials if that would be helpful.

**Comment by mbeccati** [comment]
@robertravnik I've tried to replicate it again with latest master, but all seems to be fine here:

> You are currently using Revive Adserver v5.4.1-rc1 running on Apache 2.4.52, PHP 8.1.3 and Postgres 14.1 (Debian 14.1-1.pgdg110+1)-.

Could you try to add a `debug_print_backtrace()` somewhere in the code path that's producing the error? I'd like to understand what's calling the SqlBuilder with unexpected parameters.

**Comment by robertravnik** [comment]
@mbeccati Sure, see output of backtrace below. 

First SQL error:

``
#0  SqlBuilder::_getGroupColumns(stats_by_entity, Array ([placement_id] => 1,[include] => Array ([0] => publisher_id),[exclude] => Array ([0] => ad_id,[1] => zone_id),[custom_columns] => Array ())) called at [/var/www/revive/revive-adserver-5.4.0-pgsql/lib/max/Admin_DA.php:194]
``
``
#1  Admin_DA::_getEntities(stats_by_entity, Array ([placement_id] => 1,[include] => Array ([0] => publisher_id),[exclude] => Array ([0] => ad_id,[1] => zone_id),[custom_columns] => Array ()), , pkey) called at [/var/www/revive/revive-adserver-5.4.0-pgsql/lib/max/Admin_DA.php:460]
``
``
#2  Admin_DA::getEntitiesStats(Array ([placement_id] => 1,[include] => Array ([0] => publisher_id),[exclude] => Array ([0] => ad_id,[1] => zone_id),[custom_columns] => Array ()), ) called at [/var/www/revive/revive-adserver-5.4.0-pgsql/lib/pear/Cache/Lite/Function.php:90]``
``
#3  Cache_Lite_Function->call(Admin_DA::getEntitiesStats, Array ([placement_id] => 1,[include] => Array ([0] => publisher_id),[exclude] => Array ([0] => ad_id,[1] => zone_id),[custom_columns] => Array ()), ) called at [/var/www/revive/revive-adserver-5.4.0-pgsql/lib/max/Admin_DA.php:389]
``
``
#4  Admin_DA::fromCache(getEntitiesStats, Array ([placement_id] => 1,[include] => Array ([0] => publisher_id),[exclude] => Array ([0] => ad_id,[1] => zone_id),[custom_columns] => Array ())) called at [/var/www/revive/revive-adserver-5.4.0-pgsql/lib/OA/Admin/Statistics/Delivery/CommonCrossHistory.php:133]
``
``
#5  OA_Admin_Statistics_Delivery_CommonCrossHistory->getCampaignPublishers(1) called at [/var/www/revive/revive-adserver-5.4.0-pgsql/lib/OA/Admin/Statistics/Delivery/Controller/CampaignAffiliateHistory.php:65]
``
``#6  OA_Admin_Statistics_Delivery_Controller_CampaignAffiliateHistory->start() called at [/var/www/revive/revive-adserver-5.4.0-pgsql/www/admin/stats.php:185]
``

Second SQL error:

``
#0  SqlBuilder::_getGroupColumns(stats_by_entity, Array ([placement_id] => 1,[include] => Array ([0] => publisher_id),[exclude] => Array ([0] => ad_id,[1] => zone_id),[custom_columns] => Array (),[custom_table] => data_intermediate_ad_connection)) called at [/var/www/revive/revive-adserver-5.4.0-pgsql/lib/max/Admin_DA.php:194]
``
``#1  Admin_DA::_getEntities(stats_by_entity, Array ([placement_id] => 1,[include] => Array ([0] => publisher_id),[exclude] => Array ([0] => ad_id,[1] => zone_id),[custom_columns] => Array (),[custom_table] => data_intermediate_ad_connection), , pkey) called at [/var/www/revive/revive-adserver-5.4.0-pgsql/lib/max/Admin_DA.php:460]
``
``
#2  Admin_DA::getEntitiesStats(Array ([placement_id] => 1,[include] => Array ([0] => publisher_id),[exclude] => Array ([0] => ad_id,[1] => zone_id),[custom_columns] => Array (),[custom_table] => data_intermediate_ad_connection), ) called at [/var/www/revive/revive-adserver-5.4.0-pgsql/lib/pear/Cache/Lite/Function.php:90]
``
``
#3  Cache_Lite_Function->call(Admin_DA::getEntitiesStats, Array ([placement_id] => 1,[include] => Array ([0] => publisher_id),[exclude] => Array ([0] => ad_id,[1] => zone_id),[custom_columns] => Array (),[custom_table] => data_intermediate_ad_connection), ) called at [/var/www/revive/revive-adserver-5.4.0-pgsql/lib/max/Admin_DA.php:389]
``
``
#4  Admin_DA::fromCache(getEntitiesStats, Array ([placement_id] => 1,[include] => Array ([0] => publisher_id),[exclude] => Array ([0] => ad_id,[1] => zone_id),[custom_columns] => Array (),[custom_table] => data_intermediate_ad_connection)) called at [/var/www/revive/revive-adserver-5.4.0-pgsql/lib/OA/Admin/Statistics/Delivery/CommonCrossHistory.php:133]
``
``
#5  OA_Admin_Statistics_Delivery_CommonCrossHistory->getCampaignPublishers(1) called at [/var/www/revive/revive-adserver-5.4.0-pgsql/lib/OA/Admin/Statistics/Delivery/Controller/CampaignAffiliateHistory.php:65]
``
``
#6  OA_Admin_Statistics_Delivery_Controller_CampaignAffiliateHistory->start() called at [/var/www/revive/revive-adserver-5.4.0-pgsql/www/admin/stats.php:185]
``

Revive URL on which this error is displayed is: `/www/admin/stats.php?entity=campaign&breakdown=affiliate-history&affiliateid=1&placement_id=1&period_preset=all_stats&period_start=2022-05-03&period_end=2022-05-03&clientid=1&campaignid=1&statsBreakdown=day&listorder=name&orderdirection=up&setPerPage=15`

**Comment by robertravnik** [comment]
@mbeccati I applied your code changes to our demo install and can verify that issue has been resolved. Thank you for fixing this.

**Comment by mbeccati** [comment]
Thanks for reporting!
