### ISSUE TITLE
Export statistics to Excel tool broken

### ISSUE THREAD

**Issue by crumple-zone** [revive-adserver/revive-adserver#1367]
# Problem
Upon our recent upgrade from 5.3.1 to 5.4.0, we discovered that the **Export Statistics to Excel** tool in the Statistics admin area no longer worked:

![image](https://user-images.githubusercontent.com/93990298/164542620-8db13a69-5c8e-4868-b8fd-18dc6402ebcb.png)

It looks like in the 9/21/2021 change set, "Added phpstan, rector, ecs," the branch of logic that would turn that into a link was removed from:
* `lib/OA/Admin/Statistics/Delivery/themes/breakdown_by_date.html`
* `lib/OA/Admin/Statistics/Delivery/themes/breakdown_by_entity.html`
* `lib/OA/Admin/Statistics/Delivery/themes/breakdown_by_week.html`

![image](https://user-images.githubusercontent.com/93990298/164543054-d7af1784-fa7f-44ef-afc1-be788811b4da.png)

I had wondered if there was some JavaScript that took over that functionality, but I haven't uncovered any evidence of that.

It's possible I missed something in the upgrade process, but can't put my finger on it.

# Steps to reproduce
Visit the `[Site where Revive is installed]/admin/stats.php` and try to use the **Export Statistics to Excel** link

**Comment by mbeccati** [comment]
Looks like an oversight, thanks for reporting that

**Comment by crumple-zone** [comment]
My pleasure. Stuff happens. Keep up the good work!
