### ISSUE TITLE
User Access -> Add user -> no password fields

### ISSUE THREAD

**Issue by ddjojo** [revive-adserver/revive-adserver#1379]
Both Password fields are missing when adding a new user to an advertiser account. User can be created, no error messages appears.
Version 5.4.1 running on Apache, PHP 7.4.29 and MySQL 5.5.60-0+deb7u1 (5.4.0 effected as well)

**Comment by erikgeurts** [comment]
See https://www.revive-adserver.com/faq/passwords-in-v5-4-0/
