### ISSUE TITLE
Documentation 503

### ISSUE THREAD

**Issue by mkovacek** [revive-adserver/revive-adserver#1388]
Hi,

it seems that documentation is not reachable, can someone check it.

https://documentation.revive-adserver.com/

**Comment by erikgeurts** [comment]
Thanks for your report. We'll take a look at it and try to get it back up and running again a soon as humanly possible.

**Comment by erikgeurts** [comment]
In the meantime, for some base level documentation, please also have a look at https://www.revive-adserver.com/how-to/

**Comment by erikgeurts** [comment]
The documentation sub site should be available again at https://documentation.revive-adserver.com/ , thanks to @mbeccati for looking into it.
