### ISSUE TITLE
CORS issue on revive adserver hosted edition

### ISSUE THREAD

**Issue by tripheo0412** [revive-adserver/revive-adserver#1393]
I tried to research the docs and forum but cannot find a solution related to CORS issue on revive adserver hosted edition nor can I find the support contact.
I am very sorry if this is not appropriate place, please instruct me where is approriate to post this.

Problem:
I have a subscription with revive adserver hosted edition. We try to integrate revive-adserver for preroll in-stream video ads but got CORS issue.

Request from our domain was block with CORS using this link [https://servedby.revive-adserver.net/fc.php?script=bannerTypeHtml:vastInlineBannerTypeHtml:vastInlineHtml&format=vast&nz=1&zones=pre-roll%3D13686](https://servedby.revive-adserver.net/fc.php?script=bannerTypeHtml%3AvastInlineBannerTypeHtml%3AvastInlineHtml&format=vast&nz=1&zones=pre-roll%3D13686)

![28392](https://user-images.githubusercontent.com/25382052/188437871-34cd50be-030d-4b97-bfbb-021fe8882c08.jpg)
![97953](https://user-images.githubusercontent.com/25382052/188437883-84a3027d-b61e-4ee2-88bb-3fb9784b8afc.jpg)

Steps To Reproduce:
Follow the get started 7 steps guide
[https://www.revive-adserver.com/how-to/get-started/](https://www.revive-adserver.com/how-to/get-started/)**

**Comment by mbeccati** [comment]
CORS is set up properly, but you cannot use cookie-based functionality, like frequency capping.

**Comment by tripheo0412** [comment]
Thank you for replying so fast. Appreciated! I got a couple of questions:
1. Can you list out cookie-based function that could be blocked?
2. Can frequency capping be done using Revive?

We followed jwplayer instruction but fail to get it work.

![28392](https://user-images.githubusercontent.com/25382052/188437871-34cd50be-030d-4b97-bfbb-021fe8882c08.jpg)

**Comment by erikgeurts** [comment]
Please continue to keep note of the fact that Revive Adserver Hosted edition does NOT come with support. This is not a bug either.
