### ISSUE TITLE
Links dont work for emails if zone contains multiple unique banners

### ISSUE THREAD

**Issue by MacSim75** [revive-adserver/revive-adserver#1394]
Hi
Current issue is a copy of [this issue](https://github.com/revive-adserver/revive-adserver/issues/1150) that was closed two years ago.

I have the exact same issue: as soon as more than one banner is in the same email zone, clicking on a banner leads to a blank page instead of leading to the banner URL.
I have more than one banner in my zone, each banner has a delivery rule set on it.

I tried this morning to use [Multiple Ads in en Email zone plugin](https://www.reviveadservermod.com/multiple-ads-in-an-email-zone) but it's not working as I expected.

You might have more infos about the way I configured my ads watching this video https://www.awesomescreenshot.com/video/10897432?key=3272678bc20757af49fbbd3a0403bdeb (it's a feedback about the plugin I tested this morning but you will see the steps I made)

**Comment by mbeccati** [comment]
Sorry, we don't offer support for third party modifications. Please check with their support.

Newsletter zones don't support multiple banners, unless they are from campaigns that do not overlap (e.g. the second one starts after the first one has ended).

**Comment by MacSim75** [comment]
I don't need support for the third party plugin. Revive adserver should handle this use case by default.
Actually Revive ad server doesn't support multiple banners in a single newsletter zones even if there's a single campaign.
But as the backoffice allows to add more than just one banner, to me it sounds like a bug on your side.

I installed the third party plugin to see if I would have a quick workaround.
Still the main issue is that you can add more than one banner in the backoffice but clicking on the banner in the mail will lead to a blank page. So that's a bug to fix on your side.

**Comment by mbeccati** [comment]
> Revive ad server doesn't support multiple banners in a single newsletter zone even if there's a single campaign

Yes. How would it know which one you clicked on?

**Comment by MacSim75** [comment]
> Yes. How would it know which one you clicked on?
The same way it does on the websites zones ?
I don't know what it involves, I don't know if javascript is used on the website to track the click on a banner which could explain why it can't be done in the email zone. But once again, if revive adserver can't handle this use case, then it should be written somewhere in the backoffice that adding more than one banner in an email zone is not covered - or a validate/submit callback should return an error when we try to add another banner if there's already one in the zone.

**Comment by mbeccati** [comment]
> The same way it does on the websites zones ?

 Unfortunately that can't be done.

> it should be written somewhere in the backoffice that adding more than one banner in an email zone is not covered

That's what normally happens. Sure, you might be able to trick the system, but you won't get any useful result.

![immagine](https://user-images.githubusercontent.com/282388/188463335-77fc6486-2b63-4897-ba15-a85f9c95bb70.png)

**Comment by mbeccati** [comment]
> There's no error at all when I try to link another banner to the same zone, I guess because there's no overlap between the rules, each rule leads to a single banner being picked.

The logic is not so advanced to detect that delivery rules lead to non-overlapping results. However, there might be a bug preventing the error message to pop up if two banners from the same campaign are being picked.

**Comment by MacSim75** [comment]
How about trying to fix the fact that the redirect callback is not taking care about the delivery rules instead?
The official doc doesn't says that we can't have more than one banner in an email zone ; on the other hand it says that we can inject site-variables in it. What's the point of injecting a site-variable if we can't make it vary?
It works to deliver the banner, it has to work on the redirection side as well.
Why is it so hard to have the same logic in 2 different php callbacks ?

**Comment by mbeccati** [comment]
Sure, click redirection can be addressed the same way, as long as delivery rules don't overlap, which can't be guaranteed, so you would end up with a messy user experience.

If it isn't hard, PRs are welcome.

**Comment by MacSim75** [comment]
For an ad manager, UX can't be more messy than displaying a banner which redirects to a blank page - and that's the case actually.

> If it isn't hard, PRs are welcome.

Sure I should dig into your 3442 lines written in PHP5 with no indentation at all in order to understand how it works to then provide a PR. How funny you are.

I created the issue, explained what was the problem and how to reproduce it... now it's on your side.
The only help I'll give at this point is that [the documentation](https://documentation.revive-adserver.com/display/DOCS/Tag+Variables) will need an update cause the callback cl.php will need the query params just like the img src. For the PR you're a big boy it's not my project. Show us your powerful dev skills it will be better for the project than trolling here cause it's all you've done so far since yesterday.
