### ISSUE TITLE
on AWS EC2 Linux: Cannot login: "Session cookie error, please log in again"

### ISSUE THREAD

**Issue by pirod** [revive-adserver/revive-adserver#1397]
Problem:
On AWS EC2, session cookies fail and cannot login
See topic:
https://forum.revive-adserver.com/topic/6434-cannot-login-session-cookie-error-please-log-in-again/?_fromLogin=1

**Comment by mbeccati** [comment]
I'm sorry, given the huge number of people running on EC2, this is definitaly not a Revive Adserver bug.

Possibily some misconfiguration on your side, but the issue tracker is not suitable for support questions.

**Comment by pirod** [comment]
Hi,

 

Maybe so, but if the forums were better monitored and provided solutions I would have avoided the bug report

There is more people having same issue. Also we have many more apps running and never had issues or need for any setting to make cookies work. 

 

I see other bugs reported on cookies using canonical names. We have CNAME for domain in AWS could that affect session cookies?

 

So maybe you can share the magic?

 

Thanks

Pierre

**Comment by uberhacker** [comment]
I would like to request to reopen this issue.  There appears to be a repeatable problem with the install/upgrade that is killing sessions.  I don't believe this has anything to do with the infrastructure as PHP sessions work fine outside of Revive.  For reference, see https://forum.revive-adserver.com/topic/6434-cannot-login-session-cookie-error-please-log-in-again/.  If you are not going to look into it further, fine but please reopen.
