### ISSUE TITLE
No stylesheet

### ISSUE THREAD

**Issue by lordmatt** [revive-adserver/revive-adserver#1407]
A fresh install on a dedicated subdomain following the install and set-up instructions has no styles being applied.

I cannot find a setting or path mapping that needs to be tweaked from vanilla to get that working.

**Comment by erikgeurts** [comment]
This is almost always caused by having an ad blocker installed. Could you please check that?

**Comment by lordmatt** [comment]
I finally fixed it having force SSL set to true. It would perhaps be an idea to make that a setup option.

**Comment by erikgeurts** [comment]
Sounds a bit like a server configuration more than a Revive Adserver issue.
