### ISSUE TITLE
xmlrpc delivery tag  dropdown option dont show revive 5.4.1

### ISSUE THREAD

**Issue by reinaldoviedo94** [revive-adserver/revive-adserver#1408]
Hello I installed last version of revive and in plugins about Invocation Tags Plugin options xmlrpc dont show either in dropdown selection in type banner invocation
How i can fix this??

![imagen](https://user-images.githubusercontent.com/82004527/202125521-09b7c2d2-fd5d-4a58-94ae-354a154c8a0a.png)

![imagen](https://user-images.githubusercontent.com/82004527/202126583-66d78ded-c586-4c13-8df4-a86d651741cf.png)

Thanks in advanced!!!

**Comment by mbeccati** [comment]
Pls see #1278
