### ISSUE TITLE
Rules are not applied or applied in 50% of cases only

### ISSUE THREAD

**Issue by serjyy** [revive-adserver/revive-adserver#1412]
Hi everybody! I experience the following issue: I've uploaded four images on our website: two in English & two in French. 

I have set the following rule: when person's language is any language except French (e.g., English, Italian, Spanish) --> show the English version of Image 1 and Image 2

IF person's language is French (all of its variations) --> show the French version of Image 1 and Image 

Now, whenever I visit our website I see the following: - sometimes everything is ok
                                                                                      - sometimes when I launch the French version of the site Image 1 is in French and Image 2 in English, or vice-versa
                                                                                      - sometimes both of the images are in English

The **same** happens when I launch the English version of the website 

Could you help me out please?

**Comment by erikgeurts** [comment]
This is not a support site, we use Github issues only for bug reports. Please consider posting your question on our community forum at https://forum.revive-adserver.com.
