### ISSUE TITLE
Uncaught TypeError: Unsupported operand types

### ISSUE THREAD

**Issue by Lochness122** [revive-adserver/revive-adserver#1413]
```
Fatal error: Uncaught TypeError: Unsupported operand types: string + array
in /data/b/2/b2d9ac70-6b9b-45c3-9333-85efbc0f13f4/
....sk/web/ads/www/delivery/afr.php:3999
Stack trace:
#0
/data/b/2/b2d9ac70-6b9b-45c3-9333-85efbc0f13f4/
.....sk/web/ads/www/delivery/afr.php(3810): _adSelectZone(1, Array,
'', true) 
#1 /data/b/2/b2d9ac70-6b9b-45c3-9333-85efbc0f13f4/
.....sk/web/ads/www/delivery/afr.php(4470): MAX_adSelect('zone:1',
'', '', '', 0, 'UTF-8', Array, true, '', 'https://www.mmp/...', NULL) 
#2 {main} thrown in /data/b/2/b2d9ac70-6b9b-45c3-9333-85efbc0f13f4/
.....sk/web/ads/www/delivery/afr.php on line 3999
```

**Comment by erikgeurts** [comment]
Our Github pages are not to be used for support questions. Consider posting your question on the community forums at https://forum.revive-adserver.com.

**Comment by mbeccati** [comment]
@Lochness122 It would help if you could post more information about the actions that led to the error. As is, it is pretty much useless as bug report.

**Comment by Lochness122** [comment]
Thank you for your response, here are more information
I am using revive ads, when I try to display ads via iframe, the next error
appears:

Fatal error: Uncaught TypeError: Unsupported operand types: string + array
in /data/b/2/b2d9ac70-6b9b-45c3-9333-85efbc0f13f4/
mmproject2.sk/web/ads/www/delivery/afr.php:3999 Stack trace: #0
/data/b/2/b2d9ac70-6b9b-45c3-9333-85efbc0f13f4/
mmproject2.sk/web/ads/www/delivery/afr.php(3810): _adSelectZone(1, Array,
'', true) #1 /data/b/2/b2d9ac70-6b9b-45c3-9333-85efbc0f13f4/
mmproject2.sk/web/ads/www/delivery/afr.php(4470): MAX_adSelect('zone:1',
'', '', '', 0, 'UTF-8', Array, true, '', 'https://www.mmp...', NULL) #2
{main} thrown in /data/b/2/b2d9ac70-6b9b-45c3-9333-85efbc0f13f4/
mmproject2.sk/web/ads/www/delivery/afr.php on line 3999

My php version is 7.4

st 4. 1. 2023 o 13:46 Matteo Beccati ***@***.***> napísal(a):
