### ISSUE TITLE
Revive adserver does not load probably

### ISSUE THREAD

**Issue by MahmoudMm** [revive-adserver/revive-adserver#1414]
I have used revive docker image from a repo to deploy my server
https://github.com/dustin-hawkins/ReviveDockerImage 
I use Haproxy as reverse proxy and this is the part of configration which is related to revive: 
`

frontend public
    bind *:80
    bind *:443 ssl crt /usr/local/etc/certs/ alpn h2,http/1.1
    mode http

    http-request set-header X-Forwarded-Port %[dst_port]
    http-request set-header X-Forwarded-For %[src]
    http-request set-header X-Forwarded-Proto https if { ssl_fc }
    http-request set-header X-Forwarded-Proto http if !{ ssl_fc }

    acl is_well_known path_beg -i /.well-known/
    acl host_revive hdr(host) -i ads.*****.com www.ads.*****.com
    acl host_main hdr(host) -i ******
    acl host_auth hdr(host) -i ******

    redirect scheme https code 301 if (host_main || host_auth) && !{ ssl_fc }

    use_backend revive if host_revive
`

installing the server starts with no problem as you may see in this picture 

https://ibb.co/bz22vHx

everything works fine until i reach the plugins step it shows these errors 
https://ibb.co/QM2WQV5

`
    Installation of plugin "reviveMaxMindGeoIP2" failed:
        Server returned: 0
    Installation of plugin "openXVideoAds" failed:
        Server returned: 0
    Installation of plugin "openXDeliveryLog" failed:
        Server returned: 0
    Installation of plugin "openXInvocationTags" failed:
        Server returned: 0
    Installation of plugin "openXDeliveryCacheStore" failed:
        Server returned: 0
    Installation of plugin "openXReports" failed:
        Server returned: 0
    Installation of plugin "openXDeliveryLimitations" failed:
        Server returned: 0
    Installation of plugin "openXBannerTypes" failed:
        Server returned: 0
`

trying to access the website after that shows this page which is not fully loaded 
https://ibb.co/pxZ1D8v
here is a screen from the network tab 
https://ibb.co/RPfwBg0

However i noticed this message
https://ibb.co/gwNrdVL
https://ibb.co/PmHcbSN

when i disabel the ssl page load normally with issues in login (i login with every page i enter)
Everything works fine in localhost enviroment however localhost does not have ssl/haproxy configrations

**Comment by erikgeurts** [comment]
Make sure to download Revive Adserver from https://www.revive-adserver.com/download/ only.
Any other source is not approved nor to be trusted.
Installation instructions can be found here: https://www.revive-adserver.com/how-to/install/

**Comment by MahmoudMm** [comment]
> Make sure to download Revive Adserver from https://www.revive-adserver.com/download/ only. Any other source is not approved nor to be trusted. Installation instructions can be found here: https://www.revive-adserver.com/how-to/install/

As you can i see, I have downloaded it from the official site:- 
`RUN wget -qO- https://download.revive-adserver.com/revive-adserver-5.4.1.tar.gz | tar xz --strip 1 \`

**Comment by erikgeurts** [comment]
You mentioned using a Docker image.

**Comment by MahmoudMm** [comment]
I have made the container myself downloading the official revive 
Here is Dockerfile:- 

`
FROM alpine

WORKDIR /var/www/html

RUN apk --update upgrade && apk update && apk add curl ca-certificates && update-ca-certificates --fresh && apk add openssl

RUN apk --update add \
    --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
    --repository http://dl-cdn.alpinelinux.org/alpine/edge/community \
        nginx \
        gzip \
        php7 \
        php7-dom \
        php7-ctype \
        php7-curl \
        php7-fpm \
        php7-gd \
        php7-intl \
        php7-json \
        php7-mbstring \
        php7-mcrypt \
        php7-mysqli \
        php7-mysqlnd \
        php7-opcache \
        php7-pdo \
        php7-pdo_mysql \
        php7-posix \
        php7-session \
        php7-xml \
        php7-iconv \
        php7-phar \
        php7-openssl \
        php7-zlib \
        php7-zip \
    && rm -rf /var/cache/apk/*

RUN wget -qO- https://download.revive-adserver.com/revive-adserver-5.0.5.tar.gz | tar xz --strip 1 \
    && chown -R nobody:nobody . \
    && rm -rf /var/cache/apk/*

COPY nginx/nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /run/nginx

EXPOSE 80

CMD php-fpm7 && nginx -g 'daemon off;'
`

You can notice 
` RUN wget -qO- https://download.revive-adserver.com/revive-adserver-5.4.1.tar.gz | tar xz --strip 1 \`

and here is nginx config 

`user nobody;
worker_processes 4;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    #access_log /dev/stdout;
    error_log /dev/stdout;

    gzip		on;
    gzip_vary		on;
    gzip_disable	"MSIE [1-6]\.";
    gzip_static		on;
    gzip_min_length	512;
    gzip_buffers	32 8k;
    gzip_http_version	1.0;
    gzip_comp_level	6;
    gzip_proxied	any;
    gzip_types text/plain text/css text/xml application/javascript application/x-javascript application/xml application/xml+rss application/ecmascript application/json image/svg+xml;

    server {
        listen 80;
        server_name _;

        client_max_body_size 16M;
        client_body_buffer_size 128k;

        real_ip_header X-Forwarded-For;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header HTTPS "on";
        set_real_ip_from 0.0.0.0/0;
	real_ip_recursive  on;

        root /var/www/html;
        index index.php;

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass 127.0.0.1:9000;
        }
    }
}
`

**Comment by MahmoudMm** [comment]
Update:- 
I have found out that the issue is related to https connection; 
I have disabled https in the domain and tried to deploy revive ad server without and ssl connection and it worked fine. 

Now I am trying to find a way to resolve working with https....... any help or suggestions would be helpful

**Comment by MahmoudMm** [comment]
Update:- 
Finally found the solution from this post: 
https://forum.revive-adserver.com/topic/4842-revive-login-page-redirects-from-https-to-http-why/

By activating "Force SSL Access on User Interface" option, everything now works fine!!!! 
I would like to suggest to add this option in installation proccess. 
@erikgeurts thank you for the hard work and please maintain the good work

**Comment by erikgeurts** [comment]
As mentioned so many times before: these Github issues are not a support forum.
