### ISSUE TITLE
Revive not properly tracking clicks?

### ISSUE THREAD

**Issue by 420Banners** [revive-adserver/revive-adserver#1417]
We have an advertiser account with three campaigns and a single banner. Zones are set and associated with the banner. For some reason, this advertiser's stats for the past year are weird and shows the main campaign with a much higher CTR than the other two. Impressions are similar but the CTR is drastically higher for the first campaign when compared to the last two.

Feb 6th 2022 - Feb 6th 2023

Revive's Recorded Stats:

Stats - https://i.imgur.com/n5CBSBB.png

First Campaign: https://i.imgur.com/3LhKQt1.png
Second Campaign: https://i.imgur.com/gDhBedU.png
Third Campaign: https://i.imgur.com/Cc6lclT.png

All campaign settings are identical (default settings). 

Something isn't right here.

**Comment by erikgeurts** [comment]
These Github issues are not to be used for asking support questions. Please consider using the Community Forum at https://forum.revive-adserver.com instead

**Comment by 420Banners** [comment]
> These Github issues are not to be used for asking support questions. Please consider using the Community Forum at https://forum.revive-adserver.com instead

I understand that but the tracking clearly isn't working as intended, so isn't this a bug?

**Comment by erikgeurts** [comment]
There is nothing in the screenshots that indicates there's a bug. All I can see are statistics. Based on this we can't even begin to investigate, let alone assume there is a bug that could possible by replicated.
