### ISSUE TITLE
PHP making too many processes and CPU is too high

### ISSUE THREAD

**Issue by pokolokatepetl** [revive-adserver/revive-adserver#1418]
Hi there

I have a problem with Revive adserver on my Windows 2019 machine. It used to work ok, but I think since I upgraded mysql to 8 or PHP to 8, it starts getting this problem every few days...

The number of php-cgi.exe processes rise and every one of them uses like 1 or 2% CPU time, resulting my server going from 30% CPU to 70-80% CPU.

I found out that at that time the PHP log has many more errors. They look like this:

thrown in D:\Inetpub\vhosts\mydomain.com\lib\OA\Dal\Delivery\mysqli.php on line 170
[07-Feb-2023 10:14:31 UTC] PHP Fatal error:  Uncaught TypeError: mysqli_real_escape_string(): Argument #1 ($mysql) must be of type mysqli, bool given in D:\Inetpub\vhosts\mydomain.com\lib\OA\Dal\Delivery\mysqli.php:170
Stack trace:
#0 D:\Inetpub\vhosts\mydomain.com\lib\OA\Dal\Delivery\mysqli.php(170): mysqli_real_escape_string()
#1 [internal function]: OX_escapeString()
#2 D:\Inetpub\vhosts\mydomain.com\lib\OA\Dal\Delivery\mysqli.php(200): array_map()
#3 D:\Inetpub\vhosts\mydomain.com\lib\OA\Dal\Delivery\mysqli.php(191): OX_bucket_prepareUpdateQuery()
#4 D:\Inetpub\vhosts\mydomain.com\plugins\deliveryLog\oxLogImpression\logImpression.delivery.php(27): OX_bucket_updateTable()
#5 D:\Inetpub\vhosts\mydomain.com\www\delivery\lg.php(2874): Plugin_deliveryLog_OxLogImpression_LogImpression_Delivery_logImpression()
#6 D:\Inetpub\vhosts\mydomain.com\www\delivery\lg.php(2200): OX_Delivery_Common_hook()
#7 D:\Inetpub\vhosts\mydomain.com\www\delivery\lg.php(3251): MAX_Delivery_log_logAdImpression()
#8 {main}

The Revive log says there are too many connections, but I believe each PHP takes one connection and that the PHP is the problem, not database:

on line 82 of &quot;D:\Inetpub\vhosts\mydomain.com\lib\OA\DB\AdvisoryLock.php&quot;
                           on line 53 of &quot;D:\Inetpub\vhosts\mydomain.com\lib\OA\Maintenance\Auto.php&quot;
                           on line 3268 of &quot;D:\Inetpub\vhosts\mydomain.com\www\delivery\lg.php&quot;
Feb 07 09:05:03 +0100 OX-63e2143e37240 [    error]  Will re-try connection...
                           on line 83 of &quot;D:\Inetpub\vhosts\mydomain.com\lib\OA\DB\AdvisoryLock.php&quot;
                           on line 53 of &quot;D:\Inetpub\vhosts\mydomain.com\lib\OA\Maintenance\Auto.php&quot;
                           on line 3268 of &quot;D:\Inetpub\vhosts\mydomain.com\www\delivery\lg.php&quot;
Feb 07 09:05:03 +0100 OX-63e2143e2cdef [    error]  Error connecting to database to obtain locking object. Native error follows:
                           on line 81 of &quot;D:\Inetpub\vhosts\mydomain.com\lib\OA\DB\AdvisoryLock.php&quot;
                           on line 53 of &quot;D:\Inetpub\vhosts\mydomain.com\lib\OA\Maintenance\Auto.php&quot;
                           on line 3268 of &quot;D:\Inetpub\vhosts\mydomain.com\www\delivery\lg.php&quot;
Feb 07 09:05:03 +0100 OX-63e2143e2cdef [    error]  MDB2 Error: unknown error : connect: [Error message: Too many connections]
[Native code: 1040]
[Native message: Too many connections]

Restarting the application pool resets things back to normal for a few days.

Anybody can help me with this logs, what is going wrong?

**Comment by mbeccati** [comment]
I would suggest using the forum for support requests.

**Comment by erikgeurts** [comment]
> I would suggest using the forum for support requests.

https://forum.revive-adserver.com
