### ISSUE TITLE
Upgrade from 5.0.1 to 5.4.1

### ISSUE THREAD

**Issue by jonyking** [revive-adserver/revive-adserver#1422]
While Upgrading from 5.0.1 to 5.4.01 we got the error message that the rv_agency can not be updated because of duplicated column name. This must be a bug because the column exists since 5.0.1 or before so the upgrading process is not working correctly.

```
MDB2 Error: unknown error
_doQuery: [Error message: Could not execute statement]
[Last executed query: ALTER TABLE rv_agency ADD status SMALLINT(6) DEFAULT 0 NOT NULL]
[Native code: 1060]
[Native message: Duplicate column name 'status']
```

**Comment by mbeccati** [comment]
The column has been added in 5.1.0, so perhaps there's has been an incomplete attempt of upgrading before.

I would suggesting checking our forums as github isn't the right place for support.

**Comment by jonyking** [comment]
sss

**Comment by jonyking** [comment]
> The column has been added in 5.1.0, so perhaps there's has been an incomplete attempt of upgrading before.
> 
> I would suggesting checking our forums as github isn't the right place for support.

I think it is a bug. Because why should the upgrade process add the column when it was first deployed in a previous version which was installed correctly?
