### ISSUE TITLE
Issue with HTML banner upload

### ISSUE THREAD

**Issue by raj16120912** [revive-adserver/revive-adserver#1423]
Page crashes while uploading HTML Banner.
<img width="1949" alt="image(1)" src="https://user-images.githubusercontent.com/73597025/233988409-821aefe1-2925-40df-aebd-ab82449b9565.png">

![openx](https://user-images.githubusercontent.com/73597025/233988433-37e85b2d-d116-4f2e-8bb3-6e9b7dccfd65.gif)

Problem:
Page crash when uploading HTML Banner

Steps To Reproduce:
Login -> Click on Banners -> Add new banner -> Select Generic HTML Banner -> Upload

**Comment by mbeccati** [comment]
It looks like you've upgraded PHP but you are running an incompatible version of Revive Adserver. There's no `$this` on line 602, so you must be using a version that's at least 3 years old.

If you need support, forums are better suited for this as it is definitely not a bug in the current version.
