### ISSUE TITLE
Admin credentials not accepting while upgrade

### ISSUE THREAD

**Issue by raj16120912** [revive-adserver/revive-adserver#1424]
I'm trying to upgrade revive-adserver from v3.2 to v5.4.1

Upon providing admin credentials, I get an error message saying credentials are wrong.

I tried same credentials to login in exisiting version and I'm able to access.

Here, is my apache error log output.
```
[Tue May 02 15:42:10.811761 2023] [access_compat:error] [pid 17069] [client 192.168.14.4:42788] AH01797: client denied by server configuration: /var/www/openx.trellian.com/webroot/admin/install.php, referer: http://openx.trellian.com.rajp.test/admin/install.php
[Tue May 02 15:42:44.959926 2023] [access_compat:error] [pid 17074] [client 192.168.14.4:35198] AH01797: client denied by server configuration: /var/www/openx.trellian.com/webroot/admin/install.php, referer: http://openx.trellian.com.rajp.test/admin/install.php
```

**Comment by mbeccati** [comment]
I would suggest hiding your admin interface url. Upgrades from 3.2 are manually, so I wouldn't expect to have bugs there. I would try checking the log files in the var folder too.

**Comment by mbeccati** [comment]
No useful feedback, closing.
