### ISSUE TITLE
Click based conversion tracking not working

### ISSUE THREAD

**Issue by kavit-gangar** [revive-adserver/revive-adserver#1428]
Click conversion tracking not working probably because the _OXLCA[i] cookie is not being set by cl.php. 

$lastClick = MAX_Delivery_log_getArrGetVariable('lastClick', $_COOKIE);  (line 3359 in cl.php)
Upon further debugging, got to know that the **$COOKIE** variable being passed in the above function call makes the **$array** parameter in **MAX_Delivery_log_getArrGetVariable()** function not null and hence the _OXLCA[i] cookie is not being set and returned in the response

Steps to reproduce: 
1. Create a tracker and link it to a campaign
2. Click on any of the banners linked to this campaign, load the page having tracker code in it and check the cookies -> only impression related cookies are set

Revive Ad server version: 5.4.1

**Comment by kavit-gangar** [comment]
@mbeccati Can you have a look at this?

**Comment by mbeccati** [comment]
Apologies for the delay. Thanks for the report.
