### ISSUE TITLE
 Error when accessing localhost/adserver

### ISSUE THREAD

**Issue by sonnguyentb21** [revive-adserver/revive-adserver#1435]
Hi guys,

I'm new to revive-adserver, but I'm excited about it, I did a successful installation on my local machine,  v5.4.1, tested with multi sites at localhost, everything working fine, i like it a lot!

However, today I try to access localhost/adserver again, but it fails again:

 

<?php

/*
+---------------------------------------------------------------------------+
| Revive Adserver                                                           |
| http://www.revive-adserver.com                                            |
|                                                                           |
| Copyright: See the COPYRIGHT.txt file.                                    |
| License: GPLv2 or later, see the LICENSE.txt file.                        |
+---------------------------------------------------------------------------+
*/

/**
 * This file is only called to redirect to somewhere else, however, if Revive
 * Adserver is not yet installed, we need to know that it was this file that
 * was called, so set a global variable.
 */
define('ROOT_INDEX', true);

// Require the initialisation file
require_once 'init.php';

// Required files
require_once LIB_PATH . '/Admin/Redirect.php';

// Redirect to the admin interface
if (OA_INSTALLATION_STATUS == OA_INSTALLATION_STATUS_INSTALLED) {
    OX_Admin_Redirect::redirect();
}

I using PHP version 8.1.22. I try stop service nginx and then uninstall and install apache2. Next, I stop, start and restart apache2. Finally I had update and upgrade and sudo systemctl status apache2.service.
It still that error.

I did a google search, read various topics on this forum but after a entire day I'm exhausted. Does anyone had a similar issue in recent times?

Any comment will be very welcome guys, thank you a lot!

**Comment by erikgeurts** [comment]
For community support, please visit https://forum.revive-adserver.com

**Comment by sonnguyentb21** [comment]
> 

@erikgeurts Yes, I had posted ask in community support, but my post was not just accept request
