### ISSUE TITLE
http://www.revive-adserver.com/download/ is down?

### ISSUE THREAD

**Issue by fwiessner** [revive-adserver/revive-adserver#1437]
Problem:

http://www.revive-adserver.com/download/ has no content?

Steps To Reproduce:

Open http://www.revive-adserver.com/download/ with a browser. 

https:// versions also do not work.

**Comment by erikgeurts** [comment]
https://www.revive-adserver.com/download/ is the correct page, which works just fine for me.

Where did you find a reference to the non-https version of the url?

**Comment by erikgeurts** [comment]
By the way, I just opened http://www.revive-adserver.com/download/ and it redirects to https://www.revive-adserver.com/download/ immediately (as intended).

**Comment by erikgeurts** [comment]
Since we haven't heard back from you, I'm closing this issue.
