### ISSUE TITLE
Problem with Revive installation and upgrade behind proxy

### ISSUE THREAD

**Issue by utrenkner** [revive-adserver/revive-adserver#1447]
I just upgraded our Revive installation to the latest 5.5.0 release.

I just wanted to report that I ran into problems because Revive would redirect me to the URL of the backend server rather than the public address. The setup is:

```
Public          -> Backend
ad.mydomain.com -> ad-proxy.mydomain.com
```

So, when I entered https://ad.mydomain.com/www/admin/index.php it would redirect me to https://ad-proxy.mydomain.com/www/admin/index.php. I had to set up a public web server entry for the proxy-server on the  incoming server and forward that to the backend server. 

Furthermore, I encountered the same problem as with the last upgrade for what concerns the [(wrong) domain of the admin-cookie](https://github.com/revive-adserver/revive-adserver/issues/1396). I, again, patched the code manually to allow logging in as admin.

Despite this little problems, I was able to upgrade Revive to the latest release. Thank you for the update!!!

PS: I really look forward to the possibility of upgrading via the command line, the next time.

**Comment by erikgeurts** [comment]
This is not a support forum, please use https://forum.revive-adserver.com for that.

**Comment by utrenkner** [comment]
Sorry, this was not meant as a support request. It was rather a bug report: The admin part of Revive does behave quite differently from the public part of Revive and also differently from what I had expected. I thought, this was not intended and reported the behaviour.

I have no problem with you saying that Revive should not be used behind a proxy server and that you do not intend to add this feature. Still, I think it was not unreasonable of me to think it was possible, especially after your reaction to the related #1396 

For me the reason to move Revive behind a proxy was that IPv4 addresses are more and more scarce and our web hoster increased prices, again. I would have thought other Revive admins would want to run it behind a proxy, too.

**Comment by erikgeurts** [comment]
There is no bug, you're simply attempting a method that we don't recommend.

The only recommended update procedure is described in full detail at https://www.revive-adserver.com/how-to/update/
