### ISSUE TITLE
Always redirecting to install.php

### ISSUE THREAD

**Issue by gasparuff** [revive-adserver/revive-adserver#1456]
I have installed Revive Adserver 5.5.0 now multiple times because I thought I did something wrong. First, I installed it in a Docker container together with MySQL. But after a day when I wanted to open the admin console, I was redirected to the install screen (net/revive/www/admin/install.php?action=welcome). I thought maybe it's due to my lack of high docker expertise so I kept messing with it and tried different configurations, all leading to the same results. In the end I went ahead and took a "regular" PHP hosting environment (running on PHP 8.0) together with MySQL 8.0, but now after a day of finishing installation and setting up a campaign, banner etc., I'm again seeing the installation screen. What did I do wrong? I don't see anything fishy in the debug log which I'm attaching here.
Although I noticed it took some time until the web interface opened when I tried to visit my hosted installation.

What also might be worth noting: I'm running Revive in a PHP environment on the Azure cloud and I have NOT enabled the "always stay on" configuration. That means, the server shuts down when being idle for some time. 

Delivery of my banners work though, what's also a bit strange in this situation...

    
    Dec 21 10:24:13 +0000 OX-6584124d139ef [     info]  Running Automatic Maintenance Task
     
     
    Dec 21 10:24:16 +0000 OX-maintenance-6584124d139ef [     info]  Running Maintenance Engine
    Dec 21 10:24:16 +0000 OX-maintenance-6584124d139ef [     info]  Running Maintenance Statistics Engine
    Dec 21 10:24:16 +0000 OX-maintenance-6584124d139ef [     info]  Task begin: OX_Maintenance_Statistics_Task_SetUpdateRequirements
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]  - Maintenance statistics will be run
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]  - The intermediate table statistics will be updated
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]  - The final table statistics will be updated
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]  Task complete: OX_Maintenance_Statistics_Task_SetUpdateRequirements
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]  Task begin: OX_Maintenance_Statistics_Task_MigrateBucketData
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 12:00:00 UTC and 2023-12-20 12:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 13:00:00 UTC and 2023-12-20 13:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 14:00:00 UTC and 2023-12-20 14:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 15:00:00 UTC and 2023-12-20 15:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 16:00:00 UTC and 2023-12-20 16:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 17:00:00 UTC and 2023-12-20 17:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 18:00:00 UTC and 2023-12-20 18:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 19:00:00 UTC and 2023-12-20 19:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 20:00:00 UTC and 2023-12-20 20:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 21:00:00 UTC and 2023-12-20 21:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 22:00:00 UTC and 2023-12-20 22:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 23:00:00 UTC and 2023-12-20 23:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 00:00:00 UTC and 2023-12-21 00:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 01:00:00 UTC and 2023-12-21 01:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 02:00:00 UTC and 2023-12-21 02:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 03:00:00 UTC and 2023-12-21 03:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 04:00:00 UTC and 2023-12-21 04:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 05:00:00 UTC and 2023-12-21 05:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 06:00:00 UTC and 2023-12-21 06:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 07:00:00 UTC and 2023-12-21 07:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 08:00:00 UTC and 2023-12-21 08:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 09:00:00 UTC and 2023-12-21 09:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 12:00:00 UTC and 2023-12-20 12:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 13:00:00 UTC and 2023-12-20 13:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 14:00:00 UTC and 2023-12-20 14:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 15:00:00 UTC and 2023-12-20 15:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 16:00:00 UTC and 2023-12-20 16:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 17:00:00 UTC and 2023-12-20 17:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 18:00:00 UTC and 2023-12-20 18:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 19:00:00 UTC and 2023-12-20 19:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 20:00:00 UTC and 2023-12-20 20:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 21:00:00 UTC and 2023-12-20 21:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 22:00:00 UTC and 2023-12-20 22:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-20 23:00:00 UTC and 2023-12-20 23:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 00:00:00 UTC and 2023-12-21 00:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 01:00:00 UTC and 2023-12-21 01:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 02:00:00 UTC and 2023-12-21 02:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 03:00:00 UTC and 2023-12-21 03:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 04:00:00 UTC and 2023-12-21 04:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 05:00:00 UTC and 2023-12-21 05:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 06:00:00 UTC and 2023-12-21 06:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 07:00:00 UTC and 2023-12-21 07:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 08:00:00 UTC and 2023-12-21 08:59:59 UTC
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - The rv_data_bkt_a_var table is a raw data table. Data logged in real-time, not operation intervals.
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]      - Accordingly, pruning of the rv_data_bkt_a_var table will be performed based on data that has a logged date between 
    Dec 21 10:24:17 +0000 OX-maintenance-6584124d139ef [     info]        2023-12-21 09:00:00 UTC and 2023-12-21 09:59:59 UTC
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Task complete: OX_Maintenance_Statistics_Task_MigrateBucketData
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Task begin: OX_Maintenance_Statistics_Task_DeDuplicateConversions
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Task complete: OX_Maintenance_Statistics_Task_DeDuplicateConversions
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Task begin: OX_Maintenance_Statistics_Task_ManageConversions
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Task complete: OX_Maintenance_Statistics_Task_ManageConversions
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Task begin: OX_Maintenance_Statistics_Task_SummariseFinal
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Task complete: OX_Maintenance_Statistics_Task_SummariseFinal
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Task begin: OX_Maintenance_Statistics_Task_LogCompletion
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Task complete: OX_Maintenance_Statistics_Task_LogCompletion
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Task begin: OX_Maintenance_Statistics_Task_ManageCampaigns
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  - Managing (activating/deactivating) campaigns
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Task complete: OX_Maintenance_Statistics_Task_ManageCampaigns
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Maintenance Statistics Engine Completed (Started at 2023-12-21 10:24:16 UTC)
    Dec 21 10:24:18 +0000 OX-6584124d139ef [     info]  Running Midnight Maintenance Tasks
    Dec 21 10:24:18 +0000 OX-6584124d139ef [     info]  Begin pruning old records from data_summary_ad_zone_assoc
    Dec 21 10:24:18 +0000 OX-6584124d139ef [     info]  Finished pruning old records from data_summary_ad_zone_assoc: 0 records deleted
    Dec 21 10:24:18 +0000 OX-6584124d139ef [     info]  Begin pruning records for expired inactive campaigns from data_summary_ad_zone_assoc
    Dec 21 10:24:18 +0000 OX-6584124d139ef [     info]  Finished pruning expired inactive campaigns from data_summary_ad_zone_assoc: 0 records deleted
    Dec 21 10:24:18 +0000 OX-6584124d139ef [     info]  Begin pruning records for completed inactive campaigns from data_summary_ad_zone_assoc
    Dec 21 10:24:18 +0000 OX-6584124d139ef [     info]  Table rv_data_summary_ad_zone_assoc overhead (number of allocated but unused bytes) = 0
    Dec 21 10:24:18 +0000 OX-6584124d139ef [     info]  Midnight Maintenance Tasks Completed
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Running Maintenance Priority Engine
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Task begin: OA_Maintenance_Priority_AdServer_Task_GetRequiredAdImpressionsLifetime
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Task complete: OA_Maintenance_Priority_AdServer_Task_GetRequiredAdImpressionsLifetime
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Task begin: OA_Maintenance_Priority_AdServer_Task_GetRequiredAdImpressionsDaily
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Task complete: OA_Maintenance_Priority_AdServer_Task_GetRequiredAdImpressionsDaily
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Task begin: OA_Maintenance_Priority_AdServer_Task_AllocateZoneImpressions
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]    - Selecting Zones forecasts for all managers for OI from 2023-12-21 10:00:00 to 2023-12-21 10:59:59
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Task complete: OA_Maintenance_Priority_AdServer_Task_AllocateZoneImpressions
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]  Task begin: OA_Maintenance_Priority_AdServer_Task_PriorityCompensation
    Dec 21 10:24:18 +0000 OX-maintenance-6584124d139ef [     info]    - Selecting Zones forecasts for all managers for OI from 2023-12-21 10:00:00 to 2023-12-21 10:59:59
    Dec 21 10:24:19 +0000 OX-maintenance-6584124d139ef [     info]  Task complete: OA_Maintenance_Priority_AdServer_Task_PriorityCompensation
    Dec 21 10:24:19 +0000 OX-maintenance-6584124d139ef [     info]  Task begin: OA_Maintenance_Priority_AdServer_Task_ECPMforContract
    Dec 21 10:24:19 +0000 OX-maintenance-6584124d139ef [     info]  - Selecting All Managers
    Dec 21 10:24:19 +0000 OX-maintenance-6584124d139ef [     info]    - Selecting active campaigns with priority = '9' for manager 1
    Dec 21 10:24:19 +0000 OX-maintenance-6584124d139ef [     info]    - Selecting active campaigns with priority = '8' for manager 1
    Dec 21 10:24:19 +0000 OX-maintenance-6584124d139ef [     info]    - Selecting active campaigns with priority = '7' for manager 1
    Dec 21 10:24:19 +0000 OX-maintenance-6584124d139ef [     info]    - Selecting active campaigns with priority = '6' for manager 1
    Dec 21 10:24:19 +0000 OX-maintenance-6584124d139ef [     info]  Task complete: OA_Maintenance_Priority_AdServer_Task_ECPMforContract
    Dec 21 10:24:19 +0000 OX-maintenance-6584124d139ef [     info]  Task begin: OA_Maintenance_Priority_AdServer_Task_ECPMforRemnant
    Dec 21 10:24:19 +0000 OX-maintenance-6584124d139ef [     info]  - Selecting Managers with ECPM priority campaigns running
    Dec 21 10:24:19 +0000 OX-maintenance-6584124d139ef [     info]  Task complete: OA_Maintenance_Priority_AdServer_Task_ECPMforRemnant
    Dec 21 10:24:19 +0000 OX-maintenance-6584124d139ef [     info]  Maintenance Priority Engine Completed (Started at 2023-12-21 10:24:16 UTC)
    Dec 21 10:24:19 +0000 OX-maintenance-6584124d139ef [     info]  Maintenance Engine Completed (Started at 2023-12-21 10:24:16 UTC, taking 00:00:03)
    Dec 21 10:24:19 +0000 OX-6584124d139ef [     info]  Delaying Revive Adserver sync process by 20 seconds.
    Dec 21 10:24:39 +0000 OX-6584124d139ef [     info]  Sync: No update
    Dec 21 10:24:39 +0000 OX-6584124d139ef [     info]  Finished Revive Adserver Sync process.
    Dec 21 10:24:39 +0000 OX-6584124d139ef [     info]  Automatic Maintenance Task Completed

**Comment by mbeccati** [comment]
Sorry, the Github issue tracker is not meant for support requests. Please try on our [forum](https://forum.revive-adserver.com/)
