### ISSUE TITLE
Revive Adserver v5.4.1 do not shows Invocations Code

### ISSUE THREAD

**Issue by PinkStone-24** [revive-adserver/revive-adserver#1467]
![bugRevive](https://github.com/revive-adserver/revive-adserver/assets/159150681/84934ea7-bc76-4273-8517-93cef4864413)

**Comment by mbeccati** [comment]
Your installation is most likely missing the plugins. I'd suggest asking for support on our [forum](https://forum.revive-adserver.com/).

**Comment by erikgeurts** [comment]
Also, it is highly recommended to always use the most recent version, see https://www.revive-adserver.com/download/

**Comment by PinkStone-24** [comment]
Tanks. Then it seems it is not a bug... sorry.
