### ISSUE TITLE
[Feature request] Freeze the UI while waiting for statistics

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1468]
Depending on the speed of the server being used, the size of the database, the number of inventory items and complexity of the inventory organisation, it can take a long time before the statistics appear in Revive Adserver, especially when reviewing them for a longer date range.

Users might become impatient when the statistics don't show up as quickly as they would have hoped or expected, and then click the Refresh button or press the corresponding keyboard shortcut (or even multiple times).

This will trigger one or more additional database queries, that by virtue of MySQL's way of working won't be executed until the first query completes, thus only making things worse for the user, and also for any other users that happen to be working in the same installation.

To let a user know that the statistics are being collected, and that this will take some time, it might be beneficial to show some sort of "loading" placeholder, and to freeze the UI for the time being.

There are probably dozens of ways to achieve this, one possible way is:
- https://alexradulescu.github.io/freeze-ui/
- https://github.com/alexradulescu/FreezeUI

which appears to be relatively easy to iimplement.

**Comment by mbeccati** [comment]
Totally forgot we had this issue already, sorry. Closing
