### ISSUE TITLE
[Feature request] Preconnect to static domain for faster banner delivery

### ISSUE THREAD

**Issue by tvereecke** [revive-adserver/revive-adserver#1476]
**Problem description:**
When banners are served from a different static domain (eg., cdn.example.com)  than the ad server (eg., adserver.example.com) there is a performance penalty as the browser first needs to setup a connection (DNS, TCP and TLS overhead).

This increases the time to download and display the banners. On a mobile connection this can quickly be 200-300ms.

**Proposed solution:**
In case a static subdomain is configured, the performance penalty for setting up the connection can be mitigated by adding a `Link: <cdn.example.com>; rel=preconnect` HTTP response header on the zone invocation script (eg. asyncjs.php).

Doing so will open the connection ahead of time resulting in faster loading banners and an improved Time To Ads (TTA)

![Screenshot 2024-03-22 at 5 56 20 PM](https://github.com/revive-adserver/revive-adserver/assets/58261095/b8357065-f248-4aa9-8626-c58ba59cd7cc)

More details can be found: [Establish network connections early to improve perceived page speed](https://web.dev/articles/preconnect-and-dns-prefetch)

Browser support: [96+%](https://caniuse.com/?search=preconnect)

**Comment by mbeccati** [comment]
Thanks @tvereecke, that looks like a nice suggestion!
