### ISSUE TITLE
Upgrade: Upgrade package openXInvocationTags" has a version stamp that is older than that of the package you have installed

### ISSUE THREAD

**Issue by jamieburchell** [revive-adserver/revive-adserver#1488]
Upgrading from 5.5.1 to 5.5.2 and encountered this error I have not seen before:

> Installation of plugin "openXInvocationTags" failed:
> Upgrade package openXInvocationTags" has a version stamp that is older than that of the package you have installed

![Screenshot 2024-04-18 094349](https://github.com/revive-adserver/revive-adserver/assets/3270426/68b686f7-e102-4625-9ee9-8e39d8fff93a)

The version cited in the openXInvocationTags.xml file in the 5.5.2 release is 1.6.2 and my installation tells me I have version 1.8.0 installed, which is the version cited in openXInvocationTags.xml in the 5.5.1 release.

**Comment by mbeccati** [comment]
Thanks for yoiur report. Looks like a last minute rookie mistake and I made a typo when I was packaging the final 5.5.2. 

Most likely I will fix and rebuild new packages for 5.5.2

**Comment by jamieburchell** [comment]
Is there any need for me to replace the installation or is 1.8.0 the latest version of this plugin?

**Comment by mbeccati** [comment]
You can download 1.8.1 from [github](https://github.com/revive-adserver/revive-adserver/raw/f95b4894d83d5120770480437c65d75215de0cd1/etc/plugins/openXBannerTypes.zip) and manually upgrade it.

**Comment by jamieburchell** [comment]
Thanks. It was [openXInvocationTags.zip](https://github.com/revive-adserver/revive-adserver/raw/f95b4894d83d5120770480437c65d75215de0cd1/etc/plugins/openXInvocationTags.zip).

**Comment by mbeccati** [comment]
Of course! Sorry bit busy with repackaging and testing before re-uploading ;-)

**Comment by mbeccati** [comment]
Repackaged and fixed: https://www.revive-adserver.com/download/

Thanks again for reporting
