### ISSUE TITLE
Invocation Codes not Shown for Zone

### ISSUE THREAD

**Issue by ialibrahim** [revive-adserver/revive-adserver#1490]
Problem:
When I navigate to a zone screen, the Invocation Code tab is showing a white screen.

Steps To Reproduce:
1. Go to zones page /adserver/www/admin/affiliate-zones.php
2. Click on a zone name
3. Click on "Invocation Code"
4. A white screen gets loaded without the drop-down to select the code type

![image](https://github.com/revive-adserver/revive-adserver/assets/33144444/0319ce2e-7779-4d35-9383-bf61a9b05e9a)

**Comment by erikgeurts** [comment]
See https://revive-adserver.atlassian.net/wiki/spaces/DOCS/pages/721049/Plugins+Missing+or+Disabled
