### ISSUE TITLE
Making preconnect to domain of static content optional

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#1492]
As part of #1476, it was decided to make this an optional feature. The setting to enable or disable it still needs to be added (see https://github.com/revive-adserver/revive-adserver/issues/1476#issuecomment-2034809775)

**Comment by mbeccati** [comment]
While working on this and looking up https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preconnect it occurred to me that a good default when the setting is disabled is to use `dns-prefetch`. Of course this is only relevant when using HTTPS and having a separate image server.

Doing just the DNS lookup is not as expensive as a full preconnect and is not going to increase the load on the image server when no image will be requested.
