### ISSUE TITLE
Issue with changing/deleting banner in campaign

### ISSUE THREAD

**Issue by robinvesely99** [revive-adserver/revive-adserver#1521]
Hi all,

I have little issue with my revive interface in which I am trying to disable/delete/change banner in one of my campaign, but all the time, this error applies:

![bug issue](https://github.com/user-attachments/assets/e71cb214-0d30-45cf-b7e3-197291c83285)

Please, I kindly ask for your help with this issue since I am only administrator. Thanks a lot in advance.

Robin

**Comment by erikgeurts** [comment]
This doesn't appear to be a bug.

I would like to recommend that you first update your Revive Adserver system to the latest version available, and also ensure you have compatible, up to date versions of PHP and your database software. This may very well fix the issue.

**Comment by mbeccati** [comment]
As @erikgeurts pointed out, the Revive Adserver version you are using is almost 5 years old. Closing the issue.

**Comment by robinvesely99** [comment]
> As @erikgeurts pointed out, the Revive Adserver version you are using is almost 5 years old. Closing the issue.

Hello, I did not found any info, If the newest version is available on PHP version 7.3.33. Can you please confirm? Thanks a lot in advance.

**Comment by mbeccati** [comment]
The latest version of Revive Adserver, at the time of writing 5.5.2, requires PHP 7.2.5.
