### ISSUE TITLE
PHP Deprecated and Warnings in Logs

### ISSUE THREAD

**Issue by scott8787979** [revive-adserver/revive-adserver#1524]
I am using the latest version of Revive Adserver (v5.5.2) and in my error log I see dozens per day of these two errors. My server uses the latest version of PHP 8.1.

PHP Deprecated:  substr(): Passing null to parameter #1 ($string) of type string is deprecated in /home/mydirectory/public_html/adserv/variables.php on line 89
PHP Warning:  Undefined array key "SCRIPT_NAME" in /home/mydirectory/public_html/adserv/variables.php on line 105

**Comment by mbeccati** [comment]
@scott8787979 what kind of webserver / PHP SAPI are you using?

If you don't know what the above means, please check the *www/admin/updates-product.php* page and copy/paste the versions line, e.g.:

> You are currently using Revive Adserver v5.x running on Apache 2.4.38, PHP 8.1.20 and MySQL 5.7.44-log.

**Comment by scott8787979** [comment]
Here is the info:
ou are currently using Revive Adserver v5.5.2 running on Apache, PHP 8.1.29 and MySQL 10.6.19-MariaDB.

**Comment by scott8787979** [comment]
And:
Server version: Apache/2.4.62 (cPanel)

**Comment by mbeccati** [comment]
Do you know if mod_php is used, or FastCGI, or plan old CGI?

A phpinfo() page would help (but please do not post it publicly)

**Comment by scott8787979** [comment]
Here are my installed packages:

Apache 2.4
config
config-runtime
mod_bwlimited
mod_cgid
mod_deflate
mod_expires
mod_headers
mod_http2
mod_mpm_event
mod_proxy
mod_proxy_fcgi
mod_proxy_http
mod_proxy_wstunnel
mod_remoteip
mod_security2
mod_socache_memcache
mod_socache_redis
mod_ssl
mod_suexec
mod_unique_id
tools
PHP 8.1
pear
php-bcmath
php-bz2
php-calendar
php-cli
php-common
php-curl
php-devel
php-exif
php-fileinfo
php-fpm
php-ftp
php-gd
php-gmp
php-imap
php-litespeed
php-mbstring
php-memcached
php-mysqlnd
php-opcache
php-pdo
php-posix
php-sockets
php-xml
php-zip
runtime
Additional Packages
apr
apr-util
brotli
cpanel-tools
documentroot
libargon2
libmcrypt
libmemcached
libnghttp2
libxml2
libzip
modsec-sdbm-util
nghttp2
oniguruma
oniguruma-devel
php-cli
php-cli-lsphp
profiles-cpanel
ruby27
ruby27-libuv
ruby27-mod_passenger
ruby27-ruby
ruby27-ruby-devel
ruby27-ruby-irb
ruby27-ruby-libs
ruby27-ruby-wrapper
ruby27-rubygem-bigdecimal
ruby27-rubygem-did_you_mean
ruby27-rubygem-io-console
ruby27-rubygem-json
ruby27-rubygem-openssl
ruby27-rubygem-passenger
ruby27-rubygem-psych
ruby27-rubygem-rack
ruby27-rubygem-rdoc
ruby27-rubygems
ruby27-runtime

**Comment by scott8787979** [comment]
Or you can just ask ChatGPT:

The errors you are encountering in your Revive Adserver are related to incompatibilities with the latest version of PHP (8.1). Here's a breakdown of the issues:

1. PHP Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated
This error occurs because, in PHP 8.1, passing a null value to the substr() function is deprecated, as it now expects the first parameter to be a string. If null is passed, PHP triggers a deprecated warning. The issue here is that in the variables.php file, the $string variable being passed to substr() is likely null, which is not acceptable in PHP 8.1.

Solution: Before calling substr(), ensure that the variable is not null and is indeed a string. Modify the code to check for this:
`if (!is_null($string) && is_string($string)) {
    $substring = substr($string, $start, $length);
} else {
    // Handle the case when $string is null or not a string
}
`

**Comment by mbeccati** [comment]
Thanks for having ChatGPT mansplaining that.

Problem is I've never encountered a system that doesn't have the SCRIPT_NAME server variable, which makes your setup kind of unique. I was trying to help understanding why, but it seems you are not interested in that.

Nor I am now in wasting other time on this, and without your cooperation I'll have to close this issue as the application needs that variable in multiple places.

**Comment by scott8787979** [comment]
It is not clear what you need here. On the PHP info page I see:
Linux 4.18.0-553.22.1.el8_10.x86_64

**Comment by mbeccati** [comment]
I thought I was clear, sorry. I'd need the full output of a php info page to find clues on the mystery of the missing server variable.

**Comment by scott8787979** [comment]
As you may know, it is not considered safe or good practice for a server admin to post the contents of their PHP info file online. Can you tell me what specifically you need to know here about that file? From my perspective, the best way to fix these deprecated code warnings is to update the code that is causing those warnings, which is why I posted it here.

**Comment by erikgeurts** [comment]
See https://github.com/revive-adserver/revive-adserver/issues/1524#issuecomment-2406708434

**Comment by mbeccati** [comment]
@scott8787979

1. I asked you to email it to me privately, not to publish information
2. `$_SERVER['SCRIPT_NAME']` is required for Revive Adserver to function properly
3. I cannot simply silence the deprecation warning, as that would break the software
4. All the other installations are working fine, so there's something wrong on your system
5. I offered to spend *unpaid* time to debug why your system is misbehaving, hoping to offer either a solution to you or integrate a generic fix in case anybody else is affected

If you're interested in that, great. If not I will just close the issue as invalid as your system isn't compatible and I would suggest you to find a different hosting provider.

**Comment by scott8787979** [comment]
Or you can just rewrite the deprecated code, but I'm done trying to improve this software.

**Comment by scott8787979** [comment]
mod security is a very basic server option that everyone should be running.
