### ISSUE TITLE
Issue with 'Hour of Day' Delivery Rule

### ISSUE THREAD

**Issue by IblackIshadow** [revive-adserver/revive-adserver#1525]
We have multiple Revive Adservers (of different versions) deployed across various countries. However, we are facing an issue where we need to manually add the UTC offset to the timezone difference (in hours) specifically for the stop time of delivery, while the start time works as expected.

For example, we have the timezone set to Europe/Vienna consistently across the ad server, PHP configuration, and the Linux system. During summer time, if we want to deliver ads from 12:00 to 00:00, we also need to add an extra delivery window from 00:00 to 02:00 to account for the offset. In winter time, we only need to add one hour, meaning the additional window would be from 00:00 to 01:00.

Current Situation:
To deliver ads from 12:00 to 00:00 during summer, we need to add an extra window from 00:00 to 02:00 to stop delivery properly. This manual adjustment is required to account for the UTC offset, which varies by season.
![2024-10-02 211704](https://github.com/user-attachments/assets/8612832e-a2d2-4258-9dda-646b86183d91)

Desired: 
Ad delivery should stop correctly at 00:00 without requiring any additional delivery windows or manual adjustments for different seasons, regardless of summer or winter time.
![2024-10-02 211646](https://github.com/user-attachments/assets/6cb8c44f-409b-45b4-9ed7-46047a54925c)

Thank you in advance for reviewing this issue and providing guidance on how we could resolve it.

**Comment by zizekuros** [comment]
Same issue here. Any idea about resolving it?

**Comment by erikgeurts** [comment]
I've never come across this specific situation that appears to be mostly about adjusting for the 1 hour offset during Daylight Savings Time.

Can you confirm that you're on the most recent version of Revive Adserver, and if so, if you still notice this?

**Comment by IblackIshadow** [comment]
We use the latest version of the ad server, along with two other versions, and the same problem occurs across all of them. This issue has persisted for many years, but we didn't address it earlier because we rarely used this delivery rule before. For example, I’ve attached pictures where you can see that the probability drops to 0 if we don’t add the offset hours.

![2024-10-08 172422](https://github.com/user-attachments/assets/2ad36048-70de-4fd5-a599-a6229b5d4b4d)
![2024-10-08 172112](https://github.com/user-attachments/assets/38fb0664-9661-4d0d-95cb-cb8bb7a1f804)

**Comment by mbeccati** [comment]
What do you see if you check the database table `acls`?

E.g.
| bannerid | logical | type | comparison | data | executionorder |
| :--- | :--- | :--- | :--- | :--- | :--- |
| 2 | and | deliveryLimitations:Time:Hour | =\~ | 10,11@Europe/Rome | 0 |

**Comment by IblackIshadow** [comment]
when setup matches the first picture in previous comment:
![image](https://github.com/user-attachments/assets/405f1c98-1a8b-493d-a961-a81eb753fc62)

when setup matches the second picture in previous comment:
![image](https://github.com/user-attachments/assets/2e65216d-af3c-4cd8-8cbc-2598dfa36730)

**Comment by mbeccati** [comment]
I think I've been able to reproduce the issue, which seems only to be affecting contract campaigns.

**Comment by mbeccati** [comment]
@IblackIshadow would you mind testing this [specific fix](https://github.com/revive-adserver/revive-adserver/commit/e0d7506bd41f8e0c1b92c0f7c4ad7abfc8e2779d#diff-629152fd563295a02c13c95d023a9e9532dbcd83662d0f6839904bd46716a2b9) in the `lib/OA/Maintenance/Priority/AdServer/Task/GetRequiredAdImpressions.php` file?

**Comment by IblackIshadow** [comment]
I have tested the fix, and now everything seems to be working as expected. We will update one production ad server with this fix and perform further tests.

**Comment by IblackIshadow** [comment]
We have been testing the fix in production for a week, and so far, everything seems to work well, except for one issue. When we have two selected intervals, e.g. from 18:00-18:59 and 22:00-22:59 with a pause in between, the first maintenance at the start of the next interval doesn’t save the new value into the rv_data_summary_ad_zone_assoc table.

![image](https://github.com/user-attachments/assets/ef7577e8-3184-4775-9fa2-29f2e6619ba2)

![image](https://github.com/user-attachments/assets/c4ed1617-84d0-49cd-8af5-8dd0743affc5)

**Comment by mbeccati** [comment]
Thanks @IblackIshadow. I will try to replicate with standard 1 hour operation intervals.

Using smaller OIs is not recommended and generally the overhead is not worth it.

**Comment by IblackIshadow** [comment]
Hi, I just wanted to check if you were able to replicate the last provided issue.

**Comment by mbeccati** [comment]
@IblackIshadow I was finally able to find it. The issue was in `getBlockedOperationIntervalCount` that was returning a wrong result, and causing maintenance to die with a division by zero error during some specific operation intervals.
