### ISSUE TITLE
Suggestion: Xcache

### ISSUE THREAD

**Issue by gabrielt** [revive-adserver/revive-adserver#156]
Revive/OpenX has the ability to cache banners in memory using memcached. I suggest adding support for Xcache, which we use and I believe other users use as well.

**Comment by mbeccati** [comment]
At adserverplugis.com we've recently made available some free and open source plugins that I have developed during the years via github. Feel free to fork e.g. https://github.com/adserverplugins/apDeliveryCacheApc and make the necessary changes to support either Xcache or WinCache.
