### ISSUE TITLE
Unable to choose zone invocation code

### ISSUE THREAD

**Issue by skylabz0rz** [revive-adserver/revive-adserver#163]
Upon completing a zone, I am unable to generate any code as none are available from the drop down menu.

I have four banners in the zone, from four different advertisers. Each has their own campaign.

See my setup screens below.
![capture5](https://f.cloud.github.com/assets/3923262/1565619/f5c95d86-5081-11e3-8188-6bb25ebeba9b.JPG)

![capture4](https://f.cloud.github.com/assets/3923262/1565617/f14574c0-5081-11e3-8f8d-02299151f5ca.JPG)

![capture3](https://f.cloud.github.com/assets/3923262/1565615/ed64e49e-5081-11e3-8215-1dcea7d83d9a.JPG)

![capture2](https://f.cloud.github.com/assets/3923262/1565614/e83a6610-5081-11e3-91e6-0ac9bb4078f8.JPG)

![capture](https://f.cloud.github.com/assets/3923262/1565581/56cc45a4-5081-11e3-896a-903ecf392f3d.JPG)

**Comment by tooodooo** [comment]
I am using v4.0, still there is this issues. All plugins are installed.

**Comment by erikgeurts** [comment]
Please consider posting a new topic on http://forum.revive-adserver.com

**Comment by t40** [comment]
It's 2025 and I still have exactly this issue on Version 5.5.2

**Comment by mbeccati** [comment]
@t40 then something didn't go exactly as expected when upgrading. Nothing we can do to fix your own installation.
