### ISSUE TITLE
Revive AdServer Release 3.0 Has No Standard Plugins

### ISSUE THREAD

**Issue by rrolih** [revive-adserver/revive-adserver#181]
I installed AdServer from http://download.revive-adserver.com/revive-adserver-3.0.0.zip on an AWS AMI instance with MySQL. Installation seemed to go fine.
Worked through a basice tutorial (0202_OpenX Ad Server Beginner's Guide_SampleChapter-1.pdf) and got stuck at Code Invocation: no invocation options in the list.
Eventually found that no plugins were installed. These were supposed to be bundled?
Couldn't find the standard plugins on the revive website.
Ended up building a set from the GitHub revive-adserver repository and installing.
Almost all installed without error. Basic banner delivery is now working but other features are not eg. Advanced Reporting.
Is there a definitive source of built standard plugins? I'm not entirely confident of the integrity of the ones I built.

**Comment by Blinky82** [comment]
Just one tip from me. If you see the plugins in your Plugin section after you switch to the Administrator, and they are staying in a status "Not installed", just switch them off and then switch them on. If you want to make sure that everything is OK, go to Details and see if it's still "No installed", it should be "Enabled". And then go to the admin with a Manager role and see if you have the desired functionality. That's it. Now you are ready to go.... ;)
