### ISSUE TITLE
Should advanced reporting work?

### ISSUE THREAD

**Issue by rrolih** [revive-adserver/revive-adserver#185]
Fresh install of revive-adserver-3.0.0 on AWS AMI - 9 plugins installed.
Have a simple test advertiser/campaign/.../banner - delivered ok.
When I try to run an advanced report I get HTTP 500 for:
http://.../revive-adserver-3.0.0/www/admin/report-generate.php?period_preset=this_week&period_start=25+November+2013&period_end=01+December+2013&campaign=1&sheets%5Bdaily_breakdown%5D=1&sheets%5Bad_breakdown%5D=1&sheets%5Bzone_breakdown%5D=1&plugin=reports%3AoxReportsStandard%3AcampaignAnalysisReport.

I'm not a php developer but commenting out the following avoids the error:
$oModule->generate($plugin);

**Comment by andrewatfornax** [comment]
Sounds like this is a system configuration issue, rather than a bug, so I am going to close this issue - but please raise any specific instances of this on the forums for support (but reference the ticket). Thanks.
