### ISSUE TITLE
Does not support LZMA compressed flash files

### ISSUE THREAD

**Issue by cstdenis** [revive-adserver/revive-adserver#212]
The changes necessary to detect these kinds of files are fairly trivial, just check for the magic number "ZWS" instead of "FWS" or "CWS".  File version appears to be detected the same way as the other formats. 

Adding support for decompressing and rewriting links, etc would be much more complex since php does not appear to have any built in support for lzma and I can not find any modules or native php libraries to do it.

**Comment by andrewatfornax** [comment]
I am closing this ticket. In 2020, we will not be fixing issues with Flash - we should be deprecating all Flash support from Revive Adserver.
