### ISSUE TITLE
Extended/mysql.php is not within the allowed path(s)

### ISSUE THREAD

**Issue by mrh666** [revive-adserver/revive-adserver#226]
Hi there,
After update to 3.0.2 when I log in or log out I've got a warning in the debug.log (6 similar warnings when log in and 2 same warnings when I logged out):
Jan 03 01:56:56 +0200 OX-52c5fcc825650 [  warning]  is_readable(): open_basedir restriction in effect. File(/usr/local/php54/lib/pear/MDB2/Driver/Extended/mysql.php) is not within the allowed path(s): (/tmp:/usr/local/lib/php:/home/username/revive-adserver/)

If I understand correctly, Adserver should look for this mysql.php driver inside of /home/username/revive-adserver/ installation. 
When I make an upgrade I edit www.hostname.conf.php manually and I suppose I forgot to mention some path or write it wrong.
Where should I look?

Thank you!

**Comment by natiq2004** [comment]
We got the same problem in cpanel server. Solution:

mkdir /usr/lib/php
chmod 700 /usr/lib/php
