### ISSUE TITLE
The Direct Selection method should be disabled by default

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#236]
I would like to propose to make the setting for disableDirectSelection=1 the default value. People interested in using the feature can easily enable it by editing the config file, while the rest won't be tempted to use a feature that most of them won't be able to understand correctly.

**Comment by lsmonki** [comment]
Well, and how to reenable it? I have set "disableDirectSelection = false" but is not there after update form 3.0.2 to 3.2.1

**Comment by lsmonki** [comment]
Ok, fixed, the menu cache has to be cleared deleting the files on var/cache
