### ISSUE TITLE
Include up to date version of MaxMind GeoLite Country with releases

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#262]
We should consider including an up to date version of the MaxMind GeoLite Country datafile every time a new release of Revive Adserver is published.

**Comment by andrewatfornax** [comment]
Done by @mbeccati for 4.0.1 - moved to 4.0.2.

**Comment by andrewatfornax** [comment]
Done for 4.0.2.

**Comment by erikgeurts** [comment]
Since MaxMind no longer allow the inclusion of the GeoLite2 data file without a (costly) developer license, the plan is to stop including these files and instead introduce functionality that will enable the new plugin to download the GeoLite2 country file from MaxMind's server and store it on the server hosting the Revive Adserver installation.
