### ISSUE TITLE
AdSense clicks not tracked

### ISSUE THREAD

**Issue by jensschaerer** [revive-adserver/revive-adserver#267]
AdSense clicks are not tracked correctly in Revive Adserver 3.0.2. All logging is enabled in global configuration. Also every google ad is created with Rich Media Adsense altering.

AdSense code is not modified, I use the async-code provided by Google and as mentioned in the FAQ

**Comment by ABRMBALOCH** [comment]
Google Adsense Not Counting Clicks 100% Tested Solution __  Open Google And Search "Firmwaremafia" Open First Search Website And Go Blogger Setion And Find Solution Post. This Method 100% Tested And I Fix My Both 3 Website.


https://www.youtube.com/watch?v=DvAabBbJKfA&t=83s

https://firmwaremafia.com/2023/04/07/google-adsense-not-count-clicks-account-in-2023-fix-solution-firmwaremafia/
