### ISSUE TITLE
Allow install/upgrades to run from shell

### ISSUE THREAD

**Issue by vicos59** [revive-adserver/revive-adserver#275]
Enhancement suggestion: Allow version upgrade scripts to run from shell or web browser. Upgrading from a shell should alleviate server timeouts with large databases and make problem debugging a tad bit easier.

MediaWiki is an example of a product which functions this way.

Thank you for your consideration.

**Comment by switzer** [comment]
Agree with this request.  Needed if you want to install Revive via Docker.

**Comment by erikgeurts** [comment]
@switzer Please feel free to open a PR ;)

**Comment by rhapsodyv** [comment]
A problem we faced with the web install/upgrade is that we must start over from the scratch when things go wrong. It will be more reliable if we can do things in parts: upgrade database, upgrade codebase, upgrade plugins.

**Comment by ceasbz** [comment]
👍

**Comment by mnebuerquo** [comment]
> I think the most important reason why the install and upgrade process is entirely browser bases is because a large portion of the users are on relatively simple (shared) hosting plans, which means they do not have access to the command line.

The manual steps in the deploy process are probably part of the reason that larger organizations do not adopt Revive as their solution. In such an org, software needs a repeatable and automated deploy process in order to be maintainable. This gets even more difficult if they want to run multiple instances of Revive in different roles. Being able to configure the entire install from a single file or from ENV becomes essential for adoption at scale.

**Comment by mbeccati** [comment]
@mnebuerquo the functionality has been introduced in v5.5.0 (e940227711a34fe60d4b06b03cfd25b61315fd9b and subsequent fixes), but I would still consider it experimental: I have been using it mostly for testing release files.

When I feel it's ready for prime time I will start writing down some documentation on how to use it.

**Comment by mnebuerquo** [comment]
@mbeccati , I'd be willing to try it out even before it's prime time if you have even minimal documentation for it. I'll browse that commit and see what I can learn.

**Comment by mbeccati** [comment]
@mnebuerquo 

I would start with:
```
scripts/installer install --help
scripts/installer upgrade --help
```
