### ISSUE TITLE
Slow loading of banners 

### ISSUE THREAD

**Issue by clementkoh** [revive-adserver/revive-adserver#331]
Hi,
I am experiencing slow loading of banners serve from your ad server. And the randomness is not working, as in some banner appear many more times than the others. Please assist. My website is {removed by moderator}. The first banner is the one hitting issues.

**Comment by wimlmg** [comment]
Same problem here. I did a refresh test with 4 ads, 19 out of 20 times the same ad, extremely slow loading, although running within the same domain, and one ad of those 4 never got displayed at all. This with 300 refreshes.

My old system using javascript and a hack or 2 works well, just wanted to go to a more professional system with hopefully less maintenance, where users could log in as well.

Kind regards, Wim

**Comment by erikgeurts** [comment]
@wimlmg Please do not double post.

**Comment by wimlmg** [comment]
This is not a double post, as I happened to see both these issues - this is to prevent a double post, it is exactly what I see happening - extremely slow loading, and in addition, no randomness.

OI made a post about non-randomness after searching here, and found this (closed) issue only later. However, this describes exactly what I am experiencing.

Kind regards, Wim

**Comment by erikgeurts** [comment]
This type of topic is better suited for the support forums at http://forum.revive-adserver.com/forum/13-managing-revive-adserver/
