### ISSUE TITLE
./www/images also needs 777

### ISSUE THREAD

**Issue by jamieburchell** [revive-adserver/revive-adserver#342]
Revive Adserver 3.0.5 (also present in earlier versions)

When upgrading Revive Adserver the installation wizard helpfully provides information on the folders needing write access and gives the relevant `chmod` commands to correct the issues. However, even after correcting the issues when logging in to the administration panel after a successful installation the warning about some files/folders not being writable appears.

When `./www/images` is set to `777` the message no longer appears.

Probably because of:

```
$this->aInfo['PERMS']['expected'][] = $this->buildFilePermArrayItem(MAX_PATH.'/www/images');
```

in `EnvironmentManager.php` line 74.

Should this be added to the list of directories in the installation wizard? The upgrade documentation also does not mention this folder as needing `777` permissions.

**Comment by jamieburchell** [comment]
Just did an upgrade to 3.1.0 and ./www/images wasn't 777 afterwards. There were also no banners copied from previous install (https://github.com/revive-adserver/revive-adserver/issues/481)

**Comment by erikgeurts** [comment]
see the reply on issue #481

**Comment by jamieburchell** [comment]
Shouldn't the installation check that the images folder has 777 permissions and offer a chmod to paste? I'm my latest upgrade the installation proceeded without 777 permissions on the image dir.

**Comment by andrewatfornax** [comment]
I've reviewed this, and as far as I can see, there's code in https://github.com/revive-adserver/revive-adserver/blame/master/lib/OA/Upgrade/EnvironmentManager.php which does check that Revive Adserver can write to the "images" folder.

In the event of a new installation, it checks the default "www/images" directory inside the Revive Adserver installation.

In the event of an upgrade, it checks whatever the "store > webDir" value is set to in the user's configuration file for the upgrade.

The results of the test are returned in the same way as all the other file permission tests, and having done a test in my local system, I can confirm that it reports the problem in the installer/upgrader UI, and presents the command to chmod the directory.

Apart from a bracketing formatting change, this code has remained unchanged for 11+ years, so I don't think this is a bug. I certainly cannot reproduce the issue.

Please feel free to comment with detailed reproduce steps if this remains an issue with future upgrades.

**Comment by jamieburchell** [comment]
Thanks for reviewing this. It's been a while since I needed to do an upgrade so I've not run in to this for a while. I will report back if this happens again in the future.
