### ISSUE TITLE
Hebrew language fixes, 3.0.5

### ISSUE THREAD

**Issue by MosheL** [revive-adserver/revive-adserver#354]
I was merged the 3.0.5 version changes with my translation code.

works
(I could not add a pull request right now, but the file is 3.0.5-mergable).
https://github.com/MosheL/revive-adserver/blob/arutz7/lib/max/language/he/default.lang.php

**Comment by mbeccati** [comment]
I've uploaded the translations to Crowdin.

**Comment by MosheL** [comment]
Thanks
