### ISSUE TITLE
can not redirect the ad on mobile device

### ISSUE THREAD

**Issue by laan** [revive-adserver/revive-adserver#364]
hi, I met a problem that the ad cann't redirect on page ck.php page on mobile devices.

The ad url as:
http://.../www/delivery/ck.php?n=ad8ad2d2&cb=fe

And on PC the page will redirect to the url that the assets set. But on mobile device the ck.php page can not redirect. 

I think it is a bug.

**Comment by carauzs** [comment]
+1

**Comment by mbeccati** [comment]
Closing as it isn't a Revive Adserver bug.
