### ISSUE TITLE
openXVideoAds installation

### ISSUE THREAD

**Issue by fixo94** [revive-adserver/revive-adserver#366]
Hello, when you uninstall / reinstall openXVideoAds plugins, it seems to be a problem : 
![bug](https://cloud.githubusercontent.com/assets/8167966/3583315/0aacff40-0c08-11e4-9e8a-8fc1c81f03cc.jpg)
The path is different between files expected and  file stored.
The test in "PluginManager.php" line 1389 has found a difference : 

$aDiffsExpected = array_diff($aFilesExpected, $aFilesStored);
        if (count($aDiffsExpected))

Is it possible to have an other zip file to replace this one : https://github.com/revive-adserver/revive-adserver/blob/master/plugins_repo/release/openXVideoAds.zip

Thanks a lot !
Fx

**Comment by mbeccati** [comment]
This one should be fixed already.
