### ISSUE TITLE
Select advertiser dropdown does not show the list of advertisers in "linked banners" tab

### ISSUE THREAD

**Issue by sumanth319** [revive-adserver/revive-adserver#380]
Hi,

I was able to successfully add a website,zone and a banner. But when trying to link the banner from the "Linked Banners" tab the advertiser dropdown does not show the list of advertisers in "linked banners" tab. As a result i am not able to add the advertiser and I am not even able to get the invocation code.

Thanks in advance
![screen shot 2014-08-13 at 8 24 42 pm](https://cloud.githubusercontent.com/assets/8124603/3907237/c85cca22-22f9-11e4-9a7c-6a3f61f3fe4a.png)

**Comment by andres9213** [comment]
Hi, 
What is the solution ? Thank you
