### ISSUE TITLE
Link from upgrade Wizard to FAQ is dead

### ISSUE THREAD

**Issue by rpijlman** [revive-adserver/revive-adserver#399]
When upgrading from OpenX 2.8.7 to Revive Adserver 3.0.5, the upgrade wizard gave me the PHP 5.4.<20 error. It said "You should upgrade your PHP to at least 5.4.20 or 5.5.2 in order to propery install Revive Adserver. Please see the FAQ for more information.'

The hyperlink on "FAQ" is: http://documentation.revive-adserver.com/faq.
That redirects to: http://documentation.revive-adserver.com/display/DOCS/Documentation
And that fails with: Page Not Found

**Comment by mbeccati** [comment]
Fixed already
