### ISSUE TITLE
Keywords field in banner configuration has 255 characters limit

### ISSUE THREAD

**Issue by athlan** [revive-adserver/revive-adserver#405]
Keywords field in banner configuration has 255 characters limit. Is there a possibility to increase this value changing column type to TEXT?

**Comment by csaezl** [comment]
I reopen this issue because I'm looking for a way of tagging banners in order to get just banners related with a term(s), say: sports, computer, italian food, car, and so one, and thought the way was via keywords. Since keywords seem not to be the solution, how can a search engine request Revive to deliver ads from different advertisers that match the term(s).
I understand that is difficult to tag every banner in advance to match the terms that a user could use, so I'd appreciate some guidance.
Thank you,
Carlos

**Comment by mbeccati** [comment]
Site:Variable limitations?

**Comment by erikgeurts** [comment]
This is an article that describes how to add a site-variable value to a zone's invocation code:
http://www.reviveconsultant.com/articles/how-to-dynamically-insert-an-affiliate-id-into-a-banner/

Once the zone is requested with a site variable, the variable's value is available during ad selection (delivery limitations) and for ad rendering (macros).

**Comment by csaezl** [comment]
I think your advice is right, but I need the value to change dynamically.
 
Say you have a blog that shows articles on golf, automobiles and computers, in a manner that the banners shown are related to the article type, that is, the type of article adds a new delivery limitation.

When the user accesses a golf article you want the banners to show golf related banners, so the code has to inform to AdServer: and a new limitation, the selected banner has to be classified as "golf", the same for automobiles, AdServer has to select banners classified as "automobiles" and when the user selects an article about computers you don't want AdServer to apply anything related with this classification, so the banner is selected as AdServer use to do, without worring about the article type.

I suppose a new limitation should exist, with all the possible article types, and every banner should have their related value/s marked. The snippet code should take the article type from (I suppoose) the web page and send it to AdServer. ¿Is that right?

Finally, where can I read about the behaviour of site variable limitation?
Thank you,
Carlos

**Comment by erikgeurts** [comment]
Please consider posting your support questions on the community forums at http://forum.revive-adserver.com
