### ISSUE TITLE
Image Upload Option for HTML Banner Types

### ISSUE THREAD

**Issue by dornfeder** [revive-adserver/revive-adserver#408]
In some cases the banner the client wishes for has to be a html banner because it contains an Imagemap or Javascript or just basic HTML. But most of the time these banners do also contain one or more images. With the current html banners in Revive Adserver, someone has to manually upload the banner images somewhere, adjust the banner coede and then create a new banner in revive. 

It would be a lot easier if revive had an option to upload one or more images (or other resources) and return the resulting URL as variable ( like {clickurl} ) or / and as string, so that they can be updated in the given banner code. Basically like it is possible in dfp. 

![2014-09-11_11h29_56](https://cloud.githubusercontent.com/assets/4601184/4231873/40a342ba-3996-11e4-8270-7a40128b1bb0.png)

Would be great, thanks a lot.

**Comment by songpr** [comment]
I vote for this.

**Comment by erikgeurts** [comment]
With the demise of Flash in progress, we've started discussing how we can make it more easy to create a banner that consists of HTML code, javascript, CSS, and images, so essentially HTML5 banners. The trouble is that each of the authoring tools we've looked at, produces output in a different way. We're discussing ways to proceed on this. Just "uploading an image" is not the solution, it's solves only part of the problem.

**Comment by songpr** [comment]
One solution is uploaded the whole html (a index.html , js, css, images - all needed file must be in the zip file no external reference for security) as a zip file to server. Then current html will iframe to reference the uploaded html.

This is how I use revive adserver to serve html5 at the moment.

**Comment by MosheL** [comment]
I wrote a `hack` to allow upload HTML file like SWF/GIF/JPEG and  small program that make one file and embed files (or change to absolute URL) to make it works.

**Comment by andrewatfornax** [comment]
HTML5 banner support was added in 4.1.0, so, I'm closing this ticket, as support for uploading all the assets with the banner HTML is now available.
