### ISSUE TITLE
Show shortened destination URL on banner overview page

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#425]
On the overview page of all banners of a campaign, the destination URL of each banner is displayed. In cases where one of those URLs is very long (or all of them), the page's usability suffers because everything is pushed to make room for those URLs.

It was suggested by one of my customers that we might want to consider displaying just the first X characters and the full URL to a mouseover or hover when you point the mouse at it.

**Comment by andrewatfornax** [comment]
Updated the release version to 3.3.0, as this was not included in the 3.2.2 security release.
