### ISSUE TITLE
Cannot Log into any of our accounts + Adserver is returning errors:

### ISSUE THREAD

**Issue by aptrouble** [revive-adserver/revive-adserver#429]
Randomly a few days ago I tried to log into our OpenX Ad server  account and these errors somehow popped up, and now our company can't do anything with the account (log in to retrieve stats/upload banners etc): 

I tried getting in contact with OpenX and they told me this company owns this now. I have no idea how to get into contact with support, so came here.

Here are the following errors:

Strict Standards: Non-static method PEAR::setErrorHandling() should not be called statically in /home/*******/public_html/lib/Max.php on line 222

Strict Standards: Non-static method OA::debug() should not be called statically, assuming $this from incompatible context in /home/*******/public_html/lib/max/ErrorHandler.php on line 134

Strict Standards: Non-static method Log::singleton() should not be called statically, assuming $this from incompatible context in /home/*******/public_html/lib/OA.php on line 158

Strict Standards: Non-static method Log::factory() should not be called statically, assuming $this from incompatible context in /home/*******/public_html/lib/pear/Log.php on line 199

Strict Standards: Non-static method PEAR::isError() should not be called statically, assuming $this from incompatible context in /home/*******/public_html/lib/OA.php on line 165

Strict Standards: Non-static method OX_Admin_Timezones::getTimezone() should not be called statically, assuming $this from incompatible context in /home/*******/public_html/lib/OA.php on line 198

**Comment by mbeccati** [comment]
Possibly related so disabled functions. See 1ed4585
