### ISSUE TITLE
'MAX_ErrorHandler' not found in 

### ISSUE THREAD

**Issue by dlangille** [revive-adserver/revive-adserver#450]
After installing 3.0.5 on FreeBSD 9.3 with PHP 5.4.
 
Browsing to the website produces this in the apache error logs:
 
PHP Fatal error:  Class 'MAX_ErrorHandler' not found in /usr/local/www/revive-adserver/init.php on line 130
 
I can see this class defined in lib/max/ErrorHandler.php
 
What's up with this?

**Comment by mbeccati** [comment]
@dlangille sorry for the delay. After the recent announcement from DigitalOcean, I've decided to try it out and install revive-adserver using pkg.

The package is completely broken as all the directories had missing u-x permission. Plus it was missing a required dependency on php5-session.

I would suggest ditching the port/package and installing using an official distribution tgz file.
