### ISSUE TITLE
Banner upload with apostrophe in file name

### ISSUE THREAD

**Issue by Shawnjasmin** [revive-adserver/revive-adserver#455]
Uploading a banner with an apostrophe in the file name returns a internal server error.

**Comment by mbeccati** [comment]
@alekseyp @Shawnjasmin I've just tried to add a new local banner on a test instance (running on linux) using Firefox on Win7 uploading a banner with an apostrophe in the file name. Result: everything ok.

Please check your error logs. It might be mod_security or something along the lines kicking in.

**Comment by andrewatfornax** [comment]
Suspect it's more of an issue with something like Linux allowing the apostrophe, but then trying to upload on a Windows server where it's not allowed. See that kind of thing all the time with Windows and filenames - I suspect there is nothing that we can do about it in Revive Adserver-land - it's an underlying Windows issue. A capture of the server error may help.
