### ISSUE TITLE
init.php $conf repeated?

### ISSUE THREAD

**Issue by WRLin** [revive-adserver/revive-adserver#458]
init.php file  init function $conf assigned it be repeated ?
![53560867-987f-4cdc-b6be-07fd8f12348a](https://cloud.githubusercontent.com/assets/2044099/5657436/2dba9c92-972a-11e4-99ef-27a26ab91e10.png)

**Comment by erikgeurts** [comment]
Can you please explain what you are trying to ask?

**Comment by WRLin** [comment]
@erikgeurts sorry,my english is poor.
I want ask in init.php  init function is define $conf variable is it repeated?

**Comment by mbeccati** [comment]
@WRLin I'm not sure what you're asking either. In any case PHP uses a copy-on-write mechanism, so in that case there aren't two copies of the same array in memory.

**Comment by WRLin** [comment]
@mbeccati thanks
