### ISSUE TITLE
Region delivery limitations does not work as expected with "Is not any of"

### ISSUE THREAD

**Issue by Zer0Divis0r** [revive-adserver/revive-adserver#459]
When limiting a banner with:
"Is not any of":
Country: United States
Region: Florida

What happens:
Connecting from New York: banner is delivered (expected to deliver)
Connecting from Florida: banner is not delivered (expected not to deliver)
Connecting from Israel: banner is not delivered (expected to deliver!)

Using the latest version of GeoIP database. Double-checked that the IPs I do checks from are detected correctly by Revive.

**Comment by erikgeurts** [comment]
Please consider posting your question on the community forums at http://forum.revive-adserver.com

**Comment by erikgeurts** [comment]
Can you please post the IP address that you say is from Israel?

**Comment by mbeccati** [comment]
I've been able to replicate the issue. As it is now, it appears that the delivery limitation is applied as "country being US and state not any of [Florida]". As far as I know it has been interpreted like this since ages, and I would be reluctant to change it in a minor release, even if I think it is a bug.

It could be something to consider for fixing in 3.2.

As a work around you could add one more condition, like "country NOT US", making sure the oprand is "OR".

**Comment by andrewatfornax** [comment]
This needs some new documentation to help make it easier to understand how things work currently - I have this on my list to do as part of preparations for the 4.0.2 release.

**Comment by andrewatfornax** [comment]
Oh, rats. I forgot - I haven't done any geotargeting documentation at all yet. This makes it hard to add a note to talk about how this works!

I have bumped this to the 4.1.0 release for now, but I will put geotargeting documentation higher on my list of things to do re: user documentation. Sorry for the delay.

**Comment by erikgeurts** [comment]
This shall be documented at some point at https://documentation.revive-adserver.com/display/DOCS/Geotargeting+Delivery+Rules

**Comment by erikgeurts** [comment]
Since this issue is not going to be extremely common, I think it's OK to close this here and refer to the documentation.

I've added a link on that page referring back to this issue, so that readers looking for it can easily find it while looking for documentation on setting geotargeting rules.

**Comment by andrewatfornax** [comment]
This is now documented.
