### ISSUE TITLE
VAST 2.0 and VAST 3.0 support

### ISSUE THREAD

**Issue by Dexus** [revive-adserver/revive-adserver#461]
hey, i'm new to revive, but im missing VAST 2.0 and VAST 3.0 support for video ads...

**Comment by erikgeurts** [comment]
Please have a look at this entry on the community forums:
http://forum.revive-adserver.com/topic/247-what-is-the-vast-version-used-in-revive-adserver/?hl=vast2#entry854

**Comment by DamienPirsy** [comment]
That doesn't answer the question, VAST 1 is quite old and support for VAST 2.0 (or the year-old now 3.0) should be added as a core feature, not relegated to a paid 3rd party plugin.

**Comment by tlehtimaki** [comment]
You can transform yourself to VAST 2.0 pretty easily. It's pretty much just
a small rework of the XML-output. To fully leverage the power of VAST 2.0
or VAST 3.0 you need to do a lot more, but just to get companions work eg.
JW Player Ads, you just need the syntax of VAST 2.0.

2015-02-09 12:52 GMT+02:00 Matteo Vignoli <notifications@github.com>:

> That doesn't answer the question, VAST 1 is quite old and support for VAST
> 2.0 (or the year-old now 3.0) should be added as a core feature, not
> relegated to a paid 3rd party plugin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/revive-adserver/revive-adserver/issues/461#issuecomment-73489900>
> .
>



-- 
Toni Lehtimäki
+35850 572 4056
Web-ohjelmoija

**Comment by Dexus** [comment]
@DamienPirsy :+1:

**Comment by gamesquat** [comment]
@DamienPirsy +1 from me too.

**Comment by martinshield** [comment]
Have someone updated the VAST version?

**Comment by erikgeurts** [comment]
Please have a look at http://www.revive-adserver.com/blog/can-revive-adserver-support-vast-2-0/

**Comment by krish512** [comment]
Try this VAST 1.0 to VAST 2.0 converter,
https://github.com/krish512/vast-converter

It definitely doesn't support features added in VAST 2.0 or 3.0, but at least supports basic features introduced with VAST 1.0 in VAST 2.0 formatted XML
