### ISSUE TITLE
close.gif problem - https

### ISSUE THREAD

**Issue by mydukkan** [revive-adserver/revive-adserver#465]
![revive_bug_screen_1](https://cloud.githubusercontent.com/assets/10612242/5815538/302f44b8-a09f-11e4-896c-d5294ee234e8.jpg)
![revive_bug_screen_2](https://cloud.githubusercontent.com/assets/10612242/5815555/45f195d0-a09f-11e4-9c86-3e0eb023da4d.jpg)

**Comment by erikgeurts** [comment]
@mydukkan Thanks for your report, this helped us find and fix this bug.

**Comment by mydukkan** [comment]
Thanks for your fast response.

Have a nice day.

**Comment by mydukkan** [comment]
(Add delivery limitation) When appropriate banner impressions remain, looks close.gif.
![revive_bug_screen_3](https://cloud.githubusercontent.com/assets/10612242/5824113/dbe25b42-a0ea-11e4-8784-e606f2521d4c.jpg)

**Comment by mbeccati** [comment]
@mydukkan this is not related to this bug. Please open a new issue for that.

**Comment by mydukkan** [comment]
ok, sorry.
