### ISSUE TITLE
Issue with Plugin_geoTargeting_oxMaxMindGeoIP_oxMaxMindGeoIP_Delivery_getGeoInfo()

### ISSUE THREAD

**Issue by estabij** [revive-adserver/revive-adserver#471]
Hi,
I had an issue with Plugin_geoTargeting_oxMaxMindGeoIP_oxMaxMindGeoIP_Delivery_getGeoInfo().
I have installed the geo ip plugin and then revive adserver stopped working.
In my error log I saw: FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare plugin_geotargeting_oxmaxmindgeoip_oxmaxmindgeoip_delivery_getgeoinfo() in |�
/html/revive/plugins/geoTargeting/oxMaxMindGeoIP/oxMaxMindGeoIP.delivery.php on line 32".
Then I added just above Plugin_geoTargeting_oxMaxMindGeoIP_oxMaxMindGeoIP_Delivery_getGeoInfo($useCookie = true) in oxMaxMindGeoIP.delivery.php:
if(function_exists('Plugin_geoTargeting_oxMaxMindGeoIP_oxMaxMindGeoIP_Delivery_getGeoInfo')) {
       debug_print_backtrace();
        die('Trying to define Plugin_geoTargeting_oxMaxMindGeoIP_oxMaxMindGeoIP_Delivery_getGeoInfo() a second time');
   }

This gave:
#0  include() called at [/home/estabij/www/labs.starbrain.com/html/revive/lib/max/Delivery/common.php:729]
#1  _includeDeliveryPluginFile(/plugins//geoTargeting/oxMaxMindGeoIP/oxMaxMindGeoIP.delivery.php) called at [/home/estabij/www/labs.starbrain.com/html/revive/lib/max/Delivery/common.php:705]
#2  OX_Delivery_Common_getFunctionFromComponentIdentifier(geoTargeting:oxMaxMindGeoIP:oxMaxMindGeoIP, getGeoInfo) called at [/home/estabij/www/labs.starbrain.com/html/revive/lib/max/Delivery/common.php:665]
#3  OX_Delivery_Common_hook(getGeoInfo, Array (), geoTargeting:oxMaxMindGeoIP:oxMaxMindGeoIP) called at [/home/estabij/www/labs.starbrain.com/html/revive/lib/max/Delivery/remotehost.php:159]
#4  MAX_remotehostSetGeoInfo() called at [/home/estabij/www/labs.starbrain.com/html/revive/lib/max/other/lib-acl.inc.php:26]
#5  require_once(/home/estabij/www/labs.starbrain.com/html/revive/lib/max/other/lib-acl.inc.php) called at [/home/estabij/www/labs.starbrain.com/html/revive/lib/max/other/common.php:14]
#6  require_once(/home/estabij/www/labs.starbrain.com/html/revive/lib/max/other/common.php) called at [/home/estabij/www/labs.starbrain.com/html/revive/lib/OA/Permission.php:17]
#7  require_once(/home/estabij/www/labs.starbrain.com/html/revive/lib/OA/Permission.php) called at [/home/estabij/www/labs.starbrain.com/html/revive/lib/OA/Dll.php:21]
#8  require_once(/home/estabij/www/labs.starbrain.com/html/revive/lib/OA/Dll.php) called at [/home/estabij/www/labs.starbrain.com/html/revive/lib/OA/Admin/Template.php:16]
#9  require_once(/home/estabij/www/labs.starbrain.com/html/revive/lib/OA/Admin/Template.php) called at [/home/estabij/www/labs.starbrain.com/html/revive/lib/OA/Admin/UI.php:13]
#10 require_once(/home/estabij/www/labs.starbrain.com/html/revive/lib/OA/Admin/UI.php) called at [/home/estabij/www/labs.starbrain.com/html/revive/www/admin/lib-gui.inc.php:16]
#11 require_once(/home/estabij/www/labs.starbrain.com/html/revive/www/admin/lib-gui.inc.php) called at [/home/estabij/www/labs.starbrain.com/html/revive/www/admin/config.php:17]
#12 require_once(/home/estabij/www/labs.starbrain.com/html/revive/www/admin/config.php) called at [/home/estabij/www/labs.starbrain.com/html/revive/www/admin/index.php:17]
Trying to define Plugin_geoTargeting_oxMaxMindGeoIP_oxMaxMindGeoIP_Delivery_getGeoInfo() a second time

I made a workaround like this:
if (!function_exists('Plugin_geoTargeting_oxMaxMindGeoIP_oxMaxMindGeoIP_Delivery_getGeoInfo')) {
Plugin_geoTargeting_oxMaxMindGeoIP_oxMaxMindGeoIP_Delivery_getGeoInfo($useCookie = true) {
...
}
}

**Comment by mbeccati** [comment]
@estabij what do you mean by "I have installed"? The plugin is installed by default.

**Comment by erikgeurts** [comment]
@estabij I'm going to close this issue now for lack of response, but if you have any new input, we're more than happy to re-open it.
