### ISSUE TITLE
Data loss with a server restart

### ISSUE THREAD

**Issue by jithujose** [revive-adserver/revive-adserver#472]
Hi everyone,

we had some data loss with revive following a server restart. Thanks to our daily database backups we were able to minimize this loss. 

We are running Revive 3.0.5 atm.

It seems like MySQL was not saving anything onto disk over the last few months, which is pretty strange. We got MySQL 5.5.

I think it's a serious issue.

Do you have any idea on what could be the causes of this problem?

Thanks

**Comment by ianvm** [comment]
Hi !

I don't think it's related to Revive, but to your server setup. Please 
consider posting into the forum http://forum.revive-adserver.com/

kind regards,
Ian
