### ISSUE TITLE
Fresh Install after 1 day error

### ISSUE THREAD

**Issue by rajlaksh** [revive-adserver/revive-adserver#473]
MESSAGE: Declaration of MDB2_Driver_Common::raiseError() should be compatible with & PEAR::raiseError($message = NULL, $code = NULL, $mode = NULL, $options = NULL, $userinfo = NULL, $error_class = NULL, $skipmsg = false)
TYPE: Strict
FILE: /home/public_html/adserver/lib/pear/MDB2.php
LINE: 0
DEBUG INFO:

Context cannot be shown - (0) is an invalid line number

**Comment by mbeccati** [comment]
Maybe you've changed your php configuration and now Reviva can't mask E_STRICT errors anymore?

It might be helpful to see a phpinfo() output.

**Comment by erikgeurts** [comment]
I would like to suggest that this topic is better suited for the community forum at http://forum.revive-adserver.com/forum/13-managing-revive-adserver/

**Comment by andrewatfornax** [comment]
Hey @mbeccati ! Is this a fix that will be in 3.2, and does it need a release notes update? :-)

**Comment by andrewatfornax** [comment]
Oh, you already did! :-)
