### ISSUE TITLE
Audit trail not registering remote IP address

### ISSUE THREAD

**Issue by sathio** [revive-adserver/revive-adserver#474]
Hi, somebody stole the password from the Ads manager computer, we were looking into audits in order to see which was the IP and maybe understand better what happened, but there are no IP registered.
 
What's the use of an audit if it doesn't store the IP address of who made an action?
 
Is there any interest in this? If so I could work on it and make a pull request

**Comment by erikgeurts** [comment]
Given the lack of response on this matter when you posted it on the forums before, I doubt there is a lot of interest for it, but you are more than welcome to submit a pull request.

However, I would imagine your Apache access logs will also be able to tell you what happened, and who did what.

**Comment by sathio** [comment]
Hi Erik, I'll see what I can do, I know about apache logs, but unfortunately at the time they were not enabled on the prod server... so, you know... cheers

**Comment by skynet** [comment]
Web server can log those IPs but audit trail w/o IP is very much incomplete.

**Comment by andrewatfornax** [comment]
Well, IPs are easy to fake, so, unfortunately, if you have a situation where passwords are stolen, then you're pretty much hosed at that point. Would be happy to accept a PR for adding IP logging to the auditing system, but it's not a priority item for the core team right now. 

I will close this ticket, but please feel free to comment re: reopening in the future if someone has a compelling reason why this should be added, or, better yet, a PR! Thanks.

**Comment by sathio** [comment]
https://github.com/revive-adserver/revive-adserver/pull/487
there's my PR, works locally.
ciao
