### ISSUE TITLE
Problem in Switching Default manager to Administrator account

### ISSUE THREAD

**Issue by sucae91** [revive-adserver/revive-adserver#475]
Problem in Switching Default manager to Administrator account.
I have to hit a manual refresh and it work

**Comment by erikgeurts** [comment]
Please provide more detail and or technical information about your server environment.

Otherwise, please consider posting your support question on the community forums at http://forum.revive-adserver.com

**Comment by sucae91** [comment]
Below are my server information 
Apache version  =  2.2.26
PHP version = 5.4.37
MySQL version = 5.5.40-36.1
Architecture = x86_64
Operating system = linux

I put this as subdirectory in my domain.

**Comment by sucae91** [comment]
i think this is really weird, cz in my local PC it can work properly, please kindly help

**Comment by erikgeurts** [comment]
If it works on your PC, then it is most likely not a code problem. Please consider posting your support question on the community forums at http://forum.revive-adserver.com

**Comment by sucae91** [comment]
ok, thanks :)
