### ISSUE TITLE
Mal/HappJS-A yandex.ru

### ISSUE THREAD

**Issue by berezuev** [revive-adserver/revive-adserver#479]
I've placed a zone Invocation JS code on a page, and at the next day my site was marked as an infected one in russian search system "yandex.ru" (the most popular in Russia) and "Yandex browser".

It thinks, that I've placed a Mal/HappJS-A.
Their example: ![xp9prdq0vzdq6kqkzeawgrg7kco 1](https://cloud.githubusercontent.com/assets/695546/6143662/a4a3218a-b1dd-11e4-921e-55d40e117f32.png)

**Comment by erikgeurts** [comment]
I would like to suggest moving this to http://forum.revive-adserver.com/forum/13-managing-revive-adserver/ , this is not a topic to be discussed in the Github issues section.

**Comment by andrewatfornax** [comment]
Not really sure what we can do about this one - either they are incorrectly detecting that there's an issue, in which case they need to be contacted; or, you do have an infection on your system - and there's information around on where to look to clean up from there. Closing, but please add more information if you feel there's a bug. Thanks.
