### ISSUE TITLE
SyntaxError: Unexpected token ';'

### ISSUE THREAD

**Issue by leandrosfar** [revive-adserver/revive-adserver#480]
Hello

Updated the 3.0.5 version of Revive Adserver to version 3.1.0. From there, the editing or creating a new campaign, a javascript error (SyntaxError: Unexpected token ';') is displayed and can no longer edit the start and end dates of campaigns.

Help us?

![revive-campaign-edit](https://cloud.githubusercontent.com/assets/10963400/6152599/3db92e36-b1fd-11e4-8409-a18187d88bcb.png)

**Comment by mbeccati** [comment]
@leandrosfar could you please verify if it still happens when switching to english and/or trying to force-reload the page?

**Comment by leandrosfar** [comment]
@mbeccati In both cases the problem persists
![captura de tela 2015-02-12 as 12 32](https://cloud.githubusercontent.com/assets/10963400/6170442/8a8bb146-b2b3-11e4-9e3c-1e08ff10983b.png)

**Comment by mbeccati** [comment]
I've finally been able to test this on Safari. I wasn't able to reproduce it, but I've noticed that my 3.1.0 looks a bit different from yours:

![schermata 2015-03-09 alle 15 12 29](https://cloud.githubusercontent.com/assets/282388/6556626/08d773c2-c66f-11e4-9b14-b5d8968b8a8a.png)

I guess that something went wrong during your upgrade or the webserver/php-fpm requires a restart.

**Comment by leandrosfar** [comment]
@mbeccati updated php, restarted php-fpm and nginx... Problem solved! thanks
