### ISSUE TITLE
Upgrade documentation no longer says to copy images from ./www/images

### ISSUE THREAD

**Issue by jamieburchell** [revive-adserver/revive-adserver#481]
Just upgraded Revive as per the instructions on the website from 3.0.5 > 3.1.0.

After the upgrade, there were no images in ./www/images so I needed to copy them manually. I remember this used to be in the documentation for upgrading - so either the documentation is wrong or there was a problem copying the images from the old installation.

**Comment by erikgeurts** [comment]
The upgrade process does not automatically copy the images from www/images of the old to the new location. Please have a look at the http://www.revive-adserver.com/support/upgrading/ for general instructions
and http://www.reviveconsultant.com/articles/how-to-move-the-banner-image-storage-location-in-revive-adserver/ which explains how to move your images out of the program code tree.

**Comment by jamieburchell** [comment]
Thanks. I missed the part about the images at the top of the upgrade guide.

**Comment by erikgeurts** [comment]
I've updated the upgrade instructions with a tip to copy the images from the old to the new location in case the images folder has not been moved.

**Comment by jamieburchell** [comment]
Great, thanks :)
