### ISSUE TITLE
Click script vast video player is not working well

### ISSUE THREAD

**Issue by fotohandboek** [revive-adserver/revive-adserver#484]
I like to use the video plugin from Revive but is not working for me right now. After the installation 3.1.0 it's not possible to click on the video commercial (destination url).

http://www.fotohandboek.nl/ad/www/delivery/fc.php?script=bannerTypeHtml:vastInlineBannerTypeHtml:vastInlineHtml&format=vast&nz=1&zones=pre-roll%3D3 

Can you please help me with this issue? 

Thanks Thijs

**Comment by erikgeurts** [comment]
Works just fine for me in that example you linked to.

Please consider posting support questions on the community forums at http://forum.revive-adserver.com
