### ISSUE TITLE
DB Deadlock

### ISSUE THREAD

**Issue by onaydenov** [revive-adserver/revive-adserver#494]
Deadlock found when tried to unlink campaigns from zone.
Details:
An error occurred while accessing the database

Due to a problem with the database Revive Adserver couldn't retrieve or store data. If this problem is reproducable it might be caused by a bug in Revive Adserver. Please report the following information to the creators of Revive Adserver. Also try to describe the actions that led to this error as clearly as possible.

Version:    Revive Adserver v3.0.5
PHP/DB: PHP 5.4.33 / MySQL 5.6.20-68.0-log
Page: /admin/zone-include.php
Error: Deadlock found when trying to get lock; try restarting transaction
Query: 
DELETE FROM rv_ad_zone_assoc  WHERE (  rv_ad_zone_assoc.zone_id = 461 )  AND (  rv_ad_zone_assoc.ad_id = 707 )
$_POST: 
Empty
$_GET: 
Array
(
    [affiliateid] => 93
    [zoneid] => 461
    [campaignid] => 399
    [action] => remove
)

**Comment by erikgeurts** [comment]
@onaydenov Could you please describe in a little bit more detail what you were doing immediately before this error message appeared?

**Comment by onaydenov** [comment]
@erikgeurts Nothing special. Immediately before the issue I've opened "zone edit" interface (/admin/zone-include.php?affiliateid=xxxx&zoneid=xxxx) and started to unlink ad camapign from zone.

**Comment by erikgeurts** [comment]
What was the type of that zone?

**Comment by onaydenov** [comment]
Banner, Button or Rectangle

**Comment by erikgeurts** [comment]
OK. I'm afraid that based on this information, we still don't have a lot to go on. Has this happened just once or can it be reproduced consistently?

**Comment by onaydenov** [comment]
Just once. Had no such issue before or after.

**Comment by erikgeurts** [comment]
OK, just once. That's almost impossible to diagnose then. I would like to suggest we consider this a freak incident. If you encounter it again, please collect as much detail about what you were doing immediately before the error occured.

**Comment by mbeccati** [comment]
Closing for now. Please re-open / comment if it happens again.
