### ISSUE TITLE
The click is not real, why?

### ISSUE THREAD

**Issue by volponerosso** [revive-adserver/revive-adserver#495]
hi all 
I have a problem with the tracking of clicks. I use revive adserver on several websites, two days ago I downloaded the 'latest version and installed on a another site. The statistics and click monitored but are not realistic, there are 50click on a banner of another my web site in a single day, but if I control by google analytics the visits and referrals are only two visits true. How so? It 'very strange

many thanks

**Comment by volponerosso** [comment]
This is example of today;
Banner 1 = Impr. 71 - Click 49 - CTR 69%
Banner 2 = Impr. 71 - Click 40 - CTR 56%
Banner 3 = Impr. 71 - Click 60 - CTR 84%

**Comment by erikgeurts** [comment]
Please consider posting your question on our community forums at http://forum.revive-adserver.com/

**Comment by volponerosso** [comment]
Ok i insert in this page
http://forum.revive-adserver.com/topic/1579-the-click-is-not-real-why/

many thanks

**Comment by erikgeurts** [comment]
no need to post that link here, the forum is the designated place for community support.
