### ISSUE TITLE
Contract campaigns with timezone don't reach their daily impressions

### ISSUE THREAD

**Issue by rhapsodyv** [revive-adserver/revive-adserver#497]
Hi,
I have contract campaigns cpm limited by daily impressions and without end date.
I was using UTC -3 in default account preferences. The campaigns never reach their limits.

But, in this weekend, I changed to UTC 0 and now every contract campaing is working very very fine and reaching theirs daily limit.

I'm using version 3.1.0. We upgraded our servers two weeks ago. I tried use overdeliver to 200%, but neither way the campaigns reach their target.
Setting default account to UTC 0 solved the problem even with overdeliver off.

I have found a possible origin for this error:
The method: 
```php
OA_Maintenance_Priority_AdServer_Task_GetRequiredAdImpressions::getCampaignImpressionInventoryRequirement
```

In this part:
```php 
                $oTodayDate = new Date($this->_getDate());
                $oTodayDate->convertTZ($this->currentTz);
                $oCampaign->setSummaryStatisticsToday($oTodayDate->format('%Y-%m-%d'));
```
This code query campaign delivered statistics for today, but it's not considering the start and end time for the campaing timezone.

The query executed takes Today and filters for 00:00 to 23:59:59 UTC 0, but a campaing with UTC -3 must filter for: 03:00 (of today) to 02:59:59 UTC 0 (of tomorow).
```php
        array($joinTable2, "$joinTable1.bannerid = $joinTable2.ad_id AND $joinTable2.date_time >= '$today 00:00:00' AND $joinTable2.date_time <= '$today 23:59:59'")
```
Full query:
```php
    function getCampaignDeliveryToday($id, $today)
    {
        $aConf = $GLOBALS['_MAX']['CONF'];
        $query = array();
        $table = $this->_getTablenameUnquoted('campaigns');
        $joinTable1 = $this->_getTablenameUnquoted('banners');
        $joinTable2 = $this->_getTablenameUnquoted('data_intermediate_ad');

        $query['table']    = $table;
        $query['fields']   = array(
                                "SUM($joinTable2.requests) AS sum_requests",
                                "SUM($joinTable2.impressions) AS sum_views",
                                "SUM($joinTable2.clicks) AS sum_clicks",
                                "SUM($joinTable2.conversions) AS sum_conversions",
                                "$table.campaignid AS placement_id"
        );
        $query['wheres']   = array(
        array("$table.campaignid = $id", 'AND')
        );
        $query['joins']    = array(
        array($joinTable1, "$table.campaignid = $joinTable1.campaignid"),
        array($joinTable2, "$joinTable1.bannerid = $joinTable2.ad_id AND $joinTable2.date_time >= '$today 00:00:00' AND $joinTable2.date_time <= '$today 23:59:59'")
        );
        $query['group']    = "placement_id";
        return $this->_get($query);
    }
```

The code use it to calculate the remaining impressions for today. But it just don't takes in account the time of the start and end dates, that isn't 00:00 and 23:59 for campaigns with UTC negative or positive.

I will try run a fix locally. I don't know if there's any other problem that can affect contract campaigns with timezone other than GMT.

**Comment by rhapsodyv** [comment]
I'm testing a fix. Do you have any guideline to fill a pull request?

**Comment by karen-mikaela** [comment]
Great solution @rhapsodyv! It works fine. It is very important to consider fix this bug on next release.

**Comment by mbeccati** [comment]
@rhapsodyv @karen-mikaela thanks. I'm now running the test suite on a branch w/ the patch above. If all is good I'll merge to master.
