### ISSUE TITLE
Select drop down menu does not convert the HTML entities

### ISSUE THREAD

**Issue by shefik** [revive-adserver/revive-adserver#500]
When accessing this page:

Inventory -> Zones

If a campaign name has an ampersand in it, then the select drop down menu does not convert the HTML entities.

For example, the expected display is:

```
Explore & Cultivate
```

However, the display results as:

```
Explore &amp; Cultivate
```

**Comment by shefik** [comment]
Also, when the Invocation Code is rendered, the "alt" and "title" attributes in the "omg" tag is not using HTML entities.

For example, the expected tag is:

```
<img src="http://www.example.com/www/images/1db18hdf70623c9bc6bbd33ae6d690b3.jpg" width="728" height="90" alt="Explore &amp; Cultivate" title="Explore &amp; Cultivate" border="0" />
```

But, this renders instead:

```
<img src="http://www.example.com/www/images/1db18hdf70623c9bc6bbd33ae6d690b3.jpg" width="728" height="90" alt="Explore & Cultivate" title="Explore & Cultivate" border="0">
```

**Comment by mbeccati** [comment]
@shefik I haven't been able to verify the second (<img> tag) issue. Could you please:

1. verify the steps to replicate it with 3.1.0
2. open a new issue for it
3. describe all the steps to replicate
