### ISSUE TITLE
Trying to upload new Banner but photo will not upload

### ISSUE THREAD

**Issue by btedeschi80** [revive-adserver/revive-adserver#502]
Trying to upload new banners for 3 brands. Photos are the correct size. I choose the photo and press save and it says our new banner has been uploaded but the photo does not appear and by Choose File it says no File Chosen. 

Please help us fix the issue - we need these banners live ASAP.

Thank you

**Comment by erikgeurts** [comment]
Please consider posting your support questions on the community forums at http://forum.revive-adserver.com
