### ISSUE TITLE
Some translation strings still in use are gone after the clean-up

### ISSUE THREAD

**Issue by andrewatfornax** [revive-adserver/revive-adserver#504]
In 3.2.0-beta-rc3, the installation screens have the heading "InstallStatusUpgrade" instead of "Installing Revive Adserver 3.2.0-beta-rc3".

**Comment by andrewatfornax** [comment]
Looks like the "installStatusUpgrade" string is no longer present in the translation files - lost in the move to Crowdin?

**Comment by erikgeurts** [comment]
@mbeccati has been doing a lot of work these days cleaning up strings from the languages files that are no longer being used. Perhaps by accident one or two have been removed that are still needed.

**Comment by mbeccati** [comment]
@andrewatfornax Precisely: the clean-up script might have been a bit too eager sometimes. I'll add this one back, plus any other that we find in the next days.

I'm also changing the issue description to be more generic, so we can add more here (if any!)
