### ISSUE TITLE
Impression are being under delivered

### ISSUE THREAD

**Issue by myvidster** [revive-adserver/revive-adserver#510]
After upgrading 3.0 to 3.1 the contact campaigns are under delivering impressions.  For example I set a campaign to deliver 2.6M impression but I only get 2M.  The probability calculations are not working correctly.  Any solutions on how to fix this or should I uninstall and go back to 3.0?

**Comment by rhapsodyv** [comment]
The default account timezone is GMT or UTC-something?
If you are using UTC-something, can be related to #497

**Comment by erikgeurts** [comment]
@myvidster Have you looked at @rhapsodyv 's suggestion? I'm going to close this issue, but if you have any new information, please don't hesitate to post it here, we'll be more than happy to re-open this issue.
