### ISSUE TITLE
Error message when trying to link a banner to an email zone

### ISSUE THREAD

**Issue by jmgodin** [revive-adserver/revive-adserver#511]
Trying to link a banner to an email zone but getting the following message:

Cannot link this banner: 
It was not possible to link this banner to this zone because: 
Dates of the campaign you are trying to link overlap with the dates of a campaign already linked

One campaign is set to remnant and the other to override so it should be working.

**Comment by erikgeurts** [comment]
Please consider posting your support question on the community forums at http://forum.revive-adserver.com

**Comment by erikgeurts** [comment]
Just to clarify: I don't think this is a bug. The message you read is:
```Dates of the campaign you are trying to link overlap with the dates of a campaign already linked```

It doesn't matter what the campaign types are, as far as I understand. At any given time, there can be only one active banner on an e-mail zone.

**Comment by jmgodin** [comment]
So you can't have a remnant campaign (house) that will serve when there is nothing to serve? I guess I will ask on the forum.

**Comment by erikgeurts** [comment]
Like the message says: At any given time, there can be only one active banner on an e-mail zone. Regardless of campaign type(s).
