### ISSUE TITLE
PHP Fatal error:  Call to undefined method Plugins_DeliveryLimitations_Client_Browser::Plugins_DeliveryLimitations_ArrayData()

### ISSUE THREAD

**Issue by Pedro-Miguel** [revive-adserver/revive-adserver#512]
On 3.2.0-Beta at banner delivery options always get (on php error logs):

PHP Fatal error:  Call to undefined method Plugins_DeliveryLimitations_Client_Browser::Plugins_DeliveryLimitations_ArrayData() in /home/**********/plugins/deliveryLimitations/Client/Browser.class.php on line 38

None options are populated on the select box.

**Comment by mbeccati** [comment]
HI @Pedro-Miguel, thanks for trying the beta and reporting the issue.

I suppose this was an upgrade, correct? If so, did you have any error message when upgrading the plugins? I'm asking because it seems that plugins/deliveryLimitations/Client/Browser.class.php wasn't upgraded to the latest version.

**Comment by erikgeurts** [comment]
I can confirm that this issue also occurs for me on an instance I upgraded from 3.0.6 to 3.2.0-beta. The "Delivery Limitations Plugin" in this upgraded instance is v1.2.1 here.

On a fresh install of Revive Adserver 3.2.0-beta it does work, however. The "Delivery Limitations Plugin" is v1.3.3 there.

The other plugins in my upgraded instance have the same version number as the freshly installed instance. This seems to be something related to the Delivery Limitations Plugin only.

**Comment by mbeccati** [comment]
To everyone who has downloaded the beta and performed an upgrade:
* Please apply the fix above
* Run the upgrade of the delivery limitations plugin manually, uploading the one from etc/plugins in the zip/tgz file.

I'll repackage the beta shortly to fix this nasty bug that slipped through our tests.

**Comment by erikgeurts** [comment]
A note about this issue and the repackaging of this beta release has been added to the blog post about Revive Adserver v3.2.0-beta: http://www.revive-adserver.com/blog/beta-version-of-revive-adserver-v3-2-0-released/

**Comment by Pedro-Miguel** [comment]
That fix works for me. (4b0b415)

It was a upgrade and sorry for not leave my stack specifications.
PHP 5.6.7
MySQL 5.6.23-72.1 (Percona)
Nginx 1.6.2

**Comment by erikgeurts** [comment]
Thanks @Pedro-Miguel for reporting this issue, enabling us to make the upcoming v3.2.0 release better for the community.

**Comment by richardfoley** [comment]
Good work folks, the best bugs are the dead bugs! :)
