### ISSUE TITLE
Add option to choose mod_geoip instead of flat file

### ISSUE THREAD

**Issue by Pedro-Miguel** [revive-adserver/revive-adserver#513]
Hi,

I think it will be great if we have an option on MaxMind GeoIP Plugin to choose the server variables (instead of the flat/bin file location) like:

_SERVER["GEOIP_COUNTRY_CODE"]
_SERVER["GEOIP_COUNTRY_NAME"]
_SERVER["GEOIP_CITY"]
_SERVER["GEOIP_POSTAL_CODE"]
_SERVER["GEOIP_LATITUDE"]
_SERVER["GEOIP_LONGITUDE"]

This variables are provided by mod_geoip (apache) and http_geoip_module (nginx), so a "simple" IF should be sufficient to check avaiability.

**Comment by mbeccati** [comment]
I haven't tested it in a while, but there's a specific plugin for mod_geoip: https://github.com/revive-adserver/revive-adserver/tree/master/plugins_repo

**Comment by mbeccati** [comment]
You can create a zip package running ./package.sh openXMaxMindModGeoIP

**Comment by Pedro-Miguel** [comment]
Thanks, I will test and post the results

**Comment by Pedro-Miguel** [comment]
Work's just fine with nginx, all options is displayed and banners delivered as shoud be, thanks!
