### ISSUE TITLE
Campaigns and Banners disappeared

### ISSUE THREAD

**Issue by clickmediaby** [revive-adserver/revive-adserver#516]
Hi. One day I added about 65 banners to adserver but didn't link them to zones. that day everything worked correctly. The next day I logged in and saw that http://c2n.me/3fZDRiS.png
As you see there is no banners, cmpaigns and sites. Nothing was updated or changed that night. All banners and campaigns are on server, zones work properly,but I cant link new banners and add some more. http://c2n.me/3fZIlKA.png
What could be the reason of such disappearing?

**Comment by erikgeurts** [comment]
Based on what you write, it is not certain this is a bug. I would like to recommend that you post your question on the community forums at http://forum.revive-adserver.com. If it turns out to be a bug after all, we're more than happy to re-open this issue.
