### ISSUE TITLE
Problem with export statistics to Excel

### ISSUE THREAD

**Issue by cirtapae** [revive-adserver/revive-adserver#517]
![bug_revive](https://cloud.githubusercontent.com/assets/11968932/7170242/ae6cf686-e3a2-11e4-86da-31376abd01a4.PNG)

Hi, I 'm using the latest version of revives . When I try to record the statistics of a campaign to excel, excel file is created empty with an error in this in the attached image . How do I fix it? Thanks for the help.

**Comment by mbeccati** [comment]
The quick fix should be installing the mbstring php extension. We might need to add it to the requirements.

**Comment by cirtapae** [comment]
It worked . Thank you very much friend. Greetings .

**Comment by erikgeurts** [comment]
I have updated the page describing the technical requirements at http://www.revive-adserver.com/support/requirements/ so that it also mentions that the mbstring php extension is required.
