### ISSUE TITLE
Exceeded the Maximum execution time for "User Log"

### ISSUE THREAD

**Issue by karen-mikaela** [revive-adserver/revive-adserver#518]
My revive application has a huge records number in audit table.
When I go to the "User Log" area, I receive the below message:
Fatal error: Maximum execution time of 30 seconds exceeded in revive/lib/max/Dal/DataObjects/DB_DataObjectCommon.php on line 900
I tried to increase the timeout but another error happens:
"PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 89 bytes) in revive/lib/max/Dal/DataObjects/DB_DataObjectCommon.php on line 898
Well, I think the problem is because the at the first time that you have used no filters, there is any limit for the main query.

```sql
SELECT *
FROM rv_audit
WHERE ( parentid IS NULL ) 
ORDER BY updated DESC
```
 
So,I added a else clause with limit to 500 in OA_Dll_Audit::getAuditLog in lines below:

```php
if ((!empty($aParam['startRecord']) || $aParam['startRecord'] >= 0) && $aParam['perPage']) {
    $doAudit->limit($aParam['startRecord'], $aParam['perPage']);
}else{
    $doAudit->limit(0,500);
}
```

I am not sure if is the best solution. I would to know if there are another solutions for this problem.

**Comment by erikgeurts** [comment]
@karen-mikaela Would you be able to create a pull request for this proposed improvement?

**Comment by karen-mikaela** [comment]
I will do it.
Tks @erikgeurts .
