### ISSUE TITLE
Disable AdSense ad

### ISSUE THREAD

**Issue by lludwig** [revive-adserver/revive-adserver#522]
It appears if you disable an AdSense ad you get an error message like when clicking on the disable button. I don't see this issue with other ad banners.

-----
MESSAGE: Invalid argument supplied for foreach()
TYPE: Warning
FILE: /home/ads/domains/somedomain/public_html/plugins/3rdPartyServers/ox3rdPartyServers/google.class.php
LINE: 56
DEBUG INFO:

51	$new_buffer = "". 
52	"

------

Similar message seems to occur when you re-enable it. Though it appears the disable and enable still works.

**Comment by erikgeurts** [comment]
@lludwig Would it be possible to add a screen shot of the on-screen actions that trigger this?

**Comment by erikgeurts** [comment]
Given that there is no new information, I'm closing this issue. However, feel free to add comments and we will re-open it if needed.
