### ISSUE TITLE
Internal Server Error on Stats Page

### ISSUE THREAD

**Issue by rashidrupani** [revive-adserver/revive-adserver#523]
When I click on Statistics > Advertiser Name I got Internet Server Error:
URL:
MyWebsite.com/RevivieFolder/www/admin/stats.php?entity=advertiser&breakdown=history&clientid=2&agency_id=1&period_preset=today&period_start=2015-04-24&period_end=2015-04-24

Screencast: http://screencast.com/t/Fc3czN0t5

More Details:
GoDaddy Hosting
Revive Adserver v3.1.0 running on Apache, PHP 5.3.24 and MySQL 5.5.40-36.1-log.

Any Solution?

**Comment by mbeccati** [comment]
@rashidrupani your apache error log should tell the reason for the 500 error. Also please consider using the forums as a support tool. Github issues should be used for actual bug reports.
