### ISSUE TITLE
Plz back banner link in 'Generic HTML Banner'

### ISSUE THREAD

**Issue by iz4blue** [revive-adserver/revive-adserver#525]
Hello,

I'm using 'Generic HTML Banner' like this.
But it removed, cause #89 issue.

![2015-04-28 10 18 59](https://cloud.githubusercontent.com/assets/979297/7361320/21bbdaf6-ed91-11e4-8749-9fe4d04987e8.png)

![2015-04-28 10 17 03](https://cloud.githubusercontent.com/assets/979297/7361322/25039df2-ed91-11e4-898a-7fd6a34732ea.png)

I use that function with patched by myself from revive 3.1.0. 
So I want that you should keep that function when you develop new version.

Revive is very very good Advertiser Solution.
Thank you So much, it should be remained Open Source.

**Comment by erikgeurts** [comment]
Your screen shot is not about an HTML banner but an External banner. As the screen shot shows, the Destination URL filed works just fine with the External banner. Nothing has changed in that respect.

In an HTML banner, you can include the destination URL code in the HTML code field, using an ordinary A tag.

Have you perhaps misunderstood issue 89?

**Comment by iz4blue** [comment]
Oh, sorry about that. @erikgeurts are right.

I made that banner using HTML banner in the past.
When I checked source, I find it that removed. cause #89.

As @erikgeurts say, I will make banner using External banner.

Thank you, you reply. and have a nice day!
Thanks to the kindly description.

**Comment by iz4blue** [comment]
Sorry @erikgeurts about reopen.

1. This is a HTML banner.
```
<img src="data/file/master/990580575_I2qoM3bD_yamaha_1107_body.jpg" width="870" height="100" border="0">
```
![2015-04-28 6 44 43](https://cloud.githubusercontent.com/assets/979297/7366950/e577b81c-edd6-11e4-9528-a41773d32aea.png)


2. This is a External banner.
```
http://dvdprime.donga.com/g5/data/file/master/990580575_wxZ6Woc0_epson422_body.jpg
```
![2015-04-28 6 45 07](https://cloud.githubusercontent.com/assets/979297/7366957/fd2c5436-edd6-11e4-800c-9dde38e30a51.png)

1. Click trace area of HTML banner is HTML code space.
Something like all of table space or many images.

2. Click trace area of External banner is just one image.

It is different tracing of click count.
Another thing, can't use adding HTML parameters.

Thank you for reading.

**Comment by erikgeurts** [comment]
Please consider posting your support questions on the community forum at http://forum.revive-adserver.com/
