### ISSUE TITLE
0-timestamped stats on bucket tables

### ISSUE THREAD

**Issue by dynamicplus** [revive-adserver/revive-adserver#528]
on bucket tables (ox_data_bkt_*) i have plenty of "0000-00-00 00:00:00" counters
with ad_id=0 and zone_id=0 (and also with these values pointing to existent objects).

if this behaviour cannot be prevented it shoud be good that
maintenance implements a cleaning process.

**Comment by erikgeurts** [comment]
I have not been able to replicate this in any way. Can you please provide some more information or steps to reproduce?

**Comment by dynamicplus** [comment]
at this time i don't have the way to reproduce this.

at random i'm finding these rows, and weekly deleting them.

**Comment by erikgeurts** [comment]
I'm going to close this issue now, but feel free to add a response with additional information, and we'll gladly re-open it.
