### ISSUE TITLE
You don't have access to that page. You have been re-directed.

### ISSUE THREAD

**Issue by bastienvans** [revive-adserver/revive-adserver#530]
We've been using revive adserver for quite some time. We've been getting the follow message when adding a new banner.

"You don't have access to that page. You have been re-directed."

We've tried logging out/in. We've also upgraded to the new version and the issue still persists. Permissions are fine afaik.

Thanks

**Comment by erikgeurts** [comment]
Would you be able to describe step by step how to reproduce this? 

Please add as much detail as you can.

**Comment by bastienvans** [comment]
We're able to add new advertisers, new campaigns, but once we try to add a new banner we're getting this message and we get redirected to the advertisers' screen.

After clicking "Add new banner", if we choose any option from "Please choose the type of the banner", we get redirected to the advertisers' screen followed by the message: "You don't have access to that page. You have been re-directed."

We tried adding a new User and repeating the process. When we try to add a new advertiser, we get a successful confirmation then we get redirected to our main user's account, not the new one we just created.

**Comment by erikgeurts** [comment]
I'm unable to replicate this, and I also must have done this (adding a new banner) tens of thousands of times.

Would it be possible to record a screen capture and share that?

**Comment by bastienvans** [comment]
We were not having the issue for a very long time and the issue started happening about 2 days ago. I will try to record what is going on. Thanks

**Comment by mbeccati** [comment]
We can't replicate. In order for this to be considered a bug and not a setup problem on your side, you need to give us more information.

Please edit www/admin/banner-edit.php, specifically lines 66-75. Those `OA_Permission::enforce*` calls are the ones that could lead to the behaviour you're experiencing. Which one is "failing" for you?

**Comment by bastienvans** [comment]
I apologize but how does one check if any of those lines are failing?

**Comment by erikgeurts** [comment]
I would like to propose that we take this topic to the community forums at http://forum.revive-adserver.com until there is more clarity that this is really a bug.

**Comment by mbeccati** [comment]
@bastienvans I can't possibly know what is happening on your system. I'm afraid you need a developer to have a deeper look. The bug tracker itself is not the right place for this either, unless you have actual proof this is a bug in Revive Adserver and not something specifically wrong on your system.

I'm closing the issue again for now. Please reopen in case you have such proof.
