### ISSUE TITLE
Proposal to rename Delivery Limitations to Delivery Rules

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#538]
Over the past years, I've often had clients making remarks about the term "Delivery Limitation". The general feeling seems to be that this is a negative term, and people don't always appreciate that the feature gives them control rather than limiting them.

For this reason, I would like to propose that we rename them from "Delivery Limitations" to "Delivery Rules"

**Comment by andrewatfornax** [comment]
Discussed the approach in a team meeting today, and we will go with the approach of changing the language strings only, but add in some documentation to the developer guides about historical names (i.e. delivery limitations, ACLs, etc.)

**Comment by erikgeurts** [comment]
It seems that $GLOBALS['strEditChannelLimitations'] in the EN language file has not been changed, and perhaps a few related strings have been missed too.

**Comment by andrewatfornax** [comment]
Hi @erikgeurts - there were some cases where the strings had overlap between this ticket, and #539. 

The string was changed in https://github.com/revive-adserver/revive-adserver/commit/91382eb352b4837c3a854c11f78efbd105ea92ad#diff-1a5d5803e8a46ea8830a742e80a3f79aR1036.

**Comment by erikgeurts** [comment]
I didn't look at the patch, instead I noticed it when I was updating the NL translations last week.

More specifically, I felt that "Edit delivery options for the delivery rule set" should be "Edit delivery rules for the delivery rule set".

**Comment by andrewatfornax** [comment]
Hi @erikgeurts,

Yeah, that was one I looked at for a while, and wondered what the best way of describing it is.

The issue in the end was that it re-uses the "Delivery Options" tab that's used for Banners (where you have the option of setting both Delivery Rules and Delivery Capping), but for a Delivery Rule Set, the only "Delivery Options" that are valid are Delivery Rules.... but it's still the "Delivery Options" that are being set for the Delivery Rule Set.

If that makes sense?

**Comment by erikgeurts** [comment]
@andrewatfornax Makes sense, yes. It is hard for me to judge the outcome, since all I've seen are the language strings, not how those look in the UI.

Could you post a screenshot of the result for me to see?

**Comment by andrewatfornax** [comment]
@erikgeurts of course! I'm actually in the process of updating the user docs with new screenshots, so you can see this one here:

https://documentation.revive-adserver.com/display/DOCS/Delivery+Rule+Sets

**Comment by erikgeurts** [comment]
Thanks for that link. I had a look and it confirms what I felt was the confusing part.

Delivery options are the combination of delivery rules and frequency capping. But the delivery rule sets contain delivery rules only, not the frequency capping. As such I think the word "options" in this text:
![image](https://user-images.githubusercontent.com/5102461/28579299-8b6bec56-715c-11e7-8423-ba46be7383dc.png)
could be confusing.

**Comment by andrewatfornax** [comment]
Okay. Updated!
