### ISSUE TITLE
Proposal to rename Targeting Channels to Delivery Rule Sets

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#539]
In relation to the proposal in issue #538 for a name change from Delivery Limitations to Delivery Rules, I would also like to propose a name change for Targeting Channels.

I've found that people have all sorts of expectations about what Targeting Channels could be, mostly from features in other systems and ad servers that also use the word 'channel', but for entirely different things.

For this reason I would like to propose that we change the name "Targeting Channel" to "Delivery Rule Set", to make it clearer that this is a collection of one or more delivery rules that can be used and re-used and can also be easily edited to affect all banners that have this set applied to them.

**Comment by andrewatfornax** [comment]
@erikgeurts - What about "Delivery Limitations Set"? That keeps it consistent with "Delivery Limitations"?

I think we also have various places that say "ACLs", which I think is the same thing - that perhaps needs looking at too?

**Comment by erikgeurts** [comment]
I think this discussion should start at the base, which is #538. The rest will follow from that.

ACLs, if used in the UI, should also be addressed, because that's a very nerdy term that non-IT people won't understand.

**Comment by andrewatfornax** [comment]
Good point, agreed! I've brought #538 into the same milestone.
