### ISSUE TITLE
Local Mode, XML-RPC & Cache Busting Setting

### ISSUE THREAD

**Issue by andrewatfornax** [revive-adserver/revive-adserver#542]
The tag options for Local Mode & XML-RPC tags includes the "Insert Cache-Busting code" option. However, changing this option does not appear to affect the code generated (double check this!) and there is not an INSERT_RANDOM_NUMBER_HERE field in the generated tag.

Check that this is an incorrectly displayed option, and if so, remove the option from the tag generation pages for Local Mode & XML-RPC tags and update the user documentation.

**Comment by erikgeurts** [comment]
I would like to bring to the table that we have discussed deprecating local mode, and perhaps even xml-rpc invocation code. If so, it may not be necessary to spend too much time on this particular issue.

**Comment by andrewatfornax** [comment]
Oh yeah - it's not something to waste time on, but it should be a short job to confirm that the options don't work for these tags, and if that's true, remove the options from the UI. 

I'm not planning on adding the support into the tags if it's never existed - the tag support really only stays for now for BC, and should be dropped at an appropriate point in time.

**Comment by erikgeurts** [comment]
See also #87

**Comment by erikgeurts** [comment]
Once #87 and #1278 have been implemented, it may no longer be necessary to spend time on fixing this issue (as they've been removed by then).
