### ISSUE TITLE
Inline Video banners

### ISSUE THREAD

**Issue by sevenseven** [revive-adserver/revive-adserver#543]
Hi team:
  I want use the Inline Video banners, but I can'n find the guide help me, 

this is the node
" Note:	Zone invocation codes are not used for Video Ads. 
Instead, you must include the zone in the Ad Schedule of the video player plugin configuration in your webpage. 
Please refer to the Video Ads Plugin User Guide for instructions."

and I go to the ''Video Ads Plugin User Guide", it says the page is not find.

anyone can tell me  how to do it ,
thanks,

best wish

**Comment by erikgeurts** [comment]
Please consider posting your support question on the community forums at http://forum.revive-adserver.com
