### ISSUE TITLE
Video ads plugin links to a documentation page that no longer exists

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#544]
See #543

**Comment by tlehtimaki** [comment]
Would it be possible eg. for me, to create this page?

**Comment by erikgeurts** [comment]
The problem is not the page itself, the problem is that the plugin doesn't link to it.

**Comment by sevenseven** [comment]
Do you find the eg.?

**Comment by andrewatfornax** [comment]
Need to update the link that is:

https://documentation.revive-adserver.com/display/DOCS/Invocation+code:+Zone+level#Invocationcode:Zonelevel-Video

to

https://documentation.revive-adserver.com/display/DOCS/Invocation+code:+Zone+level#InvocationCode:ZoneLevel-VideoInvocationcodeforInlineVideoadzoneorOverlayVideoadzone
