### ISSUE TITLE
Adsense Detection not working

### ISSUE THREAD

**Issue by lludwig** [revive-adserver/revive-adserver#546]
I believe this is a legit issue as this occurred with the previous version. I have made sure I have the latest version of all plugins.

When a create a Google AdSense banner and select 
"Alter HTML to enable click tracking for:" to "Google AdSense"

I get this error message when I click the "Save changes" button

MESSAGE: Invalid argument supplied for foreach()
TYPE: Warning
FILE: /home/ads/domains/ads.example.com/public_html/plugins/3rdPartyServers/ox3rdPartyServers/google.class.php
LINE: 54
DEBUG INFO:

49	$new_buffer = "". 
50	"

I don't get this issue if I select "Do not alter HTML" when clicking save.

3rd Party Servers Plugin is 1.2.1

**Comment by erikgeurts** [comment]
I've removed your domain from the code snippet you entered.

**Comment by erikgeurts** [comment]
see #565
