### ISSUE TITLE
www/delivery/spc.php generates divs with same id for SWF banners

### ISSUE THREAD

**Issue by domus71** [revive-adserver/revive-adserver#556]
www/delivery/spc.php generates divs with same id. When there are more than one zones in the same page (OA_show), the flashobject replace the first div with the given id.

Solution
At line 3335:
$rnd = md5(microtime());
replace with:
$rnd = md5(microtime()* rand(1,1000));

The system that I use is Windows 2008R2, Revive Adserver v3.2.0 running on Microsoft-IIS 7.5, PHP 5.4.40 and MySQL 5.1.73

**Comment by domus71** [comment]
The original script result:
http://adworks.pixelworks.gr/www/delivery/spc-original.php?zones=1%7C2%7C3%7C4%7C5%7C6%7C7%7C8%7C14%7C15%7C11%7C12%7C13%7C16%7C31%7C32%7C33%7C34&source=&r=66422468&charset=ISO-8859-7&loc=http%3A//www.farmakeutikoskosmos.gr/katanalotis

The corrected script result:
http://adworks.pixelworks.gr/www/delivery/spc.php?zones=1%7C2%7C3%7C4%7C5%7C6%7C7%7C8%7C14%7C15%7C11%7C12%7C13%7C16%7C31%7C32%7C33%7C34&source=&r=66422468&charset=ISO-8859-7&loc=http%3A//www.farmakeutikoskosmos.gr/katanalotis

**Comment by mbeccati** [comment]
The bug is specific to some Windows machines and some PHP versions, but worth to fix anyway: microtime is not supposed to be used to generate unique identifiers.
