### ISSUE TITLE
Random ad display not working correctly

### ISSUE THREAD

**Issue by wimlmg** [revive-adserver/revive-adserver#561]
Been doing some testing, finally, and I found that the random ad display does not work as expected.
I have been trying about 300 refreshes now, with 4 ads, each at 25%, and in literally 19 out of 20 cases I get the same ad, number 2, occasionally number 1, and occasionally number 3. In 300 refreshes ad 4 never got displayed once.

Obviously it may still be a random display, but statistically this is not all that likely after 300 refreshes.

Kind regards, Wim

**Comment by erikgeurts** [comment]
It is true that the actual distribution may not be exactly 25% for each banner, but in my personal experience it is always extremely close.

There may be some other reason what is causing this for you. Have you ensured that all 4 banners have a 25% probability in the zone being used for your experiment?

**Comment by wimlmg** [comment]
Yes, I have - these are my own ads, and I have given them all the same priority and probability.

Kind regards, Wim

**Comment by andrewatfornax** [comment]
Any targeting or limitations in place? What does the zone probability tab look like, please (can you post a screenshot?).

**Comment by andrewatfornax** [comment]
No feedback, closing (cannot reproduce).
