### ISSUE TITLE
GIF and Flash banners are wrapped in an iFrame

### ISSUE THREAD

**Issue by martinkrcho** [revive-adserver/revive-adserver#562]
I noticed that all my GIF banners are wrapped in an IFRAME in Revive 3.2.0. Is this intentional? Could this be optional?

I have a wrapper around the banner that handles positioning and some styling. The styling is not applied correctly when the banner is placed within an iframe. I think the iframe wrapper should be optional (configurable) or the "BEFORE" and "AFTER" banner HTML code should be around the iframe itself.

Anyone else experiencing this? Any ideas?
![capture](https://cloud.githubusercontent.com/assets/1962663/7766584/7c06823e-0062-11e5-8d63-5033233089e6.PNG)

**Comment by martinkrcho** [comment]
The same thing happens with Flash banners. All my positioning is completely wrong. I am also getting a JS error "FlashObject does not exist".

**Comment by martinkrcho** [comment]
I just thought about something - shouldn't the IFRAME be wrapped in the "before" and "after" HTML code for iframe-friendly banners?

What about the JS error? Should I raise another issue?

**Comment by mbeccati** [comment]
@martinkrcho first of all, thanks about the report.

"Prepend" and "Append" are a bit controversial. I would agree with you, but technically they are rendered together with the banner code, so the async delivery script cannot tell the difference. Also my personal opinion is that they should be only (and sparingly) used for additional trackers, not really for styling.

The JS error with Flash banners should have been solved in #529.

**Comment by martinkrcho** [comment]
@mbeccati, don't mention it :) I am glad there are people working on this. I know how tedious it can be to make something bug-free and make everybody happy :laughing:

I am using the before/after for styling because sometimes there are no campaigns/banners and I don't want to end up with an empty white box on my site. I hope that makes sense. I am happy if all the old zones are non-iframe friendly. BTW, is there a way to choose this setting for a new zone?

**Comment by mbeccati** [comment]
it's actually a banner setting and can be onyl set for HTML banners. It defaults to yes as it's the safest bet: if a 3rd patry JS tag uses document.write, it would wipe the entire website out.
