### ISSUE TITLE
Remove AdSense / Yahoo 3rd party click tracking

### ISSUE THREAD

**Issue by mbeccati** [revive-adserver/revive-adserver#565]
I suspect that over the years the Google AdSense code has changed quite a bit and the hacks we used back in the days to track clicks might not be working anymore.

Since @erikgeurts confirmed they don't work anymore, we should probably remove the option altogether.

**Comment by erikgeurts** [comment]
Nowadays, AdSense offers two different types of ad tags, asynchronous and synchronous. The async version is displayed as the default. I'll test both and see if a click on an AdSense tag when displayed through Revive Adserver onto a site is counted in Revive Adserver itself. More about this later.

**Comment by erikgeurts** [comment]
First finding: the asynchronous tag provided by AdSense, when delivered onto a webpage of a real website, works and displays ads just fine, but a click on such ads is not recognized (and thus not counted) by Revive Adserver.

**Comment by erikgeurts** [comment]
New finding: Revive Adserver did not recognize a click on a synchronous AdSense tag either.

This finding and the previous one were both from a website using single page call invocation code.

**Comment by erikgeurts** [comment]
I haven't had time yet to validate the above finding if the ads are being delivered via async tags or regular javascript tags. I think it is unlikely, however, that there will be any difference. If anyone else has different findings, please add a comment to this issue.

**Comment by magicmulder** [comment]
If I'm not talking about something different, injection of the click URL can be achieved by injecting
.setClickUrl("{clickurl}")
into the banner:

<script src="https://www.googletagservices.com/tag/js/gpt.js">
googletag.pubads().definePassback("********", [300, 250]).setTargeting("****", "*******").setClickUrl("{clickurl}").display();
</script>

The asynchronous version should have a part looking like this:
 googletag.cmd.push(function() {
      googletag.defineSlot('*****'+Ads_BA_ADIDsection, [[300, 250]],'Ads_BA_CAD')
        .addService(googletag.pubads())
 .setTargeting("****", "*****");
      googletag.enableServices();
      googletag.display('Ads_BA_CAD');
  });

and again just injecting .setClickUrl("{clickurl}") does the trick:

 googletag.cmd.push(function() {
      googletag.defineSlot('*****'+Ads_BA_ADIDsection, [[300, 250]],'Ads_BA_CAD')
        .addService(googletag.pubads())
 .setTargeting("****", "*****").setClickUrl("{clickurl}");
      googletag.enableServices();
      googletag.display('Ads_BA_CAD');
  });

**Comment by erikgeurts** [comment]
Google change their tags frequently, in unexpected ways, and without notice. It is likely that whatever is fixed today will just break tomorrow.
