### ISSUE TITLE
Misleading warning about companion positioning

### ISSUE THREAD

**Issue by 9500** [revive-adserver/revive-adserver#567]
In the newly introduced help box of the Companion positioning there is a warning message concerning the "Display only one banner from this advertiser on a web page" checkbox setting:

'Warning! Before use this, check the Inventory › Advertisers menu › Miscellaneous: "Display only one banner from this advertiser on a web page" checkbox setting!'

To check the checkbox setting means to select it or turn it on. As the checkbox should be unchecked or turned off or unselected, I propose something like this:

Warning! Before using Companion positioning, verify that the Inventory › Advertisers menu › Miscellaneous: "Display only one banner from this advertiser on a web page" checkbox setting is not selected!

Or am I missing something, and the checkbox should really be turned on (it makes no sense to me)?

**Comment by mbeccati** [comment]
Labeled as "Translation" as it's a matter of changing the wording.

**Comment by andrewatfornax** [comment]
Thanks, I will put this on my list to think about and aim to correct (if required, I need to think it through) in 3.2.2.

**Comment by mbeccati** [comment]
I'm sorry, I see no reference to the text you quote: @9500 could you please clarify?

**Comment by erikgeurts** [comment]
> Or am I missing something, and the checkbox should really be turned on (it makes no sense to me)?

I think the confusion is about 'check' as in "review" vs 'check' as in "turn on".

However, like @mbeccati I have not been able to find this text anywhere in the code or language files.

@9500 Can you please post a screenshot of this message as displayed in your browser.

**Comment by mbeccati** [comment]
I believe the text comes from a mod, or something. Closing because of no feedback.

**Comment by erikgeurts** [comment]
Good call. Also removing it from the 4.2.0 milestone, to avoid confusion later.

**Comment by andrewatfornax** [comment]
Ah, thanks @erikgeurts and @mbeccati - was on my list to look into, but I see you've already tracked this down as an issue that has (probably) come from a 3rd party mod.

In addition to it being closed and removed from 4.2.0, I've also marked the issue as invalid.
