### ISSUE TITLE
Banner with 100% probability doesn't render

### ISSUE THREAD

**Issue by martinkrcho** [revive-adserver/revive-adserver#569]
I have a zone in single banner in it with 100% probability. Despite this the banner doesn't show. I have seen this behavior in previous version as well, but it was pretty random.

I already tried all the obvious - clear cache, recalculate all the probabilities, checked campaign and banner setting...

Has anyone seen this issue on their Revive instance?

**Comment by mbeccati** [comment]
@martinkrcho no frequency capping, no limitation, no blocking, etc? What campaign type?

**Comment by mbeccati** [comment]
@martinkrcho also, this kind of questions are more suited to our forums. We try to use github issues exclusively for bug reports / tasks ;)

**Comment by martinkrcho** [comment]
Nope, none of the above. The campaign type is "Remnant".

![banner delivery options](https://cloud.githubusercontent.com/assets/1962663/7861698/97add3c0-0549-11e5-809b-32f47326c998.png)
![campaign](https://cloud.githubusercontent.com/assets/1962663/7861696/97ab1644-0549-11e5-8b09-21671121354f.png)
![zone probability](https://cloud.githubusercontent.com/assets/1962663/7861697/97ac4078-0549-11e5-8c61-658920b650c9.png)

**Comment by erikgeurts** [comment]
As per Matteo's suggestion, I'd like to mention that this topic is better suited to be handled on the community forums at http://forum.revive-adserver.com.

**Comment by martinkrcho** [comment]
All right, I will. I think this is a bug, however.

**Comment by erikgeurts** [comment]
If it is a bug, we will be more than happy to pick it up again here.

**Comment by martinkrcho** [comment]
Cool :)
