### ISSUE TITLE
Campaign end date before start date without warning upon save

### ISSUE THREAD

**Issue by dynamicplus** [revive-adserver/revive-adserver#570]
Under campaign editor if you set end date before start date
you can still save this setting.

this should not happen or at least an alert should be raised.

**Comment by erikgeurts** [comment]
Which version of Revive Adserver are you using?
Can you post a screen shot from just before you click "save changes"?

**Comment by mbeccati** [comment]
I cannot replicate the issue. Please try to upgrade to 3.2.1. I will re-open if necessary.

**Comment by mbeccati** [comment]
![fireshot screen capture 171 - revive adserver - aggiungi nuova campagna - revive_t3600_hq_beccati_com_www_admin_campaign-edit_php_clientid 10](https://cloud.githubusercontent.com/assets/282388/8018850/124fa922-0c30-11e5-9257-015f94a41051.png)
