### ISSUE TITLE
Not work delivery limitation "Site Channel" for banners & rules for Tracking Channels

### ISSUE THREAD

**Issue by s1l3nt** [revive-adserver/revive-adserver#572]
Hello! Apply changes from commits #549, #564 not resolved problems with Tracking Channels delivery options. Can't add tracking channel to banner & can't add delivery options for tracking channel.

![screen shot 2015-06-01 at 18 56 16](https://cloud.githubusercontent.com/assets/1584818/7917180/08663860-0891-11e5-89a5-a036f73169de.png)

**Comment by mbeccati** [comment]
I cannot replicate the issue. Please try to upgrade to 3.2.1. I will re-open if necessary.
