### ISSUE TITLE
JavaScript error in IE11: Object doesn't support property or method 'keys'

### ISSUE THREAD

**Issue by martinkrcho** [revive-adserver/revive-adserver#577]
I am getting the following error when using IE11:
Object doesn't support property or method 'keys'

This is coming from the asyncjs.php script.

Revive version: 3.2.0

**Comment by mbeccati** [comment]
@martinkrcho IE11 was tested and it was working ok. Do you have a test page where we can see the error?

**Comment by martinkrcho** [comment]
@mbeccati, have a look on my site here: https://www.mojandroid.sk/

**Comment by mbeccati** [comment]
@martinkrcho Tried IE11. No error here, sorry.

**Comment by martinkrcho** [comment]
That is weird, can you compare the version number with the one below?
![capture2](https://cloud.githubusercontent.com/assets/1962663/8184005/d4d10aa8-1433-11e5-82dd-46a145bb7d9e.PNG)

**Comment by mbeccati** [comment]
11.0.19 here

**Comment by martinkrcho** [comment]
The error is gone now, but I haven't changed anything on the site. Apologies for wasting your time. I'll keep an eye on it.
