### ISSUE TITLE
Ad will not show up on first page load

### ISSUE THREAD

**Issue by nathanoj** [revive-adserver/revive-adserver#578]
To reproduce this issue: 
 - go to: handbrewed.com/ad.php in an incognito browser (or visit this page for the first time) and you will see a blank page. 
 - reload the page - the ad shows up!
 - close the incognito browser window
 - go to handbrewed.com/ad.php again - no ad!

The ad _never_ shows on the first page load, but shows on _every_ subsequent page load. I cannot get the ad to show up when first loading the page, no matter what I seem to change in the ad server.

Why would the ad not load the first time but then load on every subsequent page refresh? I have tried changing a bunch of stuff in the campaign/banner but nothing seems to work.

Thank you,
Jonathan

**Comment by mbeccati** [comment]
Not a bug. The first time a "fresh" browser shows up, Revive doesn't know if it can accept cookies, so it won't serve ads that use frequency capping. But it will do at the next request. It's basically a safety measure to avoid mistakenly overdeliveing capped ads with cookies disabled.

**Comment by nathanoj** [comment]
Thanks for getting back to me. 

I don't understand your phrase 'ads that use frequency capping', especially when I had originally set up the ad to have NO limit on impressions when I originally found the issue. Where do I set 'frequency capping' if not with 'unlimited impressions'?

To be clear, I had originally set up the ad as a 'remnant' with unlimited impressions when I discovered the issue. I then changed it to 'contract' which required that I set a limit on impressions, so I set that to 10k. That, as you say, a 'contract' ad makes sense that it won't show the ad on first page load, but neither did a 'remnant' with unlimited impressions. In what way can I set up an ad so it shows up on the first page load?

Thank you,
Jonathan

**Comment by mbeccati** [comment]
Frequency capping doesn't have anything to do with remnants, contracts, etc. It's the "Limit banner views" and similar functionality, i.e.

![fireshot screen capture 178 - revive adserver - banner - revive_t3600_hq_beccati_com_www_admin_banner-acl_php_clientid 187847 campaignid 243226 bannerid 244201](https://cloud.githubusercontent.com/assets/282388/8119237/5f18b2a4-1094-11e5-9ab8-7bd334dd8b33.png)

**Comment by nathanoj** [comment]
I have done nothing with that. I have no capping set. Sorry, I'm confused. The 'delivery capping per visitor' for the ad I have set up looks exactly like the image you posted. ... if there's nothing in those fields, why would ads deliveries be capped? Again, how do I get the ad to show up on first page load? It seems to me if I had put in some numbers in the fields that you posted an image of, I would be experiencing what you had explained will happen with 'capping', but I haven't set any caps. What am I missing?

**Comment by mbeccati** [comment]
Please double check. You have frequency capping set at the zone level.

**Comment by nathanoj** [comment]
The zone was capped, but now I've changed it, but it still doesn't work. Also, it does not show a dash '-' in the 'limit campaign views to' inputs after I update the zone page, instead it shows '0'. I cannot change it from a zero, but that should probably work? So far, it has not.

![revive-screen-zone](https://cloud.githubusercontent.com/assets/244052/8119755/a229c290-105d-11e5-9a5f-c407538f5327.png)

**Comment by nathanoj** [comment]
OK, it's now working. I guess it was the server cache that had not yet updated. Thank you so much for your help! I really appreciate it!

Jonathan

**Comment by erikgeurts** [comment]
@nathanoj  I would like to add that this type of issue is more suited for the community forums at http://forum.revive-adserver.com

**Comment by nathanoj** [comment]
Thank you Erik. I agree, but unfortunately I went to your documentation
first, where I found nothing about capping in 'zones' which may be why I
missed it. Next time I run into a situation where things seem to be poorly
documented, I'll use the forum before I report a bug.

http://documentation.revive-adserver.com/display/DOCS/Editing+a+zone
http://documentation.revive-adserver.com/dosearchsite.action?queryString=capping

Thanks again,
Jonathan

On Fri, Jun 12, 2015 at 12:34 AM, Erik Geurts <notifications@github.com>
wrote:

> @nathanoj <https://github.com/nathanoj> I would like to add that this
> type of issue is more suited for the community forums at
> http://forum.revive-adserver.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/revive-adserver/revive-adserver/issues/578#issuecomment-111365976>
> .
>



-- 

Hand Brewed, LLC
M. 213.804.2421

www.handbrewed.com

**Comment by markxxx123** [comment]
how to set refresh rate for banner,I want every minute to change the banner on the page,

**Comment by erikgeurts** [comment]
Please post your support questions at the community forums at http://forum.revive-adserver.com
