### ISSUE TITLE
Do not display banner with SWF and GIF (version 3.2.1)

### ISSUE THREAD

**Issue by joomla-ua** [revive-adserver/revive-adserver#579]
If disable Flash plugin or use Android browser all banner with SWF and GIF/JPG/PNG do not display in the page.

**Comment by mbeccati** [comment]
I'm sorry, I can't replicate the issue. I've also tested w/ Safari on iOS and I always get the backup gif file. Please try our [forums](http://forum.revive-adserver.com/) to see if someone can help investigate what your issue actually is.

If you've upgraded from an earlier version, did you also copy your images over?

Closing the issue, for now. Please reopen if you find out it's a reproductible bug.

**Comment by joomla-ua** [comment]
I'm upgrade from v 3.0.5. 
1. Copy to 'old' folder this version
2. Upload and unzip reveve-adserver and copy to new version congiguration file and folder 'images'
3. Copy DB and upgrade to 3.2.1

If disable Flash replace image fpr banner not display but showing only banners with single image (jpg/ong/gif).

**Comment by mbeccati** [comment]
@joomla-ua could you pls set up a demo page?

**Comment by erikgeurts** [comment]
@joomla-ua Just so we're sure about it: are you talking about the display of the previews of Flash banners inside the Revive Adserver user interface? Or is this about the actual delivery of Flash banners on webpages?
