### ISSUE TITLE
Problem with long list

### ISSUE THREAD

**Issue by karen-mikaela** [revive-adserver/revive-adserver#581]
Problem with long list like campaigns  and probability zone for campaigns. A paginator for the long list would be an improvement for these screens.
My pull request is in #576. Any advice for that problem?
Tks.

**Comment by erikgeurts** [comment]
We've seen that pull request, thanks for your contribution. It will be reviewed in due course.

**Comment by erikgeurts** [comment]
Closing this issue now, but don't worry, the pull request will be reviewed in the future.
