### ISSUE TITLE
Customizing delivery path does not work with asynchronous js tag code

### ISSUE THREAD

**Issue by clabinsky** [revive-adserver/revive-adserver#582]
Whenever I change the delivery path from default /www/delivery to something else like /www/mydeliverypath, no banners will be delivered any further (I tried only html banners though). 

The other (synchronous) Javascript-Tag still works though.

**Comment by mbeccati** [comment]
If the delivery path has changed, you should generate new tags, as the "revive-id" hash won't be the same anymore.

**Comment by clabinsky** [comment]
Problem solved. Thanks!
