### ISSUE TITLE
Iframe sometimes doesn't load

### ISSUE THREAD

**Issue by stenas** [revive-adserver/revive-adserver#584]
Hello my banners sometimes don't loaded.

I'm use a iframe to implement the banner

this is my code banner:
<iframe id='ad55000c' name='ad55000c' src='http://example.com/www/delivery/afr.php?zoneid=111&amp;cb=<?= uniqid()?>' frameborder='0' scrolling='no' width='300' height='250'><a href='http://example.com/www/delivery/ck.php?n=a767147b&amp;cb=<?= uniqid()?>' target='_blank'><img src='http://example.com/www/delivery/avw.php?zoneid=111&amp;cb=<?= uniqid()?>&amp;n=a767147b' border='0' alt='' /></a></iframe>

when dont load iframe the code this is:
<div style="position: absolute; left: 0px; top: 0px; visibility: hidden;" id="beacon_aa3ff957c4"><img width="0" height="0" style="width: 0px; height: 0px;" alt="" src="http://example.com/www/delivery/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=32&amp;loc=http%3A%2F%example.com%2F%3Fgoto%3Dofferwall&amp;cb=aa3ff957c4"></div>

Any ideia why iframe dont load?

Link, make some F5 on browser
{link removed}

Thanks

**Comment by erikgeurts** [comment]
I would like to recommend that you post your question on our community forum at http://forum.revive-adserver.com

**Comment by stenas** [comment]
MOve to http://forum.revive-adserver.com/topic/1775-iframe-sometimes-doesnt-load/
