### ISSUE TITLE
Async tags cause JS errors on IE8

### ISSUE THREAD

**Issue by ratedam** [revive-adserver/revive-adserver#585]
Hello,

After using a  Asynchronous JS Tag in IE i get the following error

SCRIPT5007: It's not possible to obtain the property "appendChild" from a not defined or null reference.

Here is the line in question:

c.appendChild(b);

Appreciating your support,

ratedam.

**Comment by mbeccati** [comment]
@ratedam could you please provide a page that shows the issue and a few more details, like the IE version you're using?

**Comment by ratedam** [comment]
Hello,

This is the website http://saldopositivo.cgd.pt/ . It happens when you are in IE8 or in IE11 with compatibility to IE8.

Any help? Thank you.

**Comment by ratedam** [comment]
UPDATE

 I'm also getting the following error:

SCRIPT438: The object doesn't support the property or method 'keys'
file asyncjs.php, Line: 1, Column: 126

Thank you.

**Comment by mbeccati** [comment]
I'm sorry, IE8 was not a target when developing async tags. That said, I was expecting a graceful failure (no ads displayed), rather than errors.

**Comment by mbeccati** [comment]
I don't have access to any legacy system. Any help in fixing the errors (or hiding at least) would be very appreciated.

**Comment by erikgeurts** [comment]
As far as I recall, IE8 works on Windows XP only. Windows XP however is no longer supported.

**Comment by ratedam** [comment]
You can try compatibility mode in IE11 to IE8

**Comment by erikgeurts** [comment]
I don't see how that's relevant. If IE8 is not being used anymore because it's formally deprecated, then why would we want to support it?

**Comment by ratedam** [comment]
Hello,

That fix was meant to not show the error only? Cuz the problem still persists, the ads do not show up.

Thank you

**Comment by mbeccati** [comment]
@ratedam Precisely. Ad delivery should not cause JS errors. Other than that I'm afraid that I'm not going to spend my time on IE8 compatibility, sorry.

If you or other can come up with a pull request that fixes it, you're more than welcome.

**Comment by andrewatfornax** [comment]
@mbeccati - I've updated the version for this ticket, as I think it's coming out in 3.3.0, rather than the already released 3.2.2.
