### ISSUE TITLE
Can't install with Error "You need to enable cookies before you can use Revive Adserver " 

### ISSUE THREAD

**Issue by bumbumndb** [revive-adserver/revive-adserver#587]
![capture](https://cloud.githubusercontent.com/assets/5414968/8299423/704ec9d4-19a2-11e5-83b1-80982f89cb40.JPG)

I have problem when I setup revivead on my computer. 
I get this message " You need to enable cookies before you can use Revive Adserver " , but I checked my browser "it's not disable cookie" . I had to try other browser and I get same result . 

I use verison 3.2.0 

Pls, help me to find out.

Thanks .

**Comment by erikgeurts** [comment]
Please post your support topics on our community forums at http://forum.revive-adserver.com/
