### ISSUE TITLE
Deprecate Direct Selection?

### ISSUE THREAD

**Issue by andrewatfornax** [revive-adserver/revive-adserver#588]
Should we deprecate Direct Selection?

**Comment by goldentuna** [comment]
Absolutely not!! We must keep Direct Selection for our Ad Distribution. Thanks!

**Comment by mbeccati** [comment]
@goldentuna would you mind to elaborate? What is exacly the reason that prevents you to use other delivery methods?

**Comment by andreaskoepke** [comment]
I use the direct selection for a HTML email newsletter. I built a calendar based scheduling system into our own newsletter management site. This allows the admin person to select which editions of the newsletter get what adverts. The code which generates the HTML email uses direct selection and local invocation to get the code to insert into the newsletter.

**Comment by lsmonki** [comment]
Not all people are using Revive to show the ads in his own pages.

We use Direct Selection to send the banner tags to other (external) pages and track campaign data on our own server.

Is there another way to do this without Direct Selection?

**Comment by lsmonki** [comment]
Or any other way to select banners by keywords?

**Comment by lsmonki** [comment]
And to be clear, we do not manage the external website ads or inventory, only specific campaigns for clients on different webpages, is not an option to generate a new adzone for every combination of banner size/campaign, this could be thousands of adzones

**Comment by lsmonki** [comment]
Other scenario, this one is used in a news site we manage to show banners by the article category or some special features in this article (tags, for example). Here we use keywords with "Selection Paths" and logical operators to select the banner that fits better.

In this case the adserver tag is generated by our own software, but revive needs to support it to work.

**Comment by lparikka** [comment]
Don't remove direct selection. 

We use keywords for selecting newsletter banners in a predefined order and for the correct newsletters. The newsletter may have 10-20 banners and it is not very convenient to create and manage 20 zones for banners.

**Comment by andrewatfornax** [comment]
Looks like there's enough people that care about it. I'll close this ticket - and keep in mind that I need to document direct selection in the user docs ASAP. :-)

**Comment by erikgeurts** [comment]
I would suggest to spend very little time on documenting something like this. There are better uses for your precious time.
