### ISSUE TITLE
Strangely high number of clicks and adds

### ISSUE THREAD

**Issue by GeomaresPublishing** [revive-adserver/revive-adserver#589]
Since a month or 2, our banners show an immense high number of clicks compared to the previous months. One campaign went from a CTR of 1.1% to more than 5%. Off course it would be nice if these statistics were real, but we have some doubts about it. Our IT-department can't find anything strange, but we suspect that there's something wrong with these numbers. Can somebody help us with this?

Kind regards,
Erik Wielink
Geomares Publishing

**Comment by erikgeurts** [comment]
Please consider posting your question on our community forums at http://forum.revive-adserver.com.
