### ISSUE TITLE
Cannot add new advertisers

### ISSUE THREAD

**Issue by JanieeDee** [revive-adserver/revive-adserver#591]
Hi

I cannot add banners to campaigns so basically cannot add any new advertisers, although the adverts already in the program are working, although my stats aren't working.  I'm not running the current version and can't find a version number anywhere.  The site recently moved from one server to another and this problem probably existed then, although I only recently noticed it.  Would installing the new version stop the problem and would it cause problems to the site if I did this?

**Comment by erikgeurts** [comment]
Please consider posting your support topic on our community forums at http://forum.revive-adserver.com

**Comment by JanieeDee** [comment]
Thank you, I wasn't sure what to do, but was sent this link by openx.  I will go there now.

Sorry

**Comment by erikgeurts** [comment]
Revive Adserver is the official successor of OpenX Source. The new project has been around since September 2013. One would think OpenX (the company) knows by now, especially since they announced this themselves on their site back in the day: http://openx.com/press-releases/openx-sells-open-source-ad-serving-product/ linking to www.revive-adserver.com

**Comment by JanieeDee** [comment]
I received an email from them last night which included:

"Please note that OpenX recently sold its open source ad serving product, "OpenX Source", to Revive Adserver.  Given that transition, we recommend you contact the Revive Adserver team to address any support inquiries you may have with their product.

Please direct all future questions to their support channel at:
https://github.com/revive-adserver/revive-adserver/issues?state=open"

Sorry again.

**Comment by erikgeurts** [comment]
You're not to blame, don't worry! It's clear they sent you to the wrong place. All support options are described here: http://www.revive-adserver.com/support/

**Comment by JanieeDee** [comment]
Thanks, I hope I'm in the right place now :)
