### ISSUE TITLE
Same-day contract campaign under-delivery

### ISSUE THREAD

**Issue by gmon** [revive-adserver/revive-adserver#596]
We are having problem completing requested impression for contract campaign on Revive Adserver 3.2.1 

The campaign runs on 3 zones each one with 1.000.000 impressions (3 millions in total) but campaigns never reach the requested impressions (between 300.000 and 600.000) even with 40% of over delivery.

It seems to be a bug. 

Thanks,

Guido

**Comment by erikgeurts** [comment]
I've created this type of campaign scenario many times and it always worked fine for me. I don't rule out there is a bug, but it's unlikely. I would like to suggest this topic to be discussed on the community forums at http://forum.revive-adserver.com first. We can re-open this issue when more evidence emerges there is an actual bug.
