### ISSUE TITLE
HTML Banner - Banner code 64K limit is too small

### ISSUE THREAD

**Issue by songpr** [revive-adserver/revive-adserver#604]
HTML Banner has limit size at 64K since it stored in mysql text field.

With animation it's easily exceed the limit. could you please increase the size to ~500K

My quick fix solution is just change type of html field to be mediumtext
![11865273_1057115867634969_2094080445_o](https://cloud.githubusercontent.com/assets/3700356/9138583/f4d73356-3d4e-11e5-9361-527f83ff72bc.jpg)

![image](https://cloud.githubusercontent.com/assets/3700356/9138480/6068430e-3d4e-11e5-8c35-d0ec1962afbf.png)

**Comment by erikgeurts** [comment]
In my personal opinion, an banner that is 500K or larger is too large. If I were a publisher, I would not accept such sizes, it harms the site visitor's experience.

**Comment by songpr** [comment]
How about 150K? My point is 64K is too low, so I recommend to increase it.

Normally, html will serve in compressed form so 150k will be just about 20K - 30K.

About point, we would like to limits risk of link to external js files so every scripts and CSS are in html only so 64K is too small for animation in html banners.

**Comment by erikgeurts** [comment]
Changing a core database table is never a good idea, it may result in not being able to upgrade in the future.

See #95 and #408

**Comment by mbeccati** [comment]
I agree, with html5 banners gaining traction, 64kb are potentially limiting.

**Comment by songpr** [comment]
I recommend yo schedule this ASAP.

google announce that flash ads will autopause on chrome from 1st September 2015 
https://plus.google.com/+GoogleAds/posts/2PmwKinJ7nj

**Comment by songpr** [comment]
Another case that need increasing size is convert flash banner to html5 via swiffy https://developers.google.com/swiffy/convert/upload.

It will be much larger than 64K

**Comment by rpijlman** [comment]
Advertisers are replacing Flash ads with HTML5 ads, and indeed many use Swiffy. The converted ads easily exceed 64K.

Also, when an add is larger than this limit, Revive doesn't complain and simply stores it, apparently truncating the banner's code. Then I get Javascript syntax errors, leading to blank pages in Revive's banner properties/edit page. This is confusing and it took me a while to figure out what caused it. And of course, a truncated banner doesn't display correctly on web pages.

**Comment by rpijlman** [comment]
A workaround is to put the huge 'swiffyobject =' statement generated by Swiffy in an external Javascript file. This reduces the HTML5 code that goes into #Revive to <1KB. Implies manually editing every oversized HTML5 banner and uploading a .js file.

**Comment by nstojanoski** [comment]
With phpmyadmin I've changed htmltemplate and htmlcache from TEXT to MEDIUMTEXT using openx 2.9.something. I've made few updates from that time and using latest 3.2.1 at this time.I don't have any problems loading swiffy banners. 

TEXT is 64KB and the default that revive use, MEDIUMTEXT is 16MB

**Comment by thekuzia** [comment]
@nstojanoski, Thanks! That's good idea!

**Comment by songpr** [comment]
@nstojanoski That's good news, so there will be no issue after upgrade

**Comment by petrmifek** [comment]
Potentially the TEXT to MEDIUMTEXT change is quite taxing on installations with sql banner cache and replication. MySQL binlogs are potentially huge after populating these banners.

**Comment by emmmlee** [comment]
@rpijlman, I tried using your method for Swiff Banner in ReviveAdServer, unfortunately it doesn't work for me. I checked the external host js file, path is correct.

I have the js upload to my server and serve runtim.js via gstatic.com.


    <div id="swiffycontainer" style="width: 300px; height: 250px"></div> 
    <script>
      var stage = new swiffy.Stage(document.getElementById('swiffycontainer'),
          swiffyobject, {});
      stage.setFlashVars("clickTag=http://www.google.com" target="_blank";);
      stage.start();
    </script>

I only see a blank space in the Banner Property.

**Comment by rpijlman** [comment]
@emmmlee I see a spurious semicolon right before the close bracket in your code: target="_blank";);.

I use the code:  stage.setFlashVars("clickTAG={clickurl}");

Otherwise, the error may be in your <script> tag.

**Comment by rpijlman** [comment]
... script tag (was removed by github).

**Comment by emmmlee** [comment]
@rpijlman Thanks but unfortunately it didn't work for me. :(
Guess I have to change the banner size instead.

**Comment by songpr** [comment]
Recently, I have upgraded to 3.2.2, and there is no issue with change type of the fields to MEDIUMTEXT.

Note: I follow the upgrade guide document

**Comment by andrewatfornax** [comment]
@mbeccati - What do you think? Do we just go ahead and change the tables to use MEDIUMTEXT as of 3.3.0, or is this something that is better left for better integration with various HTML5 banner tools?
