### ISSUE TITLE
delivery of banners issues

### ISSUE THREAD

**Issue by mango1970** [revive-adserver/revive-adserver#605]
Hi all is there any bug in relation to banners being delivered using url?
Example a banner that I add using a image+ =URL gets permissions errors and the ones I add with a code example adsense all works perfectly no issues.

Regards

**Comment by erikgeurts** [comment]
Please consider posting your question on the Community Forums at http://forum.revive-adserver.com.

**Comment by mango1970** [comment]
hi erik I have done so and I have also posted a way around it... but i did post here as it is difficult to get an answer in the forum...
