### ISSUE TITLE
Error with Delivery Limitations After Upgrade to 3.2.1 from 3.1

### ISSUE THREAD

**Issue by willkat** [revive-adserver/revive-adserver#606]
We upgraded our Revive server from ver. 3.1 to ver 3.2.1 last night.  T

We noticed that the various geo limitations and device limitations that had been set prior to the upgrade were not being followed, and we saw the following error messages appearing on the Delivery Limitations page:

WARNING: The delivery engine limitations DO NOT AGREE with the limitations shown below
Please hit save changes to update the delivery engine's rules

Some of delivery limitations reports incorrect values:
Unknown operator

Is there a bug in the update that could be causing this?

**Comment by mbeccati** [comment]
Nope, I don't think it's a bug.

I've left a reply on the forum. I know it might be frustrating not to receive an answer, but the forum is better suited for support.
