### ISSUE TITLE
Banners - bad display html

### ISSUE THREAD

**Issue by antost** [revive-adserver/revive-adserver#611]
In my case when i created new banner with code:

        <article itemscope="itemscope" itemtype="http://schema.org/Recipe">
            <figure>
                <img src="http://someurl/B.png" width="186" height="190" alt="alt">
                                            </figure>

            <h2 itemprop="name" style="padding-top: 30px;"><a href="http://someurl">Some text.</a></h2>
                        <div class="hidden"><img itemprop="image" src="http://someurl/B.png" alt="alt"></div>
                                    <div class="post-content" itemprop="recipeInstructions">Some text
                                    <a style="text-decoration: underline !important;" href="http://someurl">Some text.</a> </div>
            <footer>
                            </footer>
        </article>

When i was saved this banner in database, in table banners, field htmlcache, i have:

        <a rticle itemscope="itemscope" itemtype="http://schema.org/Recipe">
            <figure>
                <img src="http://someurl/B.png" width="186" height="190" alt="alt">

                
                                            </figure>

            <h2 itemprop="name" style="padding-top: 30px;"><ahref="{clickurl}http someurl" target="{target}">Some text</a></h2>
                        <div class="hidden"><img itemprop="image" src="http://someurl/B.png" alt="alt"></div>
                                    <div class="post-content" itemprop="recipeInstructions">Some text
                                    <a style="text-decoration: underline !important;"href="{clickurl}http%3A%2Fsomeurl" target="{target}">Some text</a> </div>
            <footer>

                            </footer>
        </article>

Instead tag  html tag article, i got this: "<a rticle ..." (article tag name is splited)

Revive version 3.2.1

I replaced admin folder in project directory from revive v 3.0.1 and all works fine.
It's a bug ?

**Comment by mbeccati** [comment]
It seems to be related to the fix for #526

**Comment by antost** [comment]
Thx.
