### ISSUE TITLE
XML_RPC Sending Image Content

### ISSUE THREAD

**Issue by Narimani** [revive-adserver/revive-adserver#613]
Hi. I want to upload an image as a banner via XML_RPC and get this error:
```
    XML error: Invalid character at line 2 
```
As you know we can not send binary data via xml and we should use an encoding like base64 or ... for that. So in your function 
```
function _validateImage($aImage, &$oImage)
```
in `/revive/lib/OA/Dll/Banner.php`
you should make some changes. I mean when a content from xml_rpc arrives, it should first decode it and then work on it. sth like this:
```
        $aImage['content'] = base64_decode($aImage['content']);
```
[Stackoverflow](http://stackoverflow.com/questions/32244418/revive-adserver-xml-rpc-sending-image-content)
[forum](http://forum.revive-adserver.com/topic/1958-xml-rpc-sending-image/)

**Comment by mbeccati** [comment]
Thanks for your report. I don't think it's a but as I'm afraid you're not using the proper data type, which would be base64.

https://en.wikipedia.org/wiki/XML-RPC#Data_types

**Comment by Narimani** [comment]
You are correct!!!

**Comment by mbeccati** [comment]
Of course I am @Narimani :-D
