### ISSUE TITLE
Revive ads don't work on MobileTemplate for Joomla

### ISSUE THREAD

**Issue by estern101** [revive-adserver/revive-adserver#616]
I am using Joomla 3.4 with Mobile Joomla as a way to convert my website. The template that is used for mobile is called 'mobiletemplate'. I am having an issue with the k2 content, which only happens in k2 articles and not in regular Joomla articles. Once I put the revive ad on the k2 article it seems to strip out all the content and just displays the ads. I have tried putting the ad in different positions and it doesn't work. Any help would be welcome.

**Comment by erikgeurts** [comment]
Please consider posting your questions on our community forums at http://forum.revive-adserver.com
