### ISSUE TITLE
syntax error: unrecognized tag 'ox_entity_id'

### ISSUE THREAD

**Issue by ghayou** [revive-adserver/revive-adserver#620]
Hi,
I would like to report this issue.
ox_entity_id is called in the following files :  https://github.com/revive-adserver/revive-adserver/search?utf8=%E2%9C%93&q=ox_entity_id,

It seems like the smarty template is missing this plugin,

**Comment by mbeccati** [comment]
Where do you get such error?

The definition is here:

https://github.com/revive-adserver/revive-adserver/blob/5831a08a80da982394fabd4751c2891a872ac00a/lib/OA/Admin/Template.php#L841

**Comment by ghayou** [comment]
in www/admin/advertiser-campaigns.php when templates_compiled is empty

**Comment by mbeccati** [comment]
I'm sorry I can't replicate it. Not even by removing the directory or making it non-writable. I suppose there's something wrong with your system.
