### ISSUE TITLE
Upgrade Process/Docs Need Clarification

### ISSUE THREAD

**Issue by WOs8lfTkz3E5g7I4Lm** [revive-adserver/revive-adserver#621]
After undergoing the upgrade from 3.0.2 to 3.2.1, I observed a significant issue which made the upgrade process more difficult than it needs to be.

On Step 3, it asks: "Path to previous Revive Adserver installation"

The problem is that it gives no details as to how it expects the path to be specified. After experimentation and Googling, I was able to discover that it wanted the full path relative to the server's root, e.g. /home/myaccount/public_html/oldv302/

The confusion is further compounded by the fact that the upgrade docs do not mention that the installer requires your old files to be intact on the server where it can access them, nor does it mention why it needs them.

My files are installed in the root directory of the server. So, I can not follow the upgrade directions per se. Fortunately, I tried a test upgrade before doing the real thing, so I at least knew that it was looking for the previous files for whatever mysterious reason. I moved all the 3.0.2 files into a subfolder (./oldv302) and specified the full server path to make the upgrade work.

RECOMMENDATIONS:
1) Clarify the on screen instructions for Step 3
2) Improve Upgrade docs to:
(a) Make note of the requirement to have the old files available on the server
(b) Make note of why the files are required
(c) Make note how the software expects the path to be specified
(d) Make note that for users with Revive installed in the root directory, that they only need move the old files into a subfolder.

![asking for old install path](https://cloud.githubusercontent.com/assets/6634041/10036126/f6eada08-6170-11e5-9162-1821227dab2e.PNG)

**Comment by erikgeurts** [comment]
Thanks for your detailed suggestions, we will encorporate them in a future version of the documentation.

**Comment by xianx** [comment]
Hello update the about this section. what is the function of it? why it need. its been 3 years and still no explanation.

**Comment by xianx** [comment]
Should I need to copy all plugins to the new installation?

**Comment by erikgeurts** [comment]
I'm of the opinion that this is sufficiently covered in the upgrade instructions at https://www.revive-adserver.com/support/upgrading/

The upgrade instructions describe a number of assumptions about the existing installation that is about to be upgraded, which are also in line with the installation instructions. Obviously, there are many ways to divert from these assumptions, for good or bad reasons.

We can not possibly provide guidance for every single deviation from the assumed starting point, and we have to assume that people with a different starting point have arrived there willingly and knowingly, and therefore should be able to adjust the upgrade instructions accordingly.

As such, I believe that we can consider this issue to be sufficiently covered and ready to be closed.
