### ISSUE TITLE
Documentation about Setting file and folder permissions

### ISSUE THREAD

**Issue by davidnoss** [revive-adserver/revive-adserver#622]
Existing install and upgrade documents specify file/dir priv settings that are not true for all servers.

"If your server is running on Linux or Unix, the permissions have to be set to ‘777’."

This is only typically true if the user's web server process (apache) runs as user 'nobody'

On many contemporary servers, the web server process is running as the owner of the account. LiteSpeed does this for example as can Apache depending upon which PHP handler is selected.

Ergo, the default file privs of 644 and dir privs of 755 are writable by the web server and they need not be set to 777. Setting files to 777 if not required should be avoided IMO.

**Comment by erikgeurts** [comment]
Thanks for your detailed suggestions, we will encorporate them in a future version of the documentation.

**Comment by erikgeurts** [comment]
Documentation pages at https://www.revive-adserver.com/support/installation/ and https://www.revive-adserver.com/support/upgrading/ have been edited.

**Comment by lparikka** [comment]
At least the upgrade document still says:
"If your server is running on Linux or Unix, the permissions have to be set to ‘777’."

**Comment by erikgeurts** [comment]
Yes, and that's correct.

For further support issues, please consider using the community forums at http://forum.revive-adserver.com

**Comment by mbeccati** [comment]
FWIW, the documentation change has been reverted as it is not true that "many contemporary servers" are running PHP as the user of the account. In fact that would be a minority, according to my experience. Truth is that permissions would need to be tailored to the server setup, buit most of the user wouldn't be able to tell what to use exactly, hence 777 is the best fit for the documentation.

**Comment by lparikka** [comment]
OK, but I still think it is not wise to set the files 777. For example all the image files should not be executable.


Matteo Beccati <notifications@github.com<mailto:notifications@github.com>> kirjoitti 12.9.2016 kello 10.22:


FWIW, the documentation change has been reverted as it is not true that "many contemporary servers" are running PHP as the user of the account. In fact that would be a minority, according to my experience. Truth is that permissions would need to be tailored to the server setup, buit most of the user wouldn't be able to tell what to use exactly, hence 777 is the best fit for the documentation.

**Comment by mbeccati** [comment]
@lparikka if you have a better idea, please feel free to submit a PR or documentation comment.

**Comment by lparikka** [comment]
Well, I don't exactly know which directories and files have to be writable by the server. But the documentation should tell exactly which directories and which files have to be writable. No php-file need to be executable for example. And no image file should be executable. That was my point, I don't know what are the correct settings.

**Comment by andrewatfornax** [comment]
Hi @lparikka,

I suppose we could update the documentation to say "Here are all the exact requirements", but then we'd be flooded with people asking for more support on setting that up. Or, we could say, here is a set of more specific permissions, but then, chances are we can't possibly cater to everyone's specific requirements, and again, we'd get flooded with support.

Personally, I think what we have done is the best we can - it's permissive, yes, but that's not going to cause an issue on its own. Any issue will come from other sources. So, if users have the knowledge to be more restrictive, and the desire to do so, then they can experiment with their personal setup, for their personal needs, and be more restrictive. For anyone who doesn't have the knowledge as to why the 777 permissions are not a "great" idea (but not necessarily wrong), then this is not going to hurt them.

**Comment by davidnoss** [comment]
Why don't you just say something like this:

*The following files and directories must be writable by your web server.
The exact permissions vary based on your server's configuration. Some
servers run Apache as the account owner (your username on the server), in
which case the default permissions should suffice. Other servers run Apache
as user nobody, in which case the permissions for files should be 666, and
777 for directories.*
