### ISSUE TITLE
Possibility to upload .html files on Revive, to not depend on other uploads tools?

### ISSUE THREAD

**Issue by alexkleinubing** [revive-adserver/revive-adserver#624]
Hi ppl,

I think the Revive need a way to upload **.html** files (html5 converted via Swiffy) or an entire directory for cases like the Google Web Design, so we need no external upload tools. Likewise it is running with .swf.

Is there any solution or indication procedure?

**Comment by erikgeurts** [comment]
Duplicate of #604
