### ISSUE TITLE
Async tags result in Adsense revenue not reporting in Analytics

### ISSUE THREAD

**Issue by freekzero** [revive-adserver/revive-adserver#626]
Serving Adsense ad units via Revive, using the async tags, results in Analytics (assuming the Adsense account is linked to Analytics of course) not seeing the impressions or clicks generated by those ads. Simply switching back to the old JS tags started the data flowing.

**Comment by davkap92** [comment]
yes having this issue too. thanks

**Comment by lludwig** [comment]
Sane here.

**Comment by mbeccati** [comment]
Have you tried unchecking the box "This banner can be safely displayed inside an iframe (e.g. is not expandable)"?

**Comment by freekzero** [comment]
That did the trick. Thanks Matteo!
I presume there's a trade-off to doing this though?

**Comment by mbeccati** [comment]
The trade off is that some 3rd-party creatives could wipe out the page if they use document.write(). If that doesn't happen, it means that Adsense is "safe".
