### ISSUE TITLE
Unable to upgrade from 3.2.0 to 3.2.1

### ISSUE THREAD

**Issue by martinkrcho** [revive-adserver/revive-adserver#627]
I am not able to upgrade from 3.2.0 to 3.2.1 and I have no idea what is wrong. I tried for the third time in the span of couple of weeks with the same result.

I followed the official instructions step by step: http://www.revive-adserver.com/support/upgrading/

The problem comes when I run the upgrade wizard in the browser. It is asking me for database details instead of picking them up from the config file. When I enter the details it is not happy.

I have successfully upgraded Revive couple of times before, even when it was still OpenX. I am out of ideas here. Can somebody please help me?

This is in the install.log:
```
Attempting to detect an existing Openads (aka. phpAdsNew) installation...
PAN not detected
Attempting to detect an existing Openads (aka. Max Media Manager 0.1) installation...
MMM v0.1 not detected
Attempting to detect an existing Openads (aka. Max Media Manager 0.3) installation...
MMM v0.3 not detected
Attempting to detect an existing Revive Adserver installation...
No previous version of Revive Adserver detected
```

**Comment by erikgeurts** [comment]
Please consider posting your question on the support forums at http://forum.revive-adserver.com

**Comment by martinkrcho** [comment]
I did that twice already, but I am not getting any help from anybody.
http://forum.revive-adserver.com/topic/2984-unable-to-upgrade-from-320-to-321/

I tried the upgrade couple of times already so I am convinced it is some bug in the code.

**Comment by erikgeurts** [comment]
I'm more than happy to consider it is a bug, but so far, there is no evidence of that.

All we have right now is a case where either your config file is not recognized or you forgot to copy it from the 'old' to the 'new' folder.

**Comment by martinkrcho** [comment]
I definitely did not forget to copy it from the 'old' to the 'new'. I've done the upgrade many times before with earlier versions and this is the first time I'm stuck on this one step. As I mentioned in the forum, I checked everything I could think of including file permissions and owners. The system is still failing to find the previous installation and therefore tries to do a fresh install instead of an upgrade. I must be some edge case.

**Comment by martinkrcho** [comment]
Hi @erikgeurts, I have the same problem with upgrading to version 3.2.2. I narrowed it down to the function ```detectOpenads($skipIntegrityCheck = false)``` in ```lib/OA/Upgrade/Upgrade.php```.

It is not getting into the if statement at the beginning:
```
if ( (!empty($GLOBALS['_MAX']['CONF']['openads']['installed'])) || file_exists(MAX_PATH.'/var/INSTALLED'))
```

I believe it should be getting there in order to recognize the previous installation. Is it supposed to get inside this if statement? Does it happen when you try to upgrade?

Thanks

**Comment by martinkrcho** [comment]
Hi @erikgeurts, is there any chance you could have a look at this?
