### ISSUE TITLE
SSL detection of requests

### ISSUE THREAD

**Issue by cYzzie** [revive-adserver/revive-adserver#628]
my SSL requests are not detected correctly, i debugged it and it seems like HAPROXY is setting ssl headers differently

(i XXed out my ip)

in $_SERVER i have :
 ["forwarded"]=>   string(1) "1"
  ["HTTP_HOST"]=>   string(11) "my.adserver.com"
  ["HTTP_X_FORWARDED_FOR"]=>   string(23) "91.46.XX.XX, 127.0.0.1"
  ["HTTP_X_SECURE"] =>   string(4) "true"
  ["HTTP_X_SSL"]=>  string(4) "true"

maybe there could be a way to put SSL detection into config as a function that can overwrite internal SSL detection?

we now modified ssl config to match what revive searches for - that works too of course, i dont know how many other people are having those problems. 

maybe its enough to add better documentation of this specific problem or so.

**Comment by mbeccati** [comment]
Thanks for your report.

Historically, PHP has been relying on $_SERVER['HTTPS'] === 'on', which isn't a header a client can spoof.

I know that it's something that doesn't always work out of the box when setting up a reverse proxy, but it's not something specific to Revive Adserver, it's just part of the configuration of your proxy+webserver+php setup.
