### ISSUE TITLE
empty page bug add

### ISSUE THREAD

**Issue by developperKesako** [revive-adserver/revive-adserver#629]
Hello wenn I do the update to the version 3.0.5 to the version 3.2.2 the page 
www/admin/banner-edit.php and others page to concern banners was not found but I showed the script was executed .
I have PHP 5.3 
To resolve this problems 

go in yourBaseDirectory/lib/max 
in 
 function _addLimitation(&$aLimitations, $entityIdName, $columnName, $value, $comparison_type = MAX_LIMITATION_EQUAL)

and add in the end of this function
return '';

This are resolve the bug

**Comment by mbeccati** [comment]
I'm sorry, I don't think this is a bug and I'm not sure what the fix is trying to solve.

I believe you might ahve been victim of some apc or xcache issue, that could be solved by restarting apache / php-fpm.
