### ISSUE TITLE
Website Targeting Channel not working

### ISSUE THREAD

**Issue by Narimani** [revive-adserver/revive-adserver#631]
I have problem with website targeting channels. It does not work at all. I choose a website and add a Targeting channel to it with agent limitation. But still I see banners in all agents. other limitaions dont work either!
where is the problem?

**Comment by erikgeurts** [comment]
May I please recommend that you post this on the community forums at http://forum.revive-adserver.com first. Once it's establised that this is a bug (which I think is not very likely), we will be pleased to re-open this issue here.
