### ISSUE TITLE
Website targeting channel limitations Not Working

### ISSUE THREAD

**Issue by Narimani** [revive-adserver/revive-adserver#632]
Hi
I downloaded the latest revive adserver today and Website targeting channel limitations is Not Working.
In plugins I have **Delivery Limitations Plugin** installed and enabled!

*Version	1.3.3	Author	Revive Adserver*
*Creation Date	2015-03-30	Email	revive@revive-adserver.com*
*License	GNU Gneral Public License v2	URL	http://www.revive-adserver.com*

*Delivery Limitations Plugin *

All the plugins are enabled. I cleared directory "var/cache" too! Banner delivery limitation is working correctly. 
I asked it in the forum [Here](http://forum.revive-adserver.com/topic/3024-website-ads-check-referer/)
And got nothing there!
Is it a bug or am I missing sth?

**Comment by erikgeurts** [comment]
Let's wait until a response or resolution is provided in the forum. If it turns out to be a bug after all, we'll be glad to re-open this issue.

**Comment by Narimani** [comment]
As you can see there is no response there? What should I do now? I will ask another question in the forum and will wait for response!
