### ISSUE TITLE
Problems with banner display

### ISSUE THREAD

**Issue by Lubrick** [revive-adserver/revive-adserver#636]
Hello, I noticed a problem with AdServer and could use your help. On some mobile devices, on Android and iOS apps AdServer does not display banners due to an unknown error. However, this problem is not persistent and it manifests randomly. 

A way to reproduce the issue would be to click on a link to some banner in Chrome or Firefox mobile browser incognito windows (also noticed on desktop incognito browsers)

Banner link has this format: 
http://www.example.com/mobile_banner_43.html

On first click banner is not loaded, but it loads after a refresh.

While testing I put these variable values in javascript console "OA_output['320x50']" and on first call it returned no value, but after refreshing the page I got a response.

Here are responses for first and second call by the adserver, that returned different responses.

FIRST CALL:
```
var OA_output = new Array(); 
OA_output['320x50'] = '';
OA_output['320x50'] += "<"+"div id=\'beacon_5ac77bf265\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://ads.example.com/www/delivery/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=43&amp;source=Main&amp;loc=http%3A%2F%2Fwww.example.com%2Fmobile_banner_43.html&amp;cb=5ac77bf265\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
```

SECOND CALL:
```
var OA_output = new Array(); 
OA_output['320x50'] = '';
OA_output['320x50'] += "<"+"a href=\'http://ads.example.com/www/delivery/ck.php?oaparams=2__bannerid=6334__zoneid=43__source=Main__cb=1f321f9d78__oadest=http%3A%2F%2Fsubdomain.example.com%2Fwebsite-section%2Farticle-url-and-id\' target=\'_blank\'><"+"img src=\'http://ads.example.com/www/images/7da719d964bb4d6311c9dada6cb6f229.jpg\' width=\'320\' height=\'50\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_1f321f9d78\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://ads.example.com/www/delivery/lg.php?bannerid=6334&amp;campaignid=3618&amp;zoneid=43&amp;source=Main&amp;OAZBLOCK=3600&amp;OAZCAP=99999&amp;OASZCAP=99999&amp;loc=http%3A%2F%2Fwww.example.com%2Fmobile_banner_43.html&amp;cb=1f321f9d78\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
```

Could you please help me understand why is this happening, I am out of ideas. Thank you very much.

**Comment by erikgeurts** [comment]
Please consider posting your question on our community forums at http://forum.revive-adserver.com. The issues section of our Github page is not intended for this type of support.

**Comment by Lubrick** [comment]
I wouldn't say this is a "support" request since I believe this is a bug in the AdServer, but I will certainly do as you say.

Thank you.

**Comment by erikgeurts** [comment]
If it does turn out to be a bug (I never said it isn't), then we'll be perfectly happy to re-open this issue here.

**Comment by Lubrick** [comment]
Understood, I posted it on the forum.
thank you again. :)

**Comment by Lubrick** [comment]
Hello,
I posted this on the forum just as you suggested, but nobody replied for almost 2 months now, and the problem is still happening.

**Comment by andrewatfornax** [comment]
Can you please let me know what the link to the post is, please? I'll see if I can see it.

**Comment by Lubrick** [comment]
Sure thing, here is the link to the forum post:
http://forum.revive-adserver.com/topic/3060-problems-with-banner-display/

Thanks.
