### ISSUE TITLE
Use PDO as DBAL

### ISSUE THREAD

**Issue by heiglandreas** [revive-adserver/revive-adserver#637]
Hi. Is it possible (or is there a plan) to use PDO as DBAL? That way the deprecated mysql-library could be eliminated.

**Comment by mbeccati** [comment]
If we will ever be able to refactor Revive Adserver's core I would say that PDO is probably the only sane choice, but I'm afraid that retrofitting it in the current code is not going to work. Back in the days we tried to add a mysqli driver but all the schema management wasn't properly working. It would be easier than PDO, but I'm not sure it's worth the effort either.

When it comes to PHP7, Revive will work just fine with Postgres, unless the legacy mysql extension is installed via pecl or the packages system in use.
