### ISSUE TITLE
Banner Delivery - Site Variable not working

### ISSUE THREAD

**Issue by moesphemie** [revive-adserver/revive-adserver#638]
I'm having problems with the banner delivery limitations.

At the beginning of the year 2015 we successfully configured a site variable for postcodes in the channels-section and linked that with a banner, example:

**(regex match)
Name: plz
Value: (1|2|3|4|5|6)**
![channel config](https://cloud.githubusercontent.com/assets/11868007/11244762/994a37ce-8e0f-11e5-9410-6be8c0bc9edf.png)
![banner delivery limitation](https://cloud.githubusercontent.com/assets/11868007/11244805/cd3fd80e-8e0f-11e5-84f3-c64d63d9f59b.png)

When the user enters in the url something like: *foo.com/results?value=666&plz=5*
he then get the right banner showed up. After some months i have tried it but it doesn't work anymore, changing the limitation to something like **(Site - Page URL)** and containing *foo* then it works again. 
Is there any known issue to that? Using **v3.0.5**

Any help would be awesome!
Cheers

**Comment by mbeccati** [comment]
Thanks for you report, but it's not a bug.

The "Site - Variable" limitation only applies to parameters sent when calling the banner, e.g. *ajs.php*, *afr.php*, etc., not the URL of the page that displays the banner.

Also, please consider trying the forums before posting a bug report.
