### ISSUE TITLE
Issues with cookies and port 8080?

### ISSUE THREAD

**Issue by andrewatfornax** [revive-adserver/revive-adserver#639]
There have been two mentions on the forums of users having issues with cookies not working (probably the cookies are created, but Revive doesn't read them correctly?) when installing on port 8080:

http://forum.revive-adserver.com/topic/2993-you-need-to-enable-cookies-before-you-can-use-revive-adserver/?do=findComment&comment=6661

http://forum.revive-adserver.com/topic/3026-installation-error/#comment-6515

Perhaps needs investigating...

**Comment by jtmitchell** [comment]
The cookies are created, but the domain is set including the port number, ie 'localhost:8080'
I believe the correct behaviour is to not use the port, and just set the domain.
