### ISSUE TITLE
Deprecate support for PHP 5.3 and 5.4

### ISSUE THREAD

**Issue by andrewatfornax** [revive-adserver/revive-adserver#642]
On the official Revive website, at http://www.revive-adserver.com/support/requirements/ we list that Revive Adserver is supported on PHP 5.3 up.

However, PHP 5.3 and PHP 5.4 are now both completely out of support: http://php.net/supported-versions.php

Therefore, as of Revive Adserver 3.3.0, we will deprecate support for PHP 5.3 and PHP 5.4, and PHP 5.5.2+ will be the minimum required version.

This will require an update to the code that checks versions & documentation, release notes, etc.

**Comment by mbeccati** [comment]
It seems that other OSS (e.g. Symfony 3, Laravel 5.1, Drupal 8) projects have picked 5.5.9, mostly because that's what Ubuntu 14.04 LTS ships with. If we ever reuse some of their components anytime soon, going with 5.5.9 might save some headaches.

**Comment by andrewatfornax** [comment]
Yes, this sounds like a good idea.
