### ISSUE TITLE
Detect incompatible security mods?

### ISSUE THREAD

**Issue by andrewatfornax** [revive-adserver/revive-adserver#648]
Is it possible to detect if PHP security mods that seem to regularly cause issues with Revive Adserver are installed, and offer a warning in the UI to users when this is the case?

This may cut down on the number of support requests where these mods are to blame?

**Comment by mbeccati** [comment]
As far as I know mod_security can be detected only if PHP is running as an apache module as well (with `apache_get_modules()`), but I don't think we can detect if it's properly configured.

What other mods did you have in mind?

**Comment by andrewatfornax** [comment]
Yes, I see what you mean about mod_security:

http://stackoverflow.com/questions/3182500/detect-if-mod-security-is-installed-with-php

**Comment by andrewatfornax** [comment]
The other real one that I had in mind was something like AdBlocker, which messes up the installer/UI.

**Comment by andrewatfornax** [comment]
http://stackoverflow.com/questions/4869154/how-to-detect-adblock-on-my-website

**Comment by andrewatfornax** [comment]
suPHP is another that we could potentially look at...

**Comment by andrewatfornax** [comment]
Addressed this issue with documentation, because it's essentially impossible to do with code. See: http://documentation.revive-adserver.com/pages/viewpage.action?pageId=8028358

Still hope to address adblocker detection in the installer though via #695.
