### ISSUE TITLE
Korean translation was broken

### ISSUE THREAD

**Issue by jeyraof** [revive-adserver/revive-adserver#649]
Korean text in files of [Korean](https://github.com/revive-adserver/revive-adserver/tree/master/lib/max/language/ko) were borken :(

It looks like hex code such as `캠페�?�`.

The original text is `캠페인`.

**Comment by erikgeurts** [comment]
Please use the translation project we've opened for Revive Adserver at http://translations.revive-adserver.com, in this case http://translations.revive-adserver.com/project/revive-adserver/ko
