### ISSUE TITLE
Client / Language Delivery Limitation Mismatches

### ISSUE THREAD

**Issue by dczaretsky** [revive-adserver/revive-adserver#655]
I noticed some serious bugs in the delivery limitations for client / languages. The front-end for the language limitations stores the iso639 encodings in the database in lowercase. For example, a match of either "English" or "English/United States" would be stored in the "compilelimitations" field as: 

MAX_checkClient_Language('en,en-us', '=~')

This function is defined in plugins/deliveryLimitations/Client/Language.delivery.php, and performs a an array_intersect to determine if there are any matches between limitations and client browser languages. 

The first bug I noticed is that the array_intersect function is case sensitive, and many browsers are passing in strings like "en-US". Therefore, the banner is not delivered in this case. The comparison should be case-insensitive to correctly match browser languages.

The second bug I found is that if you select "English" (e.g. "en") it should match ALL english languages, such as en, en-us, and en-gb. However, some browsers, like safari on iOS only returns "en-us" and does not include "en". Thus, there is no match found and no banner is delivered. The language limitation should do partial matching to correctly match the browser langauages.

To solve these two problems, I have replaced the array_intersect function with array_uinteresect, which allows a user-defined callback in the comparison. I have created a function call "language_match" which correctly compares the two based on the notes above. I've verified that the solution below works, and I recommend updating the Language.delivery.php file accordingly.

---

function language_match($limitation, $language)
{
    return strncasecmp($language, $limitation, strlen($limitation));
}

/**
- Check to see if this impression contains the valid language.
  *
- @param string $limitation The language limitation
- @param string $op The operator
- @param array $aParams An array of additional parameters to be checked
- @return boolean Whether this impression's language passes this limitation's test.
  */
  function MAX_checkClient_Language($limitation, $op, $aParams = array())
  {
  if (empty($aParams)) {
      $language = $_SERVER['HTTP_ACCEPT_LANGUAGE'];
  } else {
      $language = $aParams['language'];
  }
  if ($limitation == '' || empty($language)) {
      return true;
  }
  // Strip off q=X if present
  $language = preg_replace('/;q=[0-9.]+$/', '', $language);
  
  $aLimitation = MAX_limitationsGetAFromS($limitation);
  $aLanguages = MAX_limitationsGetAFromS($language);
  
  // case-insensitive and partial matching of language codes
  $aMatchedValues = array_uintersect($aLimitation, $aLanguages, "language_match");
  if ('=~' == $op) {
      return !empty($aMatchedValues);
  } else {
      return empty($aMatchedValues);
  }
  }

**Comment by mbeccati** [comment]
I haven't tested, but the issue seems legit. Could you please provide a pull request?

**Comment by mircomacrelli** [comment]
This bug created a few problems at my workplace. I've tested the fix proposed by @dczaretsky in the last few days and noticed no problems.

To help with the fix I created a pull request (#827) with the patch.

**Comment by mbeccati** [comment]
@mircomacrelli thanks!
