### ISSUE TITLE
Automatic report emails have two "To headers"

### ISSUE THREAD

**Issue by Sabroson** [revive-adserver/revive-adserver#660]
The automatic email reports generated by Revive get blocked by my host's email server.

 Looking at the email logs the issue seems to be that the email reports are being generated with two “To Headers” which make the email server discard them. From the logs:

SMTP error from remote mail server after end of data: host xxxxxxxx.com [IP.IP.IP.IP]: 550 Messages should have one or no To headers, not 2.

**Comment by yannux** [comment]
Seems to be from lines 1191 -> 1205 in [/lib/OA/Email.php](https://github.com/revive-adserver/revive-adserver/blob/v3.2.4/lib/OA/Email.php#L1191-L1205)

As it's my first contribution, i'd rather to ask if it's good for you, here is the original :
```php
// Build the "to:" header for the email
if (!get_cfg_var('SMTP')) {
    $toParam = '"'.$userName.'" <'.$userEmail.'>';
} else {
    $toParam = $userEmail;
}
// Build additional email headers
$headersParam = "MIME-Version: 1.0\r\n";
if (isset($phpAds_CharSet)) {
    $headersParam .= "Content-Type: text/plain; charset=" . $phpAds_CharSet . "\r\n";
}
$headersParam .= "Content-Transfer-Encoding: 8bit\r\n";
if (get_cfg_var('SMTP')) {
    $headersParam .= 'To: "' . $userName . '" <' . $userEmail . ">\r\n";
}
```

It seems to me get_cfg_var('SMTP') doesn't needed here, no other reference elsewhere.
The important thing is to know if userName is null or not.

PHP mail() function requires TO as first parameter so doesn't need it in headers parameter

Here is what i suggest, 
replace from  1191 to 1196 by

```php
// Build the "to:" param for php mail()
if ($userName !== null) {
    $toParam = '"'.$userName.'" <'.$userEmail.'>';
} else {
    $toParam = $userEmail;
}
```

Then remove from 1203 to 1205
```php
if (get_cfg_var('SMTP')) {
    $headersParam .= 'To: "' . $userName . '" <' . $userEmail . ">\r\n";
}
```

I'll try to send my first PR this afternoon :)

**Comment by yannux** [comment]
oups :/ Seems to be same as  : 
Remove the double "To:" email header. #333 

My bad.
