### ISSUE TITLE
support for responsive banner

### ISSUE THREAD

**Issue by camaran** [revive-adserver/revive-adserver#664]
add support for responsive banner

**Comment by erikgeurts** [comment]
Can you please be a little bit (or actually a lot) more detailed about what it is you'd like to see happening?

**Comment by camaran** [comment]
adSense have a responsive banner that not have a fixed width and height

2016-01-21 11:50 GMT+01:00 Erik Geurts <notifications@github.com>:

**Comment by erikgeurts** [comment]
Revive Adserver is not AdSense. Can you please explain in much more detail what you would like to propose?

**Comment by camaran** [comment]
an HTML banner taht i can use in desktop and mobile with a max-width and
max-height setting for responsive template

2016-01-21 11:53 GMT+01:00 Erik Geurts <notifications@github.com>:

**Comment by chaoley** [comment]
Adsense now mainly uses responsive ads, meaning that there is no size defined in the ad slot code. The ad size is determined by the rendered size of the ad slot, which is set via CSS media queries.

I'm trying to implement Revive with remnant inventory supplied by Adsense as per http://www.revive-adserver.com/faq/using-google-adsense-with-revive-adserver/ - but have run into a wall with the requirement for hard coded banner sizes.

**Comment by chaoley** [comment]
Doubleclick has a solution here - https://support.google.com/dfp_premium/answer/3423562?hl=en

**Comment by chaoley** [comment]
`<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-7850998751176505"
     data-ad-slot="6261947537"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>`

**Comment by chaoley** [comment]
Just tried to paste in the example code for a responsive ad unit but it was removed, I'll try uploading it as a text file.

**Comment by ianvm** [comment]
So how do you see this happening ? For example: do you want to upload your image banner in 50 sizes and make Revive Adserver determine which size would fit best on the part you implemented the tag?

**Comment by chaoley** [comment]
That's Doubleclick solution, no simply removing the requirement for a fixed size should do the trick. I'll upload a text file with the current Adsense code.

**Comment by chaoley** [comment]
[adsense_responsive_code.txt](https://github.com/revive-adserver/revive-adserver/files/118994/adsense_responsive_code.txt)

**Comment by ianvm** [comment]
You can 'remove' the requirement for the sizes by adding the zone & banner with a width and height of '*' (wildcard)

**Comment by chaoley** [comment]
Aha that may work, I'll give it a try thanks.

**Comment by chaoley** [comment]
'Please enter a number (only digits allowed) '

**Comment by erikgeurts** [comment]
Try zones, not banners.

**Comment by chaoley** [comment]
I just want this to work, http://www.revive-adserver.com/faq/using-google-adsense-with-revive-adserver/ - it's outdated as it doesn't work for responsive ads, which are the current standard.

I'll try it again later with zones thanks, but I just want to run Adsense as remnant.

**Comment by ianvm** [comment]
It works fine, the sizes are anyway not used if you use a Javascript invocation tag.

**Comment by erikgeurts** [comment]
@chaoley thanks for your kinds words about that page (which I wrote). The mere fact that Google does something, doesn't make it an industry standard.

**Comment by chaoley** [comment]
I just set one up with size of 1 x 1, I'll see how it goes. Thanks for your help.

Responsive ads are pretty much standard in my world anyway :)

**Comment by chaoley** [comment]
Really like Revive and hope I can use it, my house ads are responsive too so I may have more issues.

House ads are based on this technique - http://matthewjamestaylor.com/blog/responsive-banner-ads

**Comment by erikgeurts** [comment]
This discussion would have been better at home at http://forum.revive-adserver.com
