### ISSUE TITLE
Problem with href attribute

### ISSUE THREAD

**Issue by aktuelno** [revive-adserver/revive-adserver#665]
Hi, my ads served as image files suddenly have problem with href attribute (flash ads are served normally), so now I have: http://www.aktuelno.me/ads/www/delivery/http%3A%2F%2Fwww.privrednakomora.me%2Fdobro-iz-crne-gore-0%2F instead of just http://www.privrednakomora.me/dobro-iz-crne-gore. As you see, it adds in the hyperlink http://www.aktuelno.me/ads/www/delivery/ and makes some symbols instead of "/".

Please help.

**Comment by erikgeurts** [comment]
Please consider posting your question on the Community Forums at http://forum.revive-adserver.com as we reserve the Github issues area for actual/confirmed bugs.
