### ISSUE TITLE
An error occurs during the installation phase. Help.

### ISSUE THREAD

**Issue by gio22** [revive-adserver/revive-adserver#666]
hi!

Now when you want to install this plug-in step generates the message.
 Installing Revive Adserver Plugin: Reports Plugin Permissions error.

 Then why do ??

 Last screen, and outputs the information as below.
===========================================

( ! ) Fatal error: Uncaught exception 'Exception' with message 'Unable to set current step. Unknown step: login' in C:\wamp\www\clients\jeff\platform_d\lib\OX\Admin\UI\Wizard.php on line 138

( ! ) Exception: Unable to set current step. Unknown step: login in C:\wamp\www\clients\jeff\platform_d\lib\OX\Admin\UI\Wizard.php on line 138

Call Stack

#

Time

Memory

Function

Location

1 0.0000 147544 {main}( ) ..\install.php:0 
2 0.7240 11194024 Installer->startMVC( ) ..\install.php:30 
3 0.7240 11211472 OX_Admin_UI_Controller_BaseController->process( ) ..\install.php:41 
4 0.8590 12514768 OX_Admin_UI_Controller_BaseController->execute( ) ..\BaseController.php:82 
5 0.8590 12514936 OX_Admin_UI_Install_InstallController->loginAction( ) ..\BaseController.php:94 
6 0.8590 12515288 OX_Admin_UI_Install_Wizard->__construct( ) ..\InstallController.php:298 
7 0.8590 12517048 OX_Admin_UI_Wizard->__construct( ) ..\Wizard.php:31 
8 0.8590 12517600 OX_Admin_UI_Wizard->setCurrentStep( ) ..\Wizard.php:83 

===========================================
 
And do you access again to the url information update step screen is output could see the login screen, then click OK.
 Do you attempt to log an error message is displayed and this should not logged in.
=======================================================
You need to enable cookies before you can use ad Adserver 
=======================================================

It was comfortably installed when you install the last month.
 If an attempt is made at this time why this happens What are you?

Even prayer is not normally a few times with the same error.
 Ask why the person knowing answers.

Good day ^^

**Comment by erikgeurts** [comment]
Please consider posting your question on our support forums at http://forum.revive-adserver.com/

**Comment by mbeccati** [comment]
It is not the first time I see something similar though. And every time it seems to be a WAMP setup, so maybe it's related to the fact @gio22 is using localhost or an IP address as a testing domain?
