### ISSUE TITLE
Notifications by email about ending capaigns does not work

### ISSUE THREAD

**Issue by athlan** [revive-adserver/revive-adserver#667]
Test case:

**As a Default Manager**
* go to the Preferences > Account Preferences > Campaign email Reports Preferences
* Under section "Account email Warnings" select checkbox "Send a warning to the account every time a campaign is almost expired" and set "Send a warning when the days left are less than specified here" to 1.
* Under section "Advertiser email Warnings" select checkbox "Send a warning to the advertiser every time a campaign is almost expired" and set "Send a warning when the days left are less than specified here" to 1.
* add a new advertiser, provde your email under Contact and Email fields
* select Email when a campaign is automatically activated/deactivated
* add a new campaign assigned to new advertiser:
* select type Remnant, select tart date from -3 days and end date to +1 day (tommorow)
* add text banner to this campaign, assign to zone (previously defined)

**as an Administrator**
* ensure that on "Debug Logging Settings" tab option about logging is enabled
* on the "Email Settings" tab ensure that "Log all outgoing email messages" is enabled

**from CLI run maintanence script**
php /PATH_TO_INSTALL/maintenance/maintenance.php YOUR_RV_DOMAIN

Nothing happened. In the logs there are information about maintanence, no info about email, no emails in inbox (spam checked).

It does not work.

Please note that the camapign will be expired tommorow (as set), but no notification is sent.

**Comment by ianvm** [comment]
It works fine, what does the maillog on your server say?

**Comment by athlan** [comment]
Revive log says nothing (but settings are set):
`grep mail var/debug.log`

First of all I cannot recognize if revive do anything to connect to this server. The option "Debug Logging Settings" does not log any verbose info.

**Comment by ianvm** [comment]
I meant the log of your local maild (e.g. /var/log/maillog if you use sendmail, or /var/log/exim4/mainlog if you use exim)

**Comment by athlan** [comment]
I meant first of Revive functionality. It does not log any verbose messages if emails tried to be send.

**Comment by erikgeurts** [comment]
We think this type of subject is best posted first at http://forum.revive-adserver.com

**Comment by athlan** [comment]
Thank you for the response. I am reporting an issue related with verbose logs, not asking a question.

Forum is the worst place to start this discussion in.

**Comment by erikgeurts** [comment]
We'll be more than happy to reopen this issue if it turns out to be a bug.

**Comment by athlan** [comment]
@erikgeurts Can you go throught submitted test scenario and notice any verboe log about sending an email or corrcect the scenario? If not - this is definitely a bug.

**Comment by athlan** [comment]
There is no info about sending mail while email setting "Debug Logging Settings" is enabled.

```
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Running Maintenance Engine
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Running Maintenance Statistics Engine
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task begin: OX_Maintenance_Statistics_Task_SetUpdateRequirements
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  - Maintenance statistics will NOT be run
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task complete: OX_Maintenance_Statistics_Task_SetUpdateRequirements
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task begin: OX_Maintenance_Statistics_Task_MigrateBucketData
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task complete: OX_Maintenance_Statistics_Task_MigrateBucketData
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task begin: OX_Maintenance_Statistics_Task_DeDuplicateConversions
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task complete: OX_Maintenance_Statistics_Task_DeDuplicateConversions
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task begin: OX_Maintenance_Statistics_Task_ManageConversions
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task complete: OX_Maintenance_Statistics_Task_ManageConversions
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task begin: OX_Maintenance_Statistics_Task_SummariseFinal
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task complete: OX_Maintenance_Statistics_Task_SummariseFinal
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task begin: OX_Maintenance_Statistics_Task_LogCompletion
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task complete: OX_Maintenance_Statistics_Task_LogCompletion
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task begin: OX_Maintenance_Statistics_Task_ManageCampaigns
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task complete: OX_Maintenance_Statistics_Task_ManageCampaigns
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Maintenance Statistics Engine Completed (Started at 2016-02-05 17:59$
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Running Maintenance Priority Engine
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task begin: OA_Maintenance_Priority_AdServer_Task_GetRequiredAdImpre$
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task complete: OA_Maintenance_Priority_AdServer_Task_GetRequiredAdIm$
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task begin: OA_Maintenance_Priority_AdServer_Task_GetRequiredAdImpre$
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task complete: OA_Maintenance_Priority_AdServer_Task_GetRequiredAdIm$
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task begin: OA_Maintenance_Priority_AdServer_Task_AllocateZoneImpres$
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]    - Selecting Zones forecasts for all managers for OI from 2016-02-0$
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Inserted 17 rows in the table tmp_ad_zone_impression
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task complete: OA_Maintenance_Priority_AdServer_Task_AllocateZoneImp$
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task begin: OA_Maintenance_Priority_AdServer_Task_PriorityCompensati$
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]    - Selecting Zones forecasts for all managers for OI from 2016-02-0$
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task complete: OA_Maintenance_Priority_AdServer_Task_PriorityCompens$
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task begin: OA_Maintenance_Priority_AdServer_Task_ECPMforContract
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  - Selecting All Managers
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]    - Selecting active campaigns with priority = '9' for manager 1
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]    - Selecting active campaigns with priority = '8' for manager 1
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]    - Selecting active campaigns with priority = '7' for manager 1
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]    - Selecting active campaigns with priority = '6' for manager 1
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task complete: OA_Maintenance_Priority_AdServer_Task_ECPMforContract
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task begin: OA_Maintenance_Priority_AdServer_Task_ECPMforRemnant
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  - Selecting Managers with ECPM priority campaigns running
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Task complete: OA_Maintenance_Priority_AdServer_Task_ECPMforRemnant
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Maintenance Priority Engine Completed (Started at 2016-02-05 17:59:0$
Feb 05 18:59:02 +0100 OX-maintenance-56b4e2e5d7499 [     info]  Maintenance Engine Completed (Started at 2016-02-05 17:59:02 UTC, ta$
```

**Comment by erikgeurts** [comment]
Please don't create new issues, this only clutters the matter and therefore distracts us and forces us to use valuable time deduplicating issues.

**Comment by athlan** [comment]
This well debugged bug report has been closed without any explanation.

I provide more details:

When i run maintanance script via http (not CLI) situation is the same.
Functionality does not work or my testcase is bad.

Please note that the camapign will be expired tommorow (as set), but no notification is sent.

@ianvm asked about maillog.

No logs in sendmail.

While I am sending email using simply prepared script:
```
<?php

mail('me@example.com', 'Test subject', 'Test content')
```

In mailog there are messages:
```
Feb  6 17:59:31 athlan sSMTP[31370]: Sent mail for nginx@*** (221 2.0.0 Bye) uid=998 username=nginx outbytes=403
```

Revive does not fire mail() function. Maybe my test case is bad. Please review.

**Comment by athlan** [comment]
As is written at http://www.revive-adserver.com/support/bugs/ (where users are redirected from http://forum.revive-adserver.com Bugs section)
> How to file a bug report
> Have you discovered a new issue? We’d like to hear about it!
> 
> Please file a new issue on our Github issue tracker and provide as much detail as possible.

It is in conflict with @erikgeurts statement:
> We think this type of subject is best posted first at http://forum.revive-adserver.com

Please re-open the issue.

**Comment by mbeccati** [comment]
@athlan have you checked *www/admin/userlog-maintenance.php* ?

**Comment by mbeccati** [comment]
@athlan btw, the emails are fired when the "warning" boundary is crossed, e.g. 24hrs before the expiration. Your test case is therefore broken.

**Comment by andrewatfornax** [comment]
For information: http://forum.revive-adserver.com/topic/3437-notifications-by-email-about-ending-capaigns-does-not-work/
