### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by TKList** [revive-adserver/revive-adserver#668]
Can not access Revive Adserver. 
With OPcache on.

http://newrevive.tklist.us/

Fatal error: Cannot redeclare _PEAR_call_destructors() (previously declared in /home/tklist5/public_html/TKList.us/NewRevive/lib/pear/PEAR.php:770) in /usr/lib/php/PEAR.php on line 777

**Comment by erikgeurts** [comment]
I would like to suggest posting this question on our forums at http://forum.revive-adserver.com/
