### ISSUE TITLE
PHP 7.0.2 - mySQL connection problems

### ISSUE THREAD

**Issue by omexlu** [revive-adserver/revive-adserver#670]
Hello,

After switching from PHP 5.6 to PHP 7.0.2 i get a mysql connection error with v3.2.1 ? After switching back to php 5.6 all went good again?

What can i do and why i get this error, nothing has changed with mysql data only the php version?

ERROR from debug.log:

Feb 09 00:01:10 +0100 OX-56b91e36b73ae [  warning]  is_readable(): open_basedir restriction in effect. File(/opt/plesk/php/5.6/share/pear/MDB2/Driver/Extended/mysql.php) is not within the allowed path(s): (/var/www/vhosts/domain.tld/:/tmp/)

**EDIT: I work with Plesk where mySQL ist the Server, why i cant reinstall it with mySQL? I only can use Postgres?**

Where can i edit the path in config files because my php.ini is right need only to change somewhere the saved path in config from revive.

Thanks

**Comment by erikgeurts** [comment]
Please have a look at #652 and https://www.revive-adserver.com/support/requirements/ where it says:

> Revive Adserver, from version 3.2, is also fully compatible with the newly released PHP 7. However, you will only be able to use it with Postgres out of the box, since the old “mysql” extension that Revive Adserver uses has been removed from the official distribution. Should you wish to run it with PHP7 and a MySQL backend, you will need to install the mysql extension from PECL.
