### ISSUE TITLE
Permission error when (de)activating banners

### ISSUE THREAD

**Issue by mbeccati** [revive-adserver/revive-adserver#676]
Once again, the token is missing.

**Comment by mbeccati** [comment]
The fix isn't enough, unfortunately. If a banner is activated or deactivated, the UI might trigger MPE via an ajax call, which consumes the token and breaks all the activate/deactivate links in the Banners page.

**Comment by Nobbi76** [comment]
I'm not sure if this is the right place to write this but the missing token problem seems to affect /www/admin/banner-zone.php as well. If I change the zones, I get an permission error. If I comment out the session token check it works fine.

**Comment by mbeccati** [comment]
@Nobbi76 in fact it is not the right place ;) See #675

**Comment by Nobbi76** [comment]
@mbeccati Sorry, did not see this. And thanks :-) It's working fine with the provided fix.

**Comment by MrJohnyk** [comment]
The fix solved partially the issue. You can only activate/deactivate a single banner per session then on second attempt the error appears again.
