### ISSUE TITLE
install error 

### ISSUE THREAD

**Issue by tommy-liang** [revive-adserver/revive-adserver#679]
Exception: Unable to set current step. Unknown step: login in /revive-adserver/adserver/lib/OX/Admin/UI/Wizard.php on line 138

in the debug.log
Installation started 2016-03-03 16:13:46
Attempting to connect to database revive_adserver with user root
Database created revive_adserver
Connected to database revive_adserver
Database settings and permissions are OK
creating upgrade_action audit table
successfully created upgrade_action audit table
creating database_action audit table
successfully created database_action audit table
schema definition from cache TRUE
Installation created the core tables
Installation updated the schema version to 620
Installation updated the application version to 3.3.0-dev
Preparing to set timezone preference...
Found timezone preference ID of 16
Found the admin account's timezone association, updating preference...
Updated the admin account timezone preference to: 'Asia/Shanghai'
#! openXBannerTypes(): Permissions error
#! openXDeliveryLimitations(): Permissions error
#! openX3rdPartyServers(): Permissions error
#! openXReports(): Permissions error
#! openXDeliveryCacheStore(): Permissions error
#! openXMaxMindGeoIP(): Permissions error
#! openXInvocationTags(): Permissions error
#! openXDeliveryLog(): Permissions error
#! openXVideoAds(): Permissions error

**Comment by erikgeurts** [comment]
Please consider opening a post on our community forums at http://forum.revive-adserver.com. If it turns out from the discusssion there, that there is indeed a bug, we'll be more than happy to re-open this issue.
