### ISSUE TITLE
Probably wrong time interval calculation when doing Priority recalculation

### ISSUE THREAD

**Issue by somsak** [revive-adserver/revive-adserver#684]
We had upgrade OpenX 2.8.11 to ReviveAds 3.2.2 on a test server. While inspecting 0% displayed probability in a zone. I found something that might be a potential bug.

In lib/OA/Maintenance/Priority/AdServer/Task/GetRequiredAdImpressions.php lines 332 - 337

```
321             if (
322                    ($oCampaign->impressionTargetDaily > 0)
323                    ||
324                    ($oCampaign->clickTargetDaily > 0)
325                    ||
326                    ($oCampaign->conversionTargetDaily > 0)
327                ) {
328                 // The campaign has a daily target to meet, so treat the
329                 // campaign as if it expires at the end of "today", regardless
330                 // of the existance of any activation or expiration dates that
331                 // may (or may not) be set for the campaign
332                 $oCampaignExpiryDate = new Date($this->_getDate());
333                 $oCampaignExpiryDate->setTZ($this->currentTz);
334                 $oCampaignExpiryDate->setHour(23);
335                 $oCampaignExpiryDate->setMinute(59);
336                 $oCampaignExpiryDate->setSecond(59);
337                 $oCampaignExpiryDate->toUTC();
338                 OA::debug('    - the mock oCampaignExpiryDate is ' . $oCampaignExpiryDate->getDate(), PEAR_LOG_DEBUG);
339                 // Unless the campaign has an expiry date and it happens before the end of today
340                 if (!empty($oCampaign->expireTime)) {
341                     OA::debug('    - expireTime is ' . $oCampaign->expireTime, PEAR_LOG_DEBUG);
342                     if ($oCampaignExpiryDate->after($this->_getDate($oCampaign->expireTime))) {
343                         $oCampaignExpiryDate  = $this->_getDate($oCampaign->expireTime);
344                         OA::debug('    - final oCampaignExpiryDate is ' . $oCampaignExpiryDate->getDate(), PEAR_LOG_DEBUG);
345                     }
346                 }
```

I think this code block suppose to calculate the expire date of the campaign for a campaign with limitation in impression/target/click per day. $oCampaignExpiryDate is a mock expire date set at the end of the day (23:59:59 of current date) so the final weight of such campaign will be calculated as per day.

However, for my case which is GMT+7, I found that the date is always set back to 16:59:59 of the day before. For example if today is March 7th 2016. It will become March 6th 2016 16:59:59. 

When comparing with $oCampaign->expireTime, suppose that this campaign is not expired yet, then the code will use $oCampaignExpiryDate above at March 6th 2016 16:59:59 to calculate the available interval of this campaign. Suppose that this recalculation is done at March 7th 01:00, which will be converted to UTC and become March 6th 18:00. It will thinks that the campaign is already expired since "end of the day" in this case is March 6th 2016 16:59:59. 

This means that, in my case, any recalculation between March 7th 00:00 - 06:59 will be considered all expired since it will never comes before March 6th 16:59:59. 

I think, in this case, the "end of the day" mock date should be March 7th 23:59:59 GMT+7, which is March 7th 16:59:59 UTC, to make the calculation make sense.

It seems that this happened because the code set 23:59:59 without taking TZ in consideration, thus making the mock end of the day wrong.

Local time right now -> March 7th 2016 01:00:00 GMT+7
$this->_getDate returns UTC -> March 6th 2016 18:00:00
Setting 23:59:59 -> March 6th 2016 23:59:59
toUTC -> March 6th 2016 16:59:59. 

Spare me if i'm wrong.

**Comment by somsak** [comment]
Allow me to rephrase the issue here. I think I understand the issue better.

$this->_getDate() already taking Timezone into account. So in my case the time is GMT already.

Yet the code will, after setting the hour to 23:59:59, recalculate timezone again, that's why the output date object is wrong.

I think you don't need $this->_getDate() here. Just Date() and toUTC() should be enough.

**Comment by mbeccati** [comment]
Hi @somsak, thanks for your report.

Could you please try:
```
$oCampaignExpiryDate->convertTZ($this->currentTz);
```

instead of `setTZ`?

**Comment by somsak** [comment]
Seems $oCampaignExpiryDate->convertTZ($this->currentTz) did the trick. After the call it returned localtime. Subsequent call to set the time to 23:59 and toUTC() again make the final mock Date to the correct value.
