### ISSUE TITLE
Invocation code generation (Asynchronous tags)

### ISSUE THREAD

**Issue by Reviveplugins** [revive-adserver/revive-adserver#689]
When I generate the invocation code of any zone, http or https is messing scr :
![printscreen](https://cloud.githubusercontent.com/assets/16480819/13634920/dbc72de6-e5f8-11e5-848d-962ad33f0878.png)

**Comment by tlehtimaki** [comment]
@Reviveplugins that is intended behaviour. This way the url does not care whether site is running with or without SSL.

**Comment by mbeccati** [comment]
@tlehtimaki is correct.

**Comment by Reviveplugins** [comment]
it happen in both http and https

**Comment by ianvm** [comment]
There is no difference between http & https with the async tag. Please do not re-open the ticket

**Comment by tlehtimaki** [comment]
@Reviveplugins  Heres is some reading for you (this is not a bug you see):
http://stackoverflow.com/questions/4978235/absolute-urls-omitting-the-protocol-scheme-in-order-to-preserve-the-one-of-the
http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by erikgeurts** [comment]
I would like to mention that @Reviveplugins is not affiliated with the Revive Adserver open source project nor with www.adserverplugins.com (despite the association that appears to be implied in their Github username).
