### ISSUE TITLE
Permission error when clicking "Edit targeting channel limitations"

### ISSUE THREAD

**Issue by maqmigh** [revive-adserver/revive-adserver#690]
{rv_add_session_token} missing in channel-index-list.html template, line 134.

**Comment by mbeccati** [comment]
Hmm, I cannot replicate the issue here.

**Comment by mbeccati** [comment]
@maqmigh the token is only necessary when submitting forms, so I'm not sure why the link should have a token.

**Comment by maqmigh** [comment]
Sorry, jumped to conclusions, with all these tokens missing lately. Figured it was similar to #676. I can't find the targeting channel I wanted to edit now, so I guess it was deleted by the time I clicked the link.

**Comment by mbeccati** [comment]
Good news then, thanks for taking the time to report it.
