### ISSUE TITLE
Get zone url by zone ID?

### ISSUE THREAD

**Issue by avishayil** [revive-adserver/revive-adserver#693]
Hi,

I would like to take one zone, which is connected to a few banners on rotation, and provide a link to my native mobile app, so every time the zone is displayed and clicked the rotation would pick one banner from the the selection.

Is there any way to invocate direct link by the zone id, that would redirect to the selected URL from the rotation?

I would like to get a link as follows:
````
http://adserver.url/www/delivery/ck.php?zone=ZONE_ID
```
to access directly, OpenX should pick the right banner from the rotation and redirect there.

Ayn ideas?

**Comment by erikgeurts** [comment]
We have created a community forum at http://forum.revive-adserver.com where you can post these type of questions. In this case, I would assume that http://forum.revive-adserver.com/forum/19-for-developers/ is the best place.
