### ISSUE TITLE
 Unrecognized image file format 

### ISSUE THREAD

**Issue by awaisqarnise** [revive-adserver/revive-adserver#699]
Hi, I am uploading an image to adserver using addBanner Service but I am getting "Unrecognized image file format" error. I have attached the image showing the final array I am sending to addBanner function of the service.
![revive](https://cloud.githubusercontent.com/assets/13886396/13930614/6c091a5a-efc1-11e5-8726-7dca40b1d90a.png)

 

Best Regards,

Awais Qarni

**Comment by erikgeurts** [comment]
It seems you posted this on the forums as well, which is in fact the best place to discuss topics like this. See: http://forum.revive-adserver.com/topic/3622-unrecognized-image-file-format/ . If it turns out to be a bug, we'll gladly reopen this issue here.

**Comment by awaisqarnise** [comment]
@erikgeurts Ok, But can you see it and reply at forum?
