### ISSUE TITLE
SWF banner issue

### ISSUE THREAD

**Issue by mpcnet** [revive-adserver/revive-adserver#702]
We have the following problem since Version 3.2.3.

- When we're uploading an SWF file, the hardcoded links are not identified by the system. After uploading there should be an overview with all the hardcoded links for confirmation. Right now we can only set one static link.
- Existing SWF banners are not showing up on the websites where they're included. A right click shows that it is flash, but it only shows a white box.

Are there any known bugs/issues concerning SWF banners?

**Comment by mbeccati** [comment]
@mpcnet Not that I know of. @erikgeurts how about you?

**Comment by erikgeurts** [comment]
I think this is not an issue for Github. See https://www.revive-adserver.com/faq/using-flash-with-revive-adserver/ and I would like to recommend taking this to the community forums at http://forum.revive-adserver.com.

By the way @mpcnet you might want to consider upgrading to v3.2.4, see https://www.revive-adserver.com/blog/revive-adserver-v3-2-4-released/

**Comment by mbeccati** [comment]
@mpcnet About the existing banners not showing up, I don't think that's a bug in Revive. The simplest explanation would be forgetting to copy the creative files over when upgrading.
