### ISSUE TITLE
PHP7 and Mysql follow up

### ISSUE THREAD

**Issue by planetahuevo** [revive-adserver/revive-adserver#707]
Following up this one https://github.com/revive-adserver/revive-adserver/issues/670
(cannot add a comment there):

Hi, 
When you say the "mysql extension from PECL" do you refer to this one?
https://pecl.php.net/package/mysql
Which says:
" This package is not maintained anymore and has been superseded. Package has moved to channel http://php.net/mysql, package"

Do you plan to add support to mysql in the future? 
Thanks

**Comment by sgreiner** [comment]
I am working on a patch to implement mysqli. The Admin page is working.
But I dont know how to regenerate the delivery scripts. How can that be done?

**Comment by hwde** [comment]
php scripts/delivery/rebuild.php

**Comment by daschenbrener** [comment]
@sgreiner were you able to get this figured out?

**Comment by sgreiner** [comment]
@daschenbrener Yes, my PR is already merged into master branch. See: #756

**Comment by mbeccati** [comment]
Fixed in d0495c3be5fd63f8be7d189a3f9764ed6e578483 w/ support for mysqli, thanks to @sgreiner

**Comment by daschenbrener** [comment]
Fantastic, great work @sgreiner , i'm going to download the stephan-mysqli repository and install it. Ill let you know how I make out

**Comment by erikgeurts** [comment]
I am not going to say a lot about it, but I suggest to wait for a day... Something interesting for everyone is planned for Tuesday.

**Comment by daschenbrener** [comment]
Sounds good @erikgeurts ,much appreciate the correspondence
