### ISSUE TITLE
While using xml-rpc, request/impression/click not tracked

### ISSUE THREAD

**Issue by ccdaisy** [revive-adserver/revive-adserver#708]
Successfully using the xmp-rpc to ask for ads. but while logUrl and clickUrl is invoked, no tracking log in database.

**Comment by erikgeurts** [comment]
I would like to recommend discussing this on the forums at http://forum.revive-adserver.com first. If this turns out to be some sort of bug, it can be picked up here again.

**Comment by ccdaisy** [comment]
I'd love to but I cannot pass the security check during registration. Any reason for it?
Got " You did not pass the security check. Please try again. "

**Comment by ccdaisy** [comment]
Any way to get the request logged in table : rv_data_raw_ad_click & rv_data_raw_ad_impression &  rv_data_raw_ad_request?

**Comment by mbeccati** [comment]
@ccdaisy Please send me an email and I'll do what I can to help you with the forum registration. I'm afraid github issues is no place for support requests, so I'm closing this now.

**Comment by Quix0r** [comment]
Same here, too. Nothing is logged at all in database. And registration on forums is prevented by security check. I don't like recaptcha. :-(
