### ISSUE TITLE
Probability and rendering problem

### ISSUE THREAD

**Issue by Abdujabbor** [revive-adserver/revive-adserver#712]
Hi, I have a problem on rendering the ads look at here: 

https://snag.gy/fHrlb9.jpg

as you can see in this image I have one banner with 37.23% probability, but it never shows on my site. ad revive server doesn't render this ad. what would be the solution of this problem? ? ? I have added this banner 2 days ago, and in 2 days it doesn't render . . .

**Comment by erikgeurts** [comment]
We feel this question would be better suited to be addressed on the community forums at http://forum.revive-adserver.com/ . If it turns out to be a bug after all, we'll be glad to re-open this issue.
