### ISSUE TITLE
https and rendering html banners problem

### ISSUE THREAD

**Issue by Abdujabbor** [revive-adserver/revive-adserver#713]
Hi, some days ago I have moved my site from http to https protocol. and now ad revive server doesn't render the html banners, does it require some configurations??? or this is bug??? but all other banners rendered normal, flash, images. . . but only html banners doesn't render. also I have tested manually if I ask the url: 

http://site_name_address/www/delivery/ajs.php?zoneid=17

it always renders me the html banner because it has 30% probability.

but this url with https protocol doesn't render the html banner

https://site_name_address/www/delivery/ajs.php?zoneid=17

pls, could you help me???

**Comment by erikgeurts** [comment]
We feel this question would be better suited to be addressed on the community forums at http://forum.revive-adserver.com/ . If it turns out to be a bug after all, we'll be glad to re-open this issue.
