### ISSUE TITLE
Serving HTML banners over HTTPS

### ISSUE THREAD

**Issue by athlan** [revive-adserver/revive-adserver#717]
I have fully working Revive AdServer (v3.2.3) both over http and https:

There is also defined only one HTML banner in Zone (proprly assigned, active etc):
```
<iframe src="http://third-party.com"></iframe>
```
(notice that in source of HTML banner there is http:// iframe invocation.

I noticed strange behaviour. When ads are served via non secured url, everything is ok:
**http**://adserver.mysite.com/www/delivery/ajs.php?[...]
In the source code, banner's code appears correctly.

When ads are served via https, the banner does not appear on the source of invocation:
**https**://adserver.mysite.com/www/delivery/ajs.php?[...]

The one important thing is that the site where banners are served is not served via https, just Revive is secured (for panel security reasons).

Is revive parsing the content of HTML banners and restricts http:// links over https:// delivery? Is it a bug? The client website is not under https.

No content is blocked by browser, because  the site where banners are served is not served via https. Revive do not output banner in ads.php.

**Comment by erikgeurts** [comment]
This is intentional. When a system (any system) gets a request over https, it should never respond with any http content. 

Just change the URLs in your iframe invocation code to https and it will work. Make sure the banners you want to be delivered are https as well.

**Comment by athlan** [comment]
Iframe content is not derivable via https.

I understand that Revive should be whole protected excepts /delivery/
directory which should be avaliable via both protocols?

On Monday, May 23, 2016, Erik Geurts <notifications@github.com> wrote:

> This is intentional. When a system (any system) gets a request over https,
> it should never respond with any http content.
>
> Just change the URLs in your iframe invocation code to https and it will
> work. Make sure the banners you want to be delivered are https as well.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/revive-adserver/revive-adserver/issues/717#issuecomment-221050608>
>


-- 
Pozdrawiam,
Piotr Pelczar

www.Vgroup.pl

**Comment by athlan** [comment]
Thank you for your quick reply and open source contribution. The issue can be closed.

**Comment by erikgeurts** [comment]
For the future, I would recommend posting questions like this one on http://forum.revive-adserver.com/
