### ISSUE TITLE
banners in news feed (ajax)

### ISSUE THREAD

**Issue by sdboer78** [revive-adserver/revive-adserver#721]
Hi,

In my newsfeed which is implemented with infinite scrolling, I like to alternate news with some banners.

In the news-feed (which is loaded by ajax) there are some banner elements like:
<ins data-revive-zoneid="229" data-revive-block="1" data-revive-id="5b3abbc94f96a0b5d375d85178a9a021"></ins>

That element have to be filled by Revive adserver.

Because asyncjs.php works only once, I do:
```
reviveAsync = null;
$.getScript('//delivery.ads.myserver.tld/www/delivery/asyncjs.php');
```

But that issn't nice code. And this history of the banners is not saved in the dom.

Any solution?

**Comment by erikgeurts** [comment]
I would like to recommend discussing this type of question on our forums at http://forum.revive-adserver.com
