### ISSUE TITLE
Banner Probability in Chained Zones

### ISSUE THREAD

**Issue by sikjoy** [revive-adserver/revive-adserver#726]
I have a listing of ads that are displayed in a column of 5 zones. I am assuming that the zone in the top position is more likely to get clicked, so I want ads from campaigns with higher weights to be more likely to be displayed at the top of the column. For the sake of discussion, I'll call the top zone, Zone 1, and the bottom zone, Zone 5.

- All campaigns being used are remnant campaigns.
- I use zone chaining and link all campaigns to the top zone (Zone 1) so that any banners not shown in the top zone are shown in a zone below it, and so on, and so forth.
- Zone 2 is chained to Zone 1, Zone 3 is chained to Zone 2, Zone 4 is chained to Zone 3, etc.
- The invocation code has the "Don't show the banner again on the same page" and "Don't show a banner from the same campaign again on the same page" parameters set to yes.

I've tried adjusting the weights of the campaigns, but can't seem to affect the order of the banners that are shown. For example, I can set all campaigns to weight 1, except for one that is set to 100. When I look at Zone 1's probabilities, I can see that the banner from the campaign with weight 100 has a higher probability than the others. However, the campaign with higher weight seems to show up randomly in the zone list. Certainly not consistently near the top.

**Comment by erikgeurts** [comment]
It appears to me that it would be better suited to post your question on our community forums at http://forum.revive-adserver.com/

**Comment by sikjoy** [comment]
This isn't a question. The weight settings are not functioning properly.

**Comment by erikgeurts** [comment]
Let's discuss this on the forums first. If it turns out to be a bug or some other malfunction, we'll be perfectly happy to reopen this issue.

**Comment by sikjoy** [comment]
I posted something there over a month ago and haven't gotten a response:

http://forum.revive-adserver.com/topic/3790-campaignbanner-probability-in-chained-zones/
