### ISSUE TITLE
An error occurred while accessing the database 

### ISSUE THREAD

**Issue by charlestsmith** [revive-adserver/revive-adserver#731]
I can no longer access our Revive ad server database, and am getting the following error message:

Array ( [filePerms] => File permission errors have been detected, and must be fixed before you can continue.
To fix the errors on a Linux system, try typing in the following command(s):
chmod -R a+w /home/ddwda/domains/openx.ddw-online.com/public_html/var
chmod -R a+w /home/ddwda/domains/openx.ddw-online.com/public_html/var/cache
chmod -R a+w /home/ddwda/domains/openx.ddw-online.com/public_html/var/plugins
chmod -R a+w /home/ddwda/domains/openx.ddw-online.com/public_html/var/templates_compiled
chmod -R a+w /home/ddwda/domains/openx.ddw-online.com/public_html/plugins
chmod -R a+w /home/ddwda/domains/openx.ddw-online.com/public_html/www/admin/plugins
chmod -R a+w /home/ddwda/public_html/www/images

How do I fix this ?

**Comment by erikgeurts** [comment]
Please post your questions on the Community Forums at http://forum.revive-adserver.com
