### ISSUE TITLE
Incorrect impressions and clicks

### ISSUE THREAD

**Issue by tinskey** [revive-adserver/revive-adserver#732]
The metrics for impressions and clicks are not showing proper values.
There are many banners that have 0 impressions but multiple clicks.
It seems like both of these metrics are inflated by a fairly large margin.
We have upgraded to the latest version 3.2.4 (from 3.2.1) and are still having the same issues.
It looks like the data is stored in the database as a snapshot so we don't have granular data to analyze on who's clicking what when.

**Comment by erikgeurts** [comment]
Please consider posting your question on our community forums at http://forum.revive-adserver.com/ (as per the instructions when you posted this issue).
