### ISSUE TITLE
Doubleclick plugin can't inject {clickurl} into https URLs

### ISSUE THREAD

**Issue by magicmulder** [revive-adserver/revive-adserver#735]
Fix is to change definition of $search and $replace in

etc/plugins/openX3rdPartyServers.zip/plugins/3rdPartyServers/ox3rdPartyServers/doubleclick.class.php

to

        $search  = array("/\[timestamp\]/i", "/(http:.*?;)(.*?)/i", "/(https:.*?;)(.*?)/i");
        $replace = array("{random}",      "$1click0={clickurl};$2", "$1click0={clickurl};$2");

(added last array entry in both definitions)

See http://forum.revive-adserver.com/topic/3327-doubleclick-plugin-vs-https/

**Comment by erikgeurts** [comment]
We're actually considering to remove the click tracking abilities for third party AdSense and related tags, see https://github.com/revive-adserver/revive-adserver/issues/565 . This might also affect the ability to track clicks on DoubleClick tags.

**Comment by magicmulder** [comment]
I hope not. We run a lot of these, and having to edit them manually would be a major pain in the rear.

**Comment by erikgeurts** [comment]
@mbeccati That is true, but it is also true that DoubleClick's tags are known to change from time to time, breaking the automatic insertion of the click macro. We've seen it more than once.

**Comment by mbeccati** [comment]
Hmm, the placeholders always seem the same to me, though.

**Comment by erikgeurts** [comment]
I don't have specific examples right now, but I do recall cases from several years back where a third party click tracking integration with DFA suddenly stopped working, and then we traced it back to a change by Google on their side. Knowing Google, this could happen again at any time in the future.

**Comment by mbeccati** [comment]
@erikgeurts sure. It seems to be working now, so we can leave it and keep our users happy until it doesn't anymore ;)

**Comment by magicmulder** [comment]
@mbeccati I second that. :) What good is an adserver if one of its main practical uses (3rd party ads) forces the campaign manager to hack banner codes (or pay $$$ for IT resources) for every such case?
May be a bit of a rat race to adapt to any future change, but better than nothing.

**Comment by erikgeurts** [comment]
I agree with both of you, but please don't blame Revive Adserver if suddenly Google does something unexpected in the future and breaks things (again).

**Comment by magicmulder** [comment]
No biggie. I guess we will have to adapt to changing/new formats in our local installation anyway (we get about 4-5 new ones per month that don't work with Revive out of the box) - and try to give back as much as possible to the codebase. :)
