### ISSUE TITLE
Upgrade from 3.2.2 to 3.2.4 not possible

### ISSUE THREAD

**Issue by mck9** [revive-adserver/revive-adserver#738]
Problem:
When trying to Upgrade from a previous version, the step "2. Administrator Login" does not accept my user/password. The Browser is redirected to step 3, but then back to step 2. No error is shown.

**Comment by erikgeurts** [comment]
Please post your question on our community forums at http://forum.revive-adserver.com/

**Comment by mck9** [comment]
Found it. We installed revive adserver on an internal server. It is accessed by the proxy, so the internal name is not the same as the external. Revive 3.2.3 and later added the hostname to the cookies.

**Comment by erikgeurts** [comment]
Did you see a set of informational items and instructions about adding issues (or rather, not adding issues), when you opened this?

**Comment by mck9** [comment]
Sure. I also did not see the change announced in the changelogs.

**Comment by erikgeurts** [comment]
We recently created a trick to show a set of instructions that were meant to direct people to the right resources before posting an issue here. It's not part of the code, so not part of a change log.

I was hoping it was sufficiently clear from those instructions and tips that your type of question is not really something that should be an issue on Github, but rather a new post on our community forums. Was that not clear enough? How can we improve that?

**Comment by mck9** [comment]
Hi Erik, that's clear to me. I have a different view on the issue. Setting the host part on the cookie is part of the code, so a large warning in the changelog (e.g. "Now you have to run revive on an exposed host! Proxied installations won't work due to setting the hostname in the cookie from version X.X.X on!") would be sufficient.

**Comment by erikgeurts** [comment]
This has been the case for as long as I can remember, so at least a decade. No recent changes, so nothing in the change log. 

However, that was not what I asked about. Was it not clear from the instructions when opening the issue that we have a community forum for your type of questions?

**Comment by mck9** [comment]
www/admin/lib-sessions.inc.php is very recent:

/*-------------------------------------------------------*/
/* Sets an admin cookie                                  */
/*-------------------------------------------------------*/

function phpAds_SessionSetAdminCookie($name, $value)
{
    $conf = $GLOBALS['_MAX']['CONF'];

    return setcookie(
        $name,
        $value,
        0,
        dirname($_SERVER["SCRIPT_NAME"]),
        empty($_SERVER['HTTP_HOST']) ? null : preg_replace('#:\d+$#', '', $_SERVER['HTTP_HOST']),
        !empty($conf['openads']['requireSSL']),
        true
    );
}

and it breaks running revive on an internal host. That's the issue about.

**Comment by erikgeurts** [comment]
I did many upgrades like this, never had any problems. Perhaps your setup is a bit different from what I am used to.
