### ISSUE TITLE
Feature request: duplicate website

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#739]
A customer of ours has suggested that a feature to duplicate a website, and all the zones already defined for that website, might be useful.

**Comment by panos-alp** [comment]
Hello, ou our projects we do the following configuration:
1. A demo / testing Website with Zones
2. The production / live Website with Zones

This way we ensure we can test on demo, without any impact on live environment. The challenge of this approach is that we need to configure a Website first, then duplicate the configuration of the Website and the Zones. The only way we have figured out is go on each Zone > “Duplicate” > “Move to” target Website.

Site duplication would help us clone configuration in an automated way.
