### ISSUE TITLE
Installation failed to create the core tables

### ISSUE THREAD

**Issue by pteague** [revive-adserver/revive-adserver#740]
Installing Revive Adserver 3.2.4 (the tar.gz from the project's site download page & the master branch)

During the database part fill in database information. Select MySQL & ISAM or InnoDB for table type. Click "Continue >>" and after a short period of time a red warning shows up stating "Installation failed to create the core tables".

Checking the var/debug.log it specifically states:

Jul 20 12:07:19 -0500 OX-578fafc290e07 [    error]  _doQuery: [Error message: Could not execute statement]
[Last executed query: CREATE TABLE `rv_application_variable` (`name` VARCHAR(255) DEFAULT '' NOT NULL, `value` TEXT NOT NULL, PRIMARY KEY (name)) ENGINE = INNODB]
[Native code: 1071]
[Native message: Specified key was too long; max key length is 767 bytes]

This is an issue with both MySQL & MariaDB as the index on a VARCHAR(255) is to large. I don't remember when this feature was first introduced, but I've tested against both of the following:

MySQL 5.5.46-0ubuntu0.14.04.2
MariaDB 10.0.25-MariaDB-0ubuntu0.16.04.1

Based on [lib/max/Dal/DataObjects/db_schema.ini](https://github.com/revive-adserver/revive-adserver/blob/master/lib/max/Dal/DataObjects/db_schema.ini#L137) and the variable comment for $name in [lib/max/Dal/DataObjects/Application_variable.php](https://github.com/revive-adserver/revive-adserver/blob/master/lib/max/Dal/DataObjects/Application_variable.php#L24) it looks like the name field should only be 130 characters long? I manually rewrote the create table query so that name is a VARCHAR(130) & it works for both databases:

CREATE TABLE `rv_application_variable` (`name` VARCHAR(130) DEFAULT '' NOT NULL, `value` TEXT NOT NULL, PRIMARY KEY (name)) ENGINE = INNODB

I've spent a good portion of the day trying to figure out how exactly it creates the tables and I'm still not sure what I'm missing. Just as some ideas as to how to fix this I've changed the VARCHAR(255) to VARCHAR(130) in the $name comments. I changed [etc/tables_core.xml](https://github.com/revive-adserver/revive-adserver/blob/master/etc/tables_core.xml#L911) `<length>255</length>` field to `<length>130</length>` and cleared out all the cache & template files in var/cache & var/templates_compiled. I looked at [etc/changes/EncodingMigration.php](https://github.com/revive-adserver/revive-adserver/blob/master/etc/changes/EncodingMigration.php#L78), but there doesn't seem to be a way to set a VARCHAR length there. I went through all of the files in etc/changes/ that mentioned the table & changed the `<length/>` value for name to be 130. I also grep'ed the entire project for "CREATE TABLE", but other than table copies in lib/OA/Upgrade/(DB_Upgrade.php|Migration.php|Upgrade.php) and the expected ones in lib/pear/DB & lib/pear/MDB2.

There are 2 similar issues posted in the forums with a response for more information and no reply.

**Comment by mbeccati** [comment]
It seems like your default charset might be `utfmb4`:

http://stackoverflow.com/questions/6172798/mysql-varchar255-utf8-is-too-long-for-key-but-max-length-is-1000-bytes

As of now, my suggestion is to use the good old utf8 instead, but this deserves some more investigation.

**Comment by pteague** [comment]
Ok, here's a temporary solution as I don't know how to compile or override
the cached binary files... (this works for me for both MariaDB & MySQL I
listed above).

1. open
[etc/tables_core.xml](https://github.com/revive-adserver/revive-adserver/blob/master/etc/tables_core.xml#L911)
and change the application_variable table's name field to have a
`<length>130</length>`.

2. rename `etc/xmlcache` & `etc/permanentcache` to something else (maybe
just append .bak so you'll have them if you need them again later).

3. fill in the Database server section during the install... This should
allow the database to have a small enough size for the max key length on
that field.

**Comment by mbeccati** [comment]
`php scripts/upgrade/buildXmlCache.php` should do what you want. But please bear in mind that Revive Adserver is largely untested with the fairly recent `utf8mb4` charset, so your mileage may vary.

**Comment by 717g301github** [comment]
`create database adserver character set utf8 collate utf8_general_ci;`

It works that way.

**Comment by andrewatfornax** [comment]
Given the above information that suggests that when using the utf8 charset, it works, I'm going to close this ticket, as utf8 is what is specified/required for the database.

**Comment by arnotixe** [comment]
> `create database adserver character set utf8 collate utf8_general_ci;`
> 
> It works that way.

Thanks! or if you have an existing database, like I do where I can only create databases from hosting provider gui, you can modify it:
`ALTER DATABASE <databasename here> CHARACTER SET utf8 COLLATE utf8_general_ci`
