### ISSUE TITLE
Fault Code: 801 Fault Reason: Unknown advertiserId Error

### ISSUE THREAD

**Issue by dipenpatel235** [revive-adserver/revive-adserver#744]
hello..
i have setup elgg 1.8.2  + gutwa plugin
and openx 2.8.10 server

i getting below error
Fault Code: 801 Fault Reason: Unknown advertiserId Error

How can i fix that?

Thanks

**Comment by mbeccati** [comment]
I'm sorry, this is not a bug report for Revive Adserver. You might try our forums, although OpenX Source is unsupported since a long time already.
