### ISSUE TITLE
typo (?) in /www/delivery/asyncjs.php

### ISSUE THREAD

**Issue by cYzzie** [revive-adserver/revive-adserver#747]
after updating to 3.2.4. asyncjs line 38 triggered this error:

 PHP Fatal error:  require(): Failed opening required '/path/to/revive/www/delivery/' (include_path='.:/usr/share/pear:/usr/share/php') in /path/to/revive/www/delivery/asyncjs.php on line 38
require __DIR__.'/'.$GLOBALS['_MAX']['CONF']['file']['asyncjsjs'];

when i changed asyncjsjs -> to asyncjs  it was working fine afterwards

**Comment by mbeccati** [comment]
I'm sorry @cYzzie, this is not a bug. You either didn't properly follow the upgrade instructions or something went wrong as your config file hasn't been properly updated and it's missing some entries.

For further help, please visit our forums.
