### ISSUE TITLE
ck.php redirection

### ISSUE THREAD

**Issue by mdgoerner** [revive-adserver/revive-adserver#748]
Problem:
Having defined a banner's Destination URL I am finding that the URL placed on the web page which calls ck.php results in a failed redirection. It appears there are both "__" and "&" parameter delimiters in the ck.php URL and those parameters delimited by "&" are appended to the Destination URL.

For example, a Destination URL "http://www.example.com" will result in the following URL output to the web page:

https://ads.[mysite].com/www/delivery/ck.php?oaparams=2__bannerid=239__zoneid=14__cb=e2282c87ce__oadest=http%3A%2F%2Fwww.example.com&__hstc=203139086.4c89aee336e577f29963e82a07d427a9.1471547127852.1471547127852.1471561131233.2&__hssc=203139086.9.1471561131233&__hsfp=2181564343

When the banner is clicked and ck.php is called, the resulting redirected URL looks like this:

http://www.example.com%26__hstc%3D203139086.4c89aee336e577f29963e82a07d427a9.1471547127852.1471547127852.1471561131233.2%26__hssc%3D203139086.9.1471561131233%26__hsfp%3D2181564343/?__hstc=203139086.4c89aee336e577f29963e82a07d427a9.1471547127852.1471547127852.1471561131233.2&__hssc=203139086.9.1471561131233&__hsfp=2181564343 but all that is expected is http://www.example.com

The additional parameters on the original ck.php URL following the first "&" (**&__hstc=203139086.4c89aee336e577f29963e82a07d427a9.1471547127852.1471547127852.1471561131233.2&__hssc=203139086.9.1471561131233&__hsfp=2181564343**) appear to be getting URL encoded and appended twice to the Destination URL (**%26__hstc%3D203139086.4c89aee336e577f29963e82a07d427a9.1471547127852.1471547127852.1471561131233.2%26__hssc%3D203139086.9.1471561131233%26__hsfp%3D2181564343/?__hstc=203139086.4c89aee336e577f29963e82a07d427a9.1471547127852.1471547127852.1471561131233.2&__hssc=203139086.9.1471561131233&__hsfp=2181564343**)

This appears to be the result of a recent upgrade since we have not seen this issue in the past.

**Comment by mbeccati** [comment]
I'm sorry, this is not a bug. ck.php works like that by design (i.e. whatever comes after `__oadest=` is the destination URL. You shouldn't be appending stuff to the links in the fisrt place.

**Comment by mdgoerner** [comment]
Hi, Matthew.

I am not appending anything to the link. The Destination URL in the 
banner admin is "http://www.example.com" and the call to ad server in 
the HTML is taken from the Invocation Code from the Zone defined for the 
banner. When the script from the invocation code is called the ck.php 
URL is output as described in the bug report; that is, the URL is 
generated by the ad server.

This is put into the HTML:

<script type='text/javascript'></script>

And this is what is output to the page:

<script type="text/javascript" 
src="https://ads.leafbuyer.com/www/delivery/ajs.php?zoneid=14&cb=28638491787&charset=windows-1252&loc=https%3A//www.leafbuyer.com/listings/dispensaries/CO/Edgewater/1&referer=https%3A//www.leafbuyer.com/&tgt=CO:Edgewater:1:"></script>

<a 
href="https://ads.leafbuyer.com/www/delivery/ck.php?oaparams=2__bannerid=233__zoneid=14__cb=31d369ddc2*__oadest=http%3A%2F%2Fwww.waytogrow.net*&__hstc=203139086.4c89aee336e577f29963e82a07d427a9.1471547127852.1471586947893.1471603710064.5&__hssc=203139086.13.1471603710064&__hsfp=2181564343" 
target="_blank"><img 
src="https://ads.leafbuyer.com/www/images/219955b60614bda53bf61ff7ef2f1499.png" 
width="512" height="80" alt="" title="" border="0"></a>

<div id="beacon_31d369ddc2" style="position: absolute; left: 0px; top: 
0px; visibility: hidden;"><img 
src="https://ads.leafbuyer.com/www/delivery/lg.php?bannerid=233&amp;campaignid=63&amp;zoneid=14&amp;loc=https%3A%2F%2Fwww.leafbuyer.com%2Flistings%2Fdispensaries%2FCO%2FEdgewater%2F1&amp;referer=https%3A%2F%2Fwww.leafbuyer.com%2F&amp;cb=31d369ddc2" 
width="0" height="0" alt="" style="width: 0px; height: 0px;"></div>

Note in the second line, the parameters to the ck.php call have the 
additional parameters I mentioned appended to the URL automatically - 
this is not something that I am including in the Destination URL.

Please reopen this ticket. You have misunderstood the original post and 
the issue does not appear to be one related to the destination URL being 
defined incorrectly:

**Comment by mbeccati** [comment]
I've closed the issue as the bug tracker is not meant for support requests. You might have better luck on our forums and/or disabling the HubSpot tracker scripts you've recently added to the site.

**Comment by mdgoerner** [comment]
Sorry for wasting your time. I realized the HubSpot scripts were the culprit after I responded early this morning and took them out. 

Sent by wireless email
(apologies for any terseness)
