### ISSUE TITLE
how to get the xmlrpc doc. run scripts/updateDocs.sh give errors.

### ISSUE THREAD

**Issue by hackrole** [revive-adserver/revive-adserver#752]
./updateDocs.sh: 57: ./updateDocs.sh: /usr/local/php4/bin/phpdoc: not found

and of cause, I donot understand why it need php4.

**Comment by mbeccati** [comment]
Please have a look at the example client library: 

https://github.com/revive-adserver/revive-adserver/blob/master/lib/xmlrpc/php/openx-api-v2-xmlrpc.inc.php
