### ISSUE TITLE
Update Technical Requirements on 4.0.0 Release

### ISSUE THREAD

**Issue by andrewatfornax** [revive-adserver/revive-adserver#758]
Update the technical requirements listed on the Revive Adserver website at https://www.revive-adserver.com/support/requirements/ with the formal release of Revive Adserver 4.0.0. 

In particular, check/update:

* Minimum required version of PHP
* Supported/required PHP extensions
* MySQL support in PHP 7

**Comment by erikgeurts** [comment]
Will do once v4.0.0 has been finalized after the Releae candidate testing phase.

**Comment by andrewatfornax** [comment]
Yes, sorry, that's what I intended @erikgeurts ! I was just testing out the new GitHub project feature, really :-)

**Comment by erikgeurts** [comment]
That feature seems to work nicely. Still not entirely sure what the added value is on top of the existing Milestone feature.

**Comment by erikgeurts** [comment]
The page at https://www.revive-adserver.com/support/requirements/ has been updated to reflect the new requirements that were introduced with v4.0.0 (with a little help from @mbeccati).
