### ISSUE TITLE
Fails to get database type

### ISSUE THREAD

**Issue by matjaz-elumina** [revive-adserver/revive-adserver#760]
Problem:
I just noticed my PHP error log file is full of errors like this:
[Wed Sep 21 06:11:42.583837 2016] [:error] [pid 1533] [client 82.149.23.23:50727] PHP Fatal error:  require(): **Failed opening required '/adserver/revive324/www/delivery/../../lib/OA/Dal/Delivery/.php**' (include_path='.:/usr/share/php:/usr/share/pear') in /adserver/revive324/www/delivery/lg.php on line 1977, referer: xxx
This happens every minute or so, although the ads are being served more often and I haven't noticed any issues with ads delivery.

Steps To Reproduce:
I have no idea where to start debugging or how to figure out in which case this happens. Any pointers?

Thanks!

**Comment by erikgeurts** [comment]
We have created a community forum where you can post questions like this one and share your expertise about Revive Adserver with others. See http://forum.revive-adserver.com . In this case I suggest posting it here: http://forum.revive-adserver.com/forum/13-managing-revive-adserver/
