### ISSUE TITLE
Language file string missing

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#765]
When a non-blocking problem occurs during an upgrade, the final screen of the upgrade wizard displays a message, but it seems that the appropriate string is missing in the language file:

![image](https://cloud.githubusercontent.com/assets/5102461/19014014/28f7a45c-87e2-11e6-9b3d-22da579d8496.png)

**Comment by mbeccati** [comment]
This should have been fixed in 6e8245
