### ISSUE TITLE
net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by PTIHHI** [revive-adserver/revive-adserver#782]
So our website (linksmagazine.com) is unable to display advertisements today.  I believe the adserver is rejecting the request based on this
"https://adserver.linksmagazine.com/adserver/www/delivery/ajs.php?zoneid=1&cb=60487830152&charset=UTF-8&loc=https%3A//www.linksmagazine.com/ net::ERR_CONNECTION_REFUSED"

I'm able to get it to work if I remove https:// and www. from the address ( I can't get this to work in chrome, but FF and Edge allow me to do this).  

Can someone point me in the right direction for fixing this? It was working and I don't think we changed anything.

**Comment by erikgeurts** [comment]
Please consider posting your question on our community forums at http://forum.revive-adserver.com (as per the instructions you saw when you started posting this issue).
