### ISSUE TITLE
Dates with Excel Export for Statistics 

### ISSUE THREAD

**Issue by alxgnz** [revive-adserver/revive-adserver#785]
It would be nice to have a column for a timestamp or dates.

**Comment by erikgeurts** [comment]
Can you please describe your request in more detail and perhaps include some screenshots of the report(s) with highlight of what is missing?

**Comment by andrewatfornax** [comment]
No feedback from @alxgnz, so closing for now. Happy to re-open if we can please have some more details on the request...
