### ISSUE TITLE
MaxMind geo targeting plugin does not support "cellular" value of "netspeed" field

### ISSUE THREAD

**Issue by FirstImpression** [revive-adserver/revive-adserver#792]
MaxMind's "Connection Type" database along with 'dialup','cabledsl' and 'corporate' also has 'cellular' value, which is missing in geo delivery limitations plugin.

**Comment by mbeccati** [comment]
Hmm, are you sure that's not GeoIP2? They haven't updated their libraries, not even the C one:

https://github.com/maxmind/geoip-api-c/blob/0cfb181ff20ad9297e745318fdb9f484ba86cd0c/libGeoIP/GeoIP.h#L154

**Comment by FirstImpression** [comment]
Now when you ask it I am not so sure, but:

http://us3.php.net/manual/en/function.geoip-netspeedcell-by-name.php - states "cellular" as one of values

Legacy PHP API has an example called "netspeedcell":
https://github.com/maxmind/geoip-api-php/blob/master/examples/netspeedcell.php

Although, I haven't purchased the database yet to check for myself, because not sure if this functionality is supported by Revive,.

**Comment by mbeccati** [comment]
Confirmed, GeoIP2 only:

https://github.com/maxmind/GeoIP2-php/blob/master/src/Record/Traits.php#L24

Closing this ticket.
