### ISSUE TITLE
Ads are not displayed with mysqli and socket defined in 4.0.0. fresh install

### ISSUE THREAD

**Issue by mmetatron** [revive-adserver/revive-adserver#794]
revive 4.0.0 fresh install only + mysqli + use socket = ads are not displayed

Everything else works fine.

delivery.log:
OX-delivery-5856c9279cc3d: DB connection error:

Setting socket= as undefined solved the situation.
However, when upgraded to 4.0.0. from 3.2.5 works fine, even with socket defined.

Tested with php 5.6 and php 7.0 latest versions, all requirements met.

**Comment by erikgeurts** [comment]
Please consider posting your question on the Community Forums at https://forum.revive-adserver.com

**Comment by mmetatron** [comment]
It's not a question. I have found a bug (and workaround). Hope it helps.

**Comment by erikgeurts** [comment]
If you have found a bug, there are no details on it in your initial post. Please feel free to submit a PR with your fix, and additional details to reproduce the situation you discovered.

**Comment by mmetatron** [comment]
All the details are up there, what else do you need?

**Comment by mmetatron** [comment]
If I just rephrase:

Reproduction:
- revive version 4.0.0
- fresh install
- select mysqli and socket in installation procedure

Result:
Everything works fine, just ads are not displayed.

delivery.log:
OX-delivery-5856c9279cc3d: DB connection error:
(no details on error)

Workaround:
Ads are displayed when setting socket to undefined (socket=).

Tested on php 5.6 and 7.0.

It doesn't happen with Revive 3.2.5 or after upgrading from 3.2.5. to 4.0.0. In that case works fine, even when using the socket with msqli.

**Comment by mbeccati** [comment]
I'm on mobile now and I can't properly check, but isn't this a duplicate of #771 ?

**Comment by mmetatron** [comment]
Yes. Ok then ;-)
