### ISSUE TITLE
Verification of E-mail address on forum.revive-adserver.com possible

### ISSUE THREAD

**Issue by jack7415** [revive-adserver/revive-adserver#796]
On page https://forum.revive-adserver.com/lostpassword/ a malicious user can verify if a particular E-mail address is registered on https://vimeo.com/.

Steps to reproduce for

1.Open https://forum.revive-adserver.com/lostpassword/
2.Enter non existing E-Mail Address
3.Press enter
Result: The error message discloses, that the submitted E-Mail address is not known. message:: We could not find a member account with that email address. Please verify the information and resubmit the form.

An attacker can try different E-Mail addresses and can test if they are registered or not, helping him in a brute-force attack.
![Picture in error message ](https://cloud.githubusercontent.com/assets/19896376/21541625/873db46a-cdc0-11e6-969f-6818549684ca.png)

**Comment by mbeccati** [comment]
I'm sorry, this is not a Revive Adserver issue. Please contact the IPB4 support for that.
