### ISSUE TITLE
Advertiser stats "View by" not working on PHP7

### ISSUE THREAD

**Issue by mreiden** [revive-adserver/revive-adserver#798]
After upgrading from 3.2.2 to 4.0.0, trying to view advertiser stats by month does not work.  The problem (at least on our install) is that the select has a blank name attribute `<select name="" onchange="this.form.submit()">` which obviously needs to be `<select name="statsBreakdown" onchange="this.form.submit()">`.

**Comment by mbeccati** [comment]
Confirmed. However I can't quickly understand why that's happening...

**Comment by mbeccati** [comment]
I can replicate the issue with PHP7+, wheres the dropdown works just fine with PHP5.

Nothing changed in the related code between 3.2 and 4.0, so it will take some effort to figure out why this happens. The name attribute should be automatically carried over, but it isn't.
