### ISSUE TITLE
I can't install geo plugins

### ISSUE THREAD

**Issue by danicasati** [revive-adserver/revive-adserver#800]
It is not possible to add GEO PLUGINS.
I've downloaded
- openXMaxMindGeoIP
- openXMaxMindModGeoIP

from /plugins_repo/, then I've tried to install and uploaded manually into /PLUGINS/ folder.

I can't install them into Revive.

**Comment by erikgeurts** [comment]
Have you considered posting your support question on our Community forums at https://forum.revive-adserver.com ?

**Comment by 8secz-johndpope** [comment]
seems like you need to follow instructions from here https://github.com/revive-adserver/revive-adserver/issues/513

"You can create a zip package running ./package.sh openXMaxMindModGeoIP in the plugins_repo folder of your local git clone"
