### ISSUE TITLE
Request for new feature a separate logins for Advertisers and Website-Owners from front-end to ease admin.

### ISSUE THREAD

**Issue by mdk007** [revive-adserver/revive-adserver#801]
Request for separate logins for Advertisers and Website-Owners from front-end to ease admin

**Comment by andrewatfornax** [comment]
Can separate logins for Advertisers and Websites not already be created, so that these users can log in and see the details of just their own stats, etc.?

**Comment by erikgeurts** [comment]
Yes, that's already a feature. I think what the original question is about, is giving such users more functionality, like creating campaigns and banners, or like creating zones. I'm not in favor of adding such functionality, by the way.

**Comment by andrewatfornax** [comment]
Oh, so more like allowing Revive Adserver to be a self-service solution for 3rd parties?

**Comment by erikgeurts** [comment]
It seems so. And as said, I am not in favor of self-service functionality.

**Comment by mdk007** [comment]
ok
