### ISSUE TITLE
Unable to login - screen white

### ISSUE THREAD

**Issue by jeroenla** [revive-adserver/revive-adserver#802]
We prefer to use Github issues only for reporting of actual bugs, or for requests for new features (preferably by means of a pull request).
Before submitting an issue, please check the following:
- You are using in the latest version of Revive Adserver.
- You have reviewed the information and guidelines for reporting bugs at https://www.revive-adserver.com/support/bugs/
- You have reviewed the documentation pages at http://documentation.revive-adserver.com/
- You have reviewed the FAQ page at https://www.revive-adserver.com/faq/ to ensure your case is not already answered there.
- You have searched the Community Forums at http://forum.revive-adserver.com/ for any answers to your problem or question.
- If it's not a bug, but rather a question, please post your topic at http://forum.revive-adserver.com/

If you've gone through all of the above, and are convinced you should open an issue to report a bug, then follow these guidelines:
- Properly format the issue title – `Scope :: One short and clear sentence to describe the issue`.
- Provide a detailed description of the issue.
- Provide any/all relevant information: screenshot, screencast.
- Provide the steps that one must take to reproduce the issue.

Please make sure that your issue is detailed, otherwise it will not be prioritized due to lack of information.

Problem:
{Replace this with a description of the issue you are reporting. Be sure to explain expected results vs. actual results when it might not be obvious to those who will read your report.}

Steps To Reproduce:
{Replace this with a detailed description of the steps to reproduce the issue}

**Comment by erikgeurts** [comment]
Closing this issue since there is no content. Please consider posting your question on the Community Forums at http://forum.revive-adserver.com
