### ISSUE TITLE
Update sample video URLs while creating a new inline video ad

### ISSUE THREAD

**Issue by erikgeurts** [revive-adserver/revive-adserver#803]
While creating a new Inline video ad, the user interface shows some same video ad file file URLs:
![image](https://cloud.githubusercontent.com/assets/5102461/22107173/abcfd500-de4c-11e6-8f0d-e1da3654399a.png)

Some of these URLs don't exist anymore, others are very much outdated.

I recently came across a website that lists a few short (5 second) video files that can be used as samples. The page is at http://techslides.com/sample-webm-ogg-and-mp4-video-files-for-html5

We could consider updating the sample ads listed in the UI, either to the URLs on that page, or by actually hosting a video ad in a number of video formats ourselves on a subdomain of revive-adserver.com and using those in the UI.

**Comment by mketan** [comment]
I was creating zone using Inline Video ad but i stuck in video invocation code I didn't get invocation code in video  invocation code tab.

I got this note in video  invocation code tab

# Note: Zone invocation codes are not used for Video Ads. 
Instead, you must include the zone in the Ad Schedule of the video player plugin configuration in your webpage. 
Please refer to the Video Ads Plugin User Guide for instructions.


Then I was trying using other way that is

[my domain]/www/delivery/fc.php?script=bannerTypeHtml:vastInlineBannerTypeHtml:vastInlineHtml&format=vast&nz=1&zones=pre-roll%3D2

Then  I got VideoAdServingTemplate xml file from it but I don't understand how should I run that file ? Please help me.

Regards,
Ketan Mahajan

**Comment by erikgeurts** [comment]
Please post your questions on the community forums at https://forum.revive-adserver.com.

**Comment by andrewatfornax** [comment]
@erikgeurts, I had a look at this, but it looks like those videos are all only available via HTTP, so I suspect we want to go down the path of creating some new ones, and hosting them ourselves so that we can offer examples that are both HTTP and RTMP?

**Comment by andrewatfornax** [comment]
Howevever, I have a reasonable solution for the 4.0.2 release. Rather than leaving the broken examples in place, I am going to remove them from the Revive Adserver UI. To be honest, once you know what you are doing, the big example box just gets in the way, and obscures the fact there are options further down the page!

Instead, we can update the online documentation for Inline Video Banners with examples, once they are ready.
