### ISSUE TITLE
Maybe _getChainZones() should also return zones that are -1x-1 ( * x * ) ?

### ISSUE THREAD

**Issue by FirstImpression** [revive-adserver/revive-adserver#804]
If you create a zone with size *x*, you are unable to set it as a backup zone in zone settings
"If no banners from this zone can be delivered, try to...	Display the selected zone instead:".

Will it be an acceptable change to add dynamic zones to the end of drop-down list of zones to chain? I can create a pull request.

**Comment by mbeccati** [comment]
Sounds reasonable to me.
