### ISSUE TITLE
mysqli Warning in API

### ISSUE THREAD

**Issue by wt69** [revive-adserver/revive-adserver#811]
Version 4.0.1
Problem:
myqli Warning produces invalid XML_RPC Response.

Steps To Reproduce:
Config Option:
```
[debug]
production=0
```

Code in own App:
`$service = new OA_Api_Xmlrpc($xmlRpcHost, $webXmlRpcDir, $username, $password, 0, FALSE, 90);`

Activate client debug in
\OA_Api_Xmlrpc::_send
`$client->setdebug(1);`

Result:
```
---SENT---
POST /www/api/v1/xmlrpc/LogonXmlRpcService.php HTTP/1.0
User-Agent: PEAR XML_RPC
Host: myadserver.example.com
Content-Type: text/xml
Content-Length: 242

<?xml version="1.0" encoding="UTF-8"?>
<methodCall>
<methodName>logon</methodName>
<params>
<param>
<value><string>username</string></value>
</param>
<param>
<value><string>password</string></value>
</param>
</params>
</methodCall>

---END---

---GOT---
HTTP/1.1 200 OK
Date: Mon, 06 Feb 2017 11:17:58 GMT
Server: Apache
Set-Cookie: sessionID=e8ef29cc25df0b235a236bf11f00d260; path=/www/api/v1/xmlrpc; domain=myadserver.example.com; httponly
Content-Length: 174
Connection: close
Content-Type: text/xml; charset=UTF-8
MESSAGE: mysqli_query(): (42000/3057): Incorrect user-level lock name 'OA_auth.21232f297a57a5a743894a0e4a801fc3.a90f5f54299fba00feac96c95dbf800c200759bc'.
TYPE: Warning
FILE: /var/www/myadserver.example.com/lib/pear/MDB2/Driver/mysqli.php
LINE: 727
DEBUG INFO:
722
723         if ($this->options['multi_query']) {
724             $result = mysqli_multi_query($connection, $query);
725         } else {
726             $resultmode = $this->options['result_buffering'] ? MYSQLI_USE_RESULT : MYSQLI_USE_RESULT;
727             $result = mysqli_query($connection, $query);
728         }
729
730         if (!$result) {
731             $err =& $this->customRaiseError(null, null, null,
732                 'Could not execute statement', __FUNCTION__);
<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<params>
<param>
<value><string>e8ef29cc25df0b235a236bf11f00d260</string></value>
</param>
</params>
</methodResponse>
---END---
```

**Comment by FirstImpression** [comment]
@wt69, what is the version of MySQL server?

**Comment by wt69** [comment]
It is version 5.7.14-8

**Comment by FirstImpression** [comment]
Could you please try changing lib/OA/DB/AdvisoryLock.php, line 206 to:
`$sId = substr(sha1($this->oDbh->getDsn().'/'.$aConf['table']['prefix']), 0, 64);`
And see if it works.

**Comment by wt69** [comment]
No, sorry, does not work. Same Warning.

**Comment by wt69** [comment]
![image](https://cloud.githubusercontent.com/assets/5772586/22650379/4bda8ec4-ec7f-11e6-99e5-2ccf13748a26.png)

The Warning:
`mysqli_query(): (42000/3057): Incorrect user-level lock name 'OA_auth.21232f297a57a5a743894a0e4a801fc3.a90f5f54299fba00feac96c95dbf800c200759bc`

**Comment by FirstImpression** [comment]
Revert line 206 and try to replace the "return" statement (line 208) to:
`return substr("OA_{$sName}.{$sId}", 0, 64);`

This will definitely give lock name that is supported in MySQL 5.7, which is no longer than 64 character.

**Comment by wt69** [comment]
Yeah, this works!
Will this fix available in the next release?
Thank you.

**Comment by FirstImpression** [comment]
I am not on Revive developers team, but this definitely can be reported as an issue.

**Comment by wt69** [comment]
Ok, thank you. Maybe @mbeccati can take a look an it?

**Comment by mbeccati** [comment]
Nice find!

However, I believe that 
```
[debug]
production=0
```
will break many more things.

I haven't used it in quite a while and we should probably get rid of it. What do you think @andrewatfornax ?

**Comment by NiketaNraval90** [comment]
This still create more that 64 character

can I use below code for above issue?
`return  substr(sha1($this->oDbh->getDsn().'/'.$aConf['table']['prefix']), 0, 64);`

**Comment by mbeccati** [comment]
@NiketaNraval90 How can `substr("OA_{$sName}.{$sId}", 0, 64);` return more than 64 chars?

**Comment by NiketaNraval90** [comment]
You are right @mbeccati the above line is different,my mistake


Thanks @mbeccati
