### ISSUE TITLE
CORS Issue Access-Control-Allow-Origin * not work with https

### ISSUE THREAD

**Issue by elaur** [revive-adserver/revive-adserver#814]
Hello,

Problem:
> XMLHttpRequest cannot load https://r.website.com/www/de/asyncspc.php?zones=1&prefix=revive-0-&loc=http%3A%2F%2Fother-website.com%2Ftest.html. The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'null' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

This was happen just when I move my adserver over ssl/https. My adserver is running from wildcard https://r.example.com. Before to move to https everything was perfect.
I have made this config change in nginx server https://enable-cors.org/server_nginx.html and the same, not work.

Steps To Reproduce:
-You are currently using Revive Adserver v4.0.1 running on nginx 1.11.10, PHP 7.0.16-1~dotdeb+8.1 and MySQL 5.5.5-10.1.21-MariaDB.
-Run the adserver with https from wildcard domain and the banners will not display, will receive above error.
-SSL Certificare generated by letsencrypt.

Possible Bug?
I have search everything on the forum, docs ... nothing useful.

**Comment by mbeccati** [comment]
Thanks for the report. This sounds like a bug to me. We'll check soon.

**Comment by martinkrcho** [comment]
I have been fighting the same issue for the past 2 days. I migrated from 3.2.0 to 4.0.0 and managed to "fix" it temporarily by changing line 4357 in www/delivery/asyncspc.php from...

`if (!empty($_SERVER['HTTP_ORIGIN']) && preg_match('#https?://#', $_SERVER['HTTP_ORIGIN'])) {`
...to...
`if (!empty($_SERVER['HTTP_ORIGIN'])) {`

I realize this is just a temporary fix and it should probably check if the value of the origin in the request matches the regular expression or is "null" (probably string not an actual PHP null).

I hope this helps the Revive team to come up with a long-term fix.

**Comment by ewsindia** [comment]
Please fix this bug as soon as possible. I am also facing same issue on 4.0.1 version. on https its failing and showing CORS error.

**Comment by ewsindia** [comment]
@mbeccati  - This issue only if you are using http for website and you trying to access ads over https.
if your website is also https then CROS error won't appear.

**Comment by mbeccati** [comment]
@ewsindia thanks for the clarification!

**Comment by mbeccati** [comment]
Sorry, I think the bug is due to a misconfiguration of your web servers, overriding Revive's own CORS headers.

I've tested both from http and https and the CORS headers were just fine, e.g.


```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://example.com
```

and:

```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://example.com
```
