### ISSUE TITLE
Call to undefined function dl()

### ISSUE THREAD

**Issue by AlbertoMApps** [revive-adserver/revive-adserver#815]
`Issue trying to connect to adserver with new version:   Fatal error: Uncaught Error: Call to undefined function dl() in /homepages/20/d497560162/htdocs/theadon/revive/lib/pear/PEAR.php:758 Stack trace: #0 /homepages/20/d497560162/htdocs/theadon/revive/lib/pear/MDB2/Driver/mysql.php(400): PEAR->loadExtension('mysql') #1 /homepages/20/d497560162/htdocs/theadon/revive/lib/OA/DB.php(196): MDB2_Driver_mysql->connect() #2 /homepages/20/d497560162/htdocs/theadon/revive/www/admin/config.php(24): OA_DB::singleton() #3 /homepages/20/d497560162/htdocs/theadon/revive/www/admin/index.php(17): require_once('/homepages/20/d...') #4 {main} thrown in /homepages/20/d497560162/htdocs/theadon/revive/lib/pear/PEAR.php on line 758`

**Comment by AlbertoMApps** [comment]
Issue back using new version, thanks.

**Comment by mbeccati** [comment]
Your adserver is configured to use the mysql extension, which is not available by default on PHP7+. Please update the conf file to use mysqli instead.
