### ISSUE TITLE
Error Upgrading from 4.0.0 to 4.0.1 - No Stats, No Bannerpreview in ACP

### ISSUE THREAD

**Issue by SLM66** [revive-adserver/revive-adserver#816]
Revive Adserver is located on a subdomain ads.domain.de

My Installation Steps:

Old Version 4.0.0 -> Folder renamed
New Version uploaded and set to /adserver (wich looks at ads.domain.de)

- Start Upgrade - Step 1, copy old ads.domain.de.conf.php in new /var folder
- Step 2 - Database password entered
- Step 3 - added Path to previous Revive Adserver installation & set data for System Administrator Account - continue -> Get Error:

----------------------------

> An error occurred while accessing the database
> 
> Due to a problem with the database Revive Adserver couldn't retrieve or store data. If this problem is reproducable it might be caused by a bug in Revive Adserver. Please report the following information to the creators of Revive Adserver. Also try to describe the actions that led to this error as clearly as possible.
>  
> Version:    	Revive Adserver v4.0.1
> PHP/DB: 	PHP 5.6.29-0+deb8u1 / MySQL 5.5.54-0+deb8u1
> Page: 	/www/admin/install.php
> Error: 	Duplicate entry 'xxx' for key 'rv_users_username'
> Query: 	
> 
> INSERT INTO rv_users (contact_name , email_address , username , password , language , default_account_id , date_created , email_updated ) VALUES ('Administrator' , 'ads@domain.de' , 'xxx' , '12237f9088c1417ea56846ff9596cac9' , 'de' ,  41 , '2017-02-25 02:37:52' , '2017-02-25 02:37:52' ) 
> 
> $_POST: 	
> 
> Array
> (
>     [_qf__install-config-form] => 
>     [action] => configuration
>     [moreFieldsShown] => 1
>     [previousPath] => /home/xxx/html/adserver4
>     [adminName] => xxxx
>     [adminPassword] => xxxxx
>     [adminPassword2] => xxxxx
>     [adminEmail] => ads@domain.de
>     [adminLanguage] => de
>     [prefsTimezone] => Europe/Berlin
>     [webpathAdmin] => ads.domain.de/www/admin
>     [webpathDelivery] => ads.domain.de/www/delivery
>     [webpathImages] => ads.domain.de/www/images
>     [webpathDeliverySSL] => ads.domain.de/www/delivery
>     [webpathImagesSSL] => ads.domain.de/www/images
>     [storeWebDir] => /home/xxx/html/adserver/www/images
>     [save] => Continue »
> )
> 
> $_GET: 	
> 
> Empty

----------------------
**-> Now Log on administration area  ->**

 
_

> Detected Revive Adserver 4.0.1
> Revive Adserver is up to date
> 
> Your Revive Adserver database and file structure are both using the most recent version and therefore no upgrade is required at this time. Please click Continue to proceed to the administration panel.

_

 

- No banners are displayed in the admin area (preview).
- Banners are displayed on managed websites
- No statistics are displayed

-> What can I do now?

**Comment by hogiro** [comment]
Did you backup the database and the files? 
if you copied the conf File, why did you need to give the Database password again?

If you have backups, just restore the database from the backup and use the old files again, so you will be able to upgrade again. 

if not contact me, I will try to help you

**Comment by SLM66** [comment]
@hogiro Ich denke wir können deutsch miteinander schreiben. Backup habe ich dieses mal leider keines angelegt, da die letzten Updates reibungslos verliefen. Wie kann man dich erreichen? Hier gibt es keine direkte Kontaktmöglichkeit. Oder übersehe ich da was?

**Comment by erikgeurts** [comment]
Please note that our Github pages are not a support forum. Please consider moving this to https://forum.revive-adserver.com which was specifically created for this type of matter.
