### ISSUE TITLE
Fresh install but install.log shows openXBannerTypes(): Permissions error

### ISSUE THREAD

**Issue by ntkntk2** [revive-adserver/revive-adserver#817]
Hello,
I have the following system - centos Linux 7.3, php 7.0.16,  MariaDB-10.1.21, apache server that always redirect to the https connection. I'm new to Revive , bit for my client I have to install Revive in a sub directory of the main domain. 
When I make fresh install of Revive I always end with the warning in the web installer that something is not installed, but I can continue and that I should check in install.log
--------content of install log -------------------------------
Database settings and permissions are OK
creating upgrade_action audit table
successfully created upgrade_action audit table
creating database_action audit table
successfully created database_action audit table
schema definition from cache TRUE
Installation created the core tables
Installation updated the schema version to 621
Installation updated the application version to 4.0.1
Preparing to set timezone preference...
Found timezone preference ID of 16
Found the admin account's timezone association, updating preference...
Updated the admin account timezone preference to: 'Europe/Sofia'
#! openXBannerTypes(): Permissions error
#! openXDeliveryLimitations(): Permissions error
#! openX3rdPartyServers(): Permissions error
#! openXReports(): Permissions error
#! openXDeliveryCacheStore(): Permissions error
#! openXMaxMindGeoIP(): Permissions error
#! openXInvocationTags(): Permissions error
#! openXDeliveryLog(): Permissions error
#! openXVideoAds(): Permissions error

I can login into admin interface and seems everything looks working but these modules are missing.
Having these errors for me means that the installation is not in working condition and I can't give it to the client.  I have read a lot for such a problems and probably they are related to the database that I have  MariaDB 10.1.21. 
My question is - can someone confirm that these permission errors are related to mariadb or the verision of mariadb and if this is a true to fix the installer. 
I have tested it on another server that has the same configuration and have received the same errors in install.log file. 

Another question - I saw a lot of .htaccess files protecting directories from opening if you are using apache. If I use nginx (that do not read these .htaccess files) is there in installer some warnings or ready configuration that can be applied to nginx in order to protect these directories?

regards
Nikolay Kabaivanov

**Comment by erikgeurts** [comment]
Please consider posting your question on the Community Forums at https://forum.revive-adserver.com
