### ISSUE TITLE
Undefined globals in some delivery limitation plugins

### ISSUE THREAD

**Issue by mvdklip** [revive-adserver/revive-adserver#820]
**Problem:**
I found some delivery limitation plugins which refer to language GLOBALS defined in lib/max/language/*/default.lang.php while working on the [Revive Adserver REST API](https://www.reviveadserverrestapi.com/). The problem is that these GLOBALS are not defined when the delivery limitation plugins are being used in the context of a Dll request.

**Steps To Reproduce:**
The API is targeting lib/OA/Dll/Banner.php, calling its [setBannerTargeting](https://www.reviveadserverrestapi.com/api-documentation/management-functions/banner-management/) method. At some point plugins/deliveryLimitations/Time/Date.class.php is loaded which constructor refers to $GLOBALS['strEqualTo'], $GLOBALS['strDifferentFrom'], etc. Those GLOBALS are however not defined in this context and the operators are set to a null value.

Now when calling the [setBannerTargeting](https://www.reviveadserverrestapi.com/api-documentation/management-functions/banner-management/) method with this data for example:
```
[
    {
        "logical": "and",
        "type": "deliveryLimitations:Time:Date",
        "comparison": ">=",
        "data": "20170301@UTC"
    }
]
```
This leads to a "Unknown operator" error from checkComparison in lib/OX/Extension/deliveryLimitations/DeliveryLimitations.php because it checks the existence of operators using 'isset' (which returns false on a null value).

**Comment by mvdklip** [comment]
Note that a possible fix/workaround could also be to update checkComparison to use array_key_exists instead of isset.

**Comment by mbeccati** [comment]
I'm sorry, the issue is in the REST API itself. The built-in XML-RPC API properly loads the language files.
