### ISSUE TITLE
"Text below image" doesn't appear on page

### ISSUE THREAD

**Issue by fchris82** [revive-adserver/revive-adserver#823]
The text below image appear on the admin preview, but doesn't appear on the "real page".

Revive version: **4.0.1**
Invocation type: **Asynchronous JS tag**

Steps To Reproduce:
- Create a zone and a banner with "text below image" --> the text appear on admin preview!
- Create a simple `test.html` with copied code from http://revive.loc/www/admin/zone-invocation.php?affiliateid=1&zoneid=1 :
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<!--/*
  *
  * Revive Adserver Asynchronous JS Tag
  * - Generated with Revive Adserver v4.0.1
  *
  */-->
<ins data-revive-zoneid="1" data-revive-id="2364a164e08008afe9e1d1ae7b4c0316"></ins>
<script async src="//revive.loc/www/delivery/asyncjs.php"></script>

</body>
</html>
```
The banner image is appearing but the text doesn't.

**Comment by erikgeurts** [comment]
This is caused by the fact that the banner is rendered inside an inline frame. The text below the banner doesn't fit inside that iframe, and thus it is invisible (although the browser does actually render it).

**Comment by erikgeurts** [comment]
By the way, this kind of topic would be better suited for the community forums at https://forum.revive-adserver.com

**Comment by mbeccati** [comment]
This might even be considered a bug, but:

1. who really uses text below banners in modern advertising?
2. I wouldn't know how to work around the iframe limitation, unless we make it bigger
3. You could mark the specific banner as not iframe safe

**Comment by dexter75** [comment]
HONcode demands that below banner must write advertisement, it is not possible to get certification of the web without it.

**Comment by Metamas001** [comment]
@erikgeurts fchris82 can not comment now, but his reply:

The generated source from browser:

```html
<ins style="text-decoration: none;">
    <a href="http://revive.loc/www/delivery/ck.php?oaparams=2__bannerid=1__zoneid=1__cb=61fcc37edd__oadest=http%3A%2F%2Findex.hu" target="_blank">
         <img src="http://revive.loc/www/images/0f99837e7297c6654ae7355674c7406f.jpg" width="633" height="138" alt="Alt text" title="Alt text" border="0">
    </a>
    <div id="beacon_61fcc37edd" style="position: absolute; left: 0px; top: 0px; visibility: hidden;">
        <img src="http://revive.loc/www/delivery/lg.php?bannerid=1&amp;campaignid=1&amp;zoneid=1&amp;OAZCAP=99999&amp;OASZCAP=99999&amp;loc=http%3A%2F%2Frevive.loc%2Ftest.html&amp;cb=61fcc37edd" width="0" height="0" alt="" style="width: 0px; height: 0px;">
    </div>
</ins>
```
I don't see iframe anywhere. This look like a bug. I repeat, the text appear on the admin preview!

**Comment by erikgeurts** [comment]
This is not async zone invocation code, this is:
```
<ins data-revive-zoneid="1" data-revive-id="2364a164e08008afe9e1d1ae7b4c0316"></ins>
<script async src="//revive.loc/www/delivery/asyncjs.php"></script>
```

If you inspect this in the browser, you will see it renders the ad in an iframe.

**Comment by Metamas001** [comment]
@erikgeurts please see below fchris82 answer:
OK, I uploaded it a server. Here is the test.html: http://revive.fchris82.amapa.webtown.hu/test.html . Where is the iframe? Here is the HTML source:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--/*
  *
  * Revive Adserver Asynchronous JS Tag
  * - Generated with Revive Adserver v4.0.1
  *
  */-->
<ins data-revive-zoneid="1" data-revive-id="dd7e19b0c7831ffcb1691da550154462"></ins>
<script async src="//revive.fchris82.amapa.webtown.hu/www/delivery/asyncjs.php"></script>
</body>
</html>
```

**Comment by erikgeurts** [comment]
It seems you have since disabled the checkbox indicating the banner is iframe safe?

**Comment by Metamas001** [comment]
@erikgeurts  I don't remember this kind of changes. You can login and see the options with admin - admin.

**Comment by erikgeurts** [comment]
Are you aware that you're posting your sysadmin credentials on a public page?

It is not impossible that someone has already compromised your server by now.

**Comment by fchris82** [comment]
Yes, I know the risks. This was my choice. If you see the admin, I will
delete whole page.

2017-03-29 15:12 GMT+02:00 Erik Geurts <notifications@github.com>:

**Comment by erikgeurts** [comment]
It's not just the Revive Adserver system that may have been compromised, but with it now the entire server it is installed on...

**Comment by fchris82** [comment]
Ok, I moved the directory. Did you find anything?

2017-03-29 15:28 GMT+02:00 Erik Geurts <notifications@github.com>:

**Comment by erikgeurts** [comment]
You don't get it. Once someone is able to log in as an administrator on your Revive Adserver system, they can infect the entire server, operating system, and everything else on the machine.

**Comment by fchris82** [comment]
Really? Somebody can something with an admin account? Yes, maybe in theory;
or something is very wrong in Revive code. I know the risks. But focus on
the original problem. The text doesn't appear despite of there isn't iframe
anywhere.

2017-03-29 15:38 GMT+02:00 Erik Geurts <notifications@github.com>:

**Comment by andrewatfornax** [comment]
As per your comment above @mbeccati, it certainly looks like a bug - I can't find any invocation method that allows the text under the banner to work.

So, I suspect this means that either we need to fix the issue where possible, based on invocation tag type (this must be possible - it worked for some tags before, right?), or, we decide that this is not a feature we want to support any more, and deprecate the feature.

Thoughts?

**Comment by andrewatfornax** [comment]
Discussed this with @mbeccati, and he's going to take a look to see why/when this stopped working. Based on that, we will talk further about fixing or deprecating.

However, just to be clear, if we do fix, then this feature will not work with some tags like Async JS, so it would only be a feature for some tag types.

As a result, we're likely to lean more towards deprecating the feature, as there are easier ways to do this in the site HTML if this is something the site has to do (or, put the text required in as part of the banner).

**Comment by Metamas001** [comment]
Good news, thanks. We are waiting for the results.

**Comment by mbeccati** [comment]
I've had a look and the feature is perfectly working with the invocation types that can support it. Namely the (old) Javascript tags. It is not turned on by default and you'll need to enable it when generating the invocation code:

![immagine](https://cloud.githubusercontent.com/assets/282388/24741404/07b3e876-1aa6-11e7-8fb9-86aeca9da964.png)

Unfortunately it can't be safely enabled for all banner types with asynchronous tags, so my preference would be not to put it as an option. In any case, you can try to manually enable it, by adding `data-revive-withtext="1"` to the `<ins>` tag of the async invocation code.

**Comment by fchris82** [comment]
Thank you for your answer! It's working! :)

2017-04-06 8:54 GMT+02:00 Matteo Beccati <notifications@github.com>:

**Comment by andrewatfornax** [comment]
Wow, ace - thanks @mbeccati.

I'm just re-opening this to remind me to update the documentation to capture this info on the banner page, because this is relevant - we need to highlight that this feature only works for some tag types, and requires a step to enable during tag generation!

I aim to do that next week...

**Comment by andrewatfornax** [comment]
Okay! We already had documentation about the "show text below banner" tag setting on https://documentation.revive-adserver.com/display/DOCS/Tag+Settings, so I have updated the two pages for banners that support "text below banner" to note that the tag setting needs to be enabled (and, of course, the correct tag type needs to be used).

See:

- https://documentation.revive-adserver.com/display/DOCS/SQL+and+web+banners
- https://documentation.revive-adserver.com/display/DOCS/URL+banners
