### ISSUE TITLE
installation errors and unable to sign up on forum

### ISSUE THREAD

**Issue by vesper8** [revive-adserver/revive-adserver#824]
Just got the latest download from the website (not from github) as is suggested.

Ran into a few issues on the initial page, basically it said that I was missing write permissions and to run these two commands to fix the problem:

chmod -R a+w /home/forge/revive.mydomain.com/var/templates_compiled
chmod -R a+w /home/forge/revive.mydomain.com/www/admin/plugins

but upon trying to run these commands I got errors because neither of those folders actually exist. Perhaps this is because what I did to install the software was to first commit it to a bitbucket repository and then then attach it to my new vhost I created for it.. and since these two folders are empty they did not get added to the repository. A small fix to prevent this for other users would be to add a .gitempty (or .gitignore) to prevent empty folders from being discarded by git

I was then able to install but once it got to the part where it installs plugins, most if not all plugins failed to install and gave me these errors

```
Installation of plugin "openXDeliveryLog" failed:
Invalid source path to plugin dataobjects /home/forge/revive.mydomain.com/var/plugins/DataObjects/
Failed to implement dataobjects for oxDeliveryDataPrepare
Task failed _registerSchema
Failed to write /home/forge/revive.mydomain.com/var/plugins/DataObjects/db_schema.ini
Failed to recreate old dataobject cache
Invalid source path to plugin dataobjects /home/forge/revive.mydomain.com/var/plugins/DataObjects/ for oxDeliveryDataPrepare
Failed to remove dataobjects for oxDeliveryDataPrepare
Failed to install oxDeliveryDataPrepare
Failed to install plugins for package openXDeliveryLog
Failed to initialise table class for oxDeliveryDataPrepare
Failed to drop tables for oxDeliveryDataPrepare
Task failed _unregisterSchema
Failed to uninstall oxDeliveryDataPrepare

Installation of plugin "openXVideoAds" failed:
Invalid source path to plugin dataobjects /home/forge/revive.mydomain.com/var/plugins/DataObjects/
Failed to implement dataobjects for vastInlineBannerTypeHtml
Task failed _registerSchema
Failed to write /home/forge/revive.mydomain.com/var/plugins/DataObjects/db_schema.ini
Failed to recreate old dataobject cache
Invalid source path to plugin dataobjects /home/forge/revive.mydomain.com/var/plugins/DataObjects/ for vastInlineBannerTypeHtml
Failed to remove dataobjects for vastInlineBannerTypeHtml
Failed to install vastInlineBannerTypeHtml
Failed to install plugins for package openXVideoAds
Failed to initialise table class for vastInlineBannerTypeHtml
Failed to drop tables for vastInlineBannerTypeHtml
Task failed _unregisterSchema
Failed to uninstall vastInlineBannerTypeHtml
```

Perhaps this is also related to a missing empty folder. I have no doubt I'll figure it out but this could be easily avoided with a .gitignore blank file. I know I am not following standard "ftp" instructions but everything I do goes through bitbucket/git nowadays.

Anyway the reason I came here to tell you is that I then googled the issue and found this thread https://forum.revive-adserver.com/topic/4570-error-on-installing/

Where I was going to post just to share my experience.. but upon signing up (or trying to) I am getting this error

```
Sorry, there is a problem
You are not permitted to register a user account with this site.
Error code: 2S129/1
```

And I don't know who to contact for this. I am in Indonesia right now, dunno if you blacklisted the whole country. Using my personal gmail which I've used on countless forums. I tried with a vpn after but still getting the same error. Would love to be able to sign up if you could provide me with a support email. This is not an issue with IPB but perhaps with your security settings

**Comment by vesper8** [comment]
just a note that I started over, this time using the ftp method, and was able to install ok

still can't create an account on the forum however

**Comment by mbeccati** [comment]
Hi @vesper8. I'm glead to hear you could get it working. `.gitkeep` or similar files are in place in the repo, but they are removed during packaging as they are unnecessary for zip files.

About the forum account, I guess it's the antispam kicking in, please drop me an email and I'll see what I can do.

Closing the issue.

**Comment by vesper8** [comment]
Thanks, email sent!
