### ISSUE TITLE
Bad redirect on destination URL in newsletter banner 

### ISSUE THREAD

**Issue by minarini** [revive-adserver/revive-adserver#825]
Problem:
  After click on the newsletter banner it doesn't redirect me to the destination URL defined on banner configurations in the ad server.  The browser open the url placed in the "href" param of zone tag/code ("http://adserver.guitadigital.com/www/delivery/ck.php?zoneid=2")

Here's the code placed on my newsletter html:

```
<!--/*`
  *
  * Revive Adserver No Cookie Image Tag
  * - Generated with Revive Adserver v4.0.0
  *
  */-->

<!--/*
  * The backup image section of this tag has been generated for use on a
  * non-SSL page. If this tag is to be placed on an SSL page, change the
  *   'http://adserver.guitadigital.com/www/delivery/...'
  * to
  *   'https://adserver.guitadigital.com/www/delivery/...'
  *
  */-->

<a href='http://adserver.guitadigital.com/www/delivery/ck.php?zoneid=2' target='_blank'><img src='http://adserver.guitadigital.com/www/delivery/avw.php?zoneid=2&amp;cb=125478525' border='0' alt='' /></a>
```

**Comment by erikgeurts** [comment]
We have a community forum for this type of question, see https://forum.revive-adserver.com

**Comment by andrewatfornax** [comment]
Question asked on forums, seems to be working. Closing, but we can re-open if it turns out there is something wrong.
