### ISSUE TITLE
Geo-Targeting doesn't work on mobile

### ISSUE THREAD

**Issue by Zain-Alabdin** [revive-adserver/revive-adserver#828]
I have geotargeting with three countries where each has a specific banner....
It works fine on desktop but not on mobile. 
Only this setting would solve the problem:
Evaluate banner delivery limitations during delivery
If this setting is unchecked then it works on mobile, if checked it only works on desktop but if I unchecked it then no geotargetting
Thank you

**Comment by mbeccati** [comment]
Thanks for the report, but it seems just a case of the GeoIP database not recognizing your mobile IP address. If you disable the limitations, of course all the banners are displayed regardless of your targeting rules.
