### ISSUE TITLE
Website and Github 4.0.1 Releases Not Identical

### ISSUE THREAD

**Issue by skynet** [revive-adserver/revive-adserver#830]
https://download.revive-adserver.com/revive-adserver-4.0.1.zip

not identical to 

https://github.com/revive-adserver/revive-adserver/archive/v4.0.1.zip

why?

**Comment by mbeccati** [comment]
https://github.com/revive-adserver/revive-adserver#download

**Comment by andrewatfornax** [comment]
The reason the two are not identical is that GitHub automatically generates the ZIP files from the source code, and we can't turn that off. 

However, the entire source code in GitHub includes source code in a format that needs to be merged etc. before a release - we also strip out things like the test files etc. that are not needed in a release of the product.

So, the ZIP file on GitHub (which should NOT be used for a production server) contains everything in the source code, while our official releases contain just the code you need for using the software.
