### ISSUE TITLE
Plugin_BannerTypeText_delivery_adRender

### ISSUE THREAD

**Issue by 2ge** [revive-adserver/revive-adserver#835]
in `/lib/OX/Extension/bannerTypeText/bannerTypeTextDelivery.php`
Plugin_BannerTypeText_delivery_adRender() should be defined like this:

```
if (!function_exists('Plugin_BannerTypeText_delivery_adRender')) {
...
}
```

it throws error when calling banner in local mode (/www/delivery/alocal.php)

**Comment by mbeccati** [comment]
Thanks for your report: such a check is already in place here:

https://github.com/revive-adserver/revive-adserver/blob/master/lib/max/Delivery/adRender.php#L458

I'll be happy ro re-open / revivew if you provide more context, but I guess your Revive adserver is altered in some way and the bug is actually elsewhere.

**Comment by 2ge** [comment]
Skip to content
This repository
Search
Pull requests
Issues
Gist
 @2ge
 Sign out
 Watch 170
  Star 570
 Fork 348 revive-adserver/revive-adserver
 Code  Issues 122  Pull requests 16  Projects 0  Pulse  Graphs
Edit New issue
Plugin_BannerTypeText_delivery_adRender #835
 Closed	2ge opened this issue 20 days ago · 1 comment
Assignees

 @mbeccati mbeccati

Labels

Invalid
Projects

None yet
Milestone

No milestone
Notifications

  Unsubscribe
You’re receiving notifications because you authored the thread.
2 participants

@2ge @mbeccati
 @2ge
   
2ge commented 20 days ago
in /lib/OX/Extension/bannerTypeText/bannerTypeTextDelivery.php
Plugin_BannerTypeText_delivery_adRender() should be defined like this:

if (!function_exists('Plugin_BannerTypeText_delivery_adRender')) {
...
}
it throws error when calling banner in local mode (/www/delivery/alocal.php)
 @mbeccati mbeccati self-assigned this 15 days ago
 @mbeccati mbeccati added this to the v4.0.2 milestone 15 days ago
 @mbeccati
 Contributor
mbeccati commented 4 hours ago
Thanks for your report: such a check is already in place here:

https://github.com/revive-adserver/revive-adserver/blob/master/lib/max/Delivery/adRender.php#L458

I'll be happy ro re-open / revivew if you provide more context, but I guess your Revive adserver is altered in some way and the bug is actually elsewhere.
 @mbeccati mbeccati closed this 4 hours ago
 @mbeccati mbeccati added the Invalid label 4 hours ago
 @mbeccati mbeccati removed this from the v4.0.2 milestone 4 hours ago
@2ge
  
            
 
Write  Preview
You can't comment at this time.

Hi,

I am doing this:

```
require_once('/data/www/revive_adserver/www/delivery/alocal.php');			
$adArray = view_local('', $zoneid, 0, 0, '', '', '0', $OA_context, '');       
```
