### ISSUE TITLE
Add updated column to inventory screens

### ISSUE THREAD

**Issue by 2ge** [revive-adserver/revive-adserver#836]
**UPDATED TICKET DESCRIPTION**

Add an "Updated" column to the list of Advertisers, Campaigns, Banners, Websites and Zones, to make it easy to sort these inventory items by updated date/time, so that it is easier to find the recently/least recently updated inventory item.

The "updated" date/time should be based on the inventory item itself, and not be related to sub-elements (e.g. Advertisers are not "updated" based on the date/time a Campaign in the Advertiser was updated, etc.)

Take into account date/time formatting preferences when displaying the date/time.

**ORIGINAL REQUEST**

Hi,

it would be great, if one would have option to show (and sort) last updated campaign in advertisers list. Now we can sort by Advertiser Name, but often happens, we add new campaign, which needs tuning, and when there are many (100+) advertisers, it would be handy to have shortcut. 
Column name "Updated Campaign"
Sort style: Descending | Ascending
Show: date
Link: to campaign

Thanks

**Comment by andrewatfornax** [comment]
Thinking about this ticket - what would count as an update to a campaign? Should we simply use the campaigns.updated field value? Or should we use the latest available date from the set of dates from both campaigns.updated and banners.updated, for all of the banners in the campaign?

That is, in the UI, what would the "Updated Campaign" value represent? Just a change to the campaign itself, or to the campaign or one of its banners?

Input and thoughts welcome.

**Comment by erikgeurts** [comment]
My vote would be on an update to the campaign itself only, to avoid making the list jump around too much because of (small) changes to the underlying banners.

**Comment by 2ge** [comment]
I agree with Erik, just when campaign was updated (or newly created), it would ignore updating (inserting) banners

**Comment by andrewatfornax** [comment]
Thanks! Sounds good.

**Comment by andrewatfornax** [comment]
Now working for Advertisers > Campaigns. 

Still need to implement for Advertisers, Banners, Websites, and Zones.

**Comment by mbeccati** [comment]
Fixed in #883
