### ISSUE TITLE
Impression should not be logged if banner is not deliverable

### ISSUE THREAD

**Issue by nebojsha-milosavlevski** [revive-adserver/revive-adserver#838]
Under certain conditions, request is being sent to the Ad Log script (_lg.php_) for banners that are not deliverable (_Inactive_, _Awaiting_, _Completed_ or not matching the _Delivery Limitations_).

GET request to the following URL will log impression whether or not the banner should be delivered:
`/www/delivery/lg.php?bannerid=<BannerID>&campaignid=<CampaignID>&zoneid=<ZoneID>`

The Ad Log script should probably check if the banner is deliverable before logging an impression.

In particular, I'm having trouble when banners are delivered in iframe (via iframe invocation code or javascript invocation code in iframed page) on a long lived parent page (session longer than 24 hours) and the iframe is refreshed using javascript on user action or automatically.

**Comment by mbeccati** [comment]
If you reload the impression log beacon, the impression will be logged regardless of the banner status. You are simply not reloading the ad properly.

**Comment by andrewatfornax** [comment]
@mbeccati - I raised my own ticket recently to consider this (although it was for clicks, rather than impressions). See: #826

I wonder if we could cache the state of banners after first lookup (with a similar timeout to delivery), and allow this to be done? It would not be 100% perfect, but perhaps would be enough to stop rogue impressions/clicks being recorded e.g. long after the campaign has ended?

**Comment by erikgeurts** [comment]
We should also keep in mind that a request followed by an impression on a zone that happens to have no (more) active banners linked to it (may also be because of frequency capping of all linked banners for example), is still perfectly valid, and is being recorded as a blank impression on that zone.

**Comment by nebojsha-milosavlevski** [comment]
I believe that the logging system should have at least rudimentary checks on banner and campaign status before logging impression.

Ideally, proper validation using some sort of cookie or locally stored token/key need to be implemented that will ensure that an impression is logged only when a banner is displayed.

This is just insecure, as anyone can inflate impressions and clicks by a simple HTTP request.

**Comment by erikgeurts** [comment]
If you're faced with a case where outsiders use tricks to inflate your ad statististics, you have much bigger problems than what your ad server software can fix.

**Comment by andrewatfornax** [comment]
Added to 4.1.0 just because I have worked on #826 for that version. However, not a promise to deliver, this still needs some thinking about.

**Comment by mbeccati** [comment]
Fixed in #886
