### ISSUE TITLE
Rename "History" pages to "Statistics" pages.

### ISSUE THREAD

**Issue by 2ge** [revive-adserver/revive-adserver#842]
Hi,

would be great to have shortcut - link to statistics from Advertiser details / Campaign / Banner. I think it would be really useful.

Thanks.

**Comment by mbeccati** [comment]
I think there is one: 
![immagine](https://cloud.githubusercontent.com/assets/282388/25337698/224923e4-28fd-11e7-937b-a71416cee277.png)

However not the other way around, i.e. from statistics to the edit screen.

**Comment by 2ge** [comment]
Other way around would be good too of course, so we can navigate easily. I would also rename "Banner history" to "Banner statistics" and from "Advertiser history" to "Advertiser statistics". When I read history, it could be changes for the banner made, Statistics is better wording IMHO

**Comment by andrewatfornax** [comment]
Converted this ticket to be about the rename from History to Statistics, as the original ticket was about the shortcut from inventory to stats, which existed, but was not well named.

See #847 for the reverse link.

**Comment by mbeccati** [comment]
@andrewatfornax Do you think such wording change is safe for a (mostly) bugfix-only release, such as 4.0.3? Or perhaps 4.1.0 material?
