### ISSUE TITLE
 MariaDB 10.2: window is a  keyword, broke the logConversion.class.

### ISSUE THREAD

**Issue by MosheL** [revive-adserver/revive-adserver#849]
Problem:

this query is failed when using MariaDB 10.2:

     INSERT INTO                 ox_data_intermediate_ad_connection
                 (server_raw_tracker_impression_id, server_raw_ip, tracker_id, tracker_date_time, connection_date_time, ad_id, zone_id, tracker_ip_address, connection_action, connection_window, connection_status, creative_id, inside_window)
             SELECT
                 server_conv_id AS server_raw_tracker_impression_id, server_ip AS server_raw_ip, tracker_id AS tracker_id, date_time AS tracker_date_time, action_date_time AS connection_date_time, creative_id AS ad_id, zone_id AS zone_id, ip_address AS tracker_ip_address, action AS connection_action,
                 window AS connection_window, status AS connection_status, 0 AS creative_id, 1 AS inside_window             FROM                 ox_data_bkt_a             WHERE                 date_time >= '2017-05-30 08:00:00'                 AND                 date_time <= '2017-05-30 08:59:59'

Steps To Reproduce:
wait for maintanace.

HOW TO FIX:

     `INSERT INTO                 ox_data_intermediate_ad_connection
                 (server_raw_tracker_impression_id, server_raw_ip, tracker_id, tracker_date_time, connection_date_time, ad_id, zone_id, tracker_ip_address, connection_action, connection_window, connection_status, creative_id, inside_window)
             SELECT
                 server_conv_id AS server_raw_tracker_impression_id, server_ip AS server_raw_ip, tracker_id AS tracker_id, date_time AS tracker_date_time, action_date_time AS connection_date_time, creative_id AS ad_id, zone_id AS zone_id, ip_address AS tracker_ip_address, action AS connection_action,
                   `window` AS connection_window, status AS connection_status, 0 AS creative_id, 1 AS inside_window             FROM                 ox_data_bkt_a             WHERE                 date_time >= '2017-05-30 08:00:00'                 AND                 date_time <= '2017-05-30 08:59:59'`

I think the only place with this query is

revive-adserver\plugins_repo\openXDeliveryLog\plugins\deliveryLog\oxLogConversion\logConversion.class.php

(and in the installed plugin)

so I just changed  window to `window` and I think it works.

**Comment by MosheL** [comment]
you have the same problem in logConversion.delivery.php, but in this  code you was fixed it 

(line 55:)

    // Need to also escape identifier as "window" is reserved since PgSQL 8.4
    $aFields = array_map('OX_escapeIdentifier', array_keys($aValues));

**Comment by mbeccati** [comment]
Thanks for the report. We'll look into it!

**Comment by mbeccati** [comment]
@MosheL I'm not able to properly test the fix for the next release. It would be great if you could test and give some feedback on the commit above.

**Comment by MosheL** [comment]
I will test it on my device. thanks.

**Comment by mbeccati** [comment]
@MosheL thanks. I've tested 5f828ae88715eb0f94e32b510917eebe16f6d3b5 through a debugger and the window keyword was properly quoted.
