### ISSUE TITLE
delivery limitation missing and banner type missing (fixed)

### ISSUE THREAD

**Issue by gumpjt** [revive-adserver/revive-adserver#852]
Problem:
If you find there is none option in "Add delivery limitation" (when you set "Delivery options") or missing options in "Please choose the type of the banner" (when you add a new banner), 

you need to ENABLE SCANDIR() FUNCTION in your php.ini file. 

PS: This function has been disabled due to security issues, so I think maybe,  it's better to fix it. (I'm a php newbie....)

I open this issue for searching, maybe someone have the same problem.

**Comment by erikgeurts** [comment]
We have a community forum for this type of thing, see https://forum.revive-adserver.com

**Comment by gumpjt** [comment]
I searched, but it seems no one has this problem yet. Thanks.  😄

**Comment by erikgeurts** [comment]
I'd recommend posting it there, you will become famous instantly.

**Comment by andrewatfornax** [comment]
@mbeccati, a quick search of the code base suggests that we don't check to see if scandir() is enabled as part of the install process. I think that we do check other PHP functions that we need.

I will try to locate this code, but let me know if you know where it is? We might be able to add a check to ensure scandir() is enabled as part of installing.

We will not remove the need for scandir() - there are safe ways in PHP of allowing scandir() to be enabled, but limited to the Revive Adserver directory, if that's what people want.

**Comment by andrewatfornax** [comment]
@mbeccati,

Oh, it might be RV_checkSystemInitialRequirements() in the pre-check.php file?

**Comment by mbeccati** [comment]
Fixed in #853
