### ISSUE TITLE
MySql to Postgres db problem

### ISSUE THREAD

**Issue by nazakar** [revive-adserver/revive-adserver#856]
Hi, i convert all mysql tables into postgres sql and inert data,
All tables i pgs have same rows and values, excuding datatime '0000-00-00 00 00 00' , that I sava as null
Wheh login i getting error 

 An error occurred while accessing the database
Due to a problem with the database Revive Adserver couldn't retrieve or store data. 

Thanks

**Comment by mbeccati** [comment]
This looks like a support request, not a bug report. Our [forum](https://forum.revive-adserver.com/) seems to be more suited to this kind of questions.

Besides, it sounds like a connection/authentication problem to me.
