### ISSUE TITLE
Installation session.save_path check :: Does not support all PHP-valid options

### ISSUE THREAD

**Issue by LucasLMartini** [revive-adserver/revive-adserver#860]
Installation fails even if session.save_path is writable when the PHP config utilizes the optional N and/or M parameters in session. As per PHP's [docs](http://php.net/manual/en/session.configuration.php#ini.session.save-path):

> There is an optional N argument to this directive that determines the number of directory levels your session files will be spread around in. 

And:

> The file storage module creates files using mode 600 by default. This default can be changed with the optional MODE argument: N;MODE;/path where MODE is the octal representation of the mode. Setting MODE does not affect the process umask.

Will submit a PR for this, all you should have to do is explode the session.save_path string and take the last argument only.

**Comment by mbeccati** [comment]
Thanks @LucasLMartini - I thought this was fixed already as I think I've heard this before...

**Comment by LucasLMartini** [comment]
There was another, different, issue (that I found anyway) with this check, just submitted PR #861 to fix this, works fine on my end now.

**Comment by mbeccati** [comment]
Fixed in #861
