### ISSUE TITLE
Add configuration switch to force serving SSL on delivery

### ISSUE THREAD

**Issue by mbeccati** [revive-adserver/revive-adserver#864]
Got this feature request from a friend / long time Revive user.

Discuss.

**Comment by erikgeurts** [comment]
In order to discuss, it would be good to fully understand that the request is. After all, Revive Adserver already support delivery over SSL and will do so automatically if the ad request comes in via an https call.

**Comment by mbeccati** [comment]
1. Default to generation of https codes
2. Print beacon/image URLs with https even if the request was coming via http, as if it was https in the first place

**Comment by erikgeurts** [comment]
OK, I see. I understand the request, but I don't understand the 'why'.

What's the benefit of doing it this way? Just to make sure that users don't accidentally generate non-SSL code and then have to do it again when they realize it won't work on their https sites?

One a side note, doesn't the async code leave out the protocol and thus already do something almost like this?

**Comment by mbeccati** [comment]
Well, if one decides not to use plain http at all and/or the ssl balancer doesn't pass all the necessary info for Revive to recognize it's an https connection.

**Comment by erikgeurts** [comment]
OK, makes more sense now.

Sounds like a valuable change, and not extremely complex if you ask me (but I'm not a coder).

**Comment by andrewatfornax** [comment]
It seems like it would be relatively easy to do, but is this just more complexity and configuration in Revive Adserver for something that can be very easily managed at the webserver level with appropriate permanent redirections?

**Comment by chasebolt** [comment]
with everything going full https support, personally it seems unnecessary. this is just a stop gap measure.

**Comment by wikt0r** [comment]
You can force ssl delivery in nginx when you set `fastcgi_param HTTPS 'on';` for `revive` paths in config. This sets `$_SERVER["HTTPS"]` to `on` and this is what Revive checks for delivery. Details: #1057

**Comment by mbeccati** [comment]
The more I have been looking into this, the more it is clear it was a bad idea in the first place as you all agreed. Closing as won't fix.
