### ISSUE TITLE
PHP 7.0.21 and PHP 7.1.7 error (undefined method)

### ISSUE THREAD

**Issue by wmtech-1** [revive-adserver/revive-adserver#865]
Default 4.0.2 installation, runs perfectly with PHP 5.6.

After upgrading to 7.1.7 (and also after downgrade to PHP 7.0.21) the following error is shown.

`2017/07/20 21:15:04 [error] 12965#12965: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method MDB2_Error::setFetchMode() in /home/nginx/domains/EXAMPLE.COM/public/revive-4.0.2/lib/pear/DB/QueryTool/Query.php:299
Stack trace:
#0 /home/nginx/domains/EXAMPLE.COM/public/revive-4.0.2/lib/pear/DB/QueryTool/Query.php(273): DB_QueryTool_Query->connect(Object(MDB2_Error), Array)
#1 /home/nginx/domains/EXAMPLE.COM/public/revive-4.0.2/lib/pear/DB/QueryTool/EasyJoin.php(71): DB_QueryTool_Query->__construct(Object(MDB2_Error), Array)
#2 /home/nginx/domains/EXAMPLE.COM/public/revive-4.0.2/lib/pear/DB/QueryTool.php(57): DB_QueryTool_EasyJoin->__construct(Object(MDB2_Error), Array)
#3 /home/nginx/domains/EXAMPLE.COM/public/revive-4.0.2/lib/max/Dal/Common.php(157): DB_QueryTool->__construct(Object(MDB2_Error))
#4 /home/nginx/domains/EXAMPLE.COM/public/revive-4.0.2/lib/max/Dal/Common.php(77): MAX_Dal_Common->_getQueryTool(Object(MDB2_Error))
#5 /home/nginx/domains/EXAMPLE.COM/public/revive" while reading response header from upstream, client: 00.00.00.00, server: EXAMPLE.COM, request: "GET / HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "EXAMPLE.COM"`

It is gone after downgrading again to PHP 5.6.

Very strange...

**Comment by wmtech-1** [comment]
Seems like Revive 4.0.2 is still not 100% compatible with mysqli?

After manually installing the deprecated mysql extension to PHP 7.0.21 it works. Shouldn't it work with mysqli out of the box?

**Comment by mbeccati** [comment]
I guess you just need to update your conf and set the db type to mysqli.

**Comment by andrewatfornax** [comment]
I think we cover this here: https://documentation.revive-adserver.com/display/DOCS/Revive+Adserver+Broken#ReviveAdserverBroken-Step6:CheckyourDatabase
