### ISSUE TITLE
Uninstall Software at heroku free instance

### ISSUE THREAD

**Issue by MuneebSarfraz94** [revive-adserver/revive-adserver#867]
hi! I have deployed and  installed revive-adserver on heroku free instance it works fine at start but after some time it gets uninstalled automatically . i have been trying from two days is this because of heroku free instance or i'm doing something wrong in installation

**Comment by mbeccati** [comment]
I'm sorry, this is not a bug and the topic should eventually be discussed on our [forums](https://forum.revive-adserver.com/) instead.
