### ISSUE TITLE
The banners via Revive Adservive links to spam ads

### ISSUE THREAD

**Issue by LindaLT0708** [revive-adserver/revive-adserver#870]
-I made a new campaign
-I made 3 new banners in this campaign by uploading it from my computer
-I linked the 3 new banners to the correct zones

When I click on the three banners, the thing happens that a spam ad opens (even a few porn ads). The second time I click on the banners the right page opens. I stopped the campaign, because I don't want to bother my customers. When I start another campaign there's no problem with spam ads How could this happen?

**Comment by erikgeurts** [comment]
It appears that either your system was hacked, or you pasted in some third party code that is serving those spammy ads.

Whatever is the case, this is almost 100% certainly not a bug. We recommend you post your issue on our community forums at https://forum.revive-adserver.com/ .
