### ISSUE TITLE
Revive Adserver - Crash

### ISSUE THREAD

**Issue by equinoxbroadcasting** [revive-adserver/revive-adserver#871]
Added a new advertiser and campaign. When I went to link the campaign to my website zones, there was a crash screen that came up....

Version: | Revive Adserver v3.2.4
-- | --
PHP/DB: | PHP 5.5.22 / MySQL 5.6.32-78.1-log
Page: | /adserver/www/admin/website-index.php
Error: | Table './revise_adserver_3/rv_zones' is marked as crashed and last (automatic?) repair failed
Query: | SELECT             w.affiliateid AS website_id,             w.website     AS website_url,             w.name        AS website_name,             z.zoneid      AS zone_id,             z.zonename    AS zone_name,             z.width       AS zone_width,             z.height      AS zone_height         FROM             rv_affiliates AS w,             rv_zones AS z         WHERE             z.affiliateid = w.affiliateid           AND w.agencyid = 1         ORDER BY w.name
$_POST: | Empty
$_GET: | Empty

**Comment by mbeccati** [comment]
I'm sorry, this is not a bug in Revive Adserver. The MySQL rv_zones table got corrupted and you should manually repair it.

**Comment by equinoxbroadcasting** [comment]
I'm sorry. Can you maybe provide a little more information? Like how this happened and how to repair it?

**Comment by mbeccati** [comment]
Sorry, this is a bug tracker, not a support site. We do have a [forum](https://forum.revive-adserver.com) where you could ask for help. Some Googling could help too: https://stackoverflow.com/questions/4357270/table-is-marked-as-crashed-and-should-be-repaired
