### ISSUE TITLE
Database connection error.

### ISSUE THREAD

**Issue by sindaravicius** [revive-adserver/revive-adserver#882]
WE can't connect to our banners login and also in a website there is no banners showing. 

The problem with database: 

A fatal error occurred Revive Adserver can't connect to the database. Because of this it isn't possible to use the administrator interface. The delivery of banners might also be affected. Possible reasons for the problem are: <ul> <li>The database server isn't functioning at the moment</li> <li>The location of the database server has changed</li> <li>The username or password used to contact the database server are not correct</li> <li>PHP has not loaded the MySQL Extension</li> </ul>

Where is a problem ? Is it from your side ?

**Comment by erikgeurts** [comment]
This appears to be an issue with your database or your server. Check with your hosting provider.
We have a community forum over at https://forum.revive-adserver.com where you can post topics for fellow users to reply to.

**Comment by sindaravicius** [comment]
Is REVIVE supporting 7 PHP ? Because we integrared to 7 PHP, and after that banners dissapears.

**Comment by erikgeurts** [comment]
Please use the forums over at https://forum.revive-adserver.com 

PHP7 support: yes, see https://www.revive-adserver.com/support/requirements/
