### ISSUE TITLE
Uploading an image in a banner fail almost every time

### ISSUE THREAD

**Issue by lkppo** [revive-adserver/revive-adserver#889]
Hello,

With version 4.0.1, we create a new banner with a title and an image only. On form submission the POST request ends after several minutes and request for our proxy password. Sometimes there are no problem.

There is no rule. I still can upload png images but the jpg does not pass. For my colleague none succeeded except exception.

There may be 407 errors but the browser resubmits the request.

![407_error](https://user-images.githubusercontent.com/10128284/30858658-decdde14-a2c0-11e7-980e-e0f6e7dc17ac.png)
![form_submit_ko](https://user-images.githubusercontent.com/10128284/30858657-decd07e6-a2c0-11e7-9ba5-9542538624e1.png)
![form_submit_ok](https://user-images.githubusercontent.com/10128284/30858659-ded0b832-a2c0-11e7-9dc2-2743024303a7.png)

Regards,

-- 
Stéphane Aulery
Développeur
Narbonne Accessoires

**Comment by mbeccati** [comment]
Not a bug either. Your installation and/or network seems to have quite a few issues. Please also make sure you have no ad blockers running.
