### ISSUE TITLE
Deprecate HTML banner "Banner link" information?

### ISSUE THREAD

**Issue by andrewatfornax** [revive-adserver/revive-adserver#89]
HTML banners get a little confusing when there is "Banner link" information set (i.e. a destination URL and a target), as it's an HTML banner, and it makes more sense to set the URL and target in the HTML where it belongs.

Should we deprecate the "Banner link" section for HTML banners?

Obviously, the "Banner link" information is essential for non-HTML banners like image banners, etc. as these cannot define the destination URL and target anywhere else - the proposed change is only for HTML banners.

**Comment by athlan** [comment]
I think that deprecating banner link is absolutely unnecessary. It does not break any compatibilities, and argument that HTML banners can contain URL is true, but banner URL could be still available.

Imagine the HTML5 banners use case where URL can be parametrized. Is any chance to revert this commit?

**Comment by andrewatfornax** [comment]
Hi @athlan - the difficulty is that in this day of HTML5 banners, people are doing much more than just having a static banner with a single URL. There's animation, and different URLs depending on where you click and/or what part of the animation is visible.

This makes it impossible for Revive Adserver to simply wrap the HTML in an href anchor.

Revive Adserver is already incredibly complex, and maintaining it is very difficult - wherever possible, my preference is to simplify the features in the product - in this case, saying to people that they need to provide HTML banners that define exactly how they want links to work, and only leaving the work of converting those links for click tracking to Revive Adserver.

This way, people can easily do simple HTML banners, or complex HTML5 banners, and Revive Adserver doesn't need to have complex, potentially fragile detection of what the banner is, or confusing mode toggles. It just has one simple approach, and it works.

**Comment by rpijlman** [comment]
Does this mean Revive cannot provide click tracking / click statistics for HTML5 banners? I mean, in the simple case of 1 target url for the entire ad. That's a terrible incompatibility with pre-3.1.

**Comment by mbeccati** [comment]
@rpijlman The feature used to wrap the provided html with an `<a href="">` tag if none was present, whereas now you just have to put them yourself. You can either depend on Revive's "Alter HTML" feature for click tracking, or put {clickurl} macros where necessary.

**Comment by rpijlman** [comment]
@mbeccati Ah, I thought that {clickurl} required the target url to be in Revive's database, but I just learned you can put the target url in the html:

`<a href="{clickurl}http://target-url"></a>`

Okay, that's fine. My assumption was bad. Thanks for your help.

**Comment by walderT** [comment]
+1 to reverse the commit.
In my mind it make no sense no hide these fields because the user is noch able to use the magic macros like {clickurl} or {target}. Target may be easy to use for the customer but i think clicktag its hard to determine, here is the destination url needed for the oadest param.
