### ISSUE TITLE
Some js error in http://pub.narbonneaccessoires.com/www/admin/banner-edit.php

### ISSUE THREAD

**Issue by lkppo** [revive-adserver/revive-adserver#890]
Version 4.0.1

There are also some js error in page http://pub.narbonneaccessoires.com/www/admin/banner-edit.php

![js_error](https://user-images.githubusercontent.com/10128284/30859253-24888c04-a2c3-11e7-9771-40fa8bc5f7fa.png)

**Comment by erikgeurts** [comment]
Please upgrade to the most recent stable release v4.0.2 and try again.

**Comment by lkppo** [comment]
I checked. It will not do anything better because the error is in the jQuery library.

**Comment by lkppo** [comment]
Hello erikgeurts,

I find the time to update to 4.0.2 and js errors/warnings are still there :

Échec du chargement pour l’élément <script> dont la source est « http://pub.narbonneaccessoires.com/www/delivery/fl.js ».  banner-edit.php:36
L’utilisation de « getAttributeNode() » est obsolète. Utiliser « getAttribute() » à la place.  min.php:119:33
L’utilisation de l’attribut « nodeValue » d’un attribut est obsolète. Utiliser « value » à la place.  min.php:120:7

**Comment by mbeccati** [comment]
Sorry, this is not a bug either. Deprecations do no harm and the errors are caused by something wrong on your setup.
