### ISSUE TITLE
Uploaded image permissions (chmod)

### ISSUE THREAD

**Issue by AceWT** [revive-adserver/revive-adserver#903]
Problem:
Uploaded banned image has invalid chmod permissions (0600) and it is not readable by apache.

Steps To Reproduce:
Install on cpanel account where cpanel has obscure security settings.

**Comment by erikgeurts** [comment]
Please post your support question on our community forums at https://forum.revive-adserver.com

**Comment by mbeccati** [comment]
Sorry, not a bug in Revive Adserver. Closing
