### ISSUE TITLE
Campaign Settings Page Partially Not Displaying After Upgrade to v. 4.1

### ISSUE THREAD

**Issue by willkat** [revive-adserver/revive-adserver#904]
I just upgraded from v 4.0.1 to 4.1.  

Everything else seems to work fine but when I click on a Campaign settings page, I only see the top part of the page with unselected radio buttons for delivery priority (override, contract or remnant) though the selection had already been made, typically to override.

However, once I select any one of the radio buttons, the rest of the page suddenly displays.  

But the next time the page is loaded, only the top portion shows again, with unselected radio buttons.

However, when I open an old campaign in which the priority is set to "contract", the entire settings page displays as usual, and doesn't disappear when I click away and back to the page.

Since we normally use either override or remnant settings, this glitch is unnerving because you're not sure if the priority settings will be preserved after you click away.

This happens on Chrome, Firefox and Safari.

**Comment by mbeccati** [comment]
I've been able to replicate the issue.
