### ISSUE TITLE
Class SinergiWrapper not found

### ISSUE THREAD

**Issue by reviveuser** [revive-adserver/revive-adserver#910]
Problem:
`FastCGI: server "/usr/lib/cgi-bin/php5-fcgi" stderr: PHP message: PHP Fatal error:  Class 'RV\\Extension\\DeliveryLimitations\\ClientDataWrapper\\SinergiWrapper' not found in /var/www/adserver/revive-adserver-4.1.1/plugins/deliveryLimitations/Client/initClientData.delivery.php on line 25

Any Idea? :)

**Comment by mbeccati** [comment]
It looks like you're running and older Revive version with a recent delivery Limitations plugin.

**Comment by reviveuser** [comment]
Hi,

actually it's version 4.1.1, upgraded from 3.0.5. In the old 3.0.5 
version the application (which includes the ads / revive adserver) sends 
it's ad requests to www/delivery/multiple.php. It seems like this file 
is not part of the revive adserver and is probably something custom 
develop by the previous developers (at least my search for this file and 
revive adserver showed nothing up). I get the mentioned error when an 
request is sent to "multiple.php".

**Comment by mbeccati** [comment]
@reviveuser Sorry, we can't and won't offer support 3rd party modifications. Please contact the author(s) of the modifications for support.

Closing the issue as it's not a Revive Adserver bug.
