### ISSUE TITLE
ag.php script missing

### ISSUE THREAD

**Issue by tvvpm** [revive-adserver/revive-adserver#913]
Server version Revive 4.1.1 

Problem:
On HTML banners with "Alter HTML for click-tracking" option active, the result banner code is calling the ag.php which is missing in the current version.

Steps To Reproduce:
Create a ADSENSE banner ... with click-tracking option active. Each time the banner is displayed results in 404 call to ag.php

**Comment by mbeccati** [comment]
Hi @tvvpm, thanks for your report. ag.php has been removed in 4.1.0. Apparently we forgot to also remove something that was calling it.

**Comment by mbeccati** [comment]
@tvvpm what kind of invocation code are you using?

**Comment by tvvpm** [comment]
@mbeccati We are using both "javascript tag" and "asynchronous JS Tag" invocation. In both cases ag.php is called.

**Comment by mbeccati** [comment]
@tvvpm could you please check what version of the openX3rdParty plugin are you using? It shouldn't be possible to use Google Adsense  3rd party tracking anymore, and it hasn't been working for quite some time now.

**Comment by tvvpm** [comment]
version 1.3.1

**Comment by mbeccati** [comment]
@tvvpm thanks. And can you still select Google AdSense in the 3rd party tracking dropdown?

**Comment by tvvpm** [comment]
No.  This are the options: adtech, Atlas, Bluestreak, CPX, Doubleclick/DFP, Eyeblaster, Falk, Kontera, Revive Adserver, Mediaplex, Open AdStream, Tango Zebra, Trade Doubler with "Do not alter" and "Generic HTML banner"

This banners were created with prior versions of Revive Adserver. All this banners have "Generic HTML banner" option selected. Querying the database, I can see the call to ag.php in htmlcache. Saving again the banner cleans htmlcache column. Seems that there have been a problem migrating this banners from a prior version.

**Comment by mbeccati** [comment]
@tvvpm ok, thanks for the additional investigation. This isn't something I had envisioned. I guess however that on the database they still have "google" in the `adserver` column (before saving again).

**Comment by tvvpm** [comment]
On database I only have one banner with "3rdPartyServers:ox3rdPartyServers:google" on adserver column. For the rest,  the column is "blank". All of them has "bannerTypeHtml:oxHtml:genericHtml" on ext_bannertype column. 

This is the query with the remaining adsense banners ... 

select bannerid, adserver, campaignid, ext_bannertype from ox_banners where htmlcache like '%ag.php%';

![image](https://user-images.githubusercontent.com/17924449/33168015-b08c27b6-d03f-11e7-8c86-59afca38f8f2.png)

**Comment by mbeccati** [comment]
Thanks again @tvvpm. I'm afraid the proper fix isn't as easy as I was hoping. For now I'd just suggest to edit and save the affected banners so that the cache is overwritten.

**Comment by mbeccati** [comment]
After some discussion, we've decided to put this information into a Troubleshooting guide entry. More info to come.

**Comment by andrewatfornax** [comment]
Note to self - also document the related admin feature separately.

**Comment by andrewatfornax** [comment]
Banner cache admin feature documented: https://documentation.revive-adserver.com/display/DOCS/Banners+Sub-Menu

**Comment by andrewatfornax** [comment]
New documentation on the error, and how to resolve: https://documentation.revive-adserver.com/display/DOCS/404+on+Banner+Delivery

Mention of the issue in the non-BC pages list: https://documentation.revive-adserver.com/display/DOCS/Non-BC+Changes
