### ISSUE TITLE
What folders need to be writable?

### ISSUE THREAD

**Issue by kwiborg** [revive-adserver/revive-adserver#915]
We have moved our Revive installation to another server. After login there is a red alert-box warning with this warning about  file-permissions:

"Error: File permission errors detected.
These may impact the accurate delivery of your ads,
See the debug.log file for the list of unwritable files"

The var/debug.log file is writeable and gets updated, but does not contain anything like a list of unwriteable files. Also the PHP error log does not show any errors about file permissions. I have scanned through the documentation, but I don't see a list of what folders/files that need to be writable. Can anyone help with a list of folder/files in 3.2.1?

**Comment by erikgeurts** [comment]
Please consider posting your support question on our community forums at https://forum.revive-adserver.com

**Comment by mbeccati** [comment]
For reference, the issue should have been fixed in #906

**Comment by kwiborg** [comment]
Ok, thanks
