### ISSUE TITLE
Warn on Delivery Rule Data Truncation

### ISSUE THREAD

**Issue by andrewatfornax** [revive-adserver/revive-adserver#918]
The addition of new delivery rule types "Site - Registerable Domain List" and "Site - Hostname List" allow large lists of URLs to be added. 

Some users are putting e.g. 3k+ URLs into this plugin, and are hitting truncation issues, due to the data being stored exceeding the length of the columns. 

It would appear that there is no code in place to check for this data truncation, and to roll back the change & alert the user of the issue, which leaves the database in an inconsistent state (in terms of the raw rule data vs. the compiled rule data not matching).

This should be addressed.

**Comment by andrewatfornax** [comment]
Truncation of the acls table data column happens in /lib/pear/MDB2/Driver/mysqli.php on line 727 where code 

`$result = mysqli_query($connection, $query);`

returns `true`. Which is not very helpful.

**Comment by andrewatfornax** [comment]
As far as I can tell, there is code in place to capture error from the underlying database queries:

* Both the banners and acls tables are updated from `/lib/max/other/lib-acl.inc.php` file.

* The acls are updated via `DB_DataObjectCommon::insert()`, which calls `DB_DataObject::insert()`, which calls `DataObject::_query()`, which calls `MDB2::exec()`, which calls driver-specific class' `_doQuery()` method.
* This chain checks for errors from the driver-specific class' call to the database, and if present, are raised/returned all the way back up the stack, to the `/lib/max/other/lib-acl.inc.php` file, where the result is checked to see if it is true - if not, the update is failed and the user returned to the UI where they are warned about a mismatch.
* This is not especially intuitive, but at least there is a warning.

* The banners are updated via `Banners::update()`, which calls `DB_DataObjectCommon::update()`, which calls `DB_DataObject::update()`, which calls `DB_DataObjectCommon::_query()`, which calls `DataObject::_query()`, which calls `MDB2::exec()`, which calls driver-specific class' `_doQuery()` method.
* For this pathway, the chain checks for errors from the driver-specific class' call to the database, and if present, are raised/returned only as far back up the stack as the `DB_DataObjectCommon::_query()` method.
* However, at this point, the result is checked, and if there is an error, `phpAds_sqlDie()` is called.

So, in both cases, if there's a database error detected, there is code in place to handle it.

The issue appears to be (at least in my dev environment) that the `mysqli_query()` is not returning an error when it fails to return the `ERROR 1406 (22001): Data too long for column` error that I get when manually executing the same SQL query as the code is executing.

**Comment by andrewatfornax** [comment]
@mbeccati - I wonder if this is down to a MySQL setting that allows data to be truncated without issuing a warning, and the warning I see from the MySQL CLI is actually independent from server behaviour?

**Comment by mbeccati** [comment]
@andrewatfornax Revive sets mysql40 compatibility mode, otherwise nothing would probably work. In that case, truncation just leads to a warning.

**Comment by andrewatfornax** [comment]
New approach after discussion.

If MySQL is the database:

1. Store existing values in memory;
2. Perform the update;
3. If values do not match after update but no SQL errors (i.e. truncation), restore the original values and display error.

**Comment by andrewatfornax** [comment]
Not relevant for PostgreSQL users, as column length not bounded on PostgreSQL.

**Comment by andrewatfornax** [comment]
Fixed with #945
