### ISSUE TITLE
Double encoded urls

### ISSUE THREAD

**Issue by batyrmastyr** [revive-adserver/revive-adserver#923]
Urls should not be double encoded - this breaks urls after editing.

code 
https://github.com/revive-adserver/revive-adserver/blob/0b1953a875a33ef7643dab097361c3e1d17b5aac/www/admin/lib-statistics.inc.php#L369

should be changed with 
`return htmlspecialchars($string, ENT_QUOTES | ENT_HTML401, ini_get("default_charset"), false); `

**Comment by mbeccati** [comment]
Thanks for your report @batyrmastyr 

however, we'd need to understand how to replicate the issue in the first place.

**Comment by batyrmastyr** [comment]
1. create banner with Adobe Flash content with "&" in url (ex. with utm params like `http://example.com/page1?something=1&utm_source=github`)
2. open it again and save it.

Expected link: `http://example.com/page1?something=1&utm_source=github`

Result link: `http://example.com/page1?something=1&amp;utm_source=github` (last param became "amp;utm_source")

As a result external stats services (yandex / google / etc) don't count such visits.

**Comment by batyrmastyr** [comment]
@mbeccati do you need more information?

**Comment by mbeccati** [comment]
@batyrmastyr would you mind sharing such a banner?

**Comment by erikgeurts** [comment]
@batyrmastyr You specifically mentioned Flash banners. Flash support has been removed in version 5.1.0. Does this affect other banner types as well? Also in version 5.1.0, support for third party click tracking has been reduced considerably, and we've introduced new macros {clickurl_enc} and {clickurl_html}. Do these perhaps solve your issue?

**Comment by batyrmastyr** [comment]
@erikgeurts this issue happened only with flash banners, so it’s time close this topic.
