### ISSUE TITLE
Getting "This page isn’t working xyz.com redirected you too many times."

### ISSUE THREAD

**Issue by TamiTuesdayMorning** [revive-adserver/revive-adserver#928]
Unable to access the revive ad server. Ads are not appearing on our site as a result of this. How can we resolve?

**Comment by YPCrumble** [comment]
@TamiTuesdayMorning you would need to provide more information about what happened or changed prior to the error. Is this a fresh installation? An upgrade? None of the above? Did your database change somehow?

**Comment by mbeccati** [comment]
Hi @TamiTuesdayMorning. Our [forums](https://forum.revive-adserver.com/) seem more appropriate for this discussion, since this is more like a support request and not a bug report.

However, I think I've heard about a similar behaviour when someone had problems with their database.

**Comment by TamiTuesdayMorning** [comment]
We accessed the site yesterday and uploaded an updated ad, at that point the system timed out. Since then, we have been unable to access the site and the ads no longer work on the site.

**Comment by erikgeurts** [comment]
Please use the forums, as suggested by @mbeccati . See https://forum.revive-adserver.com and post your issue there please.
