### ISSUE TITLE
SQL error when submitting the User Interface Preferences form

### ISSUE THREAD

**Issue by mbeccati** [revive-adserver/revive-adserver#943]
(EDIT)

The entry for `ui_html_wyswyg_enabled` is missing in the `preferences` table on any instance that hasn't been upgraded from a pre 4.1 version, causing the User Interface Preferences to malfunction and showing a SQL error upon submit:

```
Version: Revive Adserver v4.1.1
PHP/DB: PHP 7.1.10 / Unknown 5.7.19-
Page: /revive/www/admin/account-preferences-user-interface.php
Error: 
Query: INSERT INTO rv_account_preference_assoc (account_id , value ) VALUES ( 2 , '' )
$_POST: Array (     
     [submitok] => true
     [ui_show_campaign_info] => true
     [ui_show_banner_info] => true
...
```

**Comment by mbeccati** [comment]
Possibly due to mysqli or MySQL 5.7+

**Comment by mbeccati** [comment]
The fix is apparently causing some other issues, i.e. checkbox preferences not being saved: this requires further investigation.

**Comment by erikgeurts** [comment]
Is there any chance we could get this one fixed in v4.2.0?

**Comment by mbeccati** [comment]
I don't think we can replicate the original isue anymore?

**Comment by erikgeurts** [comment]
We can: in v4.1.4 when one attempts to change the display of the statistics columns (enabling or disabling a few, changing their names and column order), when saving the changes, the error message appears.

**Comment by mbeccati** [comment]
I think I finally identified the issue. As far as I can tell fresh installations of v4.1.0+ are missing the `ui_html_wyswyg_enabled` entry in the `preferences` table, which is in turn causing the SQL error above. 

@erikgeurts could you help confirming (or not) my findings?

**Comment by erikgeurts** [comment]
> I think I finally identified the issue. As far as I can tell fresh installations of v4.1.0+ are missing the `ui_html_wyswyg_enabled` entry in the `preferences` table, which is in turn causing the SQL error above.
> 
> @erikgeurts could you help confirming (or not) my findings?

I can confirm that on a recent new install of v4.1.4, there is now entry `ui_html_wyswyg_enabled` entry in the `preferences` table.

On a much older install that started life well before v4 or even v3, the entry is there.
