### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ronaldista** [revive-adserver/revive-adserver#955]
Where can i get a good documentation on this project because the one in website is not subtle

**Comment by erikgeurts** [comment]
http://documentation.revive-adserver.com

**Comment by andrewatfornax** [comment]
We do our best not to be subtle in the documentation! :-)

**Comment by nepster23** [comment]
will you please provide the proper documentation for this software for developers

**Comment by erikgeurts** [comment]
See https://documentation.revive-adserver.com/display/DOCS/Revive+Adserver+Documentation for our priorities regarding the creation of documentation.

**Comment by andrewatfornax** [comment]
Also: https://documentation.revive-adserver.com/display/DOCS/Missing+Features
