### ISSUE TITLE
When the rv_audit table becomes full all accounts are prevented from logging in.

### ISSUE THREAD

**Issue by sikjoy** [revive-adserver/revive-adserver#956]
I am locked out of our Revive Adserver, receiving the following message during login attempts:

"An error occurred while accessing the database
Due to a problem with the database Revive Adserver couldn't retrieve or store data."

I noticed that the rv_audit table has maxed out with 8388607 rows. As soon as I truncated this table the adserver began functioning normally.

I confirmed this on Revive Adserver 4.3.1 as well as older versions.

**Comment by mbeccati** [comment]
Hi @sikjoy, thanks for your report, but this is not an issue in Revive Adserver. Most likely your database space is limited or something. There's nothing we can do about it.
