### ISSUE TITLE
Neither Javascript Tag or Asynchronous JS Tag work.

### ISSUE THREAD

**Issue by Tomoli75** [revive-adserver/revive-adserver#958]
These provide no data, whereas Local Module tag works fine!
Any help appreciated.

**Comment by andrewatfornax** [comment]
This sounds more like a support request, than a bug report. Clearly, JS and Async tags do work for most users! Please consider posting on the forums for support, or, if this is a bug report, provide reproduce steps etc. as per the default bug report template. Thanks.
