### ISSUE TITLE
probablema al Instalar el script

### ISSUE THREAD

**Issue by remgoficial** [revive-adserver/revive-adserver#959]
timeout => La función de PHP set_time_limit () ha sido deshabilitada y max_execution_time está establecido en 20, lo que puede causar problemas con la funcionalidad, como el mantenimiento.
badPhpConfiguration => Su configuración de PHP actual no cumple con los requisitos de Revive Adserver. Para resolver los problemas, modifique la configuración en su archivo 'php.ini'.

Hay alguna solución?

**Comment by kosciuk** [comment]
Hola, fijate en http://php.net/manual/es/info.configuration.php que max_execution_time es PHP_INI_ALL y fijate en http://php.net/manual/es/configuration.changes.modes.php que ese _ALL se puede editar en desde varios lados. Yo probaría con el .htaccess

**Comment by remgoficial** [comment]
php_value display_errors On
php_flag magic_quotes 1
php_flag magic_quotes_gpc 1
php_value mbstring.http_input auto
php_value date.timezone America/Caracas

Haci me aparece el.htaccess que le modifico?

**Comment by kosciuk** [comment]
php_value max_execution_time 300

https://stackoverflow.com/questions/7739870/increase-max-execution-time-for-php

**Comment by erikgeurts** [comment]
We recommend using our community forums at https://forum.revive-adserver.com for this type of exchange. We use Github only for bug reports and similar issues.
