### ISSUE TITLE
Very Large Delivery Rules Fail - PCRE Library Limitation

### ISSUE THREAD

**Issue by andrewatfornax** [revive-adserver/revive-adserver#966]
When very large delivery rules are used (e.g. when using the Site - Registerable Domain List rule with PostgreSQL, which does not impose data limitations), it is possible that an internal error will be returned by PHP's preg_match() function, as a result of limitations on the length of the regular expression which can be handled by the PCRE library used by PHP.

This can result in incorrect delivery of banners, where banners are not delivered according to the delivery rules defined.

**Comment by erikgeurts** [comment]
See also #968
