### ISSUE TITLE
CSS not loading

### ISSUE THREAD

**Issue by ashish-balachander** [revive-adserver/revive-adserver#967]
CSS doesnt load properly, I have checked in FF, Chrome, safari, internet explore on windows and mac. i dont have adblocker running. i have installed the latest 4.1.3 server .

URL: inresto-adserver.bitnamiapp.com

**Comment by erikgeurts** [comment]
The URL you included is not a Revive Adserver installation:
![image](https://user-images.githubusercontent.com/5102461/39420603-884636e6-4c65-11e8-8e08-62e0d6f685fe.png)

Meanwhile, it is recommended to post support issues like this on our community forums at https://forum.revive-adserver.com. If it does turn out to be a bug, we will gladly take another shot at it here.

**Comment by ashish-balachander** [comment]
hello the URL is in http://inresto-adserver.bitnamiapp.com/ads

**Comment by erikgeurts** [comment]
The actual URL is http://inresto-adserver.bitnamiapp.com/ads/www/admin/index.php

Looks like you've got some sort of pagespeed/minification going on in your server that's handling the this correctly.

As said, it is recommend to post this on the forums, this is not a bug.
