### ISSUE TITLE
Issue configuring the ad on the server - no ad preview

### ISSUE THREAD

**Issue by jmexo** [revive-adserver/revive-adserver#969]
Ad is giving an error while is being configured:

![revivepublisher](https://user-images.githubusercontent.com/31240443/39705706-77c15cb0-520f-11e8-8f0e-b01a27eeab42.png)

The problem is, that banner is not showing inside revive ads on opensubtitles.org
it is requesting Request URL: https://syndication2.opensubtitles.org/native-settings.php?idzone=2985500
this URL DOESNT exists

http://www.opensubtitles.org/addons/exo.html however here it is working.

Tested on another server it displays correctly and even a preview is shown.

![reviveexoclick](https://user-images.githubusercontent.com/31240443/39705717-7f93f0e2-520f-11e8-9b3a-50b7adbe1f11.png)

Revive Adserver v4.1.3 running on both servers

What can be wrong?

**Comment by erikgeurts** [comment]
As clearly indicated during the process of opening an issue here, it is recommended to post this type of question on our community forums at https://forum.revive-adserver.com. If it turns out that there is a bug or some other issue that developers need to look at, we will gladly re-open it here.

**Comment by jmexo** [comment]
Sorry for opening on the wrong channel. Already raised here: https://forum.revive-adserver.com/topic/5033-issue-configuring-the-ad-on-the-server-no-ad-preview/

Thanks in advance.
