### ISSUE TITLE
Unpersonalized Ads for GDPR

### ISSUE THREAD

**Issue by hogiro** [revive-adserver/revive-adserver#970]
Hello,

soon in Europe the GDPR will be active (25. May). I would like to know if you are implementing any functions to make the revive-adserver compliant.  Is it possible to adapt the tags, that only unpersonalized ads will be delivered?

Best Regards,

**Comment by erikgeurts** [comment]
No need to make any changes in this regard, as the process you describe is already the default mode of operation of the software.

**Comment by andrewatfornax** [comment]
@hogiro -

@erikgeurts has written up some great information at https://www.revive-adserver.com/privacy/personal-data/ that might help explain what's going on, and why no changes are needed.
