### ISSUE TITLE
Delivery rules > Latest versions of Windows are not considered

### ISSUE THREAD

**Issue by maxlanders** [revive-adserver/revive-adserver#982]
In delivery rules > Client - Operating system (Legacy), Latest versions of Windows versions are not available (i.e Windows 8, Windows 10).

So when I need to target all Windows users, I set the following delivery rule:
Client - Operating system (Legacy) IS NOT ANY OF : Linux | FreeBSD | Solaris | Mac OSX.

And the result is : users of Windows 10 (I couldn't test for Windows 8) don't see our campaigns.
That's why I presume the versions of Windows above 7 are not taken into consideration by Revive.

For now the only solution I've found is to use plugins.

**Comment by erikgeurts** [comment]
You're using the legacy version of this delivery rule. There is a new implementation since some time:
![image](https://user-images.githubusercontent.com/5102461/40911996-a06d8a34-67f0-11e8-81c4-c9fb72fab6b6.png)
