### ISSUE TITLE
Can't view Adsense Banners

### ISSUE THREAD

**Issue by jackieb101** [revive-adserver/revive-adserver#984]
I added Adsense code snippet to Revive Banner Sever but cannot view the banner.
Followed this link exactly https://www.revive-adserver.com/faq/using-google-adsense-with-revive-adserver/
Still not working. Been searching through blogs/formus ... everywhere. Please can you assist - need to get all my advertising on one platform.

**Comment by erikgeurts** [comment]
Please post your support question(s) on the community forums over at https://forum.revive-adserver.com . We use Github for software development and bugs only.
