### ISSUE TITLE
After hack-attack, problem with false clicks on revive banners

### ISSUE THREAD

**Issue by MarkoOpserver** [revive-adserver/revive-adserver#986]
Hi,

We had a hacker attack on our web page server. After solving it, the revive adserver started having problems.
We have false clicks on our banners, even on those that are not active. 
We noticed that this clicks are happening only on desktop banners, not on mobile.

Any idea what is going on and how to solve the issue?

Regards,
Marko

**Comment by erikgeurts** [comment]
We recommend posting this type of question on the Community Forums at https://forum.revive-adserver.com

**Comment by MarkoOpserver** [comment]
Ok, thanks... :)
