### ISSUE TITLE
dateTime.iso8601 not well supported on statistics

### ISSUE THREAD

**Issue by juanjopv** [revive-adserver/revive-adserver#987]
Hello,

We are using the Revive Adserver REST API to communicate with our Revive Adserver, but we have problems on querying for statistics, since we need a strongly datetime filter. We sent and email to the REST API plugin developer and he said that timestamp filters are not well supported by Revive AdServer, but data seems Ok on Revive database. 

Seems like this plugin is a wrapper of legacy XML_RPC API, so the problem comes from there.

We're then using XML_RPC API and having the same problem.

We found some API documentation found here:
https://github.com/Artistan/Revive-XmlRpc/blob/HEAD/api.md#class-artistanrevivexmlrpcopenadsv2apixmlrpc

We're using pear/XML_RPC2 for consuming legacy XML_RPC API:
https://github.com/pear/XML_RPC2

Problem:
XML_RPC API does not support 'dateTime.iso8601' properly for statistics calls. Results seems to be for a completely day. Since this api is not working properly, the available REST API plugin for Revive AdServer, that I guess is a wrapper of XML_RPC api, has the same problem.

Steps To Reproduce:
Make a request to:
"your-revive-domain/www/api/v2/xmlrpc/ox.campaignStatisticsConversions" or any other campaign statistic public method of the XML_RPC API passing startDate and endDate on ISO8601 format.

Expected: Results are filtered properly with accordingly to timestamps ranges.

Actual: Results seems to be from YYYY-MM-dd 00:00:00 to YYYY-MM-dd 23:59:59

**Comment by erikgeurts** [comment]
As mentioned in the reply I sent you when you asked about this in relation to the Revive Adserver REST API, statistics inside Revive Adserver databases are always stored in UTC. You can set a time zone preference for your username, or the username that you use to access the API, and that time zone preference should then be respected in the UI as in the API.

**Comment by juanjopv** [comment]
I tested changing manager time zone in our Revive AdServer and checked that datetime are shown ok on Revive UI, but using XML_RPC legacy API with same user manager and setting the flag  $useManagerTimezone to true, results are still in UTC. The same with REST API plugin.

![reviveui_conversions_timezone](https://user-images.githubusercontent.com/40636551/42024877-800d1080-7ac3-11e8-92da-aeb03c713916.png)
![revive_xmlrpc_conversions](https://user-images.githubusercontent.com/40636551/42024878-802d3202-7ac3-11e8-91a1-4198f8bf77f7.png)
![revive_apirest_conversions](https://user-images.githubusercontent.com/40636551/42024879-80c44624-7ac3-11e8-8bb0-bb852227f965.png)

**Comment by erikgeurts** [comment]
OK, that's interesting. Does this happen only when you retrieve conversion data, or is this for any type of statistics?

**Comment by mbeccati** [comment]
@juanjopv Are you using the same user to access the UI and API?

**Comment by juanjopv** [comment]
@erikgeurts For the rest of statistics calls we are not retrieving datetime data, so I cannot compare results with revive UI in a easily way as in conversion statistics. By the way conversions are important for us since tracking data is there.

@mbeccati Yes, I'm using the same user manager.

Checking the Revive code, seems like the problem is on Statistics.php file at function getTimeZone.

if you are not setting $localTZ flag, the date is taken as UTC, but otherwise, the time zone is set from system Date time zone, not from user manager time zone.

` /**
     * A private method to return the current TimeZone as selected by the useUTC parameter
     *
     * @param bool $localTZ
     * @return Date_TimeZone
     */
    private function getTimeZone($localTZ = false)
    {
        if (empty($localTZ)) {
            $oTz = new Date_TimeZone('UTC');
        } else {
            $oNow = new Date();
            $oTz = $oNow->tz;
        }

        return $oTz;
    }
`

**Comment by mbeccati** [comment]
@juanjopv Manager users don't have access to the XML-RPC api, as far as I recall...

**Comment by juanjopv** [comment]
As far as I know I need to logon with user credentials in order to get a sessionId that must be passed to the next calls.

This is my code using XML_RPC API:

`        $credentials = ['username' => env('PV_ADSERVER_USER'), "password" => env('PV_ADSERVER_PASSWORD')];
        $options = ['prefix' => 'ox.'];
        $client = XML_RPC2_Client::create(env('PV_ADSERVER_URL'), $options);

        try {

            $sessionId = $client->logon($credentials['username'], $credentials['password']);
            $result = $client->campaignConversionStatistics($sessionId, $campaign_id, $startDate, $endDate);
            $client->logoff($sessionId);
            return response()->json($result);

        } catch (\XML_RPC2_FaultException $e) {

            $response = "XML_RPC2_FAULT " . $e->getFaultCode() . ": " . $e->getFaultString();
            throw new HttpResponseException($response);


        } catch (\Exception $e){
            throw new \HttpResponseException($e->getCode() . " : " . $e->getMessage());
        }
`

**Comment by mbeccati** [comment]
@juanjopv Sure, I just meant that only admin users have access to the XML-RPC. In any case, check the users table and make sure that default_account_id is a valid ID from the accounts table. I've seen a similar behaviour in past on a customer's instance.

**Comment by juanjopv** [comment]
@mbeccati  Do you mean users.default_account_id with accounts.account_id ?

**Comment by juanjopv** [comment]
By updating users table:
I switched the user account I'm using from Default mangager to Administrator account type and the same result. :(

**Comment by mbeccati** [comment]
@juanjopv pls double check that the users.default_account_id is in fact the ID of the Default manager or Administrator account.

**Comment by juanjopv** [comment]
@mbeccati I already checked it, I tested with both "Default manager" and "Administrator" account types but anyway, I'm preparing a pull request with the changes we need in order to work with statistics according to our requirements. I will send you as soon as possible, so if you guys believe the changes are good to merge (by refactoring some portion of code or not) and to be available for other users, go ahead.

From our point of veiw, is not acceptable that Revive AdServer is not ready to work with client that are at different time zone. 

In the same way, we need that hour, minutes and seconds sent by client to be used as filters in query "Where" conditions and making the corresponding time zone conversion to return the correct data to the client.

**Comment by mbeccati** [comment]
@juanjopv as ugly as a response it may seem... it works for me: I cannot reproduce the behaviour you describe on a working installation.

**Comment by juanjopv** [comment]
@mbeccati Don't worry, with my local changes it now works as we expect, if this changes are not interesting to merge into the master repository, we'll create a Fork for our own version of software.

Thanks anyway !!

**Comment by erikgeurts** [comment]
I've been working with @mbeccati in the last couple of hours, and we've been able to establish that the built-in XML-RPC API correctly handles time zones, meaning that it can be used to retrieve statistics in time zones other than UTC if so instructed. This does, of course, assume that the installation and configuration of the Revive Adserver installation have been done correctly. Issues related third party enhancements, like the REST API should be addressed to the vendor directly.

**Comment by juanjopv** [comment]
@erikgeurts Yes, I know that revive handles both UTC and local time zone, but creating a user for each customer we have on each time zone is unnacceptable.

**Comment by juanjopv** [comment]
I've created a pull request, so you guys could see the changes we need.
https://github.com/revive-adserver/revive-adserver/pull/990

**Comment by jatinderaujla** [comment]
@erikgeurts and @mbeccati Can I contribute Revive Adserver Management REST APIs to this open source project?

**Comment by erikgeurts** [comment]
There is already a well-established product https://www.reviveadserverrestapi.com/ (full disclosure: licenses sold by my company).

**Comment by mbeccati** [comment]
@jatinderaujla If you have a working REST API implementation that you wish to make open source, I'd suggest you create a github repo for it and instructions on how to use it. That would be a good first step

**Comment by jatinderaujla** [comment]
@mbeccati yeah sure I will do it
