### ISSUE TITLE
Active Advertisers/Campaigns filter should includes Awaiting campaigns also

### ISSUE THREAD

**Issue by PinkDexo** [revive-adserver/revive-adserver#992]
"Hide inactive items from all overview pages" under "Preferences > Account Preferences > User Interface Preferences" is a excellent feature. However, in situation where you have a lot of Advertisers and Campaigns, it is very easy to lose a track of "Awaiting" Campaigns.

So I think that the Active Advertisers and Active Campaigns filter should also includes Awaiting campaigns.

![camp-scr](https://user-images.githubusercontent.com/40886210/42446735-a8717982-8377-11e8-9692-26c84b01fe7a.png)

**Comment by andrewatfornax** [comment]
Closed with the inclusion of #998.
